# Generated by Django 5.1.8 on 2025-09-08 01:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutoAllocationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        help_text="執行開始時間", verbose_name="開始時間"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="執行完成時間",
                        null=True,
                        verbose_name="完成時間",
                    ),
                ),
                (
                    "execution_time",
                    models.DurationField(
                        blank=True,
                        help_text="實際執行時間",
                        null=True,
                        verbose_name="執行時間",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=False, help_text="是否執行成功", verbose_name="執行成功"
                    ),
                ),
                (
                    "total_workorders",
                    models.IntegerField(
                        default=0,
                        help_text="本次處理的工單數量",
                        verbose_name="處理工單數",
                    ),
                ),
                (
                    "successful_allocations",
                    models.IntegerField(
                        default=0,
                        help_text="成功分配的工單數量",
                        verbose_name="成功分配數",
                    ),
                ),
                (
                    "failed_allocations",
                    models.IntegerField(
                        default=0,
                        help_text="分配失敗的工單數量",
                        verbose_name="失敗分配數",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="執行失敗時的錯誤訊息",
                        verbose_name="錯誤訊息",
                    ),
                ),
                (
                    "result_details",
                    models.JSONField(
                        blank=True,
                        help_text="執行的詳細結果資訊",
                        null=True,
                        verbose_name="詳細結果",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "自動分配執行記錄",
                "verbose_name_plural": "自動分配執行記錄",
                "db_table": "workorder_auto_allocation_log",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AutoAllocationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="是否啟用自動分配功能",
                        verbose_name="啟用自動執行",
                    ),
                ),
                (
                    "completed_workorder_allocation_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="是否啟用已完工工單工序紀錄數量自動分配",
                        verbose_name="啟用已完工工單數量分配",
                    ),
                ),
                (
                    "completed_workorder_allocation_interval",
                    models.IntegerField(
                        default=60,
                        help_text="已完工工單數量分配的執行間隔時間",
                        verbose_name="已完工工單分配執行頻率（分鐘）",
                    ),
                ),
                (
                    "interval_minutes",
                    models.IntegerField(
                        default=30,
                        help_text="自動執行的間隔時間",
                        verbose_name="執行頻率（分鐘）",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        default="08:00",
                        help_text="允許執行的開始時間",
                        verbose_name="開始時間",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        default="18:00",
                        help_text="允許執行的結束時間",
                        verbose_name="結束時間",
                    ),
                ),
                (
                    "max_execution_time",
                    models.IntegerField(
                        default=30,
                        help_text="單次執行的最大時間限制",
                        verbose_name="最大執行時間（分鐘）",
                    ),
                ),
                (
                    "notification_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="是否啟用執行結果通知",
                        verbose_name="啟用通知",
                    ),
                ),
                (
                    "is_running",
                    models.BooleanField(
                        default=False,
                        help_text="當前是否正在執行",
                        verbose_name="正在執行",
                    ),
                ),
                (
                    "last_execution",
                    models.DateTimeField(
                        blank=True,
                        help_text="最近一次執行的時間",
                        null=True,
                        verbose_name="最後執行時間",
                    ),
                ),
                (
                    "next_execution",
                    models.DateTimeField(
                        blank=True,
                        help_text="預定的下次執行時間",
                        null=True,
                        verbose_name="下次執行時間",
                    ),
                ),
                (
                    "total_executions",
                    models.IntegerField(
                        default=0, help_text="累計執行次數", verbose_name="總執行次數"
                    ),
                ),
                (
                    "success_count",
                    models.IntegerField(
                        default=0, help_text="成功執行的次數", verbose_name="成功次數"
                    ),
                ),
                (
                    "failure_count",
                    models.IntegerField(
                        default=0, help_text="執行失敗的次數", verbose_name="失敗次數"
                    ),
                ),
                (
                    "total_execution_time",
                    models.DurationField(
                        blank=True,
                        help_text="累計執行時間",
                        null=True,
                        verbose_name="總執行時間",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "自動分配設定",
                "verbose_name_plural": "自動分配設定",
                "db_table": "workorder_auto_allocation_settings",
            },
        ),
        migrations.CreateModel(
            name="CompletedProductionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_workorder_id",
                    models.IntegerField(default=0, verbose_name="已完工工單ID"),
                ),
                ("report_date", models.DateField(verbose_name="報工日期")),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                ("operator", models.CharField(max_length=100, verbose_name="作業員")),
                ("equipment", models.CharField(max_length=100, verbose_name="設備")),
                (
                    "work_quantity",
                    models.IntegerField(default=0, verbose_name="合格品數量"),
                ),
                (
                    "defect_quantity",
                    models.IntegerField(default=0, verbose_name="不良品數量"),
                ),
                ("work_hours", models.FloatField(default=0.0, verbose_name="工作時數")),
                (
                    "overtime_hours",
                    models.FloatField(default=0.0, verbose_name="加班時數"),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="開始時間"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="結束時間"
                    ),
                ),
                (
                    "report_source",
                    models.CharField(max_length=50, verbose_name="報工來源"),
                ),
                (
                    "report_type",
                    models.CharField(max_length=20, verbose_name="報工類型"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="備註"),
                ),
                (
                    "abnormal_notes",
                    models.TextField(blank=True, null=True, verbose_name="異常紀錄"),
                ),
                (
                    "approval_status",
                    models.CharField(
                        default="approved", max_length=20, verbose_name="審核狀態"
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="審核者"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="審核時間"),
                ),
                (
                    "allocated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="分配時間"
                    ),
                ),
                (
                    "allocation_method",
                    models.CharField(
                        blank=True,
                        default="manual",
                        max_length=50,
                        null=True,
                        verbose_name="分配方式",
                    ),
                ),
                (
                    "is_system_allocated",
                    models.BooleanField(
                        default=False,
                        help_text="標記此數量是否為系統自動分配",
                        verbose_name="系統分配標記",
                    ),
                ),
            ],
            options={
                "verbose_name": "已完工生產報工記錄",
                "verbose_name_plural": "已完工生產報工記錄",
                "db_table": "workorder_completed_production_report",
                "ordering": ["report_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="CompletedWorkOrderProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_workorder_id",
                    models.IntegerField(default=0, verbose_name="已完工工單ID"),
                ),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                ("process_order", models.IntegerField(verbose_name="工序順序")),
                ("planned_quantity", models.IntegerField(verbose_name="計劃數量")),
                (
                    "completed_quantity",
                    models.IntegerField(default=0, verbose_name="完成數量"),
                ),
                (
                    "status",
                    models.CharField(
                        default="completed", max_length=20, verbose_name="工序狀態"
                    ),
                ),
                (
                    "assigned_operator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分配作業員"
                    ),
                ),
                (
                    "assigned_equipment",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分配設備"
                    ),
                ),
                (
                    "total_work_hours",
                    models.FloatField(default=0.0, verbose_name="工作時數"),
                ),
                (
                    "total_good_quantity",
                    models.IntegerField(default=0, verbose_name="合格品數量"),
                ),
                (
                    "total_defect_quantity",
                    models.IntegerField(default=0, verbose_name="不良品數量"),
                ),
                (
                    "report_count",
                    models.IntegerField(default=0, verbose_name="報工次數"),
                ),
                (
                    "operators",
                    models.JSONField(default=list, verbose_name="參與作業員"),
                ),
                ("equipment", models.JSONField(default=list, verbose_name="使用設備")),
            ],
            options={
                "verbose_name": "已完工工單工序",
                "verbose_name_plural": "已完工工單工序",
                "db_table": "workorder_completed_workorder_process",
                "ordering": ["process_order"],
            },
        ),
        migrations.CreateModel(
            name="DispatchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workorder_id", models.IntegerField(default=0, verbose_name="工單ID")),
                ("process_id", models.IntegerField(default=0, verbose_name="工序ID")),
                (
                    "operator_id",
                    models.IntegerField(blank=True, null=True, verbose_name="作業員ID"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="派工數量"),
                ),
                (
                    "created_by",
                    models.CharField(max_length=100, verbose_name="建立人員"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "派工單記錄",
                "verbose_name_plural": "派工單記錄",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="設定名稱",
                        max_length=50,
                        unique=True,
                        verbose_name="設定名稱",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="設定值", max_length=100, verbose_name="設定值"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="設定說明", verbose_name="設定說明"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="建立時間", verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="更新時間", verbose_name="更新時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "系統設定",
                "verbose_name_plural": "系統設定",
                "db_table": "workorder_system_config",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workorder_id", models.IntegerField(default=0, verbose_name="工單ID")),
                (
                    "equipment_id",
                    models.CharField(max_length=50, verbose_name="分配設備ID"),
                ),
                (
                    "operator_id",
                    models.CharField(max_length=50, verbose_name="分配作業員ID"),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分配時間"),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="公司代號"
                    ),
                ),
            ],
            options={
                "verbose_name": "工單分配",
                "verbose_name_plural": "工單分配記錄",
                "db_table": "workorder_assignment",
            },
        ),
        migrations.CreateModel(
            name="WorkOrderProcessCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workorder_process_id",
                    models.IntegerField(
                        default=0, unique=True, verbose_name="工單工序ID"
                    ),
                ),
                (
                    "max_operators",
                    models.IntegerField(default=1, verbose_name="最大作業員數"),
                ),
                (
                    "max_equipments",
                    models.IntegerField(default=1, verbose_name="最大設備數"),
                ),
                (
                    "target_hourly_output",
                    models.IntegerField(default=0, verbose_name="目標每小時產出"),
                ),
                (
                    "overtime_enabled",
                    models.BooleanField(default=False, verbose_name="啟用加班"),
                ),
                (
                    "parallel_work_enabled",
                    models.BooleanField(default=True, verbose_name="啟用並行作業"),
                ),
            ],
            options={
                "verbose_name": "工序產能設定",
                "verbose_name_plural": "工序產能設定",
                "db_table": "workorder_process_capacity",
            },
        ),
        migrations.CreateModel(
            name="WorkOrderProcessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workorder_process_id",
                    models.IntegerField(default=0, verbose_name="工單工序ID"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("start", "開始生產"),
                            ("pause", "暫停生產"),
                            ("resume", "恢復生產"),
                            ("complete", "完成生產"),
                            ("quality_check", "品質檢查"),
                            ("equipment_change", "設備更換"),
                            ("operator_change", "作業員更換"),
                            ("quantity_update", "數量更新"),
                            ("note", "備註"),
                            ("auto_assignment", "自動分配"),
                            ("status_change", "狀態變更"),
                            ("quick_report", "快速報工"),
                        ],
                        max_length=50,
                        verbose_name="操作類型",
                    ),
                ),
                (
                    "quantity_before",
                    models.PositiveIntegerField(default=0, verbose_name="操作前數量"),
                ),
                (
                    "quantity_after",
                    models.PositiveIntegerField(default=0, verbose_name="操作後數量"),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="操作員"
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="設備"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備註")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="記錄時間"),
                ),
            ],
            options={
                "verbose_name": "工單工序日誌",
                "verbose_name_plural": "工單工序日誌",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workorder_id",
                    models.IntegerField(
                        blank=True, null=True, unique=True, verbose_name="工單ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_production", "生產中"),
                            ("paused", "暫停"),
                            ("completed", "已完工"),
                        ],
                        default="in_production",
                        max_length=20,
                        verbose_name="生產狀態",
                    ),
                ),
                (
                    "production_start_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="生產開始時間"
                    ),
                ),
                (
                    "production_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="生產結束時間"
                    ),
                ),
                (
                    "current_process",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="當前工序"
                    ),
                ),
                (
                    "completed_processes",
                    models.TextField(
                        blank=True,
                        help_text="JSON格式記錄已完成的工序",
                        verbose_name="已完成工序",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "生產中工單",
                "verbose_name_plural": "生產中工單",
                "db_table": "workorder_production",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutoManagementConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function_type",
                    models.CharField(
                        choices=[
                            ("auto_completion_check", "完工判斷轉寫已完工"),
                            ("auto_approval", "自動核准"),
                            ("auto_notification", "自動通知"),
                        ],
                        help_text="選擇要設定的自動化功能類型",
                        max_length=50,
                        verbose_name="功能類型",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="是否啟用此自動化功能",
                        verbose_name="是否啟用",
                    ),
                ),
                (
                    "interval_minutes",
                    models.IntegerField(
                        default=30,
                        help_text="設定自動化功能的執行間隔，以分鐘為單位",
                        verbose_name="執行間隔（分鐘）",
                    ),
                ),
                (
                    "last_execution",
                    models.DateTimeField(
                        blank=True,
                        help_text="記錄此功能最後執行的時間",
                        null=True,
                        verbose_name="最後執行時間",
                    ),
                ),
                (
                    "next_execution",
                    models.DateTimeField(
                        blank=True,
                        help_text="預估下次執行的時間",
                        null=True,
                        verbose_name="下次執行時間",
                    ),
                ),
                (
                    "execution_count",
                    models.IntegerField(
                        default=0,
                        help_text="記錄此功能已執行的次數",
                        verbose_name="執行次數",
                    ),
                ),
                (
                    "success_count",
                    models.IntegerField(
                        default=0,
                        help_text="記錄此功能成功執行的次數",
                        verbose_name="成功次數",
                    ),
                ),
                (
                    "error_count",
                    models.IntegerField(
                        default=0,
                        help_text="記錄此功能執行失敗的次數",
                        verbose_name="錯誤次數",
                    ),
                ),
                (
                    "last_error_message",
                    models.TextField(
                        blank=True,
                        help_text="記錄最後一次執行失敗的錯誤訊息",
                        verbose_name="最後錯誤訊息",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        default="system", max_length=100, verbose_name="建立人員"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "自動管理功能設定",
                "verbose_name_plural": "自動管理功能設定",
                "db_table": "workorder_auto_management_config",
                "ordering": ["function_type"],
                "unique_together": {("function_type",)},
            },
        ),
        migrations.CreateModel(
            name="CompletedWorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_workorder_id",
                    models.IntegerField(
                        help_text="對應的原始工單ID", verbose_name="原始工單ID"
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=100, verbose_name="工單號"),
                ),
                (
                    "product_code",
                    models.CharField(max_length=100, verbose_name="產品編號"),
                ),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="", max_length=100, verbose_name="公司名稱"
                    ),
                ),
                ("planned_quantity", models.IntegerField(verbose_name="計劃數量")),
                (
                    "completed_quantity",
                    models.IntegerField(default=0, verbose_name="完成數量"),
                ),
                (
                    "status",
                    models.CharField(
                        default="completed", max_length=20, verbose_name="工單狀態"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="開始時間"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完工時間"
                    ),
                ),
                (
                    "production_record_id",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="生產記錄ID"
                    ),
                ),
                (
                    "total_work_hours",
                    models.FloatField(default=0.0, verbose_name="總工作時數"),
                ),
                (
                    "total_overtime_hours",
                    models.FloatField(default=0.0, verbose_name="總加班時數"),
                ),
                (
                    "total_all_hours",
                    models.FloatField(default=0.0, verbose_name="全部總時數"),
                ),
                (
                    "total_good_quantity",
                    models.IntegerField(default=0, verbose_name="總合格品"),
                ),
                (
                    "total_defect_quantity",
                    models.IntegerField(default=0, verbose_name="總不良品"),
                ),
                (
                    "total_report_count",
                    models.IntegerField(default=0, verbose_name="報工次數"),
                ),
                (
                    "unique_operators",
                    models.JSONField(default=list, verbose_name="參與作業員"),
                ),
                (
                    "unique_equipment",
                    models.JSONField(default=list, verbose_name="使用設備"),
                ),
            ],
            options={
                "verbose_name": "已完工工單",
                "verbose_name_plural": "已完工工單",
                "db_table": "workorder_completed_workorder",
                "ordering": ["-completed_at"],
                "indexes": [
                    models.Index(
                        fields=["order_number"], name="workorder_c_order_n_1c93e7_idx"
                    ),
                    models.Index(
                        fields=["product_code"], name="workorder_c_product_915fe2_idx"
                    ),
                    models.Index(
                        fields=["company_code"], name="workorder_c_company_22bdc5_idx"
                    ),
                    models.Index(
                        fields=["company_name"], name="workorder_c_company_90cd68_idx"
                    ),
                    models.Index(
                        fields=["completed_at"], name="workorder_c_complet_20aa6b_idx"
                    ),
                ],
                "unique_together": {("company_code", "order_number", "product_code")},
            },
        ),
        migrations.CreateModel(
            name="ConsistencyCheckResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("missing_fill_work", "缺失填報紀錄"),
                            ("missing_dispatch", "填報異常"),
                            ("wrong_product_code", "產品編號錯誤"),
                            ("wrong_company", "公司代號/名稱錯誤"),
                            ("wrong_workorder", "工單號碼錯誤"),
                        ],
                        max_length=50,
                        verbose_name="檢查類型",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="公司代號"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="公司名稱"
                    ),
                ),
                (
                    "workorder",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="工單號碼"
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="產品編號"
                    ),
                ),
                (
                    "wrong_company_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="錯誤公司代號",
                    ),
                ),
                (
                    "wrong_company_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="錯誤公司名稱",
                    ),
                ),
                (
                    "wrong_workorder",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="錯誤工單號碼",
                    ),
                ),
                (
                    "wrong_product_code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="錯誤產品編號",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="作業員"
                    ),
                ),
                (
                    "work_date",
                    models.DateField(blank=True, null=True, verbose_name="工作日期"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="狀態"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(blank=True, null=True, verbose_name="數量"),
                ),
                (
                    "is_fixed",
                    models.BooleanField(default=False, verbose_name="是否已修復"),
                ),
                (
                    "fixed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="修復時間"
                    ),
                ),
                (
                    "fixed_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="修復人員"
                    ),
                ),
                (
                    "fix_method",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="修復方式"
                    ),
                ),
                (
                    "fix_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="儲存修復時的額外資料",
                        verbose_name="修復資料",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "相符性檢查結果",
                "verbose_name_plural": "相符性檢查結果",
                "db_table": "workorder_consistency_check_result",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["check_type"], name="workorder_c_check_t_d3d1c7_idx"
                    ),
                    models.Index(
                        fields=["company_code"], name="workorder_c_company_06de34_idx"
                    ),
                    models.Index(
                        fields=["workorder"], name="workorder_c_workord_9543c9_idx"
                    ),
                    models.Index(
                        fields=["product_code"], name="workorder_c_product_6f9b66_idx"
                    ),
                    models.Index(
                        fields=["is_fixed"], name="workorder_c_is_fixe_6d90ec_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="workorder_c_created_dd8244_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="公司代號"
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=50, verbose_name="工單號碼"),
                ),
                (
                    "product_code",
                    models.CharField(max_length=100, verbose_name="產品編號"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="數量")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待生產"),
                            ("in_progress", "生產中"),
                            ("paused", "暫停"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "order_source",
                    models.CharField(
                        choices=[("erp", "ERP系統"), ("mes", "MES手動建立")],
                        default="erp",
                        help_text="工單來源：ERP系統同步或MES手動建立",
                        max_length=10,
                        verbose_name="工單來源",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完工時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "工單",
                "verbose_name_plural": "工單管理",
                "unique_together": {("company_code", "order_number", "product_code")},
            },
        ),
        migrations.CreateModel(
            name="WorkOrderOperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="時間戳"
                    ),
                ),
                ("user", models.CharField(max_length=150, verbose_name="用戶")),
                ("action", models.CharField(max_length=255, verbose_name="操作")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 地址"
                    ),
                ),
                (
                    "details",
                    models.TextField(blank=True, null=True, verbose_name="細節"),
                ),
                (
                    "workorder_related",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workorder.workorder",
                        verbose_name="關聯工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "工單操作日誌",
                "verbose_name_plural": "工單操作日誌",
                "db_table": "workorder_operation_log",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="WorkOrderProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workorder_id", models.IntegerField(default=0, verbose_name="工單ID")),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                ("step_order", models.IntegerField(verbose_name="工序順序")),
                ("planned_quantity", models.IntegerField(verbose_name="計劃數量")),
                (
                    "completed_quantity",
                    models.IntegerField(default=0, verbose_name="完成數量"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待生產"),
                            ("in_progress", "生產中"),
                            ("completed", "已完成"),
                            ("paused", "暫停"),
                            ("cancelled", "取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "assigned_operator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分配作業員"
                    ),
                ),
                (
                    "assigned_equipment",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分配設備"
                    ),
                ),
                (
                    "actual_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="實際開始時間"
                    ),
                ),
                (
                    "actual_end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="實際結束時間"
                    ),
                ),
                (
                    "capacity_multiplier",
                    models.IntegerField(
                        default=1,
                        help_text="1=單人, 2=雙人, 3=三人...",
                        verbose_name="產能倍數",
                    ),
                ),
                (
                    "additional_operators",
                    models.TextField(
                        blank=True,
                        help_text="JSON格式儲存額外作業員清單",
                        null=True,
                        verbose_name="額外作業員",
                    ),
                ),
                (
                    "additional_equipments",
                    models.TextField(
                        blank=True,
                        help_text="JSON格式儲存額外設備清單",
                        null=True,
                        verbose_name="額外設備",
                    ),
                ),
                (
                    "target_hourly_output",
                    models.IntegerField(default=0, verbose_name="目標每小時產出"),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="預計工時",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "工單工序明細",
                "verbose_name_plural": "工單工序明細",
                "ordering": ["workorder_id", "step_order"],
                "unique_together": {("workorder_id", "step_order")},
            },
        ),
        migrations.CreateModel(
            name="WorkOrderProductionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workorder_production_id",
                    models.IntegerField(default=0, verbose_name="生產中工單ID"),
                ),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                ("report_date", models.DateField(verbose_name="報工日期")),
                (
                    "report_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="報工時間"),
                ),
                (
                    "work_quantity",
                    models.IntegerField(default=0, verbose_name="合格品數量"),
                ),
                (
                    "defect_quantity",
                    models.IntegerField(default=0, verbose_name="不良品數量"),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="作業員"
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="設備"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="公司名稱"
                    ),
                ),
                (
                    "report_source",
                    models.CharField(
                        choices=[
                            ("operator", "作業員現場報工"),
                            ("operator_supplement", "作業員補登報工"),
                            ("smt", "SMT報工"),
                        ],
                        max_length=20,
                        verbose_name="報工來源",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="開始時間"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="結束時間"),
                ),
                ("work_hours", models.FloatField(default=0.0, verbose_name="工作時數")),
                (
                    "overtime_hours",
                    models.FloatField(default=0.0, verbose_name="加班時數"),
                ),
                (
                    "has_break",
                    models.BooleanField(default=False, verbose_name="是否有休息時間"),
                ),
                (
                    "break_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="休息開始時間"
                    ),
                ),
                (
                    "break_end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="休息結束時間"
                    ),
                ),
                (
                    "break_hours",
                    models.FloatField(default=0.0, verbose_name="休息時數"),
                ),
                (
                    "report_type",
                    models.CharField(
                        default="normal", max_length=20, verbose_name="報工類型"
                    ),
                ),
                (
                    "allocated_quantity",
                    models.IntegerField(default=0, verbose_name="分配數量"),
                ),
                (
                    "quantity_source",
                    models.CharField(
                        default="original", max_length=20, verbose_name="數量來源"
                    ),
                ),
                (
                    "allocation_notes",
                    models.TextField(blank=True, verbose_name="分配說明"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="是否已完工"),
                ),
                (
                    "completion_method",
                    models.CharField(
                        default="manual", max_length=20, verbose_name="完工判斷方式"
                    ),
                ),
                (
                    "auto_completed",
                    models.BooleanField(default=False, verbose_name="自動完工狀態"),
                ),
                (
                    "completion_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完工確認時間"
                    ),
                ),
                (
                    "cumulative_quantity",
                    models.IntegerField(default=0, verbose_name="累積完成數量"),
                ),
                (
                    "cumulative_hours",
                    models.FloatField(default=0.0, verbose_name="累積工時"),
                ),
                (
                    "approval_status",
                    models.CharField(
                        default="approved", max_length=20, verbose_name="核准狀態"
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="核准人員"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="核准時間"
                    ),
                ),
                (
                    "approval_remarks",
                    models.TextField(blank=True, verbose_name="核准備註"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="駁回原因"),
                ),
                (
                    "rejected_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="駁回人員"
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="駁回時間"
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="備註")),
                (
                    "abnormal_notes",
                    models.TextField(blank=True, verbose_name="異常記錄"),
                ),
                (
                    "original_report_id",
                    models.IntegerField(
                        blank=True,
                        help_text="對應的原始報工記錄ID",
                        null=True,
                        verbose_name="原始報工記錄ID",
                    ),
                ),
                (
                    "original_report_type",
                    models.CharField(
                        blank=True,
                        help_text="原始報工記錄的類型",
                        max_length=20,
                        null=True,
                        verbose_name="原始報工類型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "created_by",
                    models.CharField(
                        default="system", max_length=100, verbose_name="建立人員"
                    ),
                ),
            ],
            options={
                "verbose_name": "生產報工明細",
                "verbose_name_plural": "生產報工明細",
                "db_table": "workorder_production_detail",
                "ordering": ["process_name", "start_time", "report_time"],
                "indexes": [
                    models.Index(
                        fields=[
                            "workorder_production_id",
                            "process_name",
                            "report_source",
                        ],
                        name="idx_prod_detail_completion",
                    ),
                    models.Index(fields=["report_date"], name="idx_prod_detail_date"),
                    models.Index(
                        fields=["process_name"], name="idx_prod_detail_process"
                    ),
                    models.Index(
                        fields=["start_time"], name="idx_prod_detail_start_time"
                    ),
                ],
                "unique_together": {
                    ("workorder_production_id", "process_name", "report_date")
                },
            },
        ),
    ]
