# Generated by Django 5.1.8 on 2025-08-02 06:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("process", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletedWorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_workorder_id",
                    models.IntegerField(
                        help_text="對應的原始工單ID", verbose_name="原始工單ID"
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=100, verbose_name="工單號"),
                ),
                (
                    "product_code",
                    models.CharField(max_length=100, verbose_name="產品編號"),
                ),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                ("planned_quantity", models.IntegerField(verbose_name="計劃數量")),
                (
                    "completed_quantity",
                    models.IntegerField(default=0, verbose_name="完成數量"),
                ),
                (
                    "status",
                    models.CharField(
                        default="completed", max_length=20, verbose_name="工單狀態"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="開始時間"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="完工時間"),
                ),
                (
                    "total_work_hours",
                    models.FloatField(default=0.0, verbose_name="總工作時數"),
                ),
                (
                    "total_overtime_hours",
                    models.FloatField(default=0.0, verbose_name="總加班時數"),
                ),
                (
                    "total_all_hours",
                    models.FloatField(default=0.0, verbose_name="全部總時數"),
                ),
                (
                    "total_good_quantity",
                    models.IntegerField(default=0, verbose_name="總合格品"),
                ),
                (
                    "total_defect_quantity",
                    models.IntegerField(default=0, verbose_name="總不良品"),
                ),
                (
                    "total_report_count",
                    models.IntegerField(default=0, verbose_name="報工次數"),
                ),
                (
                    "unique_operators",
                    models.JSONField(default=list, verbose_name="參與作業員"),
                ),
                (
                    "unique_equipment",
                    models.JSONField(default=list, verbose_name="使用設備"),
                ),
            ],
            options={
                "verbose_name": "已完工工單",
                "verbose_name_plural": "已完工工單",
                "db_table": "workorder_completed_workorder",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="CompletedProductionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="報工日期")),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                ("operator", models.CharField(max_length=100, verbose_name="作業員")),
                ("equipment", models.CharField(max_length=100, verbose_name="設備")),
                (
                    "work_quantity",
                    models.IntegerField(default=0, verbose_name="合格品數量"),
                ),
                (
                    "defect_quantity",
                    models.IntegerField(default=0, verbose_name="不良品數量"),
                ),
                ("work_hours", models.FloatField(default=0.0, verbose_name="工作時數")),
                (
                    "overtime_hours",
                    models.FloatField(default=0.0, verbose_name="加班時數"),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="開始時間"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="結束時間"
                    ),
                ),
                (
                    "report_source",
                    models.CharField(max_length=50, verbose_name="報工來源"),
                ),
                (
                    "report_type",
                    models.CharField(max_length=20, verbose_name="報工類型"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="備註"),
                ),
                (
                    "abnormal_notes",
                    models.TextField(blank=True, null=True, verbose_name="異常紀錄"),
                ),
                (
                    "approval_status",
                    models.CharField(
                        default="approved", max_length=20, verbose_name="審核狀態"
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="審核者"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="審核時間"),
                ),
                (
                    "completed_workorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_reports",
                        to="workorder.completedworkorder",
                        verbose_name="已完工工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "已完工生產報工記錄",
                "verbose_name_plural": "已完工生產報工記錄",
                "db_table": "workorder_completed_production_report",
                "ordering": ["report_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="CompletedWorkOrderProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                ("process_order", models.IntegerField(verbose_name="工序順序")),
                ("planned_quantity", models.IntegerField(verbose_name="計劃數量")),
                (
                    "completed_quantity",
                    models.IntegerField(default=0, verbose_name="完成數量"),
                ),
                (
                    "status",
                    models.CharField(
                        default="completed", max_length=20, verbose_name="工序狀態"
                    ),
                ),
                (
                    "assigned_operator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分配作業員"
                    ),
                ),
                (
                    "assigned_equipment",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分配設備"
                    ),
                ),
                (
                    "total_work_hours",
                    models.FloatField(default=0.0, verbose_name="工作時數"),
                ),
                (
                    "total_good_quantity",
                    models.IntegerField(default=0, verbose_name="合格品數量"),
                ),
                (
                    "total_defect_quantity",
                    models.IntegerField(default=0, verbose_name="不良品數量"),
                ),
                (
                    "report_count",
                    models.IntegerField(default=0, verbose_name="報工次數"),
                ),
                (
                    "operators",
                    models.JSONField(default=list, verbose_name="參與作業員"),
                ),
                ("equipment", models.JSONField(default=list, verbose_name="使用設備")),
                (
                    "completed_workorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processes",
                        to="workorder.completedworkorder",
                        verbose_name="已完工工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "已完工工單工序",
                "verbose_name_plural": "已完工工單工序",
                "db_table": "workorder_completed_workorder_process",
                "ordering": ["process_order"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="公司代號"
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=50, verbose_name="工單號碼"),
                ),
                (
                    "product_code",
                    models.CharField(max_length=100, verbose_name="產品編號"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="數量")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待生產"),
                            ("in_progress", "生產中"),
                            ("paused", "暫停"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "工單",
                "verbose_name_plural": "工單管理",
                "unique_together": {("company_code", "order_number", "product_code")},
            },
        ),
        migrations.CreateModel(
            name="WorkOrderAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_id",
                    models.CharField(max_length=50, verbose_name="分配設備ID"),
                ),
                (
                    "operator_id",
                    models.CharField(max_length=50, verbose_name="分配作業員ID"),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分配時間"),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="公司代號"
                    ),
                ),
                (
                    "workorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workorder.workorder",
                        verbose_name="工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "工單分配",
                "verbose_name_plural": "工單分配記錄",
                "db_table": "workorder_assignment",
            },
        ),
        migrations.CreateModel(
            name="WorkOrderProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                ("step_order", models.IntegerField(verbose_name="工序順序")),
                ("planned_quantity", models.IntegerField(verbose_name="計劃數量")),
                (
                    "completed_quantity",
                    models.IntegerField(default=0, verbose_name="完成數量"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待生產"),
                            ("in_progress", "生產中"),
                            ("completed", "已完成"),
                            ("paused", "暫停"),
                            ("cancelled", "取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "assigned_operator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分配作業員"
                    ),
                ),
                (
                    "assigned_equipment",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分配設備"
                    ),
                ),
                (
                    "actual_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="實際開始時間"
                    ),
                ),
                (
                    "actual_end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="實際結束時間"
                    ),
                ),
                (
                    "capacity_multiplier",
                    models.IntegerField(
                        default=1,
                        help_text="1=單人, 2=雙人, 3=三人...",
                        verbose_name="產能倍數",
                    ),
                ),
                (
                    "additional_operators",
                    models.TextField(
                        blank=True,
                        help_text="JSON格式儲存額外作業員清單",
                        null=True,
                        verbose_name="額外作業員",
                    ),
                ),
                (
                    "additional_equipments",
                    models.TextField(
                        blank=True,
                        help_text="JSON格式儲存額外設備清單",
                        null=True,
                        verbose_name="額外設備",
                    ),
                ),
                (
                    "target_hourly_output",
                    models.IntegerField(default=0, verbose_name="目標每小時產出"),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="預計工時",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "workorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processes",
                        to="workorder.workorder",
                        verbose_name="工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "工單工序明細",
                "verbose_name_plural": "工單工序明細",
                "ordering": ["workorder", "step_order"],
                "unique_together": {("workorder", "step_order")},
            },
        ),
        migrations.CreateModel(
            name="DispatchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="派工數量"),
                ),
                (
                    "created_by",
                    models.CharField(max_length=100, verbose_name="建立人員"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        help_text="派工時選擇的作業員，可空白",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="process.operator",
                        verbose_name="作業員",
                    ),
                ),
                (
                    "workorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_logs",
                        to="workorder.workorder",
                        verbose_name="工單",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_logs",
                        to="workorder.workorderprocess",
                        verbose_name="工序",
                    ),
                ),
            ],
            options={
                "verbose_name": "派工單記錄",
                "verbose_name_plural": "派工單記錄",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderProcessCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_operators",
                    models.IntegerField(default=1, verbose_name="最大作業員數"),
                ),
                (
                    "max_equipments",
                    models.IntegerField(default=1, verbose_name="最大設備數"),
                ),
                (
                    "target_hourly_output",
                    models.IntegerField(default=0, verbose_name="目標每小時產出"),
                ),
                (
                    "overtime_enabled",
                    models.BooleanField(default=False, verbose_name="啟用加班"),
                ),
                (
                    "parallel_work_enabled",
                    models.BooleanField(default=True, verbose_name="啟用並行作業"),
                ),
                (
                    "workorder_process",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacity",
                        to="workorder.workorderprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "工序產能設定",
                "verbose_name_plural": "工序產能設定",
                "db_table": "workorder_process_capacity",
            },
        ),
        migrations.CreateModel(
            name="WorkOrderProcessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("start", "開始生產"),
                            ("pause", "暫停生產"),
                            ("resume", "恢復生產"),
                            ("complete", "完成生產"),
                            ("quality_check", "品質檢查"),
                            ("equipment_change", "設備更換"),
                            ("operator_change", "作業員更換"),
                            ("quantity_update", "數量更新"),
                            ("note", "備註"),
                            ("auto_assignment", "自動分配"),
                            ("status_change", "狀態變更"),
                            ("quick_report", "快速報工"),
                        ],
                        max_length=50,
                        verbose_name="操作類型",
                    ),
                ),
                (
                    "quantity_before",
                    models.PositiveIntegerField(default=0, verbose_name="操作前數量"),
                ),
                (
                    "quantity_after",
                    models.PositiveIntegerField(default=0, verbose_name="操作後數量"),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="操作員"
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="設備"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備註")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="記錄時間"),
                ),
                (
                    "workorder_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="workorder.workorderprocess",
                        verbose_name="工單工序",
                    ),
                ),
            ],
            options={
                "verbose_name": "工單工序日誌",
                "verbose_name_plural": "工單工序日誌",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_production", "生產中"),
                            ("paused", "暫停"),
                            ("completed", "已完工"),
                        ],
                        default="in_production",
                        max_length=20,
                        verbose_name="生產狀態",
                    ),
                ),
                (
                    "production_start_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="生產開始時間"
                    ),
                ),
                (
                    "production_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="生產結束時間"
                    ),
                ),
                (
                    "current_process",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="當前工序"
                    ),
                ),
                (
                    "completed_processes",
                    models.TextField(
                        blank=True,
                        help_text="JSON格式記錄已完成的工序",
                        verbose_name="已完成工序",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "workorder",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_record",
                        to="workorder.workorder",
                        verbose_name="工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "生產中工單",
                "verbose_name_plural": "生產中工單",
                "db_table": "workorder_production",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="completedworkorder",
            name="production_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workorder.workorderproduction",
                verbose_name="生產記錄",
            ),
        ),
        migrations.CreateModel(
            name="WorkOrderProductionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                ("report_date", models.DateField(verbose_name="報工日期")),
                (
                    "report_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="報工時間"),
                ),
                (
                    "work_quantity",
                    models.IntegerField(default=0, verbose_name="合格品數量"),
                ),
                (
                    "defect_quantity",
                    models.IntegerField(default=0, verbose_name="不良品數量"),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="作業員"
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="設備"
                    ),
                ),
                (
                    "report_source",
                    models.CharField(
                        choices=[
                            ("operator", "作業員現場報工"),
                            ("operator_supplement", "作業員補登報工"),
                            ("smt", "SMT報工"),
                        ],
                        max_length=20,
                        verbose_name="報工來源",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="開始時間"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="結束時間"),
                ),
                ("work_hours", models.FloatField(default=0.0, verbose_name="工作時數")),
                (
                    "overtime_hours",
                    models.FloatField(default=0.0, verbose_name="加班時數"),
                ),
                (
                    "has_break",
                    models.BooleanField(default=False, verbose_name="是否有休息時間"),
                ),
                (
                    "break_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="休息開始時間"
                    ),
                ),
                (
                    "break_end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="休息結束時間"
                    ),
                ),
                (
                    "break_hours",
                    models.FloatField(default=0.0, verbose_name="休息時數"),
                ),
                (
                    "report_type",
                    models.CharField(
                        default="normal", max_length=20, verbose_name="報工類型"
                    ),
                ),
                (
                    "allocated_quantity",
                    models.IntegerField(default=0, verbose_name="分配數量"),
                ),
                (
                    "quantity_source",
                    models.CharField(
                        default="original", max_length=20, verbose_name="數量來源"
                    ),
                ),
                (
                    "allocation_notes",
                    models.TextField(blank=True, verbose_name="分配說明"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="是否已完工"),
                ),
                (
                    "completion_method",
                    models.CharField(
                        default="manual", max_length=20, verbose_name="完工判斷方式"
                    ),
                ),
                (
                    "auto_completed",
                    models.BooleanField(default=False, verbose_name="自動完工狀態"),
                ),
                (
                    "completion_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完工確認時間"
                    ),
                ),
                (
                    "cumulative_quantity",
                    models.IntegerField(default=0, verbose_name="累積完成數量"),
                ),
                (
                    "cumulative_hours",
                    models.FloatField(default=0.0, verbose_name="累積工時"),
                ),
                (
                    "approval_status",
                    models.CharField(
                        default="approved", max_length=20, verbose_name="核准狀態"
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="核准人員"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="核准時間"
                    ),
                ),
                (
                    "approval_remarks",
                    models.TextField(blank=True, verbose_name="核准備註"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="駁回原因"),
                ),
                (
                    "rejected_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="駁回人員"
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="駁回時間"
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="備註")),
                (
                    "abnormal_notes",
                    models.TextField(blank=True, verbose_name="異常記錄"),
                ),
                (
                    "original_report_id",
                    models.IntegerField(
                        blank=True,
                        help_text="對應的原始報工記錄ID",
                        null=True,
                        verbose_name="原始報工記錄ID",
                    ),
                ),
                (
                    "original_report_type",
                    models.CharField(
                        blank=True,
                        help_text="原始報工記錄的類型",
                        max_length=20,
                        null=True,
                        verbose_name="原始報工類型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "created_by",
                    models.CharField(
                        default="system", max_length=100, verbose_name="建立人員"
                    ),
                ),
                (
                    "workorder_production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_details",
                        to="workorder.workorderproduction",
                        verbose_name="生產中工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "生產報工明細",
                "verbose_name_plural": "生產報工明細",
                "db_table": "workorder_production_detail",
                "ordering": ["-report_date", "-report_time"],
            },
        ),
        migrations.AddIndex(
            model_name="completedworkorder",
            index=models.Index(
                fields=["order_number"], name="workorder_c_order_n_1c93e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="completedworkorder",
            index=models.Index(
                fields=["product_code"], name="workorder_c_product_915fe2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="completedworkorder",
            index=models.Index(
                fields=["company_code"], name="workorder_c_company_22bdc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="completedworkorder",
            index=models.Index(
                fields=["completed_at"], name="workorder_c_complet_20aa6b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="completedworkorder",
            unique_together={("order_number", "product_code")},
        ),
        migrations.AddIndex(
            model_name="workorderproductiondetail",
            index=models.Index(
                fields=["workorder_production", "process_name", "report_source"],
                name="idx_prod_detail_completion",
            ),
        ),
        migrations.AddIndex(
            model_name="workorderproductiondetail",
            index=models.Index(fields=["report_date"], name="idx_prod_detail_date"),
        ),
        migrations.AddIndex(
            model_name="workorderproductiondetail",
            index=models.Index(fields=["process_name"], name="idx_prod_detail_process"),
        ),
    ]
