# Generated by Django 5.1.8 on 2025-09-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FillWork",
        ),
    ]
