# Generated by Django 5.1.8 on 2025-06-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="company_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="公司代號"
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="order_number",
            field=models.CharField(max_length=50, verbose_name="製令單號"),
        ),
        migrations.AlterUniqueTogether(
            name="workorder",
            unique_together={("company_code", "order_number")},
        ),
    ]
