# Generated by Django 5.1.8 on 2025-08-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="完工時間"),
        ),
    ]
