# Generated by Django 5.1.8 on 2025-08-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0002_workorder_completed_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workorderproductiondetail",
            options={
                "ordering": ["process_name", "start_time", "report_time"],
                "verbose_name": "生產報工明細",
                "verbose_name_plural": "生產報工明細",
            },
        ),
        migrations.AddIndex(
            model_name="workorderproductiondetail",
            index=models.Index(
                fields=["start_time"], name="idx_prod_detail_start_time"
            ),
        ),
    ]
