# Generated by Django 5.1.8 on 2025-08-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0003_alter_workorderproductiondetail_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedproductionreport",
            name="allocated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="分配時間"),
        ),
        migrations.AddField(
            model_name="completedproductionreport",
            name="allocation_method",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="分配方式"
            ),
        ),
    ]
