# Generated by Django 5.1.8 on 2025-06-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0003_prdmkordmain_prdmkordmats"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="設定名稱"
                    ),
                ),
                ("value", models.CharField(max_length=100, verbose_name="設定值")),
            ],
            options={
                "verbose_name": "系統設定",
                "verbose_name_plural": "系統設定",
            },
        ),
    ]
