# Generated by Django 5.1.8 on 2025-06-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0004_systemconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="prdmkordmain",
            name="BillStatus",
            field=models.IntegerField(blank=True, null=True, verbose_name="單況"),
        ),
        migrations.AlterField(
            model_name="systemconfig",
            name="value",
            field=models.CharField(max_length=100, verbose_name="設定值（分鐘）"),
        ),
        migrations.CreateModel(
            name="CompanyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                ("mkordno", models.CharField(max_length=50, verbose_name="製令單號")),
                (
                    "product_id",
                    models.CharField(max_length=100, verbose_name="產品編號"),
                ),
                ("prodt_qty", models.PositiveIntegerField(verbose_name="生產數量")),
                (
                    "est_take_mat_date",
                    models.CharField(max_length=20, verbose_name="預定開工日"),
                ),
                (
                    "est_stock_out_date",
                    models.CharField(max_length=20, verbose_name="預定出貨日"),
                ),
                (
                    "complete_status",
                    models.IntegerField(blank=True, null=True, verbose_name="完工狀態"),
                ),
                (
                    "bill_status",
                    models.IntegerField(blank=True, null=True, verbose_name="單況"),
                ),
                (
                    "sync_time",
                    models.DateTimeField(auto_now=True, verbose_name="同步時間"),
                ),
                (
                    "is_converted",
                    models.BooleanField(default=False, verbose_name="已轉成 MES 工單"),
                ),
            ],
            options={
                "verbose_name": "公司製令單",
                "verbose_name_plural": "公司製令單",
                "unique_together": {("company_code", "mkordno")},
            },
        ),
    ]
