# Generated by Django 5.1.8 on 2025-08-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0004_completedproductionreport_allocated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoAllocationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        help_text="執行開始時間", verbose_name="開始時間"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="執行完成時間",
                        null=True,
                        verbose_name="完成時間",
                    ),
                ),
                (
                    "execution_time",
                    models.DurationField(
                        blank=True,
                        help_text="實際執行時間",
                        null=True,
                        verbose_name="執行時間",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=False, help_text="是否執行成功", verbose_name="執行成功"
                    ),
                ),
                (
                    "total_workorders",
                    models.IntegerField(
                        default=0,
                        help_text="本次處理的工單數量",
                        verbose_name="處理工單數",
                    ),
                ),
                (
                    "successful_allocations",
                    models.IntegerField(
                        default=0,
                        help_text="成功分配的工單數量",
                        verbose_name="成功分配數",
                    ),
                ),
                (
                    "failed_allocations",
                    models.IntegerField(
                        default=0,
                        help_text="分配失敗的工單數量",
                        verbose_name="失敗分配數",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="執行失敗時的錯誤訊息",
                        verbose_name="錯誤訊息",
                    ),
                ),
                (
                    "result_details",
                    models.JSONField(
                        blank=True,
                        help_text="執行的詳細結果資訊",
                        null=True,
                        verbose_name="詳細結果",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "自動分配執行記錄",
                "verbose_name_plural": "自動分配執行記錄",
                "db_table": "workorder_auto_allocation_log",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AutoAllocationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="是否啟用自動分配功能",
                        verbose_name="啟用自動執行",
                    ),
                ),
                (
                    "interval_minutes",
                    models.IntegerField(
                        default=30,
                        help_text="自動執行的間隔時間",
                        verbose_name="執行頻率（分鐘）",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        default="08:00",
                        help_text="允許執行的開始時間",
                        verbose_name="開始時間",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        default="18:00",
                        help_text="允許執行的結束時間",
                        verbose_name="結束時間",
                    ),
                ),
                (
                    "max_execution_time",
                    models.IntegerField(
                        default=30,
                        help_text="單次執行的最大時間限制",
                        verbose_name="最大執行時間（分鐘）",
                    ),
                ),
                (
                    "notification_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="是否啟用執行結果通知",
                        verbose_name="啟用通知",
                    ),
                ),
                (
                    "is_running",
                    models.BooleanField(
                        default=False,
                        help_text="當前是否正在執行",
                        verbose_name="正在執行",
                    ),
                ),
                (
                    "last_execution",
                    models.DateTimeField(
                        blank=True,
                        help_text="最近一次執行的時間",
                        null=True,
                        verbose_name="最後執行時間",
                    ),
                ),
                (
                    "next_execution",
                    models.DateTimeField(
                        blank=True,
                        help_text="預定的下次執行時間",
                        null=True,
                        verbose_name="下次執行時間",
                    ),
                ),
                (
                    "total_executions",
                    models.IntegerField(
                        default=0, help_text="累計執行次數", verbose_name="總執行次數"
                    ),
                ),
                (
                    "success_count",
                    models.IntegerField(
                        default=0, help_text="成功執行的次數", verbose_name="成功次數"
                    ),
                ),
                (
                    "failure_count",
                    models.IntegerField(
                        default=0, help_text="執行失敗的次數", verbose_name="失敗次數"
                    ),
                ),
                (
                    "total_execution_time",
                    models.DurationField(
                        blank=True,
                        help_text="累計執行時間",
                        null=True,
                        verbose_name="總執行時間",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "自動分配設定",
                "verbose_name_plural": "自動分配設定",
                "db_table": "workorder_auto_allocation_settings",
            },
        ),
    ]
