# Generated by Django 5.1.8 on 2025-06-28 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0005_prdmkordmain_billstatus_alter_systemconfig_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrderProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                ("step_order", models.IntegerField(verbose_name="工序順序")),
                (
                    "planned_quantity",
                    models.PositiveIntegerField(verbose_name="計劃數量"),
                ),
                (
                    "completed_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="完成數量"),
                ),
                (
                    "defective_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="不良數量"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待生產"),
                            ("in_progress", "生產中"),
                            ("completed", "已完成"),
                            ("paused", "暫停"),
                            ("cancelled", "取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="工序狀態",
                    ),
                ),
                (
                    "assigned_equipment",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分配設備"
                    ),
                ),
                (
                    "assigned_operator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分配作業員"
                    ),
                ),
                (
                    "planned_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="計劃開始時間"
                    ),
                ),
                (
                    "actual_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="實際開始時間"
                    ),
                ),
                (
                    "actual_end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="實際結束時間"
                    ),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="預估工時（分鐘）"
                    ),
                ),
                (
                    "actual_duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="實際工時（分鐘）"
                    ),
                ),
                ("capacity_per_hour", models.IntegerField(verbose_name="每小時產能")),
                (
                    "quality_notes",
                    models.TextField(blank=True, null=True, verbose_name="品質備註"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "workorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processes",
                        to="workorder.workorder",
                        verbose_name="工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "工單工序明細",
                "verbose_name_plural": "工單工序明細",
                "unique_together": {("workorder", "step_order")},
                "ordering": ["workorder", "step_order"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderProcessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("start", "開始生產"),
                            ("pause", "暫停生產"),
                            ("resume", "恢復生產"),
                            ("complete", "完成生產"),
                            ("quality_check", "品質檢查"),
                            ("equipment_change", "設備更換"),
                            ("operator_change", "作業員更換"),
                            ("quantity_update", "數量更新"),
                            ("note", "備註"),
                        ],
                        max_length=50,
                        verbose_name="操作類型",
                    ),
                ),
                (
                    "quantity_before",
                    models.PositiveIntegerField(default=0, verbose_name="操作前數量"),
                ),
                (
                    "quantity_after",
                    models.PositiveIntegerField(default=0, verbose_name="操作後數量"),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="操作員"
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="設備"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備註")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="記錄時間"),
                ),
                (
                    "workorder_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="workorder.workorderprocess",
                        verbose_name="工單工序",
                    ),
                ),
            ],
            options={
                "verbose_name": "工單工序日誌",
                "verbose_name_plural": "工單工序日誌",
            },
        ),
    ]
