# Generated by Django 5.1.8 on 2025-08-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0005_autoallocationlog_autoallocationsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoManagementConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function_type",
                    models.CharField(
                        choices=[
                            ("auto_completion_check", "完工判斷轉寫已完工"),
                            ("auto_quantity_allocation", "智能數量分配"),
                            ("auto_approval", "自動核准"),
                            ("auto_notification", "自動通知"),
                        ],
                        help_text="選擇要設定的自動化功能類型",
                        max_length=50,
                        verbose_name="功能類型",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="是否啟用此自動化功能",
                        verbose_name="是否啟用",
                    ),
                ),
                (
                    "interval_minutes",
                    models.IntegerField(
                        default=30,
                        help_text="設定自動化功能的執行間隔，以分鐘為單位",
                        verbose_name="執行間隔（分鐘）",
                    ),
                ),
                (
                    "last_execution",
                    models.DateTimeField(
                        blank=True,
                        help_text="記錄此功能最後執行的時間",
                        null=True,
                        verbose_name="最後執行時間",
                    ),
                ),
                (
                    "next_execution",
                    models.DateTimeField(
                        blank=True,
                        help_text="預估下次執行的時間",
                        null=True,
                        verbose_name="下次執行時間",
                    ),
                ),
                (
                    "execution_count",
                    models.IntegerField(
                        default=0,
                        help_text="記錄此功能已執行的次數",
                        verbose_name="執行次數",
                    ),
                ),
                (
                    "success_count",
                    models.IntegerField(
                        default=0,
                        help_text="記錄此功能成功執行的次數",
                        verbose_name="成功次數",
                    ),
                ),
                (
                    "error_count",
                    models.IntegerField(
                        default=0,
                        help_text="記錄此功能執行失敗的次數",
                        verbose_name="錯誤次數",
                    ),
                ),
                (
                    "last_error_message",
                    models.TextField(
                        blank=True,
                        help_text="記錄最後一次執行失敗的錯誤訊息",
                        verbose_name="最後錯誤訊息",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        default="system", max_length=100, verbose_name="建立人員"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "自動管理功能設定",
                "verbose_name_plural": "自動管理功能設定",
                "db_table": "workorder_auto_management_config",
                "ordering": ["function_type"],
                "unique_together": {("function_type",)},
            },
        ),
    ]
