# Generated by Django 5.1.8 on 2025-06-28 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0006_workorderprocess_workorderprocesslog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workorderprocesslog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "工單工序日誌",
                "verbose_name_plural": "工單工序日誌",
            },
        ),
        migrations.CreateModel(
            name="WorkOrderAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_id",
                    models.CharField(max_length=50, verbose_name="分配設備ID"),
                ),
                (
                    "operator_id",
                    models.CharField(max_length=50, verbose_name="分配作業員ID"),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分配時間"),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="公司代號"
                    ),
                ),
                (
                    "workorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workorder.workorder",
                        verbose_name="工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "工單分配",
                "verbose_name_plural": "工單分配記錄",
                "db_table": "workorder_assignment",
            },
        ),
    ]
