# Generated by Django 5.1.8 on 2025-08-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0006_automanagementconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automanagementconfig",
            name="function_type",
            field=models.CharField(
                choices=[
                    ("auto_completion_check", "完工判斷轉寫已完工"),
                    ("auto_approval", "自動核准"),
                    ("auto_notification", "自動通知"),
                ],
                help_text="選擇要設定的自動化功能類型",
                max_length=50,
                verbose_name="功能類型",
            ),
        ),
    ]
