# Generated by Django 5.1.8 on 2025-06-29 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0007_alter_workorderprocesslog_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrderProcessAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="作業員"
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="設備"
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分配時間"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否啟用"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備註")),
                (
                    "workorder_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="workorder.workorderprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "工序分配",
                "verbose_name_plural": "工序分配",
                "db_table": "workorder_process_assignment",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderProcessCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_operators",
                    models.IntegerField(default=1, verbose_name="最大作業員數"),
                ),
                (
                    "max_equipments",
                    models.IntegerField(default=1, verbose_name="最大設備數"),
                ),
                (
                    "target_hourly_output",
                    models.IntegerField(default=0, verbose_name="目標每小時產出"),
                ),
                (
                    "overtime_enabled",
                    models.BooleanField(default=False, verbose_name="啟用加班"),
                ),
                (
                    "parallel_work_enabled",
                    models.BooleanField(default=True, verbose_name="啟用並行作業"),
                ),
                (
                    "workorder_process",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacity",
                        to="workorder.workorderprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "工序產能設定",
                "verbose_name_plural": "工序產能設定",
                "db_table": "workorder_process_capacity",
            },
        ),
    ]
