# Generated by Django 5.1.8 on 2025-08-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0008_rename_auto_allocation_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="order_source",
            field=models.CharField(
                choices=[("erp", "ERP系統"), ("mes", "MES手動建立")],
                default="erp",
                help_text="工單來源：ERP系統同步或MES手動建立",
                max_length=10,
                verbose_name="工單來源",
            ),
        ),
    ]
