# Generated by Django 5.1.8 on 2025-06-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0008_workorderprocessassignment_workorderprocesscapacity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workorderprocess",
            name="actual_duration",
        ),
        migrations.RemoveField(
            model_name="workorderprocess",
            name="capacity_per_hour",
        ),
        migrations.RemoveField(
            model_name="workorderprocess",
            name="defective_quantity",
        ),
        migrations.RemoveField(
            model_name="workorderprocess",
            name="estimated_duration",
        ),
        migrations.RemoveField(
            model_name="workorderprocess",
            name="planned_start_time",
        ),
        migrations.RemoveField(
            model_name="workorderprocess",
            name="quality_notes",
        ),
        migrations.AddField(
            model_name="workorderprocess",
            name="additional_equipments",
            field=models.TextField(
                blank=True,
                help_text="JSON格式儲存額外設備清單",
                null=True,
                verbose_name="額外設備",
            ),
        ),
        migrations.AddField(
            model_name="workorderprocess",
            name="additional_operators",
            field=models.TextField(
                blank=True,
                help_text="JSON格式儲存額外作業員清單",
                null=True,
                verbose_name="額外作業員",
            ),
        ),
        migrations.AddField(
            model_name="workorderprocess",
            name="capacity_multiplier",
            field=models.IntegerField(
                default=1,
                help_text="1=單人, 2=雙人, 3=三人...",
                verbose_name="產能倍數",
            ),
        ),
        migrations.AddField(
            model_name="workorderprocess",
            name="estimated_hours",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="預計工時"
            ),
        ),
        migrations.AddField(
            model_name="workorderprocess",
            name="target_hourly_output",
            field=models.IntegerField(default=0, verbose_name="目標每小時產出"),
        ),
        migrations.AlterField(
            model_name="workorderprocess",
            name="completed_quantity",
            field=models.IntegerField(default=0, verbose_name="完成數量"),
        ),
        migrations.AlterField(
            model_name="workorderprocess",
            name="planned_quantity",
            field=models.IntegerField(verbose_name="計劃數量"),
        ),
        migrations.AlterField(
            model_name="workorderprocess",
            name="status",
            field=models.CharField(
                default="pending", max_length=20, verbose_name="狀態"
            ),
        ),
        migrations.DeleteModel(
            name="WorkOrderProcessAssignment",
        ),
    ]
