# Generated by Django 5.1.8 on 2025-08-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0009_add_order_source_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedworkorder",
            name="company_name",
            field=models.CharField(default="", max_length=100, verbose_name="公司名稱"),
        ),
        migrations.AddField(
            model_name="workorderproductiondetail",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="公司名稱"
            ),
        ),
        migrations.AddIndex(
            model_name="completedworkorder",
            index=models.Index(
                fields=["company_name"], name="workorder_c_company_90cd68_idx"
            ),
        ),
    ]
