# Generated by Django 5.1.8 on 2025-07-14 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0010_alter_workorderprocess_status_dispatchlog_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quicksupplementlog",
            options={
                "ordering": ["-supplement_time", "-created_at"],
                "verbose_name": "補登管理作業記錄",
                "verbose_name_plural": "補登管理作業記錄",
            },
        ),
    ]
