# Generated by Django 5.1.8 on 2025-08-15 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0010_completedworkorder_company_name_and_more"),
    ]

    operations = [
        # 先添加新的複合唯一約束
        migrations.RunSQL(
            sql="""
            ALTER TABLE workorder_completed_workorder 
            ADD CONSTRAINT workorder_completed_workorder_company_code_order_number_product_code_key 
            UNIQUE (company_code, order_number, product_code);
            """,
            reverse_sql="""
            ALTER TABLE workorder_completed_workorder 
            DROP CONSTRAINT IF EXISTS workorder_completed_workorder_company_code_order_number_product_code_key;
            """
        ),
    ]
