# Generated by Django 5.1.8 on 2025-07-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0011_alter_quicksupplementlog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="quicksupplementlog",
            name="defect_qty",
            field=models.PositiveIntegerField(
                default=0,
                help_text="本次操作產生的不良品數量",
                verbose_name="不良品數量",
            ),
        ),
    ]
