# Generated by Django 5.1.8 on 2025-08-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0012_add_company_code_to_completed_workorder"),
    ]

    operations = [
        # 移除現場報工相關資料表
        migrations.RunSQL(
            sql="""
            DROP TABLE IF EXISTS workorder_onsite_report CASCADE;
            DROP TABLE IF EXISTS workorder_smt_onsite_report CASCADE;
            """,
            reverse_sql="""
            -- 如果需要回滾，這裡可以重新建立資料表
            -- 但由於現場報工功能已移除，回滾時不重新建立
            """
        ),
    ] 