# Generated by Django 5.1.8 on 2025-08-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0013_remove_onsite_reporting_models"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="completedworkorder",
            unique_together=set(),
        ),
    ]
