# Generated by Django 5.1.8 on 2025-07-16 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0013_delete_quicksupplementlog"),
    ]

    operations = []
