# Generated by Django 5.1.8 on 2025-08-17 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0014_alter_completedworkorder_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="completedworkorder",
            unique_together={("company_code", "order_number", "product_code")},
        ),
        migrations.AlterUniqueTogether(
            name="workorderproductiondetail",
            unique_together={("workorder_production", "process_name", "report_date")},
        ),
    ]
