# Generated by Django 5.1.8 on 2025-08-17 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0015_alter_completedworkorder_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionMonitoringData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_work_hours", models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="總工作時數")),
                ("total_overtime_hours", models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="總加班時數")),
                ("total_all_hours", models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="總時數")),
                ("total_good_quantity", models.IntegerField(default=0, verbose_name="總良品數量")),
                ("total_defect_quantity", models.IntegerField(default=0, verbose_name="總不良品數量")),
                ("total_quantity", models.IntegerField(default=0, verbose_name="總數量")),
                ("packaging_good_quantity", models.IntegerField(default=0, verbose_name="出貨包裝良品數量")),
                ("packaging_defect_quantity", models.IntegerField(default=0, verbose_name="出貨包裝不良品數量")),
                ("packaging_total_quantity", models.IntegerField(default=0, verbose_name="出貨包裝總數量")),
                ("fillwork_report_count", models.IntegerField(default=0, verbose_name="填報記錄數量")),
                ("fillwork_approved_count", models.IntegerField(default=0, verbose_name="已核准填報數量")),
                ("fillwork_pending_count", models.IntegerField(default=0, verbose_name="待審核填報數量")),
                ("onsite_report_count", models.IntegerField(default=0, verbose_name="現場報工記錄數量")),
                ("onsite_completed_count", models.IntegerField(default=0, verbose_name="已完成現場報工數量")),
                ("total_processes", models.IntegerField(default=0, verbose_name="總工序數")),
                ("completed_processes", models.IntegerField(default=0, verbose_name="已完成工序數")),
                ("in_progress_processes", models.IntegerField(default=0, verbose_name="進行中工序數")),
                ("pending_processes", models.IntegerField(default=0, verbose_name="待開始工序數")),
                ("unique_operators", models.JSONField(default=list, verbose_name="參與作業員清單")),
                ("unique_equipment", models.JSONField(default=list, verbose_name="使用設備清單")),
                ("operator_count", models.IntegerField(default=0, verbose_name="參與作業員數量")),
                ("equipment_count", models.IntegerField(default=0, verbose_name="使用設備數量")),
                ("completion_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="完成率(%)")),
                ("packaging_completion_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="出貨包裝完成率(%)")),
                ("can_complete", models.BooleanField(default=False, verbose_name="可完工")),
                ("completion_threshold_met", models.BooleanField(default=False, verbose_name="達到完工閾值")),
                ("last_fillwork_update", models.DateTimeField(blank=True, null=True, verbose_name="最後填報更新時間")),
                ("last_onsite_update", models.DateTimeField(blank=True, null=True, verbose_name="最後現場報工更新時間")),
                ("last_process_update", models.DateTimeField(blank=True, null=True, verbose_name="最後工序更新時間")),
                ("last_updated", models.DateTimeField(auto_now=True, verbose_name="最後更新時間")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="建立時間")),
                ("workorder", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="production_monitoring_data", to="workorder.workorder", verbose_name="工單")),
            ],
            options={
                "verbose_name": "生產中工單監控資料",
                "verbose_name_plural": "生產中工單監控資料",
                "db_table": "workorder_production_monitoring_data",
            },
        ),
        migrations.AlterUniqueTogether(
            name="productionmonitoringdata",
            unique_together={("workorder",)},
        ),
        migrations.AddIndex(
            model_name="productionmonitoringdata",
            index=models.Index(fields=["workorder", "can_complete"], name="workorder_p_workord_123456_idx"),
        ),
        migrations.AddIndex(
            model_name="productionmonitoringdata",
            index=models.Index(fields=["completion_threshold_met"], name="workorder_p_complet_789012_idx"),
        ),
        migrations.AddIndex(
            model_name="productionmonitoringdata",
            index=models.Index(fields=["last_updated"], name="workorder_p_last_up_345678_idx"),
        ),
    ]
