# Generated by Django 5.1.8 on 2025-08-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0015_alter_completedworkorder_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="autoallocationsettings",
            name="completed_workorder_allocation_enabled",
            field=models.BooleanField(
                default=False,
                help_text="是否啟用已完工工單工序紀錄數量自動分配",
                verbose_name="啟用已完工工單數量分配",
            ),
        ),
        migrations.AddField(
            model_name="autoallocationsettings",
            name="completed_workorder_allocation_interval",
            field=models.IntegerField(
                default=60,
                help_text="已完工工單數量分配的執行間隔時間",
                verbose_name="已完工工單分配執行頻率（分鐘）",
            ),
        ),
        migrations.AddField(
            model_name="completedproductionreport",
            name="is_system_allocated",
            field=models.BooleanField(
                default=False,
                help_text="標記此數量是否為系統自動分配",
                verbose_name="系統分配標記",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="completedworkorder",
            unique_together={("company_code", "order_number")},
        ),
        migrations.AlterUniqueTogether(
            name="workorder",
            unique_together={("company_code", "order_number")},
        ),
    ]
