# Generated by Django 5.1.8 on 2025-08-17 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0015_alter_completedworkorder_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductionMonitoringData",
        ),
    ]
