# Generated by Django 5.1.8 on 2025-08-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0016_fix_completed_workorder_constraints"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="completedworkorder",
            unique_together={("company_code", "order_number", "product_code")},
        ),
        migrations.AlterUniqueTogether(
            name="workorder",
            unique_together={("company_code", "order_number", "product_code")},
        ),
    ]
