# Generated by Django 5.1.8 on 2025-07-17 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0013_delete_quicksupplementlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickSupplementLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(max_length=100, verbose_name="產品編號"),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("complete", "完成"),
                            ("pause", "暫停"),
                            ("resume", "恢復"),
                        ],
                        default="complete",
                        max_length=50,
                        verbose_name="操作類型",
                    ),
                ),
                ("supplement_time", models.DateTimeField(verbose_name="補登時間")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="結束時間"
                    ),
                ),
                (
                    "completed_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="完成數量"),
                ),
                (
                    "defect_qty",
                    models.PositiveIntegerField(default=0, verbose_name="不良數量"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備註")),
                (
                    "created_by",
                    models.CharField(max_length=100, verbose_name="建立人員"),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="作業員"
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="設備"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="已核准"),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="核准人員"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="核准時間"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quick_supplements",
                        to="workorder.workorderprocess",
                        verbose_name="工序",
                    ),
                ),
                (
                    "workorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quick_supplements",
                        to="workorder.workorder",
                        verbose_name="工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "快速補登記錄",
                "verbose_name_plural": "快速補登記錄",
                "ordering": ["-supplement_time"],
            },
        ),
    ]
