# Generated by Django 5.1.8 on 2025-08-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0017_alter_completedworkorder_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workorderprocess",
            options={
                "ordering": ["workorder_id", "step_order"],
                "verbose_name": "工單工序明細",
                "verbose_name_plural": "工單工序明細",
            },
        ),
        migrations.RemoveIndex(
            model_name="workorderproductiondetail",
            name="idx_prod_detail_completion",
        ),
        migrations.RemoveField(
            model_name="completedproductionreport",
            name="completed_workorder",
        ),
        migrations.RemoveField(
            model_name="completedworkorder",
            name="production_record",
        ),
        migrations.RemoveField(
            model_name="completedworkorderprocess",
            name="completed_workorder",
        ),
        migrations.RemoveField(
            model_name="dispatchlog",
            name="operator",
        ),
        migrations.RemoveField(
            model_name="dispatchlog",
            name="process",
        ),
        migrations.RemoveField(
            model_name="dispatchlog",
            name="workorder",
        ),
        migrations.RemoveField(
            model_name="workorderassignment",
            name="workorder",
        ),
        migrations.AlterUniqueTogether(
            name="workorderprocess",
            unique_together={("workorder_id", "step_order")},
        ),
        migrations.RemoveField(
            model_name="workorderprocesscapacity",
            name="workorder_process",
        ),
        migrations.RemoveField(
            model_name="workorderprocesslog",
            name="workorder_process",
        ),
        migrations.RemoveField(
            model_name="workorderproduction",
            name="workorder",
        ),
        migrations.AlterUniqueTogether(
            name="workorderproductiondetail",
            unique_together={
                ("workorder_production_id", "process_name", "report_date")
            },
        ),
        migrations.AddField(
            model_name="completedproductionreport",
            name="completed_workorder_id",
            field=models.IntegerField(default=0, verbose_name="已完工工單ID"),
        ),
        migrations.AddField(
            model_name="completedworkorder",
            name="production_record_id",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="生產記錄ID"
            ),
        ),
        migrations.AddField(
            model_name="completedworkorderprocess",
            name="completed_workorder_id",
            field=models.IntegerField(default=0, verbose_name="已完工工單ID"),
        ),
        migrations.AddField(
            model_name="dispatchlog",
            name="operator_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="作業員ID"),
        ),
        migrations.AddField(
            model_name="dispatchlog",
            name="process_id",
            field=models.IntegerField(default=0, verbose_name="工序ID"),
        ),
        migrations.AddField(
            model_name="dispatchlog",
            name="workorder_id",
            field=models.IntegerField(default=0, verbose_name="工單ID"),
        ),
        migrations.AddField(
            model_name="workorderassignment",
            name="workorder_id",
            field=models.IntegerField(default=0, verbose_name="工單ID"),
        ),
        migrations.AddField(
            model_name="workorderprocess",
            name="workorder_id",
            field=models.IntegerField(default=0, verbose_name="工單ID"),
        ),
        migrations.AddField(
            model_name="workorderprocesscapacity",
            name="workorder_process_id",
            field=models.IntegerField(
                default=0, unique=True, verbose_name="工單工序ID"
            ),
        ),
        migrations.AddField(
            model_name="workorderprocesslog",
            name="workorder_process_id",
            field=models.IntegerField(default=0, verbose_name="工單工序ID"),
        ),
        migrations.AddField(
            model_name="workorderproduction",
            name="workorder_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="工單ID"
            ),
        ),
        migrations.AddField(
            model_name="workorderproductiondetail",
            name="workorder_production_id",
            field=models.IntegerField(default=0, verbose_name="生產中工單ID"),
        ),
        migrations.AddIndex(
            model_name="workorderproductiondetail",
            index=models.Index(
                fields=["workorder_production_id", "process_name", "report_source"],
                name="idx_prod_detail_completion",
            ),
        ),
        migrations.RemoveField(
            model_name="workorderprocess",
            name="workorder",
        ),
        migrations.RemoveField(
            model_name="workorderproductiondetail",
            name="workorder_production",
        ),
    ]
