# Generated by Django 5.1.8 on 2025-08-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0017_alter_completedworkorder_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workorderprocess",
            options={
                "ordering": ["workorder_id", "step_order"],
                "verbose_name": "工單工序明細",
                "verbose_name_plural": "工單工序明細",
            },
        ),
        migrations.RemoveIndex(
            model_name="workorderproductiondetail",
            name="idx_prod_detail_completion",
        ),
        migrations.RemoveField(
            model_name="completedproductionreport",
            name="completed_workorder",
        ),
        migrations.RemoveField(
            model_name="completedworkorder",
            name="production_record",
        ),
        migrations.RemoveField(
            model_name="completedworkorderprocess",
            name="completed_workorder",
        ),
        migrations.RemoveField(
            model_name="dispatchlog",
            name="operator",
        ),
        migrations.RemoveField(
            model_name="dispatchlog",
            name="process",
        ),
        migrations.RemoveField(
            model_name="dispatchlog",
            name="workorder",
        ),
        migrations.RemoveField(
            model_name="workorderassignment",
            name="workorder",
        ),
        migrations.AlterUniqueTogether(
            name="workorderprocess",
            unique_together={("workorder_id", "step_order")},
        ),
        migrations.RemoveField(
            model_name="workorderprocesscapacity",
            name="workorder_process",
        ),
        migrations.RemoveField(
            model_name="workorderprocesslog",
            name="workorder_process",
        ),
        migrations.RemoveField(
            model_name="workorderproduction",
            name="workorder",
        ),
        migrations.AlterUniqueTogether(
            name="workorderproductiondetail",
            unique_together={
                ("workorder_production_id", "process_name", "report_date")
            },
        ),
        migrations.AddField(
            model_name="completedproductionreport",
            name="completed_workorder_id",
            field=models.IntegerField(default=0, verbose_name="已完工工單ID"),
        ),
        migrations.AddField(
            model_name="completedworkorder",
            name="production_record_id",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="生產記錄ID"
            ),
        ),
        migrations.AddField(
            model_name="completedworkorderprocess",
            name="completed_workorder_id",
            field=models.IntegerField(default=0, verbose_name="已完工工單ID"),
        ),
        migrations.AddField(
            model_name="dispatchlog",
            name="operator_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="作業員ID"),
        ),
        migrations.AddField(
            model_name="dispatchlog",
            name="process_id",
            field=models.IntegerField(default=0, verbose_name="工序ID"),
        ),
        migrations.AddField(
            model_name="dispatchlog",
            name="workorder_id",
            field=models.IntegerField(default=0, verbose_name="工單ID"),
        ),
        migrations.AddField(
            model_name="workorderassignment",
            name="workorder_id",
            field=models.IntegerField(default=0, verbose_name="工單ID"),
        ),
        # 添加欄位存在性檢查的遷移
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                -- 檢查並添加 workorder_id 欄位到 workorderprocess
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'workorder_workorderprocess' AND column_name = 'workorder_id') THEN
                    ALTER TABLE workorder_workorderprocess ADD COLUMN workorder_id integer DEFAULT 0;
                END IF;
                
                -- 檢查並添加 workorder_process_id 欄位到 workorderprocesscapacity
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'workorder_workorderprocesscapacity' AND column_name = 'workorder_process_id') THEN
                    ALTER TABLE workorder_workorderprocesscapacity ADD COLUMN workorder_process_id integer DEFAULT 0 UNIQUE;
                END IF;
                
                -- 檢查並添加 workorder_process_id 欄位到 workorderprocesslog
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'workorder_workorderprocesslog' AND column_name = 'workorder_process_id') THEN
                    ALTER TABLE workorder_workorderprocesslog ADD COLUMN workorder_process_id integer DEFAULT 0;
                END IF;
                
                -- 檢查並添加 workorder_id 欄位到 workorderproduction
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'workorder_workorderproduction' AND column_name = 'workorder_id') THEN
                    ALTER TABLE workorder_workorderproduction ADD COLUMN workorder_id integer DEFAULT NULL UNIQUE;
                END IF;
                
                -- 檢查並添加 workorder_production_id 欄位到 workorderproductiondetail
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'workorder_workorderproductiondetail' AND column_name = 'workorder_production_id') THEN
                    ALTER TABLE workorder_workorderproductiondetail ADD COLUMN workorder_production_id integer DEFAULT 0;
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                -- 移除添加的欄位（如果需要回滾）
                IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'workorder_workorderprocess' AND column_name = 'workorder_id') THEN
                    ALTER TABLE workorder_workorderprocess DROP COLUMN workorder_id;
                END IF;
                
                IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'workorder_workorderprocesscapacity' AND column_name = 'workorder_process_id') THEN
                    ALTER TABLE workorder_workorderprocesscapacity DROP COLUMN workorder_process_id;
                END IF;
                
                IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'workorder_workorderprocesslog' AND column_name = 'workorder_process_id') THEN
                    ALTER TABLE workorder_workorderprocesslog DROP COLUMN workorder_process_id;
                END IF;
                
                IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'workorder_workorderproduction' AND column_name = 'workorder_id') THEN
                    ALTER TABLE workorder_workorderproduction DROP COLUMN workorder_id;
                END IF;
                
                IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'workorder_workorderproductiondetail' AND column_name = 'workorder_production_id') THEN
                    ALTER TABLE workorder_workorderproductiondetail DROP COLUMN workorder_production_id;
                END IF;
            END $$;
            """
        ),
        migrations.AddIndex(
            model_name="workorderproductiondetail",
            index=models.Index(
                fields=["workorder_production_id", "process_name", "report_source"],
                name="idx_prod_detail_completion",
            ),
        ),
        migrations.RemoveField(
            model_name="workorderprocess",
            name="workorder",
        ),
        migrations.RemoveField(
            model_name="workorderproductiondetail",
            name="workorder_production",
        ),
    ]
