# Generated by Django 5.1.8 on 2025-08-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0018_alter_workorderprocess_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsistencyCheckResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("missing_fill_work", "缺失填報紀錄"),
                            ("missing_dispatch", "缺失派工單"),
                            ("wrong_product_code", "產品編號錯誤"),
                            ("wrong_company", "公司代號/名稱錯誤"),
                            ("wrong_workorder", "工單號碼錯誤"),
                        ],
                        max_length=50,
                        verbose_name="檢查類型",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="公司代號"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="公司名稱"
                    ),
                ),
                (
                    "workorder",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="工單號碼"
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="產品編號"
                    ),
                ),
                (
                    "wrong_company_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="錯誤公司代號",
                    ),
                ),
                (
                    "wrong_company_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="錯誤公司名稱",
                    ),
                ),
                (
                    "wrong_workorder",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="錯誤工單號碼",
                    ),
                ),
                (
                    "wrong_product_code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="錯誤產品編號",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="作業員"
                    ),
                ),
                (
                    "work_date",
                    models.DateField(blank=True, null=True, verbose_name="工作日期"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="狀態"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(blank=True, null=True, verbose_name="數量"),
                ),
                (
                    "is_fixed",
                    models.BooleanField(default=False, verbose_name="是否已修復"),
                ),
                (
                    "fixed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="修復時間"
                    ),
                ),
                (
                    "fixed_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="修復人員"
                    ),
                ),
                (
                    "fix_method",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="修復方式"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "相符性檢查結果",
                "verbose_name_plural": "相符性檢查結果",
                "db_table": "workorder_consistency_check_result",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["check_type"], name="workorder_c_check_t_d3d1c7_idx"
                    ),
                    models.Index(
                        fields=["company_code"], name="workorder_c_company_06de34_idx"
                    ),
                    models.Index(
                        fields=["workorder"], name="workorder_c_workord_9543c9_idx"
                    ),
                    models.Index(
                        fields=["product_code"], name="workorder_c_product_6f9b66_idx"
                    ),
                    models.Index(
                        fields=["is_fixed"], name="workorder_c_is_fixe_6d90ec_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="workorder_c_created_dd8244_idx"
                    ),
                ],
            },
        ),
    ]
