# Generated by Django 5.1.8 on 2025-07-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0018_quicksupplementlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorderprocesslog",
            name="action",
            field=models.CharField(
                choices=[
                    ("start", "開始生產"),
                    ("pause", "暫停生產"),
                    ("resume", "恢復生產"),
                    ("complete", "完成生產"),
                    ("quality_check", "品質檢查"),
                    ("equipment_change", "設備更換"),
                    ("operator_change", "作業員更換"),
                    ("quantity_update", "數量更新"),
                    ("note", "備註"),
                    ("auto_assignment", "自動分配"),
                ],
                max_length=50,
                verbose_name="操作類型",
            ),
        ),
    ]
