# Generated by Django 5.1.8 on 2025-08-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0019_consistencycheckresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="設定名稱",
                        max_length=50,
                        unique=True,
                        verbose_name="設定名稱",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="設定值", max_length=100, verbose_name="設定值"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="設定說明", verbose_name="設定說明"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="建立時間", verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="更新時間", verbose_name="更新時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "系統設定",
                "verbose_name_plural": "系統設定",
                "db_table": "workorder_system_config",
                "ordering": ["key"],
            },
        ),
    ]
