# Generated by Django 5.1.8 on 2025-08-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0019_consistencycheckresult"),
    ]

    operations = [
        # 只刪除實際存在的模型，避免遷移錯誤
        # 已完工工單相關模型已移至 workorder_completed_workorder 子模組
    ]
