# Generated by Django 5.1.8 on 2025-07-18 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0002_fix_additional_fields_nullable"),
        ("workorder", "0020_alter_workorderprocesslog_action"),
    ]

    operations = []
