# Generated by Django 5.1.8 on 2025-08-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0020_auto_20250820_1622"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AutoAllocationLog",
        ),
        migrations.DeleteModel(
            name="AutoAllocationSettings",
        ),
        migrations.DeleteModel(
            name="CompletedProductionReport",
        ),
        migrations.DeleteModel(
            name="CompletedWorkOrder",
        ),
        migrations.DeleteModel(
            name="CompletedWorkOrderProcess",
        ),
        migrations.DeleteModel(
            name="DispatchLog",
        ),
    ]
