# Generated by Django 5.1.8 on 2025-07-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0014_merge_20250716_1631"),
        ("workorder", "0021_merge_20250718_1129"),
    ]

    operations = []
