# Generated by Django 5.1.8 on 2025-08-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0022_add_fix_data_to_consistency_check_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="packaging_completed_quantity",
            field=models.IntegerField(
                default=0,
                help_text="包含填報記錄和現場報工的出貨包裝總數量，用於快速完工判斷",
                verbose_name="出貨包裝累計數量",
            ),
        ),
    ]
