# Generated by Django 5.1.8 on 2025-08-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0023_add_packaging_completed_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workorder",
            name="packaging_completed_quantity",
        ),
    ]
