# Generated by Django 5.1.8 on 2025-07-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0023_smtproductionreport"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QuickSupplementLog",
        ),
    ]
