# Generated by Django 5.1.8 on 2025-08-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0024_remove_workorder_packaging_completed_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consistencycheckresult",
            name="check_type",
            field=models.CharField(
                choices=[
                    ("missing_fill_work", "缺失填報紀錄"),
                    ("missing_dispatch", "填報異常"),
                    ("wrong_product_code", "產品編號錯誤"),
                    ("wrong_company", "公司代號/名稱錯誤"),
                    ("wrong_workorder", "工單號碼錯誤"),
                ],
                max_length=50,
                verbose_name="檢查類型",
            ),
        ),
    ]
