# Generated by Django 5.1.8 on 2025-07-20 04:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0012_remove_equipmentnotification_equipment_and_more"),
        ("workorder", "0024_delete_quicksupplementlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="smtproductionreport",
            options={
                "ordering": ["-work_date", "-start_time"],
                "verbose_name": "SMT 補登報工記錄",
                "verbose_name_plural": "SMT 補登報工記錄",
            },
        ),
        migrations.RemoveField(
            model_name="smtproductionreport",
            name="hours",
        ),
        migrations.RemoveField(
            model_name="smtproductionreport",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="smtproductionreport",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="smtproductionreport",
            name="report_time",
        ),
        migrations.AddField(
            model_name="smtproductionreport",
            name="created_by",
            field=models.CharField(
                default="system", max_length=100, verbose_name="建立人員"
            ),
        ),
        migrations.AddField(
            model_name="smtproductionreport",
            name="defect_quantity",
            field=models.IntegerField(
                default=0,
                help_text="請輸入本次生產中產生的不良品數量，若無則留空或填寫0",
                verbose_name="不良品數量",
            ),
        ),
        migrations.AddField(
            model_name="smtproductionreport",
            name="end_time",
            field=models.TimeField(
                default=django.utils.timezone.now,
                help_text="請輸入實際結束時間 (24小時制)，例如 18:30",
                verbose_name="結束時間",
            ),
        ),
        migrations.AddField(
            model_name="smtproductionreport",
            name="is_completed",
            field=models.BooleanField(
                default=False,
                help_text="若此工單在此工序上已全部完成，請勾選",
                verbose_name="是否已完工",
            ),
        ),
        migrations.AddField(
            model_name="smtproductionreport",
            name="operation",
            field=models.CharField(
                default="",
                help_text="請選擇此次補登的SMT工序",
                max_length=100,
                verbose_name="工序",
            ),
        ),
        migrations.AddField(
            model_name="smtproductionreport",
            name="planned_quantity",
            field=models.IntegerField(
                default=0,
                help_text="此為工單規劃的總生產數量，不可修改",
                verbose_name="工單預設生產數量",
            ),
        ),
        migrations.AddField(
            model_name="smtproductionreport",
            name="product_id",
            field=models.CharField(
                default="",
                help_text="請選擇產品編號，將自動帶出相關工單",
                max_length=100,
                verbose_name="產品編號",
            ),
        ),
        migrations.AddField(
            model_name="smtproductionreport",
            name="remarks",
            field=models.TextField(
                blank=True,
                help_text="請輸入任何需要補充的資訊，如異常、停機等",
                verbose_name="備註",
            ),
        ),
        migrations.AddField(
            model_name="smtproductionreport",
            name="start_time",
            field=models.TimeField(
                default=django.utils.timezone.now,
                help_text="請輸入實際開始時間 (24小時制)，例如 16:00",
                verbose_name="開始時間",
            ),
        ),
        migrations.AddField(
            model_name="smtproductionreport",
            name="work_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="請選擇實際報工日期",
                verbose_name="日期",
            ),
        ),
        migrations.AddField(
            model_name="smtproductionreport",
            name="work_quantity",
            field=models.IntegerField(
                default=0,
                help_text="請輸入該時段內實際完成的合格產品數量",
                verbose_name="工作數量",
            ),
        ),
        migrations.AlterField(
            model_name="smtproductionreport",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                help_text="請選擇本次報工使用的SMT設備",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="equip.equipment",
                verbose_name="設備",
            ),
        ),
        migrations.AlterField(
            model_name="smtproductionreport",
            name="workorder",
            field=models.ForeignKey(
                blank=True,
                help_text="請選擇工單號碼，或透過產品編號自動帶出",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workorder.workorder",
                verbose_name="工單號碼",
            ),
        ),
    ]
