# Generated by Django 5.1.8 on 2025-08-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0025_update_missing_dispatch_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedproductionreport",
            name="allocation_method",
            field=models.CharField(
                blank=True,
                default="manual",
                max_length=50,
                null=True,
                verbose_name="分配方式",
            ),
        ),
    ]
