# Generated by Django 5.1.8 on 2025-07-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0025_alter_smtproductionreport_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smtproductionreport",
            name="production_status",
        ),
    ]
