# Generated by Django 5.1.8 on 2025-08-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0026_alter_completedproductionreport_allocation_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderprocess",
            name="workorder_id",
            field=models.IntegerField(default=0, verbose_name="工單ID"),
        ),
        migrations.AddField(
            model_name="workorderprocesscapacity",
            name="workorder_process_id",
            field=models.IntegerField(
                default=0, unique=True, verbose_name="工單工序ID"
            ),
        ),
        migrations.AddField(
            model_name="workorderprocesslog",
            name="workorder_process_id",
            field=models.IntegerField(default=0, verbose_name="工單工序ID"),
        ),
        migrations.AddField(
            model_name="workorderproduction",
            name="workorder_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="工單ID"
            ),
        ),
        migrations.AddField(
            model_name="workorderproductiondetail",
            name="workorder_production_id",
            field=models.IntegerField(default=0, verbose_name="生產中工單ID"),
        ),
    ]
