# Generated by Django 5.1.8 on 2025-07-21 05:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0012_alter_productprocessstandardcapacity_is_active_and_more"),
        ("workorder", "0027_smtproductionreport_approval_remarks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待生產"),
                    ("in_progress", "生產中"),
                    ("paused", "暫停"),
                    ("completed", "已完成"),
                ],
                default="pending",
                max_length=20,
                verbose_name="狀態",
            ),
        ),
        migrations.AlterField(
            model_name="workorderprocesslog",
            name="action",
            field=models.CharField(
                choices=[
                    ("start", "開始生產"),
                    ("pause", "暫停生產"),
                    ("resume", "恢復生產"),
                    ("complete", "完成生產"),
                    ("quality_check", "品質檢查"),
                    ("equipment_change", "設備更換"),
                    ("operator_change", "作業員更換"),
                    ("quantity_update", "數量更新"),
                    ("note", "備註"),
                    ("auto_assignment", "自動分配"),
                    ("status_change", "狀態變更"),
                    ("quick_report", "快速報工"),
                ],
                max_length=50,
                verbose_name="操作類型",
            ),
        ),
        migrations.CreateModel(
            name="OperatorSupplementReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="請選擇實際報工日期",
                        verbose_name="日期",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        default=django.utils.timezone.now,
                        help_text="請輸入實際開始時間 (24小時制)，例如 16:00",
                        verbose_name="開始時間",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        default=django.utils.timezone.now,
                        help_text="請輸入實際結束時間 (24小時制)，例如 18:30",
                        verbose_name="結束時間",
                    ),
                ),
                (
                    "work_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="請輸入該時段內實際完成的合格產品數量",
                        verbose_name="工作數量",
                    ),
                ),
                (
                    "defect_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="請輸入本次生產中產生的不良品數量，若無則留空或填寫0",
                        verbose_name="不良品數量",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="若此工單在此工序上已全部完成，請勾選",
                        verbose_name="是否已完工",
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待審核"),
                            ("approved", "已審核"),
                            ("rejected", "已駁回"),
                        ],
                        default="draft",
                        help_text="補登記錄的審核狀態，已審核的記錄不可修改",
                        max_length=20,
                        verbose_name="審核狀態",
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True,
                        help_text="審核此補登記錄的人員",
                        max_length=100,
                        null=True,
                        verbose_name="審核人員",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="此補登記錄的審核時間",
                        null=True,
                        verbose_name="審核時間",
                    ),
                ),
                (
                    "approval_remarks",
                    models.TextField(
                        blank=True,
                        help_text="審核時的備註說明",
                        verbose_name="審核備註",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="駁回時的原因說明",
                        verbose_name="駁回原因",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="請輸入任何需要補充的資訊，如異常、停機等",
                        verbose_name="備註",
                    ),
                ),
                (
                    "abnormal_notes",
                    models.TextField(
                        blank=True,
                        help_text="記錄生產過程中的異常情況",
                        verbose_name="異常記錄",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        default="system", max_length=100, verbose_name="建立人員"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        help_text="請選擇進行補登報工的作業員",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process.operator",
                        verbose_name="作業員",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        help_text="請選擇此次補登的工序（排除SMT相關工序）",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process.processname",
                        verbose_name="工序",
                    ),
                ),
                (
                    "workorder",
                    models.ForeignKey(
                        help_text="請選擇要補登的工單號碼",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workorder.workorder",
                        verbose_name="工單號碼",
                    ),
                ),
            ],
            options={
                "verbose_name": "作業員補登報工記錄",
                "verbose_name_plural": "作業員補登報工記錄",
                "db_table": "workorder_operator_supplement_report",
                "ordering": ["-work_date", "-start_time"],
            },
        ),
    ]
