# Generated by Django 5.1.8 on 2025-08-28 00:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0027_workorderprocess_workorder_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrderOperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="時間戳"
                    ),
                ),
                ("user", models.CharField(max_length=150, verbose_name="用戶")),
                ("action", models.CharField(max_length=255, verbose_name="操作")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 地址"
                    ),
                ),
                (
                    "details",
                    models.TextField(blank=True, null=True, verbose_name="細節"),
                ),
                (
                    "workorder_related",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workorder.workorder",
                        verbose_name="關聯工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "工單操作日誌",
                "verbose_name_plural": "工單操作日誌",
                "db_table": "workorder_operation_log",
                "default_permissions": (),
            },
        ),
    ]
