# Generated by Django 5.1.8 on 2025-08-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0028_workorderoperationlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedworkorder",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="完工時間"),
        ),
    ]
