# Generated by Django 5.1.8 on 2025-07-21 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0012_remove_equipmentnotification_equipment_and_more"),
        ("workorder", "0028_alter_workorder_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                help_text="請選擇此次補登的設備（排除SMT相關設備）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="equip.equipment",
                verbose_name="設備",
            ),
        ),
    ]
