# Generated by Django 5.1.8 on 2025-07-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0029_operatorsupplementreport_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="planned_quantity",
            field=models.IntegerField(
                default=0,
                help_text="此為工單規劃的總生產數量，不可修改",
                verbose_name="工單預設生產數量",
            ),
        ),
    ]
