# Generated by Django 5.1.8 on 2025-07-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0034_managerproductionreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="smtproductionreport",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="駁回時的原因說明", verbose_name="駁回原因"
            ),
        ),
    ]
