# Generated by Django 5.1.8 on 2025-07-22 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0035_smtproductionreport_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="rd_project_name",
            field=models.CharField(
                blank=True,
                help_text="請輸入RD樣品所屬的專案名稱",
                max_length=200,
                null=True,
                verbose_name="專案名稱",
            ),
        ),
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="rd_sample_code",
            field=models.CharField(
                blank=True,
                help_text="請輸入RD樣品的專用編號",
                max_length=100,
                null=True,
                verbose_name="RD樣品編號",
            ),
        ),
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="report_type",
            field=models.CharField(
                choices=[("normal", "正式工單"), ("rd_sample", "RD樣品")],
                default="normal",
                help_text="請選擇報工類型：正式工單或RD樣品",
                max_length=20,
                verbose_name="報工類型",
            ),
        ),
        migrations.AlterField(
            model_name="operatorsupplementreport",
            name="workorder",
            field=models.ForeignKey(
                blank=True,
                help_text="請選擇要補登的工單號碼",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workorder.workorder",
                verbose_name="工單號碼",
            ),
        ),
    ]
