# Generated by Django 5.1.8 on 2025-07-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0037_operatorsupplementreport_rd_sample_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="smtproductionreport",
            options={
                "ordering": ["-work_date", "-start_time"],
                "verbose_name": "SMT生產報工記錄",
                "verbose_name_plural": "SMT生產報工記錄",
            },
        ),
        migrations.AddField(
            model_name="smtproductionreport",
            name="report_type",
            field=models.CharField(
                choices=[("normal", "正式工單"), ("rd_sample", "RD樣品")],
                default="normal",
                help_text="請選擇報工類型：正式工單或RD樣品",
                max_length=20,
                verbose_name="報工類型",
            ),
        ),
        migrations.AlterField(
            model_name="smtproductionreport",
            name="approval_remarks",
            field=models.TextField(
                blank=True, help_text="審核時的備註說明", verbose_name="審核備註"
            ),
        ),
        migrations.AlterField(
            model_name="smtproductionreport",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "待審核"),
                    ("approved", "已核准"),
                    ("rejected", "已駁回"),
                ],
                default="pending",
                help_text="此補登記錄的審核狀態",
                max_length=20,
                verbose_name="審核狀態",
            ),
        ),
        migrations.AlterField(
            model_name="smtproductionreport",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="此補登記錄的審核時間",
                null=True,
                verbose_name="審核時間",
            ),
        ),
        migrations.AlterField(
            model_name="smtproductionreport",
            name="approved_by",
            field=models.CharField(
                blank=True,
                help_text="此補登記錄的審核人員",
                max_length=100,
                null=True,
                verbose_name="審核人員",
            ),
        ),
    ]
