# Generated by Django 5.1.8 on 2025-07-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0038_alter_smtproductionreport_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="order_number",
            field=models.CharField(max_length=50, verbose_name="工單號碼"),
        ),
    ]
