# Generated by Django 5.1.8 on 2025-07-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0039_alter_workorder_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="smtproductionreport",
            name="rd_workorder_number",
            field=models.CharField(
                blank=True,
                help_text="RD樣品模式的工單號碼",
                max_length=100,
                null=True,
                verbose_name="RD樣品工單號碼",
            ),
        ),
    ]
