# Generated by Django 5.1.8 on 2025-07-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0040_fix_inconsistent_smt_records"),
        ("workorder", "0040_smtproductionreport_rd_workorder_number"),
    ]

    operations = []
