# Generated by Django 5.1.8 on 2025-07-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0041_merge_20250723_2017"),
    ]

    operations = [
        migrations.AddField(
            model_name="smtproductionreport",
            name="rd_product_code",
            field=models.CharField(
                blank=True,
                help_text="請輸入RD樣品的產品編號，用於識別具體的RD樣品工序與設備資訊",
                max_length=100,
                null=True,
                verbose_name="RD產品編號",
            ),
        ),
        migrations.AddField(
            model_name="smtproductionreport",
            name="rd_project_name",
            field=models.CharField(
                blank=True,
                help_text="請輸入RD樣品所屬的專案名稱",
                max_length=200,
                null=True,
                verbose_name="專案名稱",
            ),
        ),
        migrations.AddField(
            model_name="smtproductionreport",
            name="rd_sample_code",
            field=models.CharField(
                blank=True,
                help_text="請輸入RD樣品的專用編號，例如：RD-2025-001",
                max_length=100,
                null=True,
                verbose_name="RD樣品編號",
            ),
        ),
        migrations.AddField(
            model_name="smtproductionreport",
            name="rd_sample_name",
            field=models.CharField(
                blank=True,
                help_text="請輸入RD樣品的具體名稱或描述",
                max_length=200,
                null=True,
                verbose_name="樣品名稱",
            ),
        ),
    ]
