# Generated by Django 5.1.8 on 2025-07-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0042_add_rd_sample_fields_to_smt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smtproductionreport",
            name="rd_project_name",
        ),
        migrations.RemoveField(
            model_name="smtproductionreport",
            name="rd_sample_code",
        ),
        migrations.RemoveField(
            model_name="smtproductionreport",
            name="rd_sample_name",
        ),
    ]
