# Generated by Django 5.1.8 on 2025-07-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0043_remove_rd_sample_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operatorsupplementreport",
            name="rd_project_name",
        ),
        migrations.RemoveField(
            model_name="operatorsupplementreport",
            name="rd_sample_code",
        ),
        migrations.RemoveField(
            model_name="operatorsupplementreport",
            name="rd_sample_name",
        ),
    ]
