# Generated by Django 5.1.8 on 2025-07-24 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0045_update_rd_sample_detection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="managerproductionreport",
            name="abnormal_notes",
        ),
        migrations.RemoveField(
            model_name="operatorsupplementreport",
            name="abnormal_notes",
        ),
    ]
