# Generated by Django 5.1.8 on 2025-07-24 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0046_remove_managerproductionreport_abnormal_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorsupplementreport',
            name='process_id',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='process.processname',
                verbose_name='工序'
            ),
        ),
    ] 