# Generated by Django 5.1.8 on 2025-07-24 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0047_add_process_id_to_operator_supplement_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operatorsupplementreport",
            name="process_id",
        ),
    ]
