# Generated by Django 5.1.8 on 2025-07-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0049_add_process_id_to_operator_supplement_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="completion_method",
            field=models.CharField(
                choices=[
                    ("manual", "手動勾選"),
                    ("auto_quantity", "自動依數量判斷"),
                    ("auto_time", "自動依工時判斷"),
                    ("auto_operator", "作業員確認"),
                    ("auto_system", "系統自動判斷"),
                ],
                default="manual",
                help_text="選擇如何判斷此筆記錄是否代表工單完工",
                max_length=20,
                verbose_name="完工判斷方式",
            ),
        ),
    ]
