# Generated by Django 5.1.8 on 2025-07-24 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0012_alter_productprocessstandardcapacity_is_active_and_more"),
        ("workorder", "0051_add_missing_fields_to_operator_supplement_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operatorsupplementreport",
            name="process",
            field=models.ForeignKey(
                blank=True,
                help_text="請選擇此次補登的工序（排除SMT相關工序）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process.processname",
                verbose_name="工序",
            ),
        ),
    ]
