# Generated by Django 5.1.8 on 2025-07-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0052_alter_operatorsupplementreport_process"),
    ]

    operations = [
        migrations.AlterField(
            model_name="managerproductionreport",
            name="approval_remarks",
            field=models.TextField(
                blank=True, help_text="核准時的備註說明", verbose_name="核准備註"
            ),
        ),
        migrations.AlterField(
            model_name="managerproductionreport",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "待核准"),
                    ("approved", "已核准"),
                    ("rejected", "已駁回"),
                ],
                default="pending",
                help_text="報工記錄的核准狀態，已核准的記錄不可修改",
                max_length=20,
                verbose_name="核准狀態",
            ),
        ),
        migrations.AlterField(
            model_name="managerproductionreport",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="此報工記錄的核准時間",
                null=True,
                verbose_name="核准時間",
            ),
        ),
        migrations.AlterField(
            model_name="managerproductionreport",
            name="approved_by",
            field=models.CharField(
                blank=True,
                help_text="核准此報工記錄的人員",
                max_length=100,
                null=True,
                verbose_name="核准人員",
            ),
        ),
        migrations.AlterField(
            model_name="operatorsupplementreport",
            name="approval_remarks",
            field=models.TextField(
                blank=True, help_text="核准時的備註說明", verbose_name="核准備註"
            ),
        ),
        migrations.AlterField(
            model_name="operatorsupplementreport",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "待核准"),
                    ("approved", "已核准"),
                    ("rejected", "已駁回"),
                ],
                default="pending",
                help_text="補登記錄的核准狀態，已核准的記錄不可修改",
                max_length=20,
                verbose_name="核准狀態",
            ),
        ),
        migrations.AlterField(
            model_name="operatorsupplementreport",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="此補登記錄的核准時間",
                null=True,
                verbose_name="核准時間",
            ),
        ),
        migrations.AlterField(
            model_name="operatorsupplementreport",
            name="approved_by",
            field=models.CharField(
                blank=True,
                help_text="核准此補登記錄的人員",
                max_length=100,
                null=True,
                verbose_name="核准人員",
            ),
        ),
        migrations.AlterField(
            model_name="prdmkordmain",
            name="Permitter",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="核准人"
            ),
        ),
        migrations.AlterField(
            model_name="smtproductionreport",
            name="approval_remarks",
            field=models.TextField(
                blank=True, help_text="核准時的備註說明", verbose_name="核准備註"
            ),
        ),
        migrations.AlterField(
            model_name="smtproductionreport",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "待核准"),
                    ("approved", "已核准"),
                    ("rejected", "已駁回"),
                ],
                default="pending",
                help_text="此補登記錄的核准狀態",
                max_length=20,
                verbose_name="核准狀態",
            ),
        ),
        migrations.AlterField(
            model_name="smtproductionreport",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="此補登記錄的核准時間",
                null=True,
                verbose_name="核准時間",
            ),
        ),
        migrations.AlterField(
            model_name="smtproductionreport",
            name="approved_by",
            field=models.CharField(
                blank=True,
                help_text="此補登記錄的核准人員",
                max_length=100,
                null=True,
                verbose_name="核准人員",
            ),
        ),
    ]
