# Generated by Django 5.1.8 on 2025-07-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0053_alter_managerproductionreport_approval_remarks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="operation",
            field=models.CharField(
                default="",
                help_text="工序名稱（自動從 process 欄位取得）",
                max_length=100,
                verbose_name="工序名稱",
            ),
        ),
    ]
