# Generated by Django 5.1.8 on 2025-07-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0054_operatorsupplementreport_operation"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="product_id",
            field=models.CharField(
                default="",
                help_text="產品編號（自動從工單取得）",
                max_length=100,
                verbose_name="產品編號",
            ),
        ),
    ]
