# Generated by Django 5.1.8 on 2025-07-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0046_fix_operator_rd_sample_records"),
        ("workorder", "0055_operatorsupplementreport_product_id"),
    ]

    operations = []
