# Generated by Django 5.1.8 on 2025-07-26 05:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0012_remove_equipmentnotification_equipment_and_more"),
        ("process", "0012_alter_productprocessstandardcapacity_is_active_and_more"),
        ("workorder", "0058_managerproductionreport_abnormal_notes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupervisorProductionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supervisor",
                    models.CharField(
                        help_text="請輸入主管姓名", max_length=100, verbose_name="主管"
                    ),
                ),
                (
                    "planned_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="此為工單規劃的總生產數量，不可修改",
                        verbose_name="工單預設生產數量",
                    ),
                ),
                (
                    "work_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="請選擇實際報工日期",
                        verbose_name="日期",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        default=django.utils.timezone.now,
                        help_text="請輸入實際開始時間 (24小時制)，例如 16:00",
                        verbose_name="開始時間",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        default=django.utils.timezone.now,
                        help_text="請輸入實際結束時間 (24小時制)，例如 18:30",
                        verbose_name="結束時間",
                    ),
                ),
                (
                    "work_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="請輸入該時段內實際完成的合格產品數量",
                        verbose_name="工作數量",
                    ),
                ),
                (
                    "defect_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="請輸入本次生產中產生的不良品數量，若無則留空或填寫0",
                        verbose_name="不良品數量",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="若此工單在此工序上已全部完成，請勾選",
                        verbose_name="是否已完工",
                    ),
                ),
                (
                    "completion_method",
                    models.CharField(
                        choices=[
                            ("manual", "手動勾選"),
                            ("auto_quantity", "自動依數量判斷"),
                            ("auto_time", "自動依工時判斷"),
                            ("supervisor_confirm", "主管確認"),
                            ("auto_system", "系統自動判斷"),
                        ],
                        default="manual",
                        help_text="選擇如何判斷此筆記錄是否代表工單完工",
                        max_length=20,
                        verbose_name="完工判斷方式",
                    ),
                ),
                (
                    "auto_completed",
                    models.BooleanField(
                        default=False,
                        help_text="系統根據累積數量或工時自動判斷的完工狀態",
                        verbose_name="自動完工狀態",
                    ),
                ),
                (
                    "completion_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="系統記錄的完工確認時間",
                        null=True,
                        verbose_name="完工確認時間",
                    ),
                ),
                (
                    "cumulative_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="此工單在此工序上的累積完成數量",
                        verbose_name="累積完成數量",
                    ),
                ),
                (
                    "cumulative_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="此工單在此工序上的累積工時",
                        max_digits=8,
                        verbose_name="累積工時",
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "待核准"),
                            ("approved", "已核准"),
                            ("rejected", "已駁回"),
                        ],
                        default="pending",
                        help_text="報工記錄的核准狀態，已核准的記錄不可修改",
                        max_length=20,
                        verbose_name="核准狀態",
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True,
                        help_text="核准此報工記錄的人員",
                        max_length=100,
                        null=True,
                        verbose_name="核准人員",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="此報工記錄的核准時間",
                        null=True,
                        verbose_name="核准時間",
                    ),
                ),
                (
                    "approval_remarks",
                    models.TextField(
                        blank=True,
                        help_text="核准時的備註說明",
                        verbose_name="核准備註",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="駁回時的原因說明",
                        verbose_name="駁回原因",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="請輸入任何需要補充的資訊，如設備標記、操作說明等",
                        verbose_name="備註",
                    ),
                ),
                (
                    "abnormal_notes",
                    models.TextField(
                        blank=True,
                        help_text="記錄生產過程中的異常情況，如設備故障、品質問題等",
                        verbose_name="異常記錄",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        default="system", max_length=100, verbose_name="建立人員"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        help_text="請選擇此次報工的設備（可選）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="equip.equipment",
                        verbose_name="設備",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        help_text="請選擇此次報工的作業員（可選）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="process.operator",
                        verbose_name="作業員",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        help_text="請選擇此次報工的工序",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process.processname",
                        verbose_name="工序",
                    ),
                ),
                (
                    "workorder",
                    models.ForeignKey(
                        help_text="請選擇要報工的工單號碼",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workorder.workorder",
                        verbose_name="工單號碼",
                    ),
                ),
            ],
            options={
                "verbose_name": "主管生產報工記錄",
                "verbose_name_plural": "主管生產報工記錄",
                "db_table": "workorder_supervisor_production_report",
                "ordering": ["-work_date", "-start_time"],
            },
        ),
        migrations.DeleteModel(
            name="ManagerProductionReport",
        ),
    ]
