# Generated by Django 5.1.8 on 2025-07-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0059_supervisorproductionreport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="allocated_quantity",
            field=models.IntegerField(
                default=0, help_text="系統智能分配的數量", verbose_name="分配數量"
            ),
        ),
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="allocation_notes",
            field=models.TextField(
                blank=True, help_text="記錄分配計算過程和依據", verbose_name="分配說明"
            ),
        ),
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="quantity_source",
            field=models.CharField(
                choices=[
                    ("original", "原始數量"),
                    ("allocated", "智能分配"),
                    ("packaging", "包裝工序"),
                ],
                default="original",
                help_text="數量的來源類型",
                max_length=20,
                verbose_name="數量來源",
            ),
        ),
    ]
