# Generated by Django 5.1.8 on 2025-07-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0060_operatorsupplementreport_allocated_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="break_end_time",
            field=models.TimeField(
                blank=True,
                help_text="中午休息結束時間（固定為13:00）",
                null=True,
                verbose_name="休息結束時間",
            ),
        ),
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="break_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="中午休息時數（固定為1小時）",
                max_digits=4,
                verbose_name="休息時數",
            ),
        ),
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="break_start_time",
            field=models.TimeField(
                blank=True,
                help_text="中午休息開始時間（固定為12:00）",
                null=True,
                verbose_name="休息開始時間",
            ),
        ),
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="has_break",
            field=models.BooleanField(
                default=False,
                help_text="系統自動判斷是否橫跨中午休息時間",
                verbose_name="是否有休息時間",
            ),
        ),
        migrations.AddField(
            model_name="supervisorproductionreport",
            name="break_end_time",
            field=models.TimeField(
                blank=True,
                help_text="中午休息結束時間（固定為13:00）",
                null=True,
                verbose_name="休息結束時間",
            ),
        ),
        migrations.AddField(
            model_name="supervisorproductionreport",
            name="break_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="中午休息時數（固定為1小時）",
                max_digits=4,
                verbose_name="休息時數",
            ),
        ),
        migrations.AddField(
            model_name="supervisorproductionreport",
            name="break_start_time",
            field=models.TimeField(
                blank=True,
                help_text="中午休息開始時間（固定為12:00）",
                null=True,
                verbose_name="休息開始時間",
            ),
        ),
        migrations.AddField(
            model_name="supervisorproductionreport",
            name="has_break",
            field=models.BooleanField(
                default=False,
                help_text="系統自動判斷是否橫跨中午休息時間",
                verbose_name="是否有休息時間",
            ),
        ),
    ]
