# Generated by Django 5.1.8 on 2025-07-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0061_add_break_time_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="overtime_hours_calculated",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="超過正常工時的部分",
                max_digits=5,
                verbose_name="加班時數",
            ),
        ),
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="work_hours_calculated",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="扣除休息時間後的實際工作時數",
                max_digits=5,
                verbose_name="工作時數",
            ),
        ),
        migrations.AddField(
            model_name="supervisorproductionreport",
            name="overtime_hours_calculated",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="超過正常工時的部分",
                max_digits=5,
                verbose_name="加班時數",
            ),
        ),
        migrations.AddField(
            model_name="supervisorproductionreport",
            name="work_hours_calculated",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="扣除休息時間後的實際工作時數",
                max_digits=5,
                verbose_name="工作時數",
            ),
        ),
    ]
