# Generated by Django 5.1.8 on 2025-07-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workorder",
            "0062_operatorsupplementreport_overtime_hours_calculated_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="smtproductionreport",
            name="overtime_hours_calculated",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="16:30 以後的工時",
                max_digits=5,
                verbose_name="加班工時",
            ),
        ),
        migrations.AddField(
            model_name="smtproductionreport",
            name="work_hours_calculated",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="16:30 之前的工時",
                max_digits=5,
                verbose_name="正常工時",
            ),
        ),
    ]
