# Generated by Django 5.1.8 on 2025-07-31 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0063_smtproductionreport_overtime_hours_calculated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrderDispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="公司代號"
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="工單號碼"
                    ),
                ),
                (
                    "product_code",
                    models.CharField(max_length=100, verbose_name="產品編號"),
                ),
                (
                    "planned_quantity",
                    models.PositiveIntegerField(verbose_name="計劃數量"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待派工"),
                            ("dispatched", "已派工"),
                            ("in_production", "生產中"),
                            ("completed", "已完工"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="派工狀態",
                    ),
                ),
                (
                    "dispatch_date",
                    models.DateField(blank=True, null=True, verbose_name="派工日期"),
                ),
                (
                    "planned_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="計劃開始日期"
                    ),
                ),
                (
                    "planned_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="計劃完成日期"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "created_by",
                    models.CharField(
                        default="system", max_length=100, verbose_name="建立人員"
                    ),
                ),
            ],
            options={
                "verbose_name": "派工單",
                "verbose_name_plural": "派工單管理",
                "db_table": "workorder_dispatch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderCompleted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completion_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="完工時間"),
                ),
                (
                    "completion_method",
                    models.CharField(
                        choices=[
                            ("quantity_reached", "數量達標"),
                            ("manual_completion", "手動完工"),
                            ("auto_completion", "自動完工"),
                        ],
                        max_length=20,
                        verbose_name="完工方式",
                    ),
                ),
                (
                    "total_work_quantity",
                    models.IntegerField(default=0, verbose_name="總合格品數量"),
                ),
                (
                    "total_defect_quantity",
                    models.IntegerField(default=0, verbose_name="總不良品數量"),
                ),
                (
                    "total_production_days",
                    models.IntegerField(default=0, verbose_name="總生產天數"),
                ),
                (
                    "process_completion_summary",
                    models.TextField(
                        blank=True,
                        help_text="JSON格式記錄每個工序的完工統計",
                        verbose_name="工序完工摘要",
                    ),
                ),
                (
                    "confirmed_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="完工確認人員",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完工確認時間"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "workorder_dispatch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_record",
                        to="workorder.workorderdispatch",
                        verbose_name="派工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "已完工工單",
                "verbose_name_plural": "已完工工單",
                "db_table": "workorder_completed",
                "ordering": ["-completion_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_production", "生產中"),
                            ("paused", "暫停"),
                            ("completed", "已完工"),
                        ],
                        default="in_production",
                        max_length=20,
                        verbose_name="生產狀態",
                    ),
                ),
                (
                    "production_start_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="生產開始時間"
                    ),
                ),
                (
                    "production_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="生產結束時間"
                    ),
                ),
                (
                    "current_process",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="當前工序"
                    ),
                ),
                (
                    "completed_processes",
                    models.TextField(
                        blank=True,
                        help_text="JSON格式記錄已完成的工序",
                        verbose_name="已完成工序",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "workorder_dispatch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_record",
                        to="workorder.workorderdispatch",
                        verbose_name="派工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "生產中工單",
                "verbose_name_plural": "生產中工單",
                "db_table": "workorder_production",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderProductionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                ("report_date", models.DateField(verbose_name="報工日期")),
                (
                    "report_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="報工時間"),
                ),
                (
                    "work_quantity",
                    models.IntegerField(default=0, verbose_name="合格品數量"),
                ),
                (
                    "defect_quantity",
                    models.IntegerField(default=0, verbose_name="不良品數量"),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="作業員"
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="設備"
                    ),
                ),
                (
                    "report_source",
                    models.CharField(
                        choices=[
                            ("operator", "作業員現場報工"),
                            ("operator_supplement", "作業員補登報工"),
                            ("supervisor", "主管報工"),
                            ("smt", "SMT報工"),
                        ],
                        max_length=20,
                        verbose_name="報工來源",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="開始時間"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="結束時間"),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="備註")),
                (
                    "abnormal_notes",
                    models.TextField(blank=True, verbose_name="異常記錄"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "created_by",
                    models.CharField(
                        default="system", max_length=100, verbose_name="建立人員"
                    ),
                ),
                (
                    "workorder_production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_details",
                        to="workorder.workorderproduction",
                        verbose_name="生產中工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "生產報工明細",
                "verbose_name_plural": "生產報工明細",
                "db_table": "workorder_production_detail",
                "ordering": ["-report_date", "-report_time"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderCompletedProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                ("step_order", models.IntegerField(verbose_name="工序順序")),
                (
                    "total_work_quantity",
                    models.IntegerField(default=0, verbose_name="總合格品數量"),
                ),
                (
                    "total_defect_quantity",
                    models.IntegerField(default=0, verbose_name="總不良品數量"),
                ),
                (
                    "report_count",
                    models.IntegerField(default=0, verbose_name="報工次數"),
                ),
                (
                    "first_report_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="首次報工日期"
                    ),
                ),
                (
                    "last_report_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="最後報工日期"
                    ),
                ),
                (
                    "total_work_hours",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, verbose_name="總工時"
                    ),
                ),
                (
                    "operators_used",
                    models.TextField(
                        blank=True,
                        help_text="JSON格式記錄使用的作業員",
                        verbose_name="使用作業員",
                    ),
                ),
                (
                    "equipments_used",
                    models.TextField(
                        blank=True,
                        help_text="JSON格式記錄使用的設備",
                        verbose_name="使用設備",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "workorder_completed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_processes",
                        to="workorder.workordercompleted",
                        verbose_name="已完工工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "已完工工序統計",
                "verbose_name_plural": "已完工工序統計",
                "db_table": "workorder_completed_process",
                "ordering": ["workorder_completed", "step_order"],
                "unique_together": {("workorder_completed", "process_name")},
            },
        ),
        migrations.CreateModel(
            name="WorkOrderDispatchProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                ("step_order", models.IntegerField(verbose_name="工序順序")),
                ("planned_quantity", models.IntegerField(verbose_name="計劃數量")),
                (
                    "assigned_operator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分配作業員"
                    ),
                ),
                (
                    "assigned_equipment",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分配設備"
                    ),
                ),
                (
                    "dispatch_status",
                    models.CharField(
                        choices=[
                            ("pending", "待派工"),
                            ("dispatched", "已派工"),
                            ("in_progress", "進行中"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="派工狀態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "workorder_dispatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_processes",
                        to="workorder.workorderdispatch",
                        verbose_name="派工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "派工單工序",
                "verbose_name_plural": "派工單工序明細",
                "db_table": "workorder_dispatch_process",
                "ordering": ["workorder_dispatch", "step_order"],
                "unique_together": {("workorder_dispatch", "step_order")},
            },
        ),
    ]
