# Generated by Django 5.1.8 on 2025-07-31 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0064_workorderdispatch_workordercompleted_and_more"),
        ("workorder_dispatch", "__first__"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompanyOrder",
        ),
        migrations.RemoveField(
            model_name="operatorsupplementreport",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="operatorsupplementreport",
            name="operator",
        ),
        migrations.RemoveField(
            model_name="operatorsupplementreport",
            name="process",
        ),
        migrations.RemoveField(
            model_name="operatorsupplementreport",
            name="workorder",
        ),
        migrations.DeleteModel(
            name="PrdMKOrdMain",
        ),
        migrations.DeleteModel(
            name="PrdMkOrdMats",
        ),
        migrations.RemoveField(
            model_name="smtproductionreport",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="smtproductionreport",
            name="workorder",
        ),
        migrations.RemoveField(
            model_name="supervisorproductionreport",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="supervisorproductionreport",
            name="operator",
        ),
        migrations.RemoveField(
            model_name="supervisorproductionreport",
            name="process",
        ),
        migrations.RemoveField(
            model_name="supervisorproductionreport",
            name="workorder",
        ),
        migrations.DeleteModel(
            name="SystemConfig",
        ),
        migrations.RemoveField(
            model_name="workordercompleted",
            name="workorder_dispatch",
        ),
        migrations.RemoveField(
            model_name="workordercompletedprocess",
            name="workorder_completed",
        ),
        migrations.AlterUniqueTogether(
            name="workordercompletedprocess",
            unique_together=None,
        ),
        migrations.AlterField(
            model_name="workorderproduction",
            name="workorder_dispatch",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_record",
                to="workorder_dispatch.workorderdispatch",
                verbose_name="派工單",
            ),
        ),
        migrations.RemoveField(
            model_name="workorderdispatchprocess",
            name="workorder_dispatch",
        ),
        migrations.AlterUniqueTogether(
            name="workorderdispatchprocess",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="OperatorSupplementReport",
        ),
        migrations.DeleteModel(
            name="SMTProductionReport",
        ),
        migrations.DeleteModel(
            name="SupervisorProductionReport",
        ),
        migrations.DeleteModel(
            name="WorkOrderCompleted",
        ),
        migrations.DeleteModel(
            name="WorkOrderCompletedProcess",
        ),
        migrations.DeleteModel(
            name="WorkOrderDispatch",
        ),
        migrations.DeleteModel(
            name="WorkOrderDispatchProcess",
        ),
    ]
