# Generated by Django 5.1.8 on 2025-08-01 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0065_delete_companyorder_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workorderproduction",
            name="workorder_dispatch",
        ),
        migrations.AddField(
            model_name="workorderproduction",
            name="workorder",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_record",
                to="workorder.workorder",
                verbose_name="工單",
            ),
        ),
    ]
