# Generated by Django 5.1.8 on 2025-08-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0066_remove_workorderproduction_workorder_dispatch_and_more"),
    ]

    operations = [
        # 為 workorder_operator_supplement_report 表添加駁回相關欄位
        migrations.RunSQL(
            sql="""
            ALTER TABLE workorder_operator_supplement_report 
            ADD COLUMN rejected_by VARCHAR(100) NULL,
            ADD COLUMN rejected_at TIMESTAMP WITH TIME ZONE NULL;
            """,
            reverse_sql="""
            ALTER TABLE workorder_operator_supplement_report 
            DROP COLUMN rejected_by,
            DROP COLUMN rejected_at;
            """
        ),
        # 為 workorder_smt_production_report 表添加駁回相關欄位
        migrations.RunSQL(
            sql="""
            ALTER TABLE workorder_smt_production_report 
            ADD COLUMN rejected_by VARCHAR(100) NULL,
            ADD COLUMN rejected_at TIMESTAMP WITH TIME ZONE NULL;
            """,
            reverse_sql="""
            ALTER TABLE workorder_smt_production_report 
            DROP COLUMN rejected_by,
            DROP COLUMN rejected_at;
            """
        ),
        # 為 workorder_supervisor_production_report 表添加駁回相關欄位
        migrations.RunSQL(
            sql="""
            ALTER TABLE workorder_supervisor_production_report 
            ADD COLUMN rejected_by VARCHAR(100) NULL,
            ADD COLUMN rejected_at TIMESTAMP WITH TIME ZONE NULL;
            """,
            reverse_sql="""
            ALTER TABLE workorder_supervisor_production_report 
            DROP COLUMN rejected_by,
            DROP COLUMN rejected_at;
            """
        ),
    ]
