# Generated by Django 5.1.8 on 2025-08-01 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0067_auto_20250801_1315"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletedWorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_workorder_id",
                    models.IntegerField(
                        help_text="對應的原始工單ID", verbose_name="原始工單ID"
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="工單號"
                    ),
                ),
                (
                    "product_code",
                    models.CharField(max_length=100, verbose_name="產品編號"),
                ),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                ("planned_quantity", models.IntegerField(verbose_name="計劃數量")),
                (
                    "completed_quantity",
                    models.IntegerField(default=0, verbose_name="完成數量"),
                ),
                (
                    "status",
                    models.CharField(
                        default="completed", max_length=20, verbose_name="工單狀態"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="開始時間"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="完工時間"),
                ),
                (
                    "total_work_hours",
                    models.FloatField(default=0.0, verbose_name="總工作時數"),
                ),
                (
                    "total_overtime_hours",
                    models.FloatField(default=0.0, verbose_name="總加班時數"),
                ),
                (
                    "total_all_hours",
                    models.FloatField(default=0.0, verbose_name="全部總時數"),
                ),
                (
                    "total_good_quantity",
                    models.IntegerField(default=0, verbose_name="總合格品"),
                ),
                (
                    "total_defect_quantity",
                    models.IntegerField(default=0, verbose_name="總不良品"),
                ),
                (
                    "total_report_count",
                    models.IntegerField(default=0, verbose_name="報工次數"),
                ),
                (
                    "unique_operators",
                    models.JSONField(default=list, verbose_name="參與作業員"),
                ),
                (
                    "unique_equipment",
                    models.JSONField(default=list, verbose_name="使用設備"),
                ),
                (
                    "production_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workorder.workorderproduction",
                        verbose_name="生產記錄",
                    ),
                ),
            ],
            options={
                "verbose_name": "已完工工單",
                "verbose_name_plural": "已完工工單",
                "db_table": "workorder_completed_workorder",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="CompletedProductionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="報工日期")),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                ("operator", models.CharField(max_length=100, verbose_name="作業員")),
                ("equipment", models.CharField(max_length=100, verbose_name="設備")),
                (
                    "work_quantity",
                    models.IntegerField(default=0, verbose_name="合格品數量"),
                ),
                (
                    "defect_quantity",
                    models.IntegerField(default=0, verbose_name="不良品數量"),
                ),
                ("work_hours", models.FloatField(default=0.0, verbose_name="工作時數")),
                (
                    "overtime_hours",
                    models.FloatField(default=0.0, verbose_name="加班時數"),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="開始時間"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="結束時間"
                    ),
                ),
                (
                    "report_source",
                    models.CharField(max_length=50, verbose_name="報工來源"),
                ),
                (
                    "report_type",
                    models.CharField(max_length=20, verbose_name="報工類型"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="備註"),
                ),
                (
                    "abnormal_notes",
                    models.TextField(blank=True, null=True, verbose_name="異常紀錄"),
                ),
                (
                    "approval_status",
                    models.CharField(
                        default="approved", max_length=20, verbose_name="審核狀態"
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="審核者"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="審核時間"),
                ),
                (
                    "completed_workorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_reports",
                        to="workorder.completedworkorder",
                        verbose_name="已完工工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "已完工生產報工記錄",
                "verbose_name_plural": "已完工生產報工記錄",
                "db_table": "workorder_completed_production_report",
                "ordering": ["report_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="CompletedWorkOrderProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                ("process_order", models.IntegerField(verbose_name="工序順序")),
                ("planned_quantity", models.IntegerField(verbose_name="計劃數量")),
                (
                    "completed_quantity",
                    models.IntegerField(default=0, verbose_name="完成數量"),
                ),
                (
                    "status",
                    models.CharField(
                        default="completed", max_length=20, verbose_name="工序狀態"
                    ),
                ),
                (
                    "assigned_operator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分配作業員"
                    ),
                ),
                (
                    "assigned_equipment",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分配設備"
                    ),
                ),
                (
                    "total_work_hours",
                    models.FloatField(default=0.0, verbose_name="工作時數"),
                ),
                (
                    "total_good_quantity",
                    models.IntegerField(default=0, verbose_name="合格品數量"),
                ),
                (
                    "total_defect_quantity",
                    models.IntegerField(default=0, verbose_name="不良品數量"),
                ),
                (
                    "report_count",
                    models.IntegerField(default=0, verbose_name="報工次數"),
                ),
                (
                    "operators",
                    models.JSONField(default=list, verbose_name="參與作業員"),
                ),
                ("equipment", models.JSONField(default=list, verbose_name="使用設備")),
                (
                    "completed_workorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processes",
                        to="workorder.completedworkorder",
                        verbose_name="已完工工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "已完工工單工序",
                "verbose_name_plural": "已完工工單工序",
                "db_table": "workorder_completed_workorder_process",
                "ordering": ["process_order"],
            },
        ),
        migrations.AddIndex(
            model_name="completedworkorder",
            index=models.Index(
                fields=["order_number"], name="workorder_c_order_n_1c93e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="completedworkorder",
            index=models.Index(
                fields=["product_code"], name="workorder_c_product_915fe2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="completedworkorder",
            index=models.Index(
                fields=["company_code"], name="workorder_c_company_22bdc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="completedworkorder",
            index=models.Index(
                fields=["completed_at"], name="workorder_c_complet_20aa6b_idx"
            ),
        ),
    ]
