# Generated by Django 5.1.8 on 2025-08-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0068_completedworkorder_completedproductionreport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderproductiondetail",
            name="original_report_id",
            field=models.IntegerField(
                blank=True,
                help_text="對應的原始報工記錄ID",
                null=True,
                verbose_name="原始報工記錄ID",
            ),
        ),
        migrations.AddField(
            model_name="workorderproductiondetail",
            name="original_report_type",
            field=models.CharField(
                blank=True,
                help_text="原始報工記錄的類型",
                max_length=20,
                null=True,
                verbose_name="原始報工類型",
            ),
        ),
    ]
