# Generated by Django 5.1.8 on 2025-08-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0069_add_original_report_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workorderproductiondetail",
            index=models.Index(
                fields=["workorder_production", "process_name", "report_source"],
                name="idx_prod_detail_completion",
            ),
        ),
        migrations.AddIndex(
            model_name="workorderproductiondetail",
            index=models.Index(fields=["report_date"], name="idx_prod_detail_date"),
        ),
        migrations.AddIndex(
            model_name="workorderproductiondetail",
            index=models.Index(fields=["process_name"], name="idx_prod_detail_process"),
        ),
    ]
