# Generated by Django 5.1.8 on 2025-08-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0070_add_production_detail_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedworkorder",
            name="order_number",
            field=models.CharField(max_length=100, verbose_name="工單號"),
        ),
        migrations.AlterUniqueTogether(
            name="completedworkorder",
            unique_together={("order_number", "product_code")},
        ),
        migrations.AlterUniqueTogether(
            name="workorder",
            unique_together={("company_code", "order_number", "product_code")},
        ),
    ]
