# Generated by Django 5.1.8 on 2025-08-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0070_add_missing_fields_to_production_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedworkorder",
            name="order_number",
            field=models.CharField(max_length=100, verbose_name="工單號"),
        ),
        migrations.AlterField(
            model_name="workorderproductiondetail",
            name="report_source",
            field=models.CharField(
                choices=[
                    ("operator", "作業員現場報工"),
                    ("operator_supplement", "作業員補登報工"),
                    ("smt", "SMT報工"),
                ],
                max_length=20,
                verbose_name="報工來源",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="completedworkorder",
            unique_together={("order_number", "product_code")},
        ),
        migrations.AlterUniqueTogether(
            name="workorder",
            unique_together={("company_code", "order_number", "product_code")},
        ),
        migrations.AddIndex(
            model_name="workorderproductiondetail",
            index=models.Index(
                fields=["workorder_production", "process_name", "report_source"],
                name="idx_prod_detail_completion",
            ),
        ),
        migrations.AddIndex(
            model_name="workorderproductiondetail",
            index=models.Index(fields=["report_date"], name="idx_prod_detail_date"),
        ),
        migrations.AddIndex(
            model_name="workorderproductiondetail",
            index=models.Index(fields=["process_name"], name="idx_prod_detail_process"),
        ),
    ]
