# Generated by Django 5.1.8 on 2025-08-02 06:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "mes_database",
                    models.CharField(max_length=100, verbose_name="MES資料庫名稱"),
                ),
                (
                    "sync_database",
                    models.TextField(blank=True, verbose_name="要同步的資料庫名稱"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "公司檢視",
                "verbose_name_plural": "公司檢視",
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="標題")),
                ("start", models.DateTimeField(verbose_name="開始時間")),
                ("end", models.DateTimeField(verbose_name="結束時間")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("holiday", "放假日"),
                            ("production", "生產任務"),
                            ("meeting", "會議"),
                            ("maintenance", "維護"),
                            ("workday", "上班日"),
                            ("overtime", "加班"),
                        ],
                        max_length=20,
                        verbose_name="類型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "classNames",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="樣式類別"
                    ),
                ),
                (
                    "all_day",
                    models.BooleanField(default=False, verbose_name="全天事件"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "一般"),
                            ("urgent", "緊急"),
                            ("routine", "例行"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="分類",
                    ),
                ),
                ("created_by", models.CharField(max_length=150, verbose_name="創建者")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="作業員ID"
                    ),
                ),
                (
                    "equipment_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="設備ID"
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="訂單ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "事件",
                "verbose_name_plural": "事件",
                "ordering": ["start"],
            },
        ),
        migrations.CreateModel(
            name="OrderMain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "customer_short_name",
                    models.CharField(max_length=100, verbose_name="客戶簡稱"),
                ),
                ("bill_no", models.CharField(max_length=50, verbose_name="訂單號")),
                (
                    "product_id",
                    models.CharField(max_length=50, verbose_name="產品編號"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="產品名稱"),
                ),
                ("quantity", models.IntegerField(verbose_name="訂購數量")),
                (
                    "pre_in_date",
                    models.CharField(max_length=10, verbose_name="預交貨日期"),
                ),
                ("qty_remain", models.IntegerField(verbose_name="未交貨數量")),
                (
                    "order_type",
                    models.CharField(max_length=20, verbose_name="訂單類型"),
                ),
                ("bill_date", models.CharField(max_length=10, verbose_name="訂單日期")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "訂單主檔",
                "verbose_name_plural": "訂單主檔",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderUpdateSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_interval_minutes",
                    models.IntegerField(
                        default=0, verbose_name="自動同步間隔（分鐘，0表示禁用）"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次更新時間"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "訂單更新排程",
                "verbose_name_plural": "訂單更新排程",
            },
        ),
        migrations.CreateModel(
            name="ProcessIntervalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_interval_minutes",
                    models.IntegerField(default=5, verbose_name="工序間隔時間（分鐘）"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "工序間隔設置",
                "verbose_name_plural": "工序間隔設置",
            },
        ),
        migrations.CreateModel(
            name="ProductionSafetySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_to_completion_safety_days",
                    models.IntegerField(
                        default=3, verbose_name="預定出貨日到完工日安全天數（天）"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "生產安全設置",
                "verbose_name_plural": "生產安全設置",
            },
        ),
        migrations.CreateModel(
            name="ScheduleWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=50, verbose_name="訂單編號")),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                ("warning_message", models.TextField(verbose_name="警告內容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="產生時間"),
                ),
            ],
            options={
                "verbose_name": "排程警告",
                "verbose_name_plural": "排程警告",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="單位名稱"
                    ),
                ),
                (
                    "work_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="上班開始時間"
                    ),
                ),
                (
                    "work_end",
                    models.TimeField(blank=True, null=True, verbose_name="下班時間"),
                ),
                (
                    "has_lunch_break",
                    models.BooleanField(default=False, verbose_name="是否有中午休息"),
                ),
                (
                    "lunch_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="午休開始時間"
                    ),
                ),
                (
                    "lunch_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="午休結束時間"
                    ),
                ),
                (
                    "overtime_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="加班開始時間"
                    ),
                ),
                (
                    "overtime_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="加班結束時間"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "單位",
                "verbose_name_plural": "單位",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SchedulingOperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="時間戳"
                    ),
                ),
                ("user", models.CharField(max_length=150, verbose_name="用戶")),
                ("action", models.CharField(max_length=255, verbose_name="操作")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 地址"
                    ),
                ),
                (
                    "details",
                    models.TextField(blank=True, null=True, verbose_name="細節"),
                ),
                (
                    "event_related",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scheduling.event",
                        verbose_name="關聯事件",
                    ),
                ),
            ],
            options={
                "verbose_name": "排程操作日誌",
                "verbose_name_plural": "排程操作日誌",
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="event",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scheduling.unit",
                verbose_name="單位",
            ),
        ),
    ]
