# Generated by Django 5.1.8 on 2025-06-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=50, verbose_name="訂單編號")),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                ("warning_message", models.TextField(verbose_name="警告內容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="產生時間"),
                ),
            ],
            options={
                "verbose_name": "排程警告",
                "verbose_name_plural": "排程警告",
                "ordering": ["-created_at"],
            },
        ),
    ]
