# Generated by Django 5.2.6 on 2025-09-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        # event_related_title 欄位在模型中已存在，無需添加
        # 此遷移檔案保持空白以避免重複欄位錯誤
    ]