# Generated by Django 5.1.8 on 2025-06-29 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_schedulewarning"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="smt_equipment_id",
        ),
    ]
