# Generated by Django 5.2.6 on 2025-09-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_auto_20250910_1047"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulingoperationlog",
            name="event_related_title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="關聯事件標題"
            ),
        ),
    ]
