# Generated by Django 5.1.8 on 2025-07-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0003_remove_smt_equipment_fields"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderData",
        ),
        migrations.DeleteModel(
            name="OrderUpdateSchedule",
        ),
    ]
