# Generated by Django 5.1.8 on 2025-07-06 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0004_delete_orderdata_delete_orderupdateschedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderUpdateSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_interval_minutes",
                    models.IntegerField(
                        default=0, verbose_name="自動同步間隔（分鐘，0表示禁用）"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="上次更新時間",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="創建時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "訂單更新排程",
                "verbose_name_plural": "訂單更新排程",
            },
        ),
        migrations.CreateModel(
            name="OrderMain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "customer_short_name",
                    models.CharField(max_length=100, verbose_name="客戶簡稱"),
                ),
                ("bill_no", models.CharField(max_length=50, verbose_name="訂單號")),
                (
                    "product_id",
                    models.CharField(max_length=50, verbose_name="產品編號"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="產品名稱"),
                ),
                ("quantity", models.IntegerField(verbose_name="訂購數量")),
                (
                    "pre_in_date",
                    models.CharField(max_length=10, verbose_name="預交貨日期"),
                ),
                ("qty_remain", models.IntegerField(verbose_name="未交貨數量")),
                (
                    "order_type",
                    models.CharField(max_length=20, verbose_name="訂單類型"),
                ),
                (
                    "bill_date",
                    models.CharField(max_length=10, verbose_name="訂單日期"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "訂單主檔",
                "verbose_name_plural": "訂單主檔",
                "ordering": ["-updated_at"],
            },
        ),
    ]
