# Generated by Django 5.2.6 on 2025-09-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0004_orderupdateschedule_test_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderupdateschedule",
            name="test_field",
        ),
    ]
