# Generated by Django 5.1.8 on 2025-07-07 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0005_move_order_models"),
    ]

    operations = []
