# Generated by Django 5.1.8 on 2025-07-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0006_auto_20250707_1323"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulingoperationlog",
            name="details",
            field=models.TextField(blank=True, null=True, verbose_name="細節"),
        ),
    ]
