# Generated by Django 5.1.8 on 2025-08-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        help_text="公司代號，例如：01、02、03",
                        max_length=10,
                        verbose_name="公司代號",
                    ),
                ),
                (
                    "mkordno",
                    models.CharField(
                        help_text="製令單號碼", max_length=50, verbose_name="製令單號"
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        help_text="產品編號", max_length=100, verbose_name="產品編號"
                    ),
                ),
                (
                    "prodt_qty",
                    models.PositiveIntegerField(
                        help_text="計劃生產數量", verbose_name="生產數量"
                    ),
                ),
                (
                    "est_take_mat_date",
                    models.CharField(
                        help_text="預定開工日期",
                        max_length=20,
                        verbose_name="預定開工日",
                    ),
                ),
                (
                    "est_stock_out_date",
                    models.CharField(
                        help_text="預定出貨日期",
                        max_length=20,
                        verbose_name="預定出貨日",
                    ),
                ),
                (
                    "complete_status",
                    models.IntegerField(
                        blank=True,
                        help_text="完工狀態代碼",
                        null=True,
                        verbose_name="完工狀態",
                    ),
                ),
                (
                    "bill_status",
                    models.IntegerField(
                        blank=True,
                        help_text="單據狀況代碼",
                        null=True,
                        verbose_name="單況",
                    ),
                ),
                (
                    "sync_time",
                    models.DateTimeField(
                        auto_now=True, help_text="最後同步時間", verbose_name="同步時間"
                    ),
                ),
                (
                    "is_converted",
                    models.BooleanField(
                        default=False,
                        help_text="是否已轉換為MES工單",
                        verbose_name="已轉成MES工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "公司製令單",
                "verbose_name_plural": "公司製令單管理",
                "ordering": ["-sync_time"],
                "indexes": [
                    models.Index(
                        fields=["company_code"], name="workorder_c_company_a72e9c_idx"
                    ),
                    models.Index(
                        fields=["mkordno"], name="workorder_c_mkordno_26aeb9_idx"
                    ),
                    models.Index(
                        fields=["product_id"], name="workorder_c_product_f9f452_idx"
                    ),
                    models.Index(
                        fields=["sync_time"], name="workorder_c_sync_ti_9218c5_idx"
                    ),
                    models.Index(
                        fields=["is_converted"], name="workorder_c_is_conv_2e410b_idx"
                    ),
                ],
                "unique_together": {("company_code", "mkordno", "product_id")},
            },
        ),
        migrations.CreateModel(
            name="ERPPrdMKOrdMain",
            fields=[
                (
                    "row_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="主鍵ID"
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        help_text="公司代號", max_length=10, verbose_name="公司代號"
                    ),
                ),
                ("Flag", models.IntegerField(verbose_name="狀態Flag")),
                ("MKOrdNO", models.CharField(max_length=30, verbose_name="製令單號")),
                (
                    "MKOrdDate",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="製令日期"
                    ),
                ),
                (
                    "MakeType",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="製令類型"
                    ),
                ),
                (
                    "FromRowNO",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="來源行號"
                    ),
                ),
                ("ProductID", models.CharField(max_length=50, verbose_name="產品編號")),
                (
                    "ProductType",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="產品類型"
                    ),
                ),
                (
                    "ProdtQty",
                    models.DecimalField(
                        decimal_places=4, max_digits=16, verbose_name="生產數量"
                    ),
                ),
                (
                    "Producer",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="生產人員"
                    ),
                ),
                (
                    "CostType",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="成本類型"
                    ),
                ),
                (
                    "SourceType",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="來源類型"
                    ),
                ),
                (
                    "SourceNo",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="來源單號"
                    ),
                ),
                (
                    "Functionary",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="負責人"
                    ),
                ),
                (
                    "WareInType",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="入庫類型"
                    ),
                ),
                (
                    "EstTakeMatDate",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="預計領料日"
                    ),
                ),
                (
                    "EstWareInDate",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="預計入庫日"
                    ),
                ),
                ("CompleteStatus", models.IntegerField(verbose_name="完工狀態")),
                (
                    "ChangeDate",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="異動日期"
                    ),
                ),
                (
                    "GoodsQty",
                    models.DecimalField(
                        decimal_places=4, max_digits=16, verbose_name="良品數量"
                    ),
                ),
                (
                    "BadsQty",
                    models.DecimalField(
                        decimal_places=4, max_digits=16, verbose_name="不良品數量"
                    ),
                ),
                (
                    "Remark",
                    models.TextField(blank=True, null=True, verbose_name="備註"),
                ),
                (
                    "Maker",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="製單人"
                    ),
                ),
                (
                    "Permitter",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="核准人"
                    ),
                ),
                (
                    "BillStatus",
                    models.IntegerField(blank=True, null=True, verbose_name="單況"),
                ),
                ("updated_at", models.DateTimeField(verbose_name="更新時間")),
            ],
            options={
                "verbose_name": "ERP製令主檔",
                "verbose_name_plural": "ERP製令主檔管理",
                "db_table": "workorder_companyorder_erp_prdmkordmain",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["company_code"], name="workorder_c_company_d9f396_idx"
                    ),
                    models.Index(
                        fields=["MKOrdNO"], name="workorder_c_MKOrdNO_81d046_idx"
                    ),
                    models.Index(
                        fields=["ProductID"], name="workorder_c_Product_6d7a2e_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="workorder_c_updated_b8baa7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ERPPrdMkOrdMats",
            fields=[
                (
                    "row_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="主鍵ID"
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        help_text="公司代號", max_length=10, verbose_name="公司代號"
                    ),
                ),
                ("Flag", models.IntegerField(verbose_name="狀態Flag")),
                ("MkOrdNO", models.CharField(max_length=30, verbose_name="製令單號")),
                ("RowNO", models.IntegerField(verbose_name="表身行號")),
                ("SerNO", models.IntegerField(verbose_name="序號")),
                ("SubProdID", models.CharField(max_length=50, verbose_name="用料編號")),
                (
                    "OriginalQty",
                    models.DecimalField(
                        decimal_places=4, max_digits=16, verbose_name="需求數量"
                    ),
                ),
                (
                    "WestingRate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="損耗率",
                    ),
                ),
                (
                    "MatsRemark",
                    models.TextField(blank=True, null=True, verbose_name="用料備註"),
                ),
                (
                    "Detail",
                    models.TextField(blank=True, null=True, verbose_name="說明"),
                ),
                (
                    "UnitOughtQty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=16,
                        null=True,
                        verbose_name="單位應發數量",
                    ),
                ),
                (
                    "OughtQty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=16,
                        null=True,
                        verbose_name="應發數量",
                    ),
                ),
                ("updated_at", models.DateTimeField(verbose_name="更新時間")),
            ],
            options={
                "verbose_name": "ERP製令明細",
                "verbose_name_plural": "ERP製令明細管理",
                "db_table": "workorder_companyorder_erp_prdmkordmats",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["company_code"], name="workorder_c_company_27ce37_idx"
                    ),
                    models.Index(
                        fields=["MkOrdNO"], name="workorder_c_MkOrdNO_8eb02b_idx"
                    ),
                    models.Index(
                        fields=["SubProdID"], name="workorder_c_SubProd_b92da7_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="workorder_c_updated_bd129c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ERPSystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        help_text="公司代號，例如：01、02、03",
                        max_length=10,
                        verbose_name="公司代號",
                    ),
                ),
                (
                    "server_name",
                    models.CharField(
                        help_text="ERP資料庫伺服器名稱",
                        max_length=100,
                        verbose_name="伺服器名稱",
                    ),
                ),
                (
                    "database_name",
                    models.CharField(
                        help_text="ERP資料庫名稱",
                        max_length=100,
                        verbose_name="資料庫名稱",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="ERP資料庫使用者名稱",
                        max_length=50,
                        verbose_name="使用者名稱",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="ERP資料庫密碼", max_length=100, verbose_name="密碼"
                    ),
                ),
                (
                    "sync_interval",
                    models.IntegerField(
                        default=30,
                        help_text="自動同步間隔時間（分鐘）",
                        verbose_name="同步間隔(分鐘)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="是否啟用此ERP連線",
                        verbose_name="啟用狀態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "ERP系統配置",
                "verbose_name_plural": "ERP系統配置管理",
                "db_table": "workorder_companyorder_erp_systemconfig",
                "ordering": ["company_code"],
                "indexes": [
                    models.Index(
                        fields=["company_code"], name="workorder_c_company_0e17b6_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="workorder_c_is_acti_2fe30b_idx"
                    ),
                ],
                "unique_together": {("company_code",)},
            },
        ),
    ]
