# 使用 Node.js 作為基礎映像
FROM node:14

# 設定工作目錄
WORKDIR /app

# 複製 package.json 和 package-lock.json 並安裝依賴
COPY package*.json ./
RUN npm install

# 複製其餘的應用程式檔案
COPY . .

# 建立 React 應用
RUN npm run build

# 開放 8080 端口，這是 React 應用的預設端口
EXPOSE 8080

# 使用 http-server 來運行構建後的應用
CMD ["npx", "http-server", "build"]
