# Generated by Django 5.1.8 on 2025-08-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackupSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("daily", "每天"),
                            ("weekly", "每週"),
                            ("monthly", "每月"),
                        ],
                        default="daily",
                        max_length=10,
                        verbose_name="備份頻率",
                    ),
                ),
                (
                    "backup_time",
                    models.TimeField(
                        help_text="每天執行備份的時間", verbose_name="備份時間"
                    ),
                ),
                (
                    "retention_days",
                    models.IntegerField(
                        default=30,
                        help_text="備份檔案保留的天數",
                        verbose_name="保留天數",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="啟用備份"),
                ),
                (
                    "last_backup",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最後備份時間"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "備份排程設定",
                "verbose_name_plural": "備份排程設定",
            },
        ),
        migrations.CreateModel(
            name="EmailConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_host",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("email_port", models.IntegerField(default=25)),
                ("email_use_tls", models.BooleanField(default=True)),
                (
                    "email_host_user",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "email_host_password",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "default_from_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="OperationLogConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "DEBUG"),
                            ("INFO", "INFO"),
                            ("WARNING", "WARNING"),
                            ("ERROR", "ERROR"),
                        ],
                        default="INFO",
                        max_length=20,
                        verbose_name="日誌等級",
                    ),
                ),
                (
                    "retention_days",
                    models.IntegerField(
                        default=90,
                        help_text="操作日誌保留的天數",
                        verbose_name="保留天數",
                    ),
                ),
                (
                    "max_file_size",
                    models.IntegerField(
                        default=10,
                        help_text="單個日誌檔案的最大大小",
                        verbose_name="最大檔案大小(MB)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="啟用日誌記錄"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "操作日誌設定",
                "verbose_name_plural": "操作日誌設定",
            },
        ),
        migrations.CreateModel(
            name="ReportDataSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sync_type", models.CharField(max_length=50, verbose_name="同步類型")),
                ("period_start", models.DateField(verbose_name="期間開始")),
                ("period_end", models.DateField(verbose_name="期間結束")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失敗"),
                            ("partial", "部分成功"),
                        ],
                        max_length=20,
                        verbose_name="同步狀態",
                    ),
                ),
                (
                    "records_processed",
                    models.IntegerField(default=0, verbose_name="處理記錄數"),
                ),
                (
                    "records_updated",
                    models.IntegerField(default=0, verbose_name="更新記錄數"),
                ),
                (
                    "records_created",
                    models.IntegerField(default=0, verbose_name="新增記錄數"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="錯誤訊息"),
                ),
                ("started_at", models.DateTimeField(verbose_name="開始時間")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成時間"
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(default=0, verbose_name="執行時間(秒)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "報表資料同步日誌",
                "verbose_name_plural": "報表資料同步日誌",
                "db_table": "system_report_data_sync_log",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportSyncSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("work_time", "工作報表"),
                            ("work_order", "工單機種報表"),
                            ("personnel", "人員績效報表"),
                            ("equipment", "設備效率報表"),
                            ("quality", "品質分析報表"),
                            ("comprehensive", "綜合分析報表"),
                            ("all", "所有報表"),
                        ],
                        max_length=20,
                        verbose_name="同步類型",
                    ),
                ),
                (
                    "sync_frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "每小時"),
                            ("daily", "每天"),
                            ("weekly", "每週"),
                            ("monthly", "每月"),
                        ],
                        default="daily",
                        max_length=10,
                        verbose_name="同步頻率",
                    ),
                ),
                (
                    "sync_time",
                    models.TimeField(
                        help_text="每天執行同步的時間", verbose_name="同步時間"
                    ),
                ),
                (
                    "data_source_modules",
                    models.JSONField(
                        default=list,
                        help_text="要同步的資料來源模組清單",
                        verbose_name="資料來源模組",
                    ),
                ),
                (
                    "include_pending_reports",
                    models.BooleanField(
                        default=False,
                        help_text="是否包含待核准的報工記錄",
                        verbose_name="包含待核准報工",
                    ),
                ),
                (
                    "include_approved_reports",
                    models.BooleanField(
                        default=True,
                        help_text="是否包含已核准的報工記錄",
                        verbose_name="包含已核准報工",
                    ),
                ),
                (
                    "auto_sync",
                    models.BooleanField(
                        default=True,
                        help_text="是否啟用自動同步",
                        verbose_name="自動同步",
                    ),
                ),
                (
                    "sync_retention_days",
                    models.IntegerField(
                        default=365,
                        help_text="同步資料的保留天數",
                        verbose_name="資料保留天數",
                    ),
                ),
                (
                    "retry_on_failure",
                    models.BooleanField(
                        default=True,
                        help_text="同步失敗時是否重試",
                        verbose_name="失敗重試",
                    ),
                ),
                (
                    "max_retry_attempts",
                    models.IntegerField(default=3, verbose_name="最大重試次數"),
                ),
                (
                    "last_sync_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最後同步時間"
                    ),
                ),
                (
                    "last_sync_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "成功"),
                            ("failed", "失敗"),
                            ("partial", "部分成功"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="最後同步狀態",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="啟用設定"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "報表同步設定",
                "verbose_name_plural": "報表同步設定",
                "unique_together": {("sync_type", "sync_frequency")},
            },
        ),
    ]
