# Generated by Django 5.1.8 on 2025-09-08 01:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoApprovalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="啟用後，符合條件的報工將自動審核通過",
                        verbose_name="啟用自動審核",
                    ),
                ),
                (
                    "approval_conditions",
                    models.JSONField(
                        default=dict,
                        help_text="自動審核的條件設定",
                        verbose_name="審核條件",
                    ),
                ),
                (
                    "auto_approve_work_hours",
                    models.BooleanField(
                        default=True,
                        help_text="工作時數在正常範圍內時自動審核",
                        verbose_name="自動審核工作時數",
                    ),
                ),
                (
                    "max_work_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=12.0,
                        help_text="超過此時數的報工需要人工審核",
                        max_digits=4,
                        verbose_name="最大工作時數",
                    ),
                ),
                (
                    "auto_approve_defect_rate",
                    models.BooleanField(
                        default=True,
                        help_text="不良率在正常範圍內時自動審核",
                        verbose_name="自動審核不良率",
                    ),
                ),
                (
                    "max_defect_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="超過此不良率的報工需要人工審核",
                        max_digits=5,
                        verbose_name="最大不良率(%)",
                    ),
                ),
                (
                    "auto_approve_overtime",
                    models.BooleanField(
                        default=False,
                        help_text="加班時數在正常範圍內時自動審核",
                        verbose_name="自動審核加班",
                    ),
                ),
                (
                    "max_overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=4.0,
                        help_text="超過此時數的加班需要人工審核",
                        max_digits=4,
                        verbose_name="最大加班時數",
                    ),
                ),
                (
                    "exclude_operators",
                    models.JSONField(
                        default=list,
                        help_text="這些作業員的報工不會自動審核",
                        verbose_name="排除作業員",
                    ),
                ),
                (
                    "exclude_processes",
                    models.JSONField(
                        default=list,
                        help_text="這些工序的報工不會自動審核",
                        verbose_name="排除工序",
                    ),
                ),
                (
                    "notification_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="自動審核後發送通知給主管",
                        verbose_name="啟用通知",
                    ),
                ),
                (
                    "notification_recipients",
                    models.JSONField(
                        default=list,
                        help_text="自動審核通知的收件人清單",
                        verbose_name="通知收件人",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "自動審核設定",
                "verbose_name_plural": "自動審核設定",
            },
        ),
        migrations.CreateModel(
            name="BackupSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("daily", "每天"),
                            ("weekly", "每週"),
                            ("monthly", "每月"),
                        ],
                        default="daily",
                        max_length=10,
                        verbose_name="備份頻率",
                    ),
                ),
                (
                    "backup_time",
                    models.TimeField(
                        default="02:00:00",
                        help_text="每天執行備份的時間",
                        verbose_name="備份時間",
                    ),
                ),
                (
                    "retention_days",
                    models.IntegerField(
                        default=30,
                        help_text="備份檔案保留的天數",
                        verbose_name="保留天數",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="啟用備份"),
                ),
                (
                    "last_backup",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最後備份時間"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "備份排程設定",
                "verbose_name_plural": "備份排程設定",
            },
        ),
        migrations.CreateModel(
            name="EmailConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_host",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="郵件主機"
                    ),
                ),
                (
                    "email_port",
                    models.IntegerField(default=25, verbose_name="郵件埠號"),
                ),
                (
                    "email_use_tls",
                    models.BooleanField(default=True, verbose_name="使用TLS加密"),
                ),
                (
                    "email_host_user",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="郵件帳號"
                    ),
                ),
                (
                    "email_host_password",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="郵件密碼"
                    ),
                ),
                (
                    "default_from_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="預設寄件者郵箱",
                    ),
                ),
            ],
            options={
                "verbose_name": "郵件主機設定",
                "verbose_name_plural": "郵件主機設定",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="OperationLogConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "DEBUG"),
                            ("INFO", "INFO"),
                            ("WARNING", "WARNING"),
                            ("ERROR", "ERROR"),
                        ],
                        default="INFO",
                        max_length=20,
                        verbose_name="日誌等級",
                    ),
                ),
                (
                    "retention_days",
                    models.IntegerField(
                        default=90,
                        help_text="操作日誌保留的天數",
                        verbose_name="保留天數",
                    ),
                ),
                (
                    "max_file_size",
                    models.IntegerField(
                        default=10,
                        help_text="單個日誌檔案的最大大小",
                        verbose_name="最大檔案大小(MB)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="啟用日誌記錄"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "操作日誌設定",
                "verbose_name_plural": "操作日誌設定",
            },
        ),
        migrations.CreateModel(
            name="OrderSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("sync", "資料同步"),
                            ("cleanup", "資料清理"),
                            ("status_update", "狀態更新"),
                        ],
                        max_length=20,
                        verbose_name="同步類型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "執行中"),
                            ("success", "成功"),
                            ("failed", "失敗"),
                        ],
                        max_length=20,
                        verbose_name="執行狀態",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="執行訊息")),
                ("details", models.JSONField(default=dict, verbose_name="詳細資訊")),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="開始時間"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成時間"
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="執行時間（秒）"
                    ),
                ),
            ],
            options={
                "verbose_name": "訂單同步日誌",
                "verbose_name_plural": "訂單同步日誌",
                "db_table": "system_order_sync_log",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderSyncSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_enabled",
                    models.BooleanField(default=True, verbose_name="啟用自動同步"),
                ),
                (
                    "sync_interval_minutes",
                    models.IntegerField(default=30, verbose_name="同步間隔（分鐘）"),
                ),
                (
                    "last_sync_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次同步時間"
                    ),
                ),
                (
                    "last_sync_status",
                    models.CharField(
                        default="未執行", max_length=20, verbose_name="上次同步狀態"
                    ),
                ),
                (
                    "last_sync_message",
                    models.TextField(blank=True, verbose_name="上次同步訊息"),
                ),
                (
                    "cleanup_enabled",
                    models.BooleanField(default=True, verbose_name="啟用自動清理"),
                ),
                (
                    "cleanup_interval_hours",
                    models.IntegerField(default=24, verbose_name="清理間隔（小時）"),
                ),
                (
                    "cleanup_retention_days",
                    models.IntegerField(default=90, verbose_name="資料保留天數"),
                ),
                (
                    "last_cleanup_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次清理時間"
                    ),
                ),
                (
                    "last_cleanup_count",
                    models.IntegerField(default=0, verbose_name="上次清理數量"),
                ),
                (
                    "status_update_enabled",
                    models.BooleanField(default=True, verbose_name="啟用狀態更新"),
                ),
                (
                    "status_update_interval_minutes",
                    models.IntegerField(
                        default=60, verbose_name="狀態更新間隔（分鐘）"
                    ),
                ),
                (
                    "last_status_update_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次狀態更新時間"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "訂單同步設定",
                "verbose_name_plural": "訂單同步設定",
                "db_table": "system_order_sync_settings",
            },
        ),
        migrations.CreateModel(
            name="ReportDataSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sync_type", models.CharField(max_length=50, verbose_name="同步類型")),
                ("period_start", models.DateField(verbose_name="期間開始")),
                ("period_end", models.DateField(verbose_name="期間結束")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失敗"),
                            ("partial", "部分成功"),
                        ],
                        max_length=20,
                        verbose_name="同步狀態",
                    ),
                ),
                (
                    "records_processed",
                    models.IntegerField(default=0, verbose_name="處理記錄數"),
                ),
                (
                    "records_updated",
                    models.IntegerField(default=0, verbose_name="更新記錄數"),
                ),
                (
                    "records_created",
                    models.IntegerField(default=0, verbose_name="新增記錄數"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="錯誤訊息"),
                ),
                ("started_at", models.DateTimeField(verbose_name="開始時間")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成時間"
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(default=0, verbose_name="執行時間(秒)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "報表資料同步日誌",
                "verbose_name_plural": "報表資料同步日誌",
                "db_table": "system_report_data_sync_log",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="任務名稱")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("auto_approve", "自動審核"),
                            ("workorder_analysis", "工單分析"),
                            ("data_backup", "資料備份"),
                            ("report_generation", "報表生成"),
                            ("data_cleanup", "資料清理"),
                            ("completion_check", "完工判斷"),
                        ],
                        max_length=50,
                        verbose_name="任務類型",
                    ),
                ),
                (
                    "task_function",
                    models.CharField(max_length=200, verbose_name="任務函數"),
                ),
                (
                    "execution_type",
                    models.CharField(
                        choices=[("interval", "間隔執行"), ("fixed_time", "固定時間")],
                        default="interval",
                        help_text="選擇執行方式：間隔執行或固定時間執行",
                        max_length=20,
                        verbose_name="執行類型",
                    ),
                ),
                (
                    "interval_minutes",
                    models.IntegerField(
                        default=30,
                        help_text="每多少分鐘執行一次（僅適用於間隔執行）",
                        verbose_name="間隔分鐘數",
                    ),
                ),
                (
                    "fixed_time",
                    models.TimeField(
                        blank=True,
                        help_text="每天固定時間執行（僅適用於固定時間執行）",
                        null=True,
                        verbose_name="固定執行時間",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="啟用狀態"),
                ),
                ("description", models.TextField(blank=True, verbose_name="任務描述")),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最後執行時間"
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="下次執行時間"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "定時任務",
                "verbose_name_plural": "定時任務",
                "db_table": "system_scheduled_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CleanupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100, verbose_name="操作類型")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失敗"),
                            ("pending", "執行中"),
                        ],
                        max_length=10,
                        verbose_name="執行狀態",
                    ),
                ),
                (
                    "execution_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="執行時間"),
                ),
                (
                    "details",
                    models.TextField(blank=True, null=True, verbose_name="執行詳情"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="執行使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "清理操作日誌",
                "verbose_name_plural": "清理操作日誌",
                "ordering": ["-execution_time"],
            },
        ),
        migrations.CreateModel(
            name="ReportSyncSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("work_time", "工作報表"),
                            ("work_order", "工單機種報表"),
                            ("personnel", "人員績效報表"),
                            ("equipment", "設備效率報表"),
                            ("quality", "品質分析報表"),
                            ("comprehensive", "綜合分析報表"),
                            ("all", "所有報表"),
                        ],
                        max_length=20,
                        verbose_name="同步類型",
                    ),
                ),
                (
                    "sync_frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "每小時"),
                            ("daily", "每天"),
                            ("weekly", "每週"),
                            ("monthly", "每月"),
                        ],
                        default="daily",
                        max_length=10,
                        verbose_name="同步頻率",
                    ),
                ),
                (
                    "sync_time",
                    models.TimeField(
                        help_text="每天執行同步的時間", verbose_name="同步時間"
                    ),
                ),
                (
                    "data_source_modules",
                    models.JSONField(
                        default=list,
                        help_text="要同步的資料來源模組清單",
                        verbose_name="資料來源模組",
                    ),
                ),
                (
                    "include_pending_reports",
                    models.BooleanField(
                        default=False,
                        help_text="是否包含待核准的報工記錄",
                        verbose_name="包含待核准報工",
                    ),
                ),
                (
                    "include_approved_reports",
                    models.BooleanField(
                        default=True,
                        help_text="是否包含已核准的報工記錄",
                        verbose_name="包含已核准報工",
                    ),
                ),
                (
                    "auto_sync",
                    models.BooleanField(
                        default=True,
                        help_text="是否啟用自動同步",
                        verbose_name="自動同步",
                    ),
                ),
                (
                    "sync_retention_days",
                    models.IntegerField(
                        default=365,
                        help_text="同步資料的保留天數",
                        verbose_name="資料保留天數",
                    ),
                ),
                (
                    "retry_on_failure",
                    models.BooleanField(
                        default=True,
                        help_text="同步失敗時是否重試",
                        verbose_name="失敗重試",
                    ),
                ),
                (
                    "max_retry_attempts",
                    models.IntegerField(default=3, verbose_name="最大重試次數"),
                ),
                (
                    "last_sync_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最後同步時間"
                    ),
                ),
                (
                    "last_sync_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "成功"),
                            ("failed", "失敗"),
                            ("partial", "部分成功"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="最後同步狀態",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="啟用設定"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "報表同步設定",
                "verbose_name_plural": "報表同步設定",
                "unique_together": {("sync_type", "sync_frequency")},
            },
        ),
        migrations.CreateModel(
            name="UserWorkPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_operate_all_operators",
                    models.BooleanField(default=True, verbose_name="可操作所有作業員"),
                ),
                (
                    "allowed_operators",
                    models.JSONField(
                        blank=True, default=list, verbose_name="允許的作業員ID列表"
                    ),
                ),
                (
                    "can_operate_all_processes",
                    models.BooleanField(default=True, verbose_name="可操作所有工序"),
                ),
                (
                    "allowed_processes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="允許的工序ID列表"
                    ),
                ),
                (
                    "can_operate_all_equipments",
                    models.BooleanField(default=True, verbose_name="可操作所有設備"),
                ),
                (
                    "allowed_equipments",
                    models.JSONField(
                        blank=True, default=list, verbose_name="允許的設備ID列表"
                    ),
                ),
                (
                    "can_fill_work",
                    models.BooleanField(default=True, verbose_name="可進行補登填報"),
                ),
                (
                    "can_onsite_reporting",
                    models.BooleanField(default=True, verbose_name="可進行現場報工"),
                ),
                (
                    "can_smt_reporting",
                    models.BooleanField(default=True, verbose_name="可進行SMT報工"),
                ),
                (
                    "data_scope",
                    models.CharField(
                        choices=[
                            ("all", "全部資料"),
                            ("own", "僅自己的資料"),
                            ("department", "部門資料"),
                            ("custom", "自定義範圍"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="資料範圍",
                    ),
                ),
                ("can_view", models.BooleanField(default=True, verbose_name="可查看")),
                ("can_add", models.BooleanField(default=True, verbose_name="可新增")),
                ("can_edit", models.BooleanField(default=True, verbose_name="可編輯")),
                (
                    "can_delete",
                    models.BooleanField(default=False, verbose_name="可刪除"),
                ),
                (
                    "can_approve",
                    models.BooleanField(default=False, verbose_name="可審核"),
                ),
                (
                    "can_reject",
                    models.BooleanField(default=False, verbose_name="可駁回"),
                ),
                (
                    "can_override_limits",
                    models.BooleanField(default=False, verbose_name="可超越限制"),
                ),
                (
                    "can_export_data",
                    models.BooleanField(default=True, verbose_name="可匯出資料"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "用戶工作權限",
                "verbose_name_plural": "用戶工作權限",
                "db_table": "system_user_work_permission",
            },
        ),
        migrations.CreateModel(
            name="AutoApprovalTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="為此定時任務設定一個描述性名稱",
                        max_length=100,
                        verbose_name="任務名稱",
                    ),
                ),
                (
                    "execution_type",
                    models.CharField(
                        choices=[("interval", "間隔執行"), ("fixed_time", "固定時間")],
                        default="interval",
                        help_text="選擇執行方式：間隔執行或固定時間執行",
                        max_length=20,
                        verbose_name="執行類型",
                    ),
                ),
                (
                    "interval_minutes",
                    models.IntegerField(
                        default=30,
                        help_text="每多少分鐘執行一次自動審核（僅適用於間隔執行）",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                        verbose_name="執行間隔（分鐘）",
                    ),
                ),
                (
                    "fixed_time",
                    models.TimeField(
                        blank=True,
                        help_text="每天固定時間執行（僅適用於固定時間執行）",
                        null=True,
                        verbose_name="固定執行時間",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="是否啟用此定時任務",
                        verbose_name="啟用狀態",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="可選的任務描述", verbose_name="任務描述"
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最後執行時間"
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="下次執行時間"
                    ),
                ),
                (
                    "execution_count",
                    models.IntegerField(
                        default=0,
                        help_text="此任務已執行的總次數",
                        verbose_name="執行次數",
                    ),
                ),
                (
                    "success_count",
                    models.IntegerField(
                        default=0,
                        help_text="此任務成功執行的次數",
                        verbose_name="成功次數",
                    ),
                ),
                (
                    "error_count",
                    models.IntegerField(
                        default=0,
                        help_text="此任務執行失敗的次數",
                        verbose_name="錯誤次數",
                    ),
                ),
                (
                    "last_error_message",
                    models.TextField(
                        blank=True,
                        help_text="記錄最後一次執行失敗的錯誤訊息",
                        verbose_name="最後錯誤訊息",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_auto_approval_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="建立者",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_auto_approval_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "自動審核定時任務",
                "verbose_name_plural": "自動審核定時任務",
                "db_table": "system_auto_approval_task",
                "ordering": ["-created_at"],
                "unique_together": {("name",)},
            },
        ),
        migrations.CreateModel(
            name="UserPermissionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_operate_all_operators",
                    models.BooleanField(default=True, verbose_name="可操作全部作業員"),
                ),
                (
                    "allowed_operators",
                    models.JSONField(
                        blank=True, default=list, verbose_name="可操作作業員列表"
                    ),
                ),
                (
                    "can_operate_all_processes",
                    models.BooleanField(default=True, verbose_name="可操作全部工序"),
                ),
                (
                    "allowed_processes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="可操作工序列表"
                    ),
                ),
                (
                    "can_operate_all_equipments",
                    models.BooleanField(default=True, verbose_name="可操作全部設備"),
                ),
                (
                    "allowed_equipments",
                    models.JSONField(
                        blank=True, default=list, verbose_name="可操作設備列表"
                    ),
                ),
                (
                    "can_fill_work",
                    models.BooleanField(default=True, verbose_name="可填報報工"),
                ),
                (
                    "can_onsite_reporting",
                    models.BooleanField(default=True, verbose_name="可現場報工"),
                ),
                (
                    "can_smt_reporting",
                    models.BooleanField(default=False, verbose_name="可SMT報工"),
                ),
                (
                    "can_access_equip",
                    models.BooleanField(default=True, verbose_name="可訪問設備管理"),
                ),
                (
                    "can_access_workorder",
                    models.BooleanField(default=True, verbose_name="可訪問工單管理"),
                ),
                (
                    "can_access_quality",
                    models.BooleanField(default=True, verbose_name="可訪問品質管理"),
                ),
                (
                    "can_access_material",
                    models.BooleanField(default=True, verbose_name="可訪問物料管理"),
                ),
                (
                    "can_access_scheduling",
                    models.BooleanField(default=True, verbose_name="可訪問排程管理"),
                ),
                (
                    "can_access_process",
                    models.BooleanField(default=True, verbose_name="可訪問製程管理"),
                ),
                (
                    "can_access_reporting",
                    models.BooleanField(default=True, verbose_name="可訪問報表管理"),
                ),
                (
                    "can_access_kanban",
                    models.BooleanField(default=True, verbose_name="可訪問看板管理"),
                ),
                (
                    "can_access_ai",
                    models.BooleanField(default=True, verbose_name="可訪問AI管理"),
                ),
                ("can_view", models.BooleanField(default=True, verbose_name="可查看")),
                ("can_add", models.BooleanField(default=True, verbose_name="可新增")),
                ("can_edit", models.BooleanField(default=True, verbose_name="可編輯")),
                (
                    "can_delete",
                    models.BooleanField(default=False, verbose_name="可刪除"),
                ),
                (
                    "can_export",
                    models.BooleanField(default=True, verbose_name="可匯出"),
                ),
                (
                    "can_import",
                    models.BooleanField(default=False, verbose_name="可匯入"),
                ),
                (
                    "can_approve",
                    models.BooleanField(default=False, verbose_name="可審核"),
                ),
                (
                    "data_scope",
                    models.CharField(
                        choices=[
                            ("own", "自己的資料"),
                            ("department", "部門資料"),
                            ("company", "公司資料"),
                            ("all", "所有資料"),
                        ],
                        default="own",
                        max_length=20,
                        verbose_name="資料範圍",
                    ),
                ),
                (
                    "can_manage_users",
                    models.BooleanField(default=False, verbose_name="可管理使用者"),
                ),
                (
                    "can_manage_permissions",
                    models.BooleanField(default=False, verbose_name="可管理權限"),
                ),
                (
                    "can_view_logs",
                    models.BooleanField(default=False, verbose_name="可查看日誌"),
                ),
                (
                    "can_system_config",
                    models.BooleanField(default=False, verbose_name="可系統設定"),
                ),
                (
                    "can_access_24h",
                    models.BooleanField(default=True, verbose_name="24小時存取權限"),
                ),
                (
                    "can_access_worktime",
                    models.BooleanField(default=True, verbose_name="工作時間存取權限"),
                ),
                (
                    "work_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="工作開始時間"
                    ),
                ),
                (
                    "work_end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="工作結束時間"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "使用者權限細分",
                "verbose_name_plural": "使用者權限細分",
                "db_table": "system_user_permission_detail",
                "unique_together": {("user",)},
            },
        ),
    ]
