# Generated by Django 5.1.8 on 2025-09-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledtask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("auto_approve", "自動審核"),
                    ("workorder_analysis", "工單分析"),
                    ("data_backup", "資料備份"),
                    ("report_generation", "報表生成"),
                    ("data_cleanup", "資料清理"),
                    ("completion_check", "完工判斷"),
                ],
                max_length=50,
                verbose_name="任務類型",
            ),
        ),
    ]
