# Generated by Django 5.1.8 on 2025-07-28 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDataSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sync_type", models.CharField(max_length=50, verbose_name="同步類型")),
                ("period_start", models.DateField(verbose_name="期間開始")),
                ("period_end", models.DateField(verbose_name="期間結束")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失敗"),
                            ("partial", "部分成功"),
                        ],
                        max_length=20,
                        verbose_name="同步狀態",
                    ),
                ),
                (
                    "records_processed",
                    models.IntegerField(default=0, verbose_name="處理記錄數"),
                ),
                (
                    "records_updated",
                    models.IntegerField(default=0, verbose_name="更新記錄數"),
                ),
                (
                    "records_created",
                    models.IntegerField(default=0, verbose_name="新增記錄數"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="錯誤訊息"),
                ),
                ("started_at", models.DateTimeField(verbose_name="開始時間")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成時間"
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(default=0, verbose_name="執行時間(秒)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "報表資料同步日誌",
                "verbose_name_plural": "報表資料同步日誌",
                "db_table": "system_report_data_sync_log",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="backupschedule",
            options={
                "verbose_name": "備份排程設定",
                "verbose_name_plural": "備份排程設定",
            },
        ),
        migrations.AlterModelOptions(
            name="operationlogconfig",
            options={
                "verbose_name": "操作日誌設定",
                "verbose_name_plural": "操作日誌設定",
            },
        ),
        migrations.RemoveField(
            model_name="backupschedule",
            name="retain_count",
        ),
        migrations.RemoveField(
            model_name="operationlogconfig",
            name="retain_days",
        ),
        migrations.AddField(
            model_name="backupschedule",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="建立時間",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="backupschedule",
            name="last_backup",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最後備份時間"
            ),
        ),
        migrations.AddField(
            model_name="backupschedule",
            name="retention_days",
            field=models.IntegerField(
                default=30, help_text="備份檔案保留的天數", verbose_name="保留天數"
            ),
        ),
        migrations.AddField(
            model_name="backupschedule",
            name="schedule_type",
            field=models.CharField(
                choices=[("daily", "每天"), ("weekly", "每週"), ("monthly", "每月")],
                default="daily",
                max_length=10,
                verbose_name="備份頻率",
            ),
        ),
        migrations.AddField(
            model_name="backupschedule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
        migrations.AddField(
            model_name="operationlogconfig",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="建立時間",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="operationlogconfig",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="啟用日誌記錄"),
        ),
        migrations.AddField(
            model_name="operationlogconfig",
            name="log_level",
            field=models.CharField(
                choices=[
                    ("DEBUG", "DEBUG"),
                    ("INFO", "INFO"),
                    ("WARNING", "WARNING"),
                    ("ERROR", "ERROR"),
                ],
                default="INFO",
                max_length=20,
                verbose_name="日誌等級",
            ),
        ),
        migrations.AddField(
            model_name="operationlogconfig",
            name="max_file_size",
            field=models.IntegerField(
                default=10,
                help_text="單個日誌檔案的最大大小",
                verbose_name="最大檔案大小(MB)",
            ),
        ),
        migrations.AddField(
            model_name="operationlogconfig",
            name="retention_days",
            field=models.IntegerField(
                default=90, help_text="操作日誌保留的天數", verbose_name="保留天數"
            ),
        ),
        migrations.AddField(
            model_name="operationlogconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
        migrations.AlterField(
            model_name="backupschedule",
            name="backup_time",
            field=models.TimeField(
                help_text="每天執行備份的時間", verbose_name="備份時間"
            ),
        ),
        migrations.AlterField(
            model_name="backupschedule",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="啟用備份"),
        ),
        migrations.CreateModel(
            name="ReportEmailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("work_time", "工作時間報表"),
                            ("work_order", "工單機種報表"),
                            ("personnel", "人員績效報表"),
                            ("equipment", "設備效率報表"),
                            ("quality", "品質分析報表"),
                            ("comprehensive", "綜合分析報表"),
                            ("all", "所有報表"),
                        ],
                        max_length=20,
                        verbose_name="報表類型",
                    ),
                ),
                (
                    "send_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "每天"),
                            ("weekly", "每週"),
                            ("monthly", "每月"),
                            ("on_demand", "按需發送"),
                        ],
                        default="daily",
                        max_length=10,
                        verbose_name="發送頻率",
                    ),
                ),
                (
                    "send_time",
                    models.TimeField(
                        help_text="每天發送報表的時間", verbose_name="發送時間"
                    ),
                ),
                (
                    "recipients",
                    models.TextField(
                        help_text="多個郵箱請用逗號分隔", verbose_name="收件人郵箱"
                    ),
                ),
                (
                    "cc_recipients",
                    models.TextField(
                        blank=True,
                        help_text="多個郵箱請用逗號分隔",
                        verbose_name="副本收件人",
                    ),
                ),
                (
                    "bcc_recipients",
                    models.TextField(
                        blank=True,
                        help_text="多個郵箱請用逗號分隔",
                        verbose_name="密件副本收件人",
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        default="MES 系統 - {report_type} - {date}",
                        help_text="支援 {report_type}、{date}、{company} 等變數",
                        max_length=200,
                        verbose_name="郵件主旨模板",
                    ),
                ),
                (
                    "email_template",
                    models.TextField(
                        blank=True,
                        help_text="支援 HTML 格式，可使用 {report_data}、{summary} 等變數",
                        verbose_name="郵件內容模板",
                    ),
                ),
                (
                    "include_excel",
                    models.BooleanField(default=True, verbose_name="包含 Excel 附件"),
                ),
                (
                    "include_csv",
                    models.BooleanField(default=False, verbose_name="包含 CSV 附件"),
                ),
                (
                    "include_pdf",
                    models.BooleanField(default=False, verbose_name="包含 PDF 附件"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="啟用發送"),
                ),
                (
                    "auto_send",
                    models.BooleanField(
                        default=True,
                        help_text="是否啟用自動發送",
                        verbose_name="自動發送",
                    ),
                ),
                (
                    "last_send_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最後發送時間"
                    ),
                ),
                (
                    "last_send_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "成功"),
                            ("failed", "失敗"),
                            ("partial", "部分成功"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="最後發送狀態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "報表郵件設定",
                "verbose_name_plural": "報表郵件設定",
                "unique_together": {("report_type", "send_frequency")},
            },
        ),
        migrations.CreateModel(
            name="ReportSyncSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("work_time", "工作時間報表"),
                            ("work_order", "工單機種報表"),
                            ("personnel", "人員績效報表"),
                            ("equipment", "設備效率報表"),
                            ("quality", "品質分析報表"),
                            ("comprehensive", "綜合分析報表"),
                            ("all", "所有報表"),
                        ],
                        max_length=20,
                        verbose_name="同步類型",
                    ),
                ),
                (
                    "sync_frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "每小時"),
                            ("daily", "每天"),
                            ("weekly", "每週"),
                            ("monthly", "每月"),
                        ],
                        default="daily",
                        max_length=10,
                        verbose_name="同步頻率",
                    ),
                ),
                (
                    "sync_time",
                    models.TimeField(
                        help_text="每天執行同步的時間", verbose_name="同步時間"
                    ),
                ),
                (
                    "data_source_modules",
                    models.JSONField(
                        default=list,
                        help_text="要同步的資料來源模組清單",
                        verbose_name="資料來源模組",
                    ),
                ),
                (
                    "include_pending_reports",
                    models.BooleanField(
                        default=False,
                        help_text="是否包含待核准的報工記錄",
                        verbose_name="包含待核准報工",
                    ),
                ),
                (
                    "include_approved_reports",
                    models.BooleanField(
                        default=True,
                        help_text="是否包含已核准的報工記錄",
                        verbose_name="包含已核准報工",
                    ),
                ),
                (
                    "auto_sync",
                    models.BooleanField(
                        default=True,
                        help_text="是否啟用自動同步",
                        verbose_name="自動同步",
                    ),
                ),
                (
                    "sync_retention_days",
                    models.IntegerField(
                        default=365,
                        help_text="同步資料的保留天數",
                        verbose_name="資料保留天數",
                    ),
                ),
                (
                    "retry_on_failure",
                    models.BooleanField(
                        default=True,
                        help_text="同步失敗時是否重試",
                        verbose_name="失敗重試",
                    ),
                ),
                (
                    "max_retry_attempts",
                    models.IntegerField(default=3, verbose_name="最大重試次數"),
                ),
                (
                    "last_sync_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最後同步時間"
                    ),
                ),
                (
                    "last_sync_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "成功"),
                            ("failed", "失敗"),
                            ("partial", "部分成功"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="最後同步狀態",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="啟用設定"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "報表同步設定",
                "verbose_name_plural": "報表同步設定",
                "unique_together": {("sync_type", "sync_frequency")},
            },
        ),
    ]
