# Generated by Django 5.2.6 on 2025-09-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        # 添加 user 欄位到 UserWorkPermission
        migrations.AddField(
            model_name='userworkpermission',
            name='user',
            field=models.CharField(max_length=100, null=True, blank=True, verbose_name='使用者'),
        ),
    ]
