# Generated by Django 5.1.8 on 2025-08-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_add_user_work_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userworkpermission",
            name="operator_codes",
            field=models.TextField(
                help_text="可操作的作業員編號，多個用逗號分隔，留空表示可操作所有作業員",
                verbose_name="作業員編號",
            ),
        ),
        migrations.AlterField(
            model_name="userworkpermission",
            name="process_names",
            field=models.TextField(
                help_text="可操作的工序名稱，多個用逗號分隔，留空表示可操作所有工序",
                verbose_name="工序名稱",
            ),
        ),
    ]
