# Generated by Django 5.2.6 on 2025-09-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_auto_20250910_1047"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoapprovaltask",
            name="created_by",
            field=models.CharField(
                blank=True,
                help_text="建立者名稱（非外鍵關係，純文字欄位）",
                max_length=150,
                null=True,
                verbose_name="建立者",
            ),
        ),
        migrations.AlterField(
            model_name="autoapprovaltask",
            name="updated_by",
            field=models.CharField(
                blank=True,
                help_text="更新者名稱（非外鍵關係，純文字欄位）",
                max_length=150,
                null=True,
                verbose_name="更新者",
            ),
        ),
        migrations.AlterField(
            model_name="cleanuplog",
            name="user",
            field=models.CharField(
                blank=True,
                help_text="執行使用者名稱（非外鍵關係，純文字欄位）",
                max_length=150,
                null=True,
                verbose_name="執行使用者",
            ),
        ),
        migrations.AlterField(
            model_name="userpermissiondetail",
            name="user",
            field=models.CharField(
                help_text="使用者名稱（非外鍵關係，純文字欄位）",
                max_length=150,
                verbose_name="使用者",
            ),
        ),
        migrations.AlterField(
            model_name="userworkpermission",
            name="user",
            field=models.CharField(
                default="system",
                help_text="用戶名稱（非外鍵關係，純文字欄位）",
                max_length=100,
                unique=True,
                verbose_name="用戶",
            ),
        ),
    ]
