# Generated by Django 5.1.8 on 2025-07-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_reportdatasynclog_alter_backupschedule_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReportEmailSettings",
        ),
    ]
