# Generated by Django 5.1.8 on 2025-08-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_alter_userworkpermission_operator_codes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoApprovalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="啟用後，符合條件的報工將自動審核通過",
                        verbose_name="啟用自動審核",
                    ),
                ),
                (
                    "approval_conditions",
                    models.JSONField(
                        default=dict,
                        help_text="自動審核的條件設定",
                        verbose_name="審核條件",
                    ),
                ),
                (
                    "auto_approve_work_hours",
                    models.BooleanField(
                        default=True,
                        help_text="工作時數在正常範圍內時自動審核",
                        verbose_name="自動審核工作時數",
                    ),
                ),
                (
                    "max_work_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=12.0,
                        help_text="超過此時數的報工需要人工審核",
                        max_digits=4,
                        verbose_name="最大工作時數",
                    ),
                ),
                (
                    "auto_approve_defect_rate",
                    models.BooleanField(
                        default=True,
                        help_text="不良率在正常範圍內時自動審核",
                        verbose_name="自動審核不良率",
                    ),
                ),
                (
                    "max_defect_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="超過此不良率的報工需要人工審核",
                        max_digits=5,
                        verbose_name="最大不良率(%)",
                    ),
                ),
                (
                    "auto_approve_overtime",
                    models.BooleanField(
                        default=False,
                        help_text="加班時數在正常範圍內時自動審核",
                        verbose_name="自動審核加班",
                    ),
                ),
                (
                    "max_overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=4.0,
                        help_text="超過此時數的加班需要人工審核",
                        max_digits=4,
                        verbose_name="最大加班時數",
                    ),
                ),
                (
                    "exclude_operators",
                    models.JSONField(
                        default=list,
                        help_text="這些作業員的報工不會自動審核",
                        verbose_name="排除作業員",
                    ),
                ),
                (
                    "exclude_processes",
                    models.JSONField(
                        default=list,
                        help_text="這些工序的報工不會自動審核",
                        verbose_name="排除工序",
                    ),
                ),
                (
                    "notification_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="自動審核後發送通知給主管",
                        verbose_name="啟用通知",
                    ),
                ),
                (
                    "notification_recipients",
                    models.JSONField(
                        default=list,
                        help_text="自動審核通知的收件人清單",
                        verbose_name="通知收件人",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "自動審核設定",
                "verbose_name_plural": "自動審核設定",
            },
        ),
    ]
