# Generated by Django 5.1.8 on 2025-07-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_delete_reportemailsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportsyncsettings",
            name="sync_type",
            field=models.CharField(
                choices=[
                    ("work_time", "工作報表"),
                    ("work_order", "工單機種報表"),
                    ("personnel", "人員績效報表"),
                    ("equipment", "設備效率報表"),
                    ("quality", "品質分析報表"),
                    ("comprehensive", "綜合分析報表"),
                    ("all", "所有報表"),
                ],
                max_length=20,
                verbose_name="同步類型",
            ),
        ),
    ]
