# Generated by Django 5.1.8 on 2025-08-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0004_autoapprovalsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="userworkpermission",
            name="equipment_names",
            field=models.TextField(
                blank=True,
                help_text="可操作的設備名稱，多個用逗號分隔，留空表示可操作所有設備",
                null=True,
                verbose_name="設備名稱",
            ),
        ),
    ]
