# Generated by Django 5.1.8 on 2025-08-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0005_add_equipment_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="userworkpermission",
            name="disable_all_equipment",
            field=models.BooleanField(
                default=False,
                help_text="勾選此項將禁用該使用者的所有設備操作權限",
                verbose_name="禁用所有設備",
            ),
        ),
    ]
