# Generated by Django 5.1.8 on 2025-08-26 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0006_add_disable_all_equipment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CleanupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100, verbose_name="操作類型")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失敗"),
                            ("pending", "執行中"),
                        ],
                        max_length=10,
                        verbose_name="執行狀態",
                    ),
                ),
                (
                    "execution_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="執行時間"),
                ),
                (
                    "details",
                    models.TextField(blank=True, null=True, verbose_name="執行詳情"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="執行使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "清理操作日誌",
                "verbose_name_plural": "清理操作日誌",
                "ordering": ["-execution_time"],
            },
        ),
    ]
