# Generated by Django 5.1.8 on 2025-08-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0007_cleanuplog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="任務名稱")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("auto_approve", "自動審核"),
                            ("workorder_analysis", "工單分析"),
                            ("data_backup", "資料備份"),
                            ("report_generation", "報表生成"),
                            ("data_cleanup", "資料清理"),
                        ],
                        max_length=50,
                        verbose_name="任務類型",
                    ),
                ),
                (
                    "task_function",
                    models.CharField(max_length=200, verbose_name="任務函數"),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        help_text="格式: 分鐘 小時 日 月 星期 (例如: 0 9 * * 1-5)",
                        max_length=100,
                        verbose_name="Cron表達式",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="啟用狀態"),
                ),
                ("description", models.TextField(blank=True, verbose_name="任務描述")),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最後執行時間"
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="下次執行時間"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "定時任務",
                "verbose_name_plural": "定時任務",
                "db_table": "system_scheduled_task",
                "ordering": ["-created_at"],
            },
        ),
    ]
