# Generated by Django 5.1.8 on 2025-08-26 07:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0008_scheduledtask"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledtask",
            name="cron_expression",
        ),
        migrations.AddField(
            model_name="scheduledtask",
            name="interval_minutes",
            field=models.IntegerField(
                blank=True,
                default=30,
                help_text="每多少分鐘執行一次",
                null=True,
                verbose_name="間隔分鐘數",
            ),
        ),
        migrations.CreateModel(
            name="AutoApprovalTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="為此定時任務設定一個描述性名稱",
                        max_length=100,
                        verbose_name="任務名稱",
                    ),
                ),
                (
                    "interval_minutes",
                    models.IntegerField(
                        default=30,
                        help_text="每多少分鐘執行一次自動審核",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                        verbose_name="執行間隔（分鐘）",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="是否啟用此定時任務",
                        verbose_name="啟用狀態",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="可選的任務描述", verbose_name="任務描述"
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最後執行時間"
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="下次執行時間"
                    ),
                ),
                (
                    "execution_count",
                    models.IntegerField(
                        default=0,
                        help_text="此任務已執行的總次數",
                        verbose_name="執行次數",
                    ),
                ),
                (
                    "success_count",
                    models.IntegerField(
                        default=0,
                        help_text="此任務成功執行的次數",
                        verbose_name="成功次數",
                    ),
                ),
                (
                    "error_count",
                    models.IntegerField(
                        default=0,
                        help_text="此任務執行失敗的次數",
                        verbose_name="錯誤次數",
                    ),
                ),
                (
                    "last_error_message",
                    models.TextField(
                        blank=True,
                        help_text="記錄最後一次執行失敗的錯誤訊息",
                        verbose_name="最後錯誤訊息",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_auto_approval_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="建立者",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_auto_approval_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "自動審核定時任務",
                "verbose_name_plural": "自動審核定時任務",
                "db_table": "system_auto_approval_task",
                "ordering": ["-created_at"],
                "unique_together": {("name",)},
            },
        ),
    ]
