# Generated by Django 5.1.8 on 2025-08-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0009_remove_scheduledtask_cron_expression_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledtask",
            name="interval_minutes",
            field=models.IntegerField(
                default=30, help_text="每多少分鐘執行一次", verbose_name="間隔分鐘數"
            ),
        ),
    ]
