# Generated by Django 5.1.8 on 2025-08-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0011_autoapprovaltask_execution_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledtask",
            name="execution_type",
            field=models.CharField(
                choices=[("interval", "間隔執行"), ("fixed_time", "固定時間")],
                default="interval",
                help_text="選擇執行方式：間隔執行或固定時間執行",
                max_length=20,
                verbose_name="執行類型",
            ),
        ),
        migrations.AddField(
            model_name="scheduledtask",
            name="fixed_time",
            field=models.TimeField(
                blank=True,
                help_text="每天固定時間執行（僅適用於固定時間執行）",
                null=True,
                verbose_name="固定執行時間",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="interval_minutes",
            field=models.IntegerField(
                default=30,
                help_text="每多少分鐘執行一次（僅適用於間隔執行）",
                verbose_name="間隔分鐘數",
            ),
        ),
    ]
