# Generated by Django 5.1.8 on 2025-08-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0012_scheduledtask_execution_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("sync", "資料同步"),
                            ("cleanup", "資料清理"),
                            ("status_update", "狀態更新"),
                        ],
                        max_length=20,
                        verbose_name="同步類型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "執行中"),
                            ("success", "成功"),
                            ("failed", "失敗"),
                        ],
                        max_length=20,
                        verbose_name="執行狀態",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="執行訊息")),
                ("details", models.JSONField(default=dict, verbose_name="詳細資訊")),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="開始時間"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成時間"
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="執行時間（秒）"
                    ),
                ),
            ],
            options={
                "verbose_name": "訂單同步日誌",
                "verbose_name_plural": "訂單同步日誌",
                "db_table": "system_order_sync_log",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderSyncSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_enabled",
                    models.BooleanField(default=True, verbose_name="啟用自動同步"),
                ),
                (
                    "sync_interval_minutes",
                    models.IntegerField(default=30, verbose_name="同步間隔（分鐘）"),
                ),
                (
                    "last_sync_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次同步時間"
                    ),
                ),
                (
                    "last_sync_status",
                    models.CharField(
                        default="未執行", max_length=20, verbose_name="上次同步狀態"
                    ),
                ),
                (
                    "last_sync_message",
                    models.TextField(blank=True, verbose_name="上次同步訊息"),
                ),
                (
                    "cleanup_enabled",
                    models.BooleanField(default=True, verbose_name="啟用自動清理"),
                ),
                (
                    "cleanup_interval_hours",
                    models.IntegerField(default=24, verbose_name="清理間隔（小時）"),
                ),
                (
                    "cleanup_retention_days",
                    models.IntegerField(default=90, verbose_name="資料保留天數"),
                ),
                (
                    "last_cleanup_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次清理時間"
                    ),
                ),
                (
                    "last_cleanup_count",
                    models.IntegerField(default=0, verbose_name="上次清理數量"),
                ),
                (
                    "status_update_enabled",
                    models.BooleanField(default=True, verbose_name="啟用狀態更新"),
                ),
                (
                    "status_update_interval_minutes",
                    models.IntegerField(
                        default=60, verbose_name="狀態更新間隔（分鐘）"
                    ),
                ),
                (
                    "last_status_update_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次狀態更新時間"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "訂單同步設定",
                "verbose_name_plural": "訂單同步設定",
                "db_table": "system_order_sync_settings",
            },
        ),
    ]
