version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mes-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mes
      MYSQL_USER: mes
      MYSQL_PASSWORD: ctech2015
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/mes_database.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: mes-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: mes-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
