version: '3.7'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ctech2015
      MYSQL_DATABASE: mes
      MYSQL_USER: mes
      MYSQL_PASSWORD: ctech2015
    ports:
      - "3306:3306"
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
