# Generated by Django 5.1.8 on 2025-08-17 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder_erp", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="companyorder",
            unique_together={("company_code", "mkordno", "product_id")},
        ),
    ]
