# Generated by Django 5.1.8 on 2025-09-08 01:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OnsiteReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        help_text="作業員姓名", max_length=100, verbose_name="作業員"
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True,
                        help_text="公司代號",
                        max_length=10,
                        null=True,
                        verbose_name="公司代號",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="公司名稱", max_length=100, verbose_name="公司名稱"
                    ),
                ),
                (
                    "workorder",
                    models.CharField(
                        help_text="工單號碼", max_length=100, verbose_name="工單號碼"
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        help_text="產品編號", max_length=100, verbose_name="產品編號"
                    ),
                ),
                (
                    "planned_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="工單預設生產數量",
                        verbose_name="工單預設生產數量",
                    ),
                ),
                (
                    "process",
                    models.CharField(
                        help_text="工序", max_length=100, verbose_name="工序"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        blank=True,
                        help_text="工序名稱",
                        max_length=100,
                        verbose_name="工序名稱",
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="使用的設備",
                        max_length=100,
                        verbose_name="使用的設備",
                    ),
                ),
                (
                    "work_date",
                    models.DateField(help_text="工作日期", verbose_name="工作日期"),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        help_text="開始日期時間", verbose_name="開始日期時間"
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="結束日期時間",
                        null=True,
                        verbose_name="結束日期時間",
                    ),
                ),
                (
                    "work_minutes",
                    models.IntegerField(
                        default=0, help_text="工作分鐘數", verbose_name="工作分鐘數"
                    ),
                ),
                (
                    "work_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="工作數量",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="工作數量",
                    ),
                ),
                (
                    "defect_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="不良品數量",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="不良品數量",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "開工"),
                            ("paused", "暫停"),
                            ("resumed", "重啟開工"),
                            ("completed", "完工"),
                            ("stopped", "停工"),
                        ],
                        default="started",
                        max_length=20,
                        verbose_name="報工狀態",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("operator", "作業員現場報工"),
                            ("operator_rd", "作業員RD樣品現場報工"),
                            ("smt", "SMT現場報工"),
                            ("smt_rd", "SMT_RD樣品現場報工"),
                        ],
                        max_length=20,
                        verbose_name="報工類型",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="備註", verbose_name="備註"),
                ),
                (
                    "abnormal_notes",
                    models.TextField(
                        blank=True, help_text="異常記錄", verbose_name="異常記錄"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        help_text="建立人員", max_length=100, verbose_name="建立人員"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="建立時間", verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="更新時間", verbose_name="更新時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "現場報工記錄",
                "verbose_name_plural": "現場報工記錄",
                "db_table": "workorder_onsite_report",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company_code"], name="workorder_o_company_3635aa_idx"
                    ),
                    models.Index(
                        fields=["company_name"], name="workorder_o_company_33ef74_idx"
                    ),
                    models.Index(
                        fields=["operator"], name="workorder_o_operato_f03543_idx"
                    ),
                    models.Index(
                        fields=["workorder"], name="workorder_o_workord_a67023_idx"
                    ),
                    models.Index(
                        fields=["product_id"], name="workorder_o_product_cf7f96_idx"
                    ),
                    models.Index(
                        fields=["status"], name="workorder_o_status_d2f91c_idx"
                    ),
                    models.Index(
                        fields=["report_type"], name="workorder_o_report__671c03_idx"
                    ),
                    models.Index(
                        fields=["work_date"], name="workorder_o_work_da_d12dc7_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="workorder_o_created_0b9bfc_idx"
                    ),
                ],
                "unique_together": {
                    (
                        "company_name",
                        "workorder",
                        "product_id",
                        "operation",
                        "operator",
                        "work_date",
                        "start_datetime",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="OnsiteReportConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("operator", "作業員報工"),
                            ("smt", "SMT設備報工"),
                            ("system", "系統配置"),
                        ],
                        help_text="配置類型",
                        max_length=20,
                        verbose_name="配置類型",
                    ),
                ),
                (
                    "config_key",
                    models.CharField(
                        help_text="配置鍵", max_length=100, verbose_name="配置鍵"
                    ),
                ),
                (
                    "config_value",
                    models.TextField(help_text="配置值", verbose_name="配置值"),
                ),
                (
                    "config_description",
                    models.TextField(
                        blank=True, help_text="配置說明", verbose_name="配置說明"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="是否啟用", verbose_name="是否啟用"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        help_text="建立人員", max_length=100, verbose_name="建立人員"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="建立時間", verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="更新時間", verbose_name="更新時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "現場報工配置",
                "verbose_name_plural": "現場報工配置",
                "db_table": "workorder_onsite_report_config",
                "ordering": ["config_type", "config_key"],
                "indexes": [
                    models.Index(
                        fields=["config_type"], name="workorder_o_config__b2f2db_idx"
                    ),
                    models.Index(
                        fields=["config_key"], name="workorder_o_config__bd25a2_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="workorder_o_is_acti_f81988_idx"
                    ),
                ],
                "unique_together": {("config_type", "config_key")},
            },
        ),
        migrations.CreateModel(
            name="OnsiteReportSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        help_text="作業員姓名", max_length=100, verbose_name="作業員"
                    ),
                ),
                (
                    "workorder",
                    models.CharField(
                        help_text="工單號碼", max_length=100, verbose_name="工單號碼"
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        help_text="產品編號", max_length=100, verbose_name="產品編號"
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True,
                        help_text="公司代號",
                        max_length=10,
                        null=True,
                        verbose_name="公司代號",
                    ),
                ),
                (
                    "process",
                    models.CharField(
                        help_text="工序", max_length=100, verbose_name="工序"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        blank=True,
                        help_text="工序名稱",
                        max_length=100,
                        verbose_name="工序名稱",
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="使用的設備",
                        max_length=100,
                        verbose_name="使用的設備",
                    ),
                ),
                (
                    "planned_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="工單預設生產數量",
                        verbose_name="工單預設生產數量",
                    ),
                ),
                (
                    "total_work_minutes",
                    models.IntegerField(
                        default=0, help_text="總工作分鐘數", verbose_name="總工作分鐘數"
                    ),
                ),
                (
                    "total_quantity_produced",
                    models.IntegerField(
                        default=0, help_text="總生產數量", verbose_name="總生產數量"
                    ),
                ),
                (
                    "total_defect_quantity",
                    models.IntegerField(
                        default=0, help_text="總不良品數量", verbose_name="總不良品數量"
                    ),
                ),
                (
                    "session_count",
                    models.IntegerField(
                        default=0, help_text="工作時段數", verbose_name="工作時段數"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="是否活躍", verbose_name="是否活躍"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        help_text="建立人員", max_length=100, verbose_name="建立人員"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="建立時間", verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="更新時間", verbose_name="更新時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "現場報工工作時段",
                "verbose_name_plural": "現場報工工作時段",
                "db_table": "workorder_onsite_report_session",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["operator"], name="workorder_o_operato_94327b_idx"
                    ),
                    models.Index(
                        fields=["workorder"], name="workorder_o_workord_5df36f_idx"
                    ),
                    models.Index(
                        fields=["product_id"], name="workorder_o_product_524c55_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="workorder_o_is_acti_42375a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OnsiteReportHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("start", "開始報工"),
                            ("update", "更新數量"),
                            ("pause", "暫停"),
                            ("resume", "恢復"),
                            ("complete", "完成"),
                            ("abnormal", "異常"),
                            ("normal", "恢復正常"),
                        ],
                        help_text="變更類型",
                        max_length=20,
                        verbose_name="變更類型",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        help_text="原狀態",
                        max_length=20,
                        verbose_name="原狀態",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        help_text="新狀態",
                        max_length=20,
                        verbose_name="新狀態",
                    ),
                ),
                (
                    "old_quantity",
                    models.IntegerField(
                        default=0, help_text="原數量", verbose_name="原數量"
                    ),
                ),
                (
                    "new_quantity",
                    models.IntegerField(
                        default=0, help_text="新數量", verbose_name="新數量"
                    ),
                ),
                (
                    "change_notes",
                    models.TextField(
                        blank=True, help_text="變更說明", verbose_name="變更說明"
                    ),
                ),
                (
                    "changed_by",
                    models.CharField(
                        help_text="變更人員", max_length=100, verbose_name="變更人員"
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="變更時間", verbose_name="變更時間"
                    ),
                ),
                (
                    "onsite_report",
                    models.ForeignKey(
                        help_text="現場報工記錄",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="onsite_reporting.onsitereport",
                        verbose_name="現場報工記錄",
                    ),
                ),
            ],
            options={
                "verbose_name": "現場報工歷史記錄",
                "verbose_name_plural": "現場報工歷史記錄",
                "db_table": "workorder_onsite_report_history",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["onsite_report"], name="workorder_o_onsite__d1c188_idx"
                    ),
                    models.Index(
                        fields=["change_type"], name="workorder_o_change__6b4c07_idx"
                    ),
                    models.Index(
                        fields=["changed_at"], name="workorder_o_changed_c2ebc6_idx"
                    ),
                ],
            },
        ),
    ]
