# Generated by Django 5.1.8 on 2025-08-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onsite_reporting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onsitereport",
            name="start_time",
            field=models.TimeField(
                blank=True, help_text="開始時間", null=True, verbose_name="開始時間"
            ),
        ),
    ]
