# Generated by Django 5.2.6 on 2025-09-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onsite_reporting", "0002_auto_20250910_1048"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onsitereporthistory",
            name="onsite_report_name",
            field=models.CharField(
                help_text="現場報工記錄名稱",
                max_length=200,
                verbose_name="現場報工記錄名稱",
            ),
        ),
    ]
