# Generated by Django 5.1.8 on 2025-08-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onsite_reporting", "0002_alter_onsitereport_start_time"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="onsitereport",
            name="workorder_o_work_da_d12dc7_idx",
        ),
        migrations.RemoveField(
            model_name="onsitereport",
            name="work_date",
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="status",
            field=models.CharField(
                choices=[
                    ("started", "開工"),
                    ("paused", "暫停"),
                    ("resumed", "重啟開工"),
                    ("completed", "完工"),
                    ("stopped", "完全停工"),
                ],
                default="started",
                help_text="報工狀態",
                max_length=20,
                verbose_name="報工狀態",
            ),
        ),
    ]
