# Generated by Django 5.1.8 on 2025-08-15 07:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "onsite_reporting",
            "0003_remove_onsitereport_workorder_o_work_da_d12dc7_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OnsiteReportPauseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pause_start_datetime",
                    models.DateTimeField(
                        help_text="暫停開始時間", verbose_name="暫停開始時間"
                    ),
                ),
                (
                    "pause_end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="暫停結束時間",
                        null=True,
                        verbose_name="暫停結束時間",
                    ),
                ),
                (
                    "pause_minutes",
                    models.IntegerField(
                        default=0, help_text="暫停分鐘數", verbose_name="暫停分鐘數"
                    ),
                ),
                (
                    "pause_reason",
                    models.CharField(
                        blank=True,
                        help_text="暫停原因",
                        max_length=200,
                        verbose_name="暫停原因",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        help_text="操作人員", max_length=100, verbose_name="操作人員"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="建立時間", verbose_name="建立時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "現場報工暫停記錄",
                "verbose_name_plural": "現場報工暫停記錄",
                "db_table": "workorder_onsite_report_pause",
                "ordering": ["-pause_start_datetime"],
            },
        ),
        migrations.RemoveField(
            model_name="onsitereport",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="onsitereport",
            name="start_time",
        ),
        migrations.AddField(
            model_name="onsitereport",
            name="end_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="結束日期時間",
                null=True,
                verbose_name="結束日期時間",
            ),
        ),
        migrations.AddField(
            model_name="onsitereport",
            name="start_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="開始日期時間",
                null=True,
                verbose_name="開始日期時間",
            ),
        ),
        migrations.AddField(
            model_name="onsitereport",
            name="total_pause_minutes",
            field=models.IntegerField(
                default=0, help_text="總暫停分鐘數", verbose_name="總暫停分鐘數"
            ),
        ),
        migrations.AddField(
            model_name="onsitereport",
            name="total_work_minutes",
            field=models.IntegerField(
                default=0, help_text="總工作分鐘數", verbose_name="總工作分鐘數"
            ),
        ),
        migrations.AddField(
            model_name="onsitereport",
            name="work_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="報工日期",
                verbose_name="報工日期",
            ),
        ),
        migrations.AddIndex(
            model_name="onsitereport",
            index=models.Index(
                fields=["work_date"], name="workorder_o_work_da_d12dc7_idx"
            ),
        ),
        migrations.AddField(
            model_name="onsitereportpauserecord",
            name="onsite_report",
            field=models.ForeignKey(
                help_text="現場報工記錄",
                on_delete=django.db.models.deletion.CASCADE,
                to="onsite_reporting.onsitereport",
                verbose_name="現場報工記錄",
            ),
        ),
        migrations.AddIndex(
            model_name="onsitereportpauserecord",
            index=models.Index(
                fields=["onsite_report"], name="workorder_o_onsite__b33a75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onsitereportpauserecord",
            index=models.Index(
                fields=["pause_start_datetime"], name="workorder_o_pause_s_41bf55_idx"
            ),
        ),
    ]
