# Generated by Django 5.1.8 on 2025-08-15 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "onsite_reporting",
            "0004_onsitereportpauserecord_remove_onsitereport_end_time_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OnsiteReportSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        help_text="作業員姓名", max_length=100, verbose_name="作業員"
                    ),
                ),
                (
                    "workorder",
                    models.CharField(
                        help_text="工單號碼", max_length=100, verbose_name="工單號碼"
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        help_text="產品編號", max_length=100, verbose_name="產品編號"
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True,
                        help_text="公司代號",
                        max_length=10,
                        null=True,
                        verbose_name="公司代號",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="公司名稱", max_length=100, verbose_name="公司名稱"
                    ),
                ),
                (
                    "process",
                    models.CharField(
                        help_text="工序", max_length=100, verbose_name="工序"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        blank=True,
                        help_text="工序名稱",
                        max_length=100,
                        verbose_name="工序名稱",
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="使用的設備",
                        max_length=100,
                        verbose_name="使用的設備",
                    ),
                ),
                (
                    "planned_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="工單預設生產數量",
                        verbose_name="工單預設生產數量",
                    ),
                ),
                (
                    "total_work_minutes",
                    models.IntegerField(
                        default=0, help_text="總工作分鐘數", verbose_name="總工作分鐘數"
                    ),
                ),
                (
                    "total_quantity_produced",
                    models.IntegerField(
                        default=0, help_text="總生產數量", verbose_name="總生產數量"
                    ),
                ),
                (
                    "total_defect_quantity",
                    models.IntegerField(
                        default=0, help_text="總不良品數量", verbose_name="總不良品數量"
                    ),
                ),
                (
                    "session_count",
                    models.IntegerField(
                        default=0, help_text="工作時段數", verbose_name="工作時段數"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="是否活躍", verbose_name="是否活躍"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        help_text="建立人員", max_length=100, verbose_name="建立人員"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="建立時間", verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="更新時間", verbose_name="更新時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "現場報工工作時段",
                "verbose_name_plural": "現場報工工作時段",
                "db_table": "workorder_onsite_report_session",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="onsitereportpauserecord",
            name="onsite_report",
        ),
        migrations.RemoveIndex(
            model_name="onsitereport",
            name="workorder_o_is_acti_dc3e06_idx",
        ),
        migrations.RemoveField(
            model_name="onsitereport",
            name="abnormal_end_time",
        ),
        migrations.RemoveField(
            model_name="onsitereport",
            name="abnormal_start_time",
        ),
        migrations.RemoveField(
            model_name="onsitereport",
            name="current_quantity",
        ),
        migrations.RemoveField(
            model_name="onsitereport",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="onsitereport",
            name="last_update_time",
        ),
        migrations.RemoveField(
            model_name="onsitereport",
            name="total_pause_minutes",
        ),
        migrations.RemoveField(
            model_name="onsitereport",
            name="total_work_minutes",
        ),
        migrations.AddField(
            model_name="onsitereport",
            name="work_minutes",
            field=models.IntegerField(default=0, verbose_name="工作分鐘數"),
        ),
        migrations.AddField(
            model_name="onsitereport",
            name="work_quantity",
            field=models.IntegerField(default=0, verbose_name="工作數量"),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="abnormal_notes",
            field=models.TextField(blank=True, verbose_name="異常記錄"),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="company_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="公司代號"
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="company_name",
            field=models.CharField(max_length=100, verbose_name="公司名稱"),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="created_by",
            field=models.CharField(max_length=100, verbose_name="建立人員"),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="defect_quantity",
            field=models.IntegerField(default=0, verbose_name="不良品數量"),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="end_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="結束日期時間"
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="equipment",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="使用的設備"
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="operation",
            field=models.CharField(blank=True, max_length=100, verbose_name="工序名稱"),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="operator",
            field=models.CharField(max_length=100, verbose_name="作業員"),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="planned_quantity",
            field=models.IntegerField(default=0, verbose_name="工單預設生產數量"),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="process",
            field=models.CharField(max_length=100, verbose_name="工序"),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="product_id",
            field=models.CharField(max_length=100, verbose_name="產品編號"),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="remarks",
            field=models.TextField(blank=True, verbose_name="備註"),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("operator", "作業員現場報工"),
                    ("operator_rd", "作業員RD樣品現場報工"),
                    ("smt", "SMT現場報工"),
                    ("smt_rd", "SMT_RD樣品現場報工"),
                ],
                max_length=20,
                verbose_name="報工類型",
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="start_datetime",
            field=models.DateTimeField(verbose_name="開始日期時間"),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="status",
            field=models.CharField(
                choices=[
                    ("started", "開工"),
                    ("paused", "暫停"),
                    ("resumed", "重啟開工"),
                    ("completed", "完工"),
                    ("stopped", "停工"),
                ],
                default="started",
                max_length=20,
                verbose_name="報工狀態",
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="work_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="報工日期"
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="workorder",
            field=models.CharField(max_length=100, verbose_name="工單號碼"),
        ),
        migrations.AddIndex(
            model_name="onsitereportsession",
            index=models.Index(
                fields=["operator"], name="workorder_o_operato_94327b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onsitereportsession",
            index=models.Index(
                fields=["workorder"], name="workorder_o_workord_5df36f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onsitereportsession",
            index=models.Index(
                fields=["product_id"], name="workorder_o_product_524c55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onsitereportsession",
            index=models.Index(
                fields=["is_active"], name="workorder_o_is_acti_42375a_idx"
            ),
        ),
        migrations.DeleteModel(
            name="OnsiteReportPauseRecord",
        ),
    ]
