# Generated by Django 5.1.8 on 2025-08-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onsite_reporting", "0006_rename_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="onsitereport",
            name="workorder_o_workord_a67023_idx",
        ),
        migrations.RemoveIndex(
            model_name="onsitereport",
            name="workorder_o_product_cf7f96_idx",
        ),
        migrations.RemoveIndex(
            model_name="onsitereportsession",
            name="workorder_o_workord_5df36f_idx",
        ),
        migrations.RemoveIndex(
            model_name="onsitereportsession",
            name="workorder_o_product_524c55_idx",
        ),
        migrations.RenameField(
            model_name="onsitereportsession",
            old_name="workorder",
            new_name="order_number",
        ),
        migrations.RenameField(
            model_name="onsitereportsession",
            old_name="product_id",
            new_name="product_code",
        ),
        migrations.AlterUniqueTogether(
            name="onsitereport",
            unique_together={("company_code", "order_number", "product_code")},
        ),
        migrations.RemoveField(
            model_name="onsitereportsession",
            name="company_name",
        ),
        migrations.AddIndex(
            model_name="onsitereport",
            index=models.Index(
                fields=["order_number"], name="workorder_o_order_n_75e344_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onsitereport",
            index=models.Index(
                fields=["product_code"], name="workorder_o_product_b4de02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onsitereportsession",
            index=models.Index(
                fields=["order_number"], name="workorder_o_order_n_06ee9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onsitereportsession",
            index=models.Index(
                fields=["product_code"], name="workorder_o_product_54598a_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="onsitereport",
            name="company_name",
        ),
    ]
