# Generated by Django 5.1.8 on 2025-08-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "onsite_reporting",
            "0007_remove_onsitereport_workorder_o_workord_a67023_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="onsitereport",
            unique_together={
                (
                    "company_code",
                    "order_number",
                    "product_code",
                    "operation",
                    "operator",
                    "work_date",
                    "start_datetime",
                )
            },
        ),
    ]
