# Generated by Django 5.1.8 on 2025-08-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onsite_reporting", "0008_alter_onsitereport_unique_together"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="onsitereport",
            name="workorder_o_company_3635aa_idx",
        ),
        migrations.RemoveIndex(
            model_name="onsitereport",
            name="workorder_o_order_n_75e344_idx",
        ),
        migrations.RemoveIndex(
            model_name="onsitereport",
            name="workorder_o_product_b4de02_idx",
        ),
        migrations.RemoveIndex(
            model_name="onsitereportsession",
            name="workorder_o_order_n_06ee9e_idx",
        ),
        migrations.RemoveIndex(
            model_name="onsitereportsession",
            name="workorder_o_product_54598a_idx",
        ),
        migrations.RenameField(
            model_name="onsitereport",
            old_name="product_code",
            new_name="product_id",
        ),
        migrations.RenameField(
            model_name="onsitereport",
            old_name="order_number",
            new_name="workorder",
        ),
        migrations.RenameField(
            model_name="onsitereportsession",
            old_name="product_code",
            new_name="product_id",
        ),
        migrations.RenameField(
            model_name="onsitereportsession",
            old_name="order_number",
            new_name="workorder",
        ),
        migrations.AlterUniqueTogether(
            name="onsitereport",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="onsitereport",
            name="company_name",
            field=models.CharField(
                default="",
                help_text="公司名稱",
                max_length=100,
                verbose_name="公司名稱",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="onsitereport",
            unique_together={
                (
                    "company_name",
                    "workorder",
                    "product_id",
                    "operation",
                    "operator",
                    "work_date",
                    "start_datetime",
                )
            },
        ),
        migrations.AddIndex(
            model_name="onsitereport",
            index=models.Index(
                fields=["company_name"], name="workorder_o_company_33ef74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onsitereport",
            index=models.Index(
                fields=["workorder"], name="workorder_o_workord_a67023_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onsitereport",
            index=models.Index(
                fields=["product_id"], name="workorder_o_product_cf7f96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onsitereportsession",
            index=models.Index(
                fields=["workorder"], name="workorder_o_workord_5df36f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onsitereportsession",
            index=models.Index(
                fields=["product_id"], name="workorder_o_product_524c55_idx"
            ),
        ),
    ]
