# Generated by Django 5.1.8 on 2025-08-18 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "onsite_reporting",
            "0009_remove_onsitereport_workorder_o_company_3635aa_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="onsitereport",
            name="abnormal_notes",
            field=models.TextField(
                blank=True, help_text="異常記錄", verbose_name="異常記錄"
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="company_code",
            field=models.CharField(
                blank=True,
                help_text="公司代號",
                max_length=10,
                null=True,
                verbose_name="公司代號",
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="company_name",
            field=models.CharField(
                help_text="公司名稱", max_length=100, verbose_name="公司名稱"
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="建立時間", verbose_name="建立時間"
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="created_by",
            field=models.CharField(
                help_text="建立人員", max_length=100, verbose_name="建立人員"
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="defect_quantity",
            field=models.IntegerField(
                default=0,
                help_text="不良品數量",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="不良品數量",
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="end_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="結束日期時間",
                null=True,
                verbose_name="結束日期時間",
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="equipment",
            field=models.CharField(
                blank=True,
                default="",
                help_text="使用的設備",
                max_length=100,
                verbose_name="使用的設備",
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="operation",
            field=models.CharField(
                blank=True,
                help_text="工序名稱",
                max_length=100,
                verbose_name="工序名稱",
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="operator",
            field=models.CharField(
                help_text="作業員姓名", max_length=100, verbose_name="作業員"
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="planned_quantity",
            field=models.IntegerField(
                default=0, help_text="工單預設生產數量", verbose_name="工單預設生產數量"
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="process",
            field=models.CharField(
                help_text="工序", max_length=100, verbose_name="工序"
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="product_id",
            field=models.CharField(
                help_text="產品編號", max_length=100, verbose_name="產品編號"
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="remarks",
            field=models.TextField(blank=True, help_text="備註", verbose_name="備註"),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="start_datetime",
            field=models.DateTimeField(
                help_text="開始日期時間", verbose_name="開始日期時間"
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="更新時間", verbose_name="更新時間"
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="work_date",
            field=models.DateField(help_text="工作日期", verbose_name="工作日期"),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="work_minutes",
            field=models.IntegerField(
                default=0, help_text="工作分鐘數", verbose_name="工作分鐘數"
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="work_quantity",
            field=models.IntegerField(
                default=0,
                help_text="工作數量",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="工作數量",
            ),
        ),
        migrations.AlterField(
            model_name="onsitereport",
            name="workorder",
            field=models.CharField(
                help_text="工單號碼", max_length=100, verbose_name="工單號碼"
            ),
        ),
        migrations.AddIndex(
            model_name="onsitereport",
            index=models.Index(
                fields=["company_code"], name="workorder_o_company_3635aa_idx"
            ),
        ),
    ]
