# Generated by Django 5.2.6 on 2025-09-22 03:10

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CapacityHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity_id", models.CharField(max_length=50, verbose_name="產能ID")),
                (
                    "capacity_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="產能名稱"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "建立"),
                            ("updated", "更新"),
                            ("deactivated", "停用"),
                            ("reactivated", "重新啟用"),
                        ],
                        max_length=20,
                        verbose_name="變更類型",
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(blank=True, null=True, verbose_name="舊值"),
                ),
                (
                    "new_values",
                    models.JSONField(blank=True, null=True, verbose_name="新值"),
                ),
                (
                    "change_reason",
                    models.TextField(blank=True, verbose_name="變更原因"),
                ),
                ("changed_by", models.CharField(max_length=100, verbose_name="變更者")),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="變更時間"),
                ),
            ],
            options={
                "verbose_name": "產能歷史記錄",
                "verbose_name_plural": "產能歷史記錄",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="作業員名稱"
                    ),
                ),
                (
                    "production_line_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="所屬產線ID"
                    ),
                ),
                (
                    "production_line_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="所屬產線名稱",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="更新時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "作業員",
                "verbose_name_plural": "作業員",
                "permissions": [
                    ("can_view_operator", "可以查看作業員"),
                    ("can_add_operator", "可以添加作業員"),
                    ("can_edit_operator", "可以編輯作業員"),
                    ("can_delete_operator", "可以刪除作業員"),
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="OperatorSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator_id",
                    models.CharField(max_length=50, verbose_name="作業員ID"),
                ),
                (
                    "operator_name",
                    models.CharField(max_length=100, verbose_name="作業員名稱"),
                ),
                (
                    "process_name_id",
                    models.CharField(max_length=50, verbose_name="工序名稱ID"),
                ),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="優先順序",
                    ),
                ),
            ],
            options={
                "verbose_name": "作業員技能",
                "verbose_name_plural": "作業員技能",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ProcessName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="工序名稱"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
            ],
            options={
                "verbose_name": "工序名稱",
                "verbose_name_plural": "工序名稱",
                "permissions": [
                    ("can_view_process_name", "可以查看工序名稱"),
                    ("can_add_process_name", "可以添加工序名稱"),
                    ("can_edit_process_name", "可以編輯工序名稱"),
                    ("can_delete_process_name", "可以刪除工序名稱"),
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ProcessOperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        help_text="用戶名稱（非外鍵關係，純文字欄位）",
                        max_length=100,
                        verbose_name="用戶",
                    ),
                ),
                ("action", models.TextField(verbose_name="操作")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="時間戳"
                    ),
                ),
            ],
            options={
                "verbose_name": "工序操作日誌",
                "verbose_name_plural": "工序操作日誌",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CapacityTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_name",
                    models.CharField(max_length=100, verbose_name="模板名稱"),
                ),
                (
                    "process_name",
                    models.CharField(max_length=50, verbose_name="工序名稱"),
                ),
                (
                    "equipment_type",
                    models.CharField(max_length=20, verbose_name="設備類型"),
                ),
                (
                    "operator_level",
                    models.CharField(max_length=20, verbose_name="作業員等級"),
                ),
                (
                    "standard_capacity_per_hour",
                    models.PositiveIntegerField(verbose_name="標準每小時產能"),
                ),
                (
                    "setup_time_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="換線準備時間(分鐘)"
                    ),
                ),
                (
                    "cycle_time_seconds",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="標準週期時間(秒)",
                    ),
                ),
                (
                    "efficiency_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=3,
                        verbose_name="效率因子",
                    ),
                ),
                (
                    "applicable_products",
                    models.TextField(
                        blank=True,
                        help_text="產品編號前綴或關鍵字，用逗號分隔",
                        verbose_name="適用產品類型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否啟用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "產能模板",
                "verbose_name_plural": "產能模板",
                "unique_together": {
                    (
                        "template_name",
                        "process_name",
                        "equipment_type",
                        "operator_level",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="ProcessEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_name_id",
                    models.CharField(max_length=50, verbose_name="工序名稱ID"),
                ),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                ("equipment_id", models.IntegerField(verbose_name="設備 ID")),
            ],
            options={
                "verbose_name": "工序設備",
                "verbose_name_plural": "工序設備",
                "default_permissions": (),
                "unique_together": {("process_name", "equipment_id")},
            },
        ),
        migrations.CreateModel(
            name="ProductProcessRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(max_length=100, verbose_name="產品編號"),
                ),
                (
                    "process_name_id",
                    models.CharField(max_length=50, verbose_name="工序名稱ID"),
                ),
                (
                    "process_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="工序名稱"
                    ),
                ),
                (
                    "step_order",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="工序順序",
                    ),
                ),
                (
                    "usable_equipment_ids",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="指定可用設備 ID 列表"
                    ),
                ),
                (
                    "dependent_semi_product",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="依賴半成品"
                    ),
                ),
            ],
            options={
                "verbose_name": "產品工序路線",
                "verbose_name_plural": "產品工序路線",
                "db_table": "process_productroute",
                "permissions": [
                    ("can_view_product_route", "可以查看產品工序路線"),
                    ("can_add_product_route", "可以添加產品工序路線"),
                    ("can_edit_product_route", "可以編輯產品工序路線"),
                    ("can_delete_product_route", "可以刪除產品工序路線"),
                ],
                "default_permissions": (),
                "unique_together": {("product_id", "step_order")},
            },
        ),
        migrations.CreateModel(
            name="ProductProcessStandardCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        default="", max_length=50, verbose_name="產品編號"
                    ),
                ),
                (
                    "process_name",
                    models.CharField(
                        default="", max_length=50, verbose_name="工序名稱"
                    ),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("standard", "標準設備"),
                            ("smt", "SMT設備"),
                            ("dip", "DIP設備"),
                            ("test", "測試設備"),
                            ("packaging", "包裝設備"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="設備類型",
                    ),
                ),
                (
                    "operator_level",
                    models.CharField(
                        choices=[
                            ("beginner", "新手"),
                            ("standard", "標準"),
                            ("expert", "熟手"),
                            ("master", "大師"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="作業員等級",
                    ),
                ),
                (
                    "standard_capacity_per_hour",
                    models.PositiveIntegerField(verbose_name="標準每小時產能"),
                ),
                (
                    "min_capacity_per_hour",
                    models.PositiveIntegerField(verbose_name="最低每小時產能"),
                ),
                (
                    "max_capacity_per_hour",
                    models.PositiveIntegerField(verbose_name="最高每小時產能"),
                ),
                (
                    "setup_time_minutes",
                    models.PositiveIntegerField(verbose_name="換線準備時間(分鐘)"),
                ),
                (
                    "teardown_time_minutes",
                    models.PositiveIntegerField(verbose_name="收線時間(分鐘)"),
                ),
                (
                    "cycle_time_seconds",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="標準週期時間(秒)"
                    ),
                ),
                (
                    "optimal_batch_size",
                    models.PositiveIntegerField(verbose_name="最佳批量大小"),
                ),
                (
                    "min_batch_size",
                    models.PositiveIntegerField(verbose_name="最小批量大小"),
                ),
                (
                    "max_batch_size",
                    models.PositiveIntegerField(verbose_name="最大批量大小"),
                ),
                (
                    "efficiency_factor",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="效率因子"
                    ),
                ),
                (
                    "learning_curve_factor",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="學習曲線因子"
                    ),
                ),
                (
                    "expected_defect_rate",
                    models.DecimalField(
                        decimal_places=4, max_digits=5, verbose_name="預期不良率"
                    ),
                ),
                (
                    "rework_time_factor",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="重工時間因子"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="版本號"),
                ),
                (
                    "effective_date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="生效日期"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="失效日期"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否啟用"),
                ),
                (
                    "created_by",
                    models.CharField(blank=True, max_length=100, verbose_name="建立者"),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=100, verbose_name="核准者"),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="核准日期"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備註")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="更新時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "產品工序標準產能",
                "verbose_name_plural": "產品工序標準產能",
                "ordering": [
                    "product_code",
                    "process_name",
                    "equipment_type",
                    "operator_level",
                    "-version",
                ],
                "unique_together": {
                    (
                        "product_code",
                        "process_name",
                        "equipment_type",
                        "operator_level",
                        "version",
                    )
                },
            },
        ),
    ]
