# Generated by Django 5.1.8 on 2025-06-22 01:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="作業員名稱"
                    ),
                ),
            ],
            options={
                "verbose_name": "作業員",
                "verbose_name_plural": "作業員",
                "permissions": [
                    ("can_view_operator", "可以查看作業員"),
                    ("can_add_operator", "可以添加作業員"),
                    ("can_edit_operator", "可以編輯作業員"),
                    ("can_delete_operator", "可以刪除作業員"),
                ],
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="ProcessName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="工序名稱"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
            ],
            options={
                "verbose_name": "工序名稱",
                "verbose_name_plural": "工序名稱",
                "permissions": [
                    ("can_view_process_name", "可以查看工序名稱"),
                    ("can_add_process_name", "可以添加工序名稱"),
                    ("can_edit_process_name", "可以編輯工序名稱"),
                    ("can_delete_process_name", "可以刪除工序名稱"),
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ProcessOperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100, verbose_name="用戶")),
                ("action", models.TextField(verbose_name="操作")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="時間戳"
                    ),
                ),
            ],
            options={
                "verbose_name": "工序操作日誌",
                "verbose_name_plural": "工序操作日誌",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="OperatorSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="優先順序",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="process.operator",
                        verbose_name="作業員",
                    ),
                ),
                (
                    "process_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process.processname",
                        verbose_name="工序名稱",
                    ),
                ),
            ],
            options={
                "verbose_name": "作業員技能",
                "verbose_name_plural": "作業員技能",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ProcessEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_id", models.IntegerField(verbose_name="設備 ID")),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[("normal", "普通設備"), ("smt", "SMT 設備")],
                        max_length=10,
                        verbose_name="設備類型",
                    ),
                ),
                (
                    "process_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipments",
                        to="process.processname",
                        verbose_name="工序名稱",
                    ),
                ),
            ],
            options={
                "verbose_name": "工序設備",
                "verbose_name_plural": "工序設備",
                "default_permissions": (),
                "unique_together": {("process_name", "equipment_id", "equipment_type")},
            },
        ),
        migrations.CreateModel(
            name="ProductProcessRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(max_length=100, verbose_name="產品編號"),
                ),
                (
                    "step_order",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="工序順序",
                    ),
                ),
                (
                    "capacity_per_hour",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="每小時產能",
                    ),
                ),
                (
                    "usable_equipment_ids",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="指定可用設備 ID 列表"
                    ),
                ),
                (
                    "dependent_semi_product",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="依賴半成品"
                    ),
                ),
                (
                    "process_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process.processname",
                        verbose_name="工序名稱",
                    ),
                ),
            ],
            options={
                "verbose_name": "產品工序路線",
                "verbose_name_plural": "產品工序路線",
                "db_table": "process_productroute",
                "permissions": [
                    ("can_view_product_route", "可以查看產品工序路線"),
                    ("can_add_product_route", "可以添加產品工序路線"),
                    ("can_edit_product_route", "可以編輯產品工序路線"),
                    ("can_delete_product_route", "可以刪除產品工序路線"),
                ],
                "default_permissions": "",
                "unique_together": {("product_id", "step_order")},
            },
        ),
    ]
