# Generated by Django 5.1.8 on 2025-06-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="processequipment",
            unique_together={("process_name", "equipment_id")},
        ),
        migrations.RemoveField(
            model_name="processequipment",
            name="equipment_type",
        ),
    ]
