# Generated by Django 5.1.8 on 2025-06-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0002_alter_processequipment_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductProcessStandardCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(max_length=50, verbose_name="產品編號"),
                ),
                (
                    "process_name",
                    models.CharField(max_length=50, verbose_name="工序名稱"),
                ),
                (
                    "standard_capacity",
                    models.PositiveIntegerField(verbose_name="標準產能（每人每小時）"),
                ),
            ],
            options={
                "verbose_name": "產品工序標準產能",
                "verbose_name_plural": "產品工序標準產能",
                "unique_together": {("product_code", "process_name")},
            },
        ),
    ]
