# Generated by Django 5.1.8 on 2025-07-02 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0003_productprocessstandardcapacity"),
    ]

    operations = [
        # 先新增所有新欄位
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="equipment_type",
            field=models.CharField(
                choices=[
                    ("standard", "標準設備"),
                    ("smt", "SMT設備"),
                    ("dip", "DIP設備"),
                    ("test", "測試設備"),
                    ("packaging", "包裝設備"),
                ],
                default="standard",
                max_length=20,
                verbose_name="設備類型",
            ),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="operator_level",
            field=models.CharField(
                choices=[
                    ("beginner", "新手"),
                    ("standard", "標準"),
                    ("expert", "熟手"),
                    ("master", "大師"),
                ],
                default="standard",
                max_length=20,
                verbose_name="作業員等級",
            ),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="版本號"),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="核准日期"),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="approved_by",
            field=models.CharField(blank=True, max_length=100, verbose_name="核准者"),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="建立時間"
            ),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="created_by",
            field=models.CharField(blank=True, max_length=100, verbose_name="建立者"),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="cycle_time_seconds",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=6,
                verbose_name="標準週期時間(秒)",
            ),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="effective_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="生效日期"
            ),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="efficiency_factor",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="1.00=100%效率，0.80=80%效率",
                max_digits=3,
                verbose_name="效率因子",
            ),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="expected_defect_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                help_text="0.0000=0%，0.0100=1%",
                max_digits=5,
                verbose_name="預期不良率",
            ),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="expiry_date",
            field=models.DateField(blank=True, null=True, verbose_name="失效日期"),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否啟用"),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="learning_curve_factor",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="考慮作業員熟練度對產能的影響",
                max_digits=3,
                verbose_name="學習曲線因子",
            ),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="max_batch_size",
            field=models.PositiveIntegerField(
                default=1000, verbose_name="最大批量大小"
            ),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="max_capacity_per_hour",
            field=models.PositiveIntegerField(default=0, verbose_name="最高每小時產能"),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="min_batch_size",
            field=models.PositiveIntegerField(default=1, verbose_name="最小批量大小"),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="min_capacity_per_hour",
            field=models.PositiveIntegerField(default=0, verbose_name="最低每小時產能"),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="notes",
            field=models.TextField(blank=True, verbose_name="備註"),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="optimal_batch_size",
            field=models.PositiveIntegerField(default=1, verbose_name="最佳批量大小"),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="rework_time_factor",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="重工所需時間倍數",
                max_digits=3,
                verbose_name="重工時間因子",
            ),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="setup_time_minutes",
            field=models.PositiveIntegerField(
                default=0, verbose_name="換線準備時間(分鐘)"
            ),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="standard_capacity_per_hour",
            field=models.PositiveIntegerField(default=0, verbose_name="標準每小時產能"),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="teardown_time_minutes",
            field=models.PositiveIntegerField(default=0, verbose_name="收線時間(分鐘)"),
        ),
        migrations.AddField(
            model_name="productprocessstandardcapacity",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="更新時間"
            ),
        ),
        # 然後修改欄位屬性
        migrations.AlterField(
            model_name="productprocessstandardcapacity",
            name="product_code",
            field=models.CharField(default="", max_length=50, verbose_name="產品編號"),
        ),
        migrations.AlterField(
            model_name="productprocessstandardcapacity",
            name="process_name",
            field=models.CharField(default="", max_length=50, verbose_name="工序名稱"),
        ),
        # 最後修改 Meta 選項和 unique_together
        migrations.AlterModelOptions(
            name="productprocessstandardcapacity",
            options={
                "ordering": [
                    "product_code",
                    "process_name",
                    "equipment_type",
                    "operator_level",
                    "-version",
                ],
                "verbose_name": "產品工序標準產能",
                "verbose_name_plural": "產品工序標準產能",
            },
        ),
        migrations.AlterUniqueTogether(
            name="productprocessstandardcapacity",
            unique_together={
                (
                    "product_code",
                    "process_name",
                    "equipment_type",
                    "operator_level",
                    "version",
                )
            },
        ),
        # 移除舊欄位
        migrations.RemoveField(
            model_name="productprocessstandardcapacity",
            name="standard_capacity",
        ),
        # 新增新模型
        migrations.CreateModel(
            name="CapacityHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "建立"),
                            ("updated", "更新"),
                            ("deactivated", "停用"),
                            ("reactivated", "重新啟用"),
                        ],
                        max_length=20,
                        verbose_name="變更類型",
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, null=True, verbose_name="舊值"
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, null=True, verbose_name="新值"
                    ),
                ),
                (
                    "change_reason",
                    models.TextField(blank=True, verbose_name="變更原因"),
                ),
                (
                    "changed_by",
                    models.CharField(max_length=100, verbose_name="變更者"),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="變更時間"
                    ),
                ),
                (
                    "capacity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="process.productprocessstandardcapacity",
                        verbose_name="產能設定",
                    ),
                ),
            ],
            options={
                "verbose_name": "產能歷史記錄",
                "verbose_name_plural": "產能歷史記錄",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="CapacityTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_name",
                    models.CharField(max_length=100, verbose_name="模板名稱"),
                ),
                (
                    "process_name",
                    models.CharField(max_length=50, verbose_name="工序名稱"),
                ),
                (
                    "equipment_type",
                    models.CharField(max_length=20, verbose_name="設備類型"),
                ),
                (
                    "operator_level",
                    models.CharField(max_length=20, verbose_name="作業員等級"),
                ),
                (
                    "standard_capacity_per_hour",
                    models.PositiveIntegerField(verbose_name="標準每小時產能"),
                ),
                (
                    "setup_time_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="換線準備時間(分鐘)"
                    ),
                ),
                (
                    "cycle_time_seconds",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="標準週期時間(秒)",
                    ),
                ),
                (
                    "efficiency_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=3,
                        verbose_name="效率因子",
                    ),
                ),
                (
                    "applicable_products",
                    models.TextField(
                        blank=True,
                        help_text="產品編號前綴或關鍵字，用逗號分隔",
                        verbose_name="適用產品類型",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="描述"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否啟用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="建立時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "產能模板",
                "verbose_name_plural": "產能模板",
                "unique_together": {
                    (
                        "template_name",
                        "process_name",
                        "equipment_type",
                        "operator_level",
                    )
                },
            },
        ),
    ]
