# Generated by Django 5.1.8 on 2025-07-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0005_alter_capacityhistory_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="建立時間"
            ),
        ),
        migrations.AddField(
            model_name="operator",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="更新時間"
            ),
        ),
    ]
