# Generated by Django 5.1.8 on 2025-07-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0006_operator_created_at_operator_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operator",
            options={
                "default_permissions": (),
                "permissions": [
                    ("can_view_operator", "可以查看作業員"),
                    ("can_add_operator", "可以添加作業員"),
                    ("can_edit_operator", "可以編輯作業員"),
                    ("can_delete_operator", "可以刪除作業員"),
                ],
                "verbose_name": "作業員",
                "verbose_name_plural": "作業員",
            },
        ),
        migrations.AlterModelOptions(
            name="productprocessroute",
            options={
                "default_permissions": (),
                "permissions": [
                    ("can_view_product_route", "可以查看產品工序路線"),
                    ("can_add_product_route", "可以添加產品工序路線"),
                    ("can_edit_product_route", "可以編輯產品工序路線"),
                    ("can_delete_product_route", "可以刪除產品工序路線"),
                ],
                "verbose_name": "產品工序路線",
                "verbose_name_plural": "產品工序路線",
            },
        ),
    ]
