# Generated by Django 5.1.8 on 2025-07-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0008_alter_productprocessstandardcapacity_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productprocessstandardcapacity",
            options={
                "ordering": [
                    "product_code",
                    "process_name",
                    "equipment_type",
                    "operator_level",
                    "-version",
                ],
                "verbose_name": "產品工序標準產能",
                "verbose_name_plural": "產品工序標準產能",
            },
        ),
        migrations.AlterField(
            model_name="productprocessstandardcapacity",
            name="process_name",
            field=models.CharField(default="", max_length=50, verbose_name="工序名稱"),
        ),
    ]
