# Generated by Django 5.1.8 on 2025-07-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0009_alter_productprocessstandardcapacity_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productprocessroute",
            name="capacity_per_hour",
        ),
    ]
