# Generated by Django 5.1.8 on 2025-07-10 06:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0010_remove_productprocessroute_capacity_per_hour"),
        ("production", "0003_alter_productionline_lunch_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator",
            name="production_line",
            field=models.ForeignKey(
                blank=True,
                help_text="此作業員所屬的生產線",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="production.productionline",
                verbose_name="所屬產線",
            ),
        ),
        migrations.AlterField(
            model_name="operatorskill",
            name="priority",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="優先順序",
            ),
        ),
        migrations.AlterField(
            model_name="productprocessstandardcapacity",
            name="cycle_time_seconds",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="標準週期時間(秒)"
            ),
        ),
        migrations.AlterField(
            model_name="productprocessstandardcapacity",
            name="efficiency_factor",
            field=models.DecimalField(
                decimal_places=2, max_digits=3, verbose_name="效率因子"
            ),
        ),
        migrations.AlterField(
            model_name="productprocessstandardcapacity",
            name="expected_defect_rate",
            field=models.DecimalField(
                decimal_places=4, max_digits=5, verbose_name="預期不良率"
            ),
        ),
        migrations.AlterField(
            model_name="productprocessstandardcapacity",
            name="is_active",
            field=models.BooleanField(verbose_name="是否啟用"),
        ),
        migrations.AlterField(
            model_name="productprocessstandardcapacity",
            name="learning_curve_factor",
            field=models.DecimalField(
                decimal_places=2, max_digits=3, verbose_name="學習曲線因子"
            ),
        ),
        migrations.AlterField(
            model_name="productprocessstandardcapacity",
            name="max_batch_size",
            field=models.PositiveIntegerField(verbose_name="最大批量大小"),
        ),
        migrations.AlterField(
            model_name="productprocessstandardcapacity",
            name="max_capacity_per_hour",
            field=models.PositiveIntegerField(verbose_name="最高每小時產能"),
        ),
        migrations.AlterField(
            model_name="productprocessstandardcapacity",
            name="min_batch_size",
            field=models.PositiveIntegerField(verbose_name="最小批量大小"),
        ),
        migrations.AlterField(
            model_name="productprocessstandardcapacity",
            name="min_capacity_per_hour",
            field=models.PositiveIntegerField(verbose_name="最低每小時產能"),
        ),
        migrations.AlterField(
            model_name="productprocessstandardcapacity",
            name="optimal_batch_size",
            field=models.PositiveIntegerField(verbose_name="最佳批量大小"),
        ),
        migrations.AlterField(
            model_name="productprocessstandardcapacity",
            name="rework_time_factor",
            field=models.DecimalField(
                decimal_places=2, max_digits=3, verbose_name="重工時間因子"
            ),
        ),
        migrations.AlterField(
            model_name="productprocessstandardcapacity",
            name="setup_time_minutes",
            field=models.PositiveIntegerField(verbose_name="換線準備時間(分鐘)"),
        ),
        migrations.AlterField(
            model_name="productprocessstandardcapacity",
            name="standard_capacity_per_hour",
            field=models.PositiveIntegerField(verbose_name="標準每小時產能"),
        ),
        migrations.AlterField(
            model_name="productprocessstandardcapacity",
            name="teardown_time_minutes",
            field=models.PositiveIntegerField(verbose_name="收線時間(分鐘)"),
        ),
        migrations.AlterField(
            model_name="productprocessstandardcapacity",
            name="version",
            field=models.PositiveIntegerField(verbose_name="版本號"),
        ),
    ]
