# Generated by Django 5.1.8 on 2025-07-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0011_operator_production_line_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productprocessstandardcapacity",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否啟用"),
        ),
        migrations.AlterField(
            model_name="productprocessstandardcapacity",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="版本號"),
        ),
    ]
