# Generated by Django 5.1.8 on 2025-08-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kanbanproductionprogress",
            name="company_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="公司代號"
            ),
        ),
    ]
