# Generated by Django 5.2.6 on 2025-09-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0002_kanbanproductionprogress_test_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kanbanproductionprogress",
            name="test_field",
        ),
    ]
