# Generated by Django 5.1.8 on 2025-08-07 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0001_initial"),
        ("unified_work_reporting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unifiedworkreport",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                help_text="選擇使用的設備",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="equip.equipment",
                verbose_name="使用的設備",
            ),
        ),
    ]
