# Generated by Django 5.1.8 on 2025-09-08 01:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("process", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FillWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        help_text="作業員姓名", max_length=100, verbose_name="作業員"
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True,
                        help_text="公司代號",
                        max_length=10,
                        null=True,
                        verbose_name="公司代號",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="公司名稱", max_length=100, verbose_name="公司名稱"
                    ),
                ),
                (
                    "workorder",
                    models.CharField(
                        help_text="工單號碼", max_length=100, verbose_name="工單號碼"
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        help_text="產品編號", max_length=100, verbose_name="產品編號"
                    ),
                ),
                (
                    "planned_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="工單預設生產數量",
                        verbose_name="工單預設生產數量",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        blank=True,
                        help_text="工序名稱",
                        max_length=100,
                        verbose_name="工序名稱",
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="使用的設備",
                        max_length=100,
                        verbose_name="使用的設備",
                    ),
                ),
                (
                    "work_date",
                    models.DateField(help_text="工作日期", verbose_name="工作日期"),
                ),
                (
                    "start_time",
                    models.TimeField(help_text="開始時間", verbose_name="開始時間"),
                ),
                (
                    "end_time",
                    models.TimeField(help_text="結束時間", verbose_name="結束時間"),
                ),
                (
                    "has_break",
                    models.BooleanField(
                        default=False,
                        help_text="是否有休息時間",
                        verbose_name="是否有休息時間",
                    ),
                ),
                (
                    "break_start_time",
                    models.TimeField(
                        blank=True,
                        help_text="休息開始時間",
                        null=True,
                        verbose_name="休息開始時間",
                    ),
                ),
                (
                    "break_end_time",
                    models.TimeField(
                        blank=True,
                        help_text="休息結束時間",
                        null=True,
                        verbose_name="休息結束時間",
                    ),
                ),
                (
                    "break_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="休息時數",
                        max_digits=4,
                        verbose_name="休息時數",
                    ),
                ),
                (
                    "work_hours_calculated",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="工作時數",
                        max_digits=4,
                        verbose_name="工作時數",
                    ),
                ),
                (
                    "overtime_hours_calculated",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="加班時數",
                        max_digits=4,
                        verbose_name="加班時數",
                    ),
                ),
                (
                    "work_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="工作數量",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="工作數量",
                    ),
                ),
                (
                    "defect_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="不良品數量",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="不良品數量",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, help_text="是否已完工", verbose_name="是否已完工"
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "待核准"),
                            ("approved", "已核准"),
                            ("rejected", "已駁回"),
                        ],
                        default="pending",
                        help_text="核准狀態",
                        max_length=20,
                        verbose_name="核准狀態",
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True,
                        help_text="核准人員",
                        max_length=100,
                        verbose_name="核准人員",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="核准時間",
                        null=True,
                        verbose_name="核准時間",
                    ),
                ),
                (
                    "approval_remarks",
                    models.TextField(
                        blank=True, help_text="核准備註", verbose_name="核准備註"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="駁回原因", verbose_name="駁回原因"
                    ),
                ),
                (
                    "rejected_by",
                    models.CharField(
                        blank=True,
                        help_text="駁回人員",
                        max_length=100,
                        verbose_name="駁回人員",
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="駁回時間",
                        null=True,
                        verbose_name="駁回時間",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="備註", verbose_name="備註"),
                ),
                (
                    "abnormal_notes",
                    models.TextField(
                        blank=True, help_text="異常記錄", verbose_name="異常記錄"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        help_text="建立人員", max_length=100, verbose_name="建立人員"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="建立時間", verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="更新時間", verbose_name="更新時間"
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        help_text="工序",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process.processname",
                        verbose_name="工序",
                    ),
                ),
            ],
            options={
                "verbose_name": "填報作業",
                "verbose_name_plural": "填報作業",
                "db_table": "workorder_fill_work",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company_code"], name="workorder_f_company_ad0826_idx"
                    ),
                    models.Index(
                        fields=["company_name"], name="workorder_f_company_888e04_idx"
                    ),
                    models.Index(
                        fields=["work_date"], name="workorder_f_work_da_ab456b_idx"
                    ),
                    models.Index(
                        fields=["operator"], name="workorder_f_operato_ff194a_idx"
                    ),
                    models.Index(
                        fields=["workorder"], name="workorder_f_workord_f50ae3_idx"
                    ),
                    models.Index(
                        fields=["product_id"], name="workorder_f_product_db04c9_idx"
                    ),
                    models.Index(
                        fields=["approval_status"],
                        name="workorder_f_approva_843348_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="workorder_f_created_1ca212_idx"
                    ),
                ],
                "unique_together": {
                    (
                        "company_name",
                        "workorder",
                        "product_id",
                        "operation",
                        "operator",
                        "work_date",
                        "start_time",
                    )
                },
            },
        ),
    ]
