# Generated by Django 5.1.8 on 2025-08-12 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0001_initial"),
        ("fill_work", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fillwork",
            name="end_time",
            field=models.CharField(
                help_text="結束時間 (HH:MM格式)", max_length=5, verbose_name="結束時間"
            ),
        ),
        migrations.AlterField(
            model_name="fillwork",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                help_text="使用的設備",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="equip.equipment",
                verbose_name="使用的設備",
            ),
        ),
        migrations.AlterField(
            model_name="fillwork",
            name="start_time",
            field=models.CharField(
                help_text="開始時間 (HH:MM格式)", max_length=5, verbose_name="開始時間"
            ),
        ),
    ]
