# Generated by Django 5.1.8 on 2025-08-11 03:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0001_initial"),
        ("fill_work", "0001_initial"),
        ("process", "0001_initial"),
        ("workorder", "0008_rename_auto_allocation_tables"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fillsmtwork",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="fillsmtwork",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="fillsmtwork",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="fillsmtwork",
            name="operator",
        ),
        migrations.RemoveField(
            model_name="fillsmtwork",
            name="process",
        ),
        migrations.RemoveField(
            model_name="fillsmtwork",
            name="workorder",
        ),
        migrations.CreateModel(
            name="FillWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[("operator", "一般作業員"), ("smt", "SMT作業員")],
                        default="operator",
                        help_text="選擇填報作業的類型",
                        max_length=20,
                        verbose_name="填報類型",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        default="",
                        help_text="公司代號，用於多公司架構",
                        max_length=10,
                        verbose_name="公司代號",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        default="",
                        help_text="請選擇產品編號，將自動帶出相關工單",
                        max_length=100,
                        verbose_name="產品編號",
                    ),
                ),
                (
                    "original_workorder_number",
                    models.CharField(
                        blank=True,
                        help_text="用於儲存舊資料匯入時的工單號碼，當工單不存在於系統中時使用",
                        max_length=100,
                        null=True,
                        verbose_name="原始工單號碼",
                    ),
                ),
                (
                    "planned_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="此為工單規劃的總生產數量，不可修改",
                        verbose_name="工單預設生產數量",
                    ),
                ),
                (
                    "fill_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="請選擇填報作業的日期",
                        verbose_name="填報日期",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="請選擇填報作業的開始時間",
                        null=True,
                        verbose_name="開始時間",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="請選擇填報作業的結束時間",
                        null=True,
                        verbose_name="結束時間",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0,
                        help_text="請輸入此次填報的良品數量",
                        verbose_name="良品數量",
                    ),
                ),
                (
                    "defect_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="請輸入此次填報的不良品數量",
                        verbose_name="不良品數量",
                    ),
                ),
                (
                    "run_time_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="SMT作業員請輸入設備的運行時間（分鐘）",
                        verbose_name="運行時間（分鐘）",
                    ),
                ),
                (
                    "down_time_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="SMT作業員請輸入設備的停機時間（分鐘）",
                        verbose_name="停機時間（分鐘）",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("submitted", "已提交"),
                            ("approved", "已核准"),
                            ("rejected", "已駁回"),
                            ("completed", "已完成"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="填報狀態",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="核准時間"
                    ),
                ),
                (
                    "approval_notes",
                    models.TextField(blank=True, null=True, verbose_name="核准備註"),
                ),
                (
                    "fill_notes",
                    models.TextField(
                        blank=True,
                        help_text="請輸入填報作業的相關備註",
                        null=True,
                        verbose_name="填報備註",
                    ),
                ),
                (
                    "abnormal_notes",
                    models.TextField(
                        blank=True,
                        help_text="請記錄填報作業中的異常情況",
                        null=True,
                        verbose_name="異常記錄",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_fill_works",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="核准人員",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_fill_works",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="建立者",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        help_text="SMT作業員請選擇操作的設備",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equip.equipment",
                        verbose_name="設備",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        help_text="請選擇執行此填報作業的作業員",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作業員",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        help_text="請選擇此次填報的工序",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process.processname",
                        verbose_name="工序",
                    ),
                ),
                (
                    "workorder",
                    models.ForeignKey(
                        blank=True,
                        help_text="請選擇工單號碼，或透過產品編號自動帶出",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workorder.workorder",
                        verbose_name="工單號碼",
                    ),
                ),
            ],
            options={
                "verbose_name": "填報作業",
                "verbose_name_plural": "填報作業",
                "db_table": "fill_work",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="FillOperatorWork",
        ),
        migrations.DeleteModel(
            name="FillSMTWork",
        ),
        migrations.AddIndex(
            model_name="fillwork",
            index=models.Index(
                fields=["work_type"], name="fill_work_work_ty_618e94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fillwork",
            index=models.Index(
                fields=["fill_date"], name="fill_work_fill_da_a41d1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fillwork",
            index=models.Index(
                fields=["operator"], name="fill_work_operato_f5270a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fillwork",
            index=models.Index(fields=["status"], name="fill_work_status_2adf54_idx"),
        ),
        migrations.AddIndex(
            model_name="fillwork",
            index=models.Index(
                fields=["workorder"], name="fill_work_workord_12e52c_idx"
            ),
        ),
    ]
