# Generated by Django 5.1.8 on 2025-08-11 03:23

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0001_initial"),
        ("fill_work", "0002_remove_fillsmtwork_approved_by_and_more"),
        ("process", "0001_initial"),
        ("workorder", "0008_rename_auto_allocation_tables"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="fillwork",
            name="fill_work_work_ty_618e94_idx",
        ),
        migrations.RemoveIndex(
            model_name="fillwork",
            name="fill_work_fill_da_a41d1d_idx",
        ),
        migrations.RemoveIndex(
            model_name="fillwork",
            name="fill_work_status_2adf54_idx",
        ),
        migrations.RenameIndex(
            model_name="fillwork",
            new_name="fill_work_operato_475862_idx",
            old_name="fill_work_operato_f5270a_idx",
        ),
        migrations.RemoveField(
            model_name="fillwork",
            name="approval_notes",
        ),
        migrations.RemoveField(
            model_name="fillwork",
            name="down_time_minutes",
        ),
        migrations.RemoveField(
            model_name="fillwork",
            name="fill_date",
        ),
        migrations.RemoveField(
            model_name="fillwork",
            name="fill_notes",
        ),
        migrations.RemoveField(
            model_name="fillwork",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="fillwork",
            name="run_time_minutes",
        ),
        migrations.RemoveField(
            model_name="fillwork",
            name="status",
        ),
        migrations.RemoveField(
            model_name="fillwork",
            name="work_type",
        ),
        migrations.AddField(
            model_name="fillwork",
            name="approval_remarks",
            field=models.TextField(
                blank=True, help_text="核准備註", null=True, verbose_name="核准備註"
            ),
        ),
        migrations.AddField(
            model_name="fillwork",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "待核准"),
                    ("approved", "已核准"),
                    ("rejected", "已駁回"),
                ],
                default="pending",
                help_text="核准狀態",
                max_length=20,
                verbose_name="核准狀態",
            ),
        ),
        migrations.AddField(
            model_name="fillwork",
            name="break_end_time",
            field=models.TimeField(
                blank=True,
                help_text="休息結束時間",
                null=True,
                verbose_name="休息結束時間",
            ),
        ),
        migrations.AddField(
            model_name="fillwork",
            name="break_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="休息時數（小時）",
                max_digits=5,
                verbose_name="休息時數",
            ),
        ),
        migrations.AddField(
            model_name="fillwork",
            name="break_start_time",
            field=models.TimeField(
                blank=True,
                help_text="休息開始時間",
                null=True,
                verbose_name="休息開始時間",
            ),
        ),
        migrations.AddField(
            model_name="fillwork",
            name="has_break",
            field=models.BooleanField(
                default=False, help_text="是否有休息時間", verbose_name="是否有休息時間"
            ),
        ),
        migrations.AddField(
            model_name="fillwork",
            name="is_completed",
            field=models.BooleanField(
                default=False, help_text="是否已完工", verbose_name="是否已完工"
            ),
        ),
        migrations.AddField(
            model_name="fillwork",
            name="operation",
            field=models.CharField(
                blank=True,
                help_text="工序名稱",
                max_length=100,
                null=True,
                verbose_name="工序名稱",
            ),
        ),
        migrations.AddField(
            model_name="fillwork",
            name="overtime_hours_calculated",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="加班時數（小時）",
                max_digits=5,
                verbose_name="加班時數",
            ),
        ),
        migrations.AddField(
            model_name="fillwork",
            name="rejected_at",
            field=models.DateTimeField(
                blank=True, help_text="駁回時間", null=True, verbose_name="駁回時間"
            ),
        ),
        migrations.AddField(
            model_name="fillwork",
            name="rejected_by",
            field=models.CharField(
                blank=True,
                help_text="駁回人員姓名",
                max_length=100,
                null=True,
                verbose_name="駁回人員",
            ),
        ),
        migrations.AddField(
            model_name="fillwork",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="駁回原因", null=True, verbose_name="駁回原因"
            ),
        ),
        migrations.AddField(
            model_name="fillwork",
            name="remarks",
            field=models.TextField(
                blank=True,
                help_text="請輸入填報作業的相關備註",
                null=True,
                verbose_name="備註",
            ),
        ),
        migrations.AddField(
            model_name="fillwork",
            name="work_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="請選擇填報作業的日期",
                verbose_name="日期",
            ),
        ),
        migrations.AddField(
            model_name="fillwork",
            name="work_hours_calculated",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="工作時數（小時）",
                max_digits=5,
                verbose_name="工作時數",
            ),
        ),
        migrations.AddField(
            model_name="fillwork",
            name="work_quantity",
            field=models.IntegerField(
                default=0, help_text="請輸入此次填報的工作數量", verbose_name="工作數量"
            ),
        ),
        migrations.AlterField(
            model_name="fillwork",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, help_text="核准時間", null=True, verbose_name="核准時間"
            ),
        ),
        migrations.AlterField(
            model_name="fillwork",
            name="approved_by",
            field=models.CharField(
                blank=True,
                help_text="核准人員姓名",
                max_length=100,
                null=True,
                verbose_name="核准人員",
            ),
        ),
        migrations.AlterField(
            model_name="fillwork",
            name="created_by",
            field=models.CharField(
                default="",
                help_text="建立人員姓名",
                max_length=100,
                verbose_name="建立人員",
            ),
        ),
        migrations.AlterField(
            model_name="fillwork",
            name="end_time",
            field=models.TimeField(
                blank=True,
                help_text="請選擇填報作業的結束時間",
                null=True,
                verbose_name="結束時間",
            ),
        ),
        migrations.AlterField(
            model_name="fillwork",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                help_text="請選擇使用的設備",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="equip.equipment",
                verbose_name="使用的設備",
            ),
        ),
        migrations.AlterField(
            model_name="fillwork",
            name="operator",
            field=models.CharField(
                default="",
                help_text="作業員姓名",
                max_length=100,
                verbose_name="作業員",
            ),
        ),
        migrations.AlterField(
            model_name="fillwork",
            name="start_time",
            field=models.TimeField(
                blank=True,
                help_text="請選擇填報作業的開始時間",
                null=True,
                verbose_name="開始時間",
            ),
        ),
        migrations.AddIndex(
            model_name="fillwork",
            index=models.Index(
                fields=["work_date"], name="fill_work_work_da_d598a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fillwork",
            index=models.Index(fields=["process"], name="fill_work_process_2c1f15_idx"),
        ),
        migrations.AddIndex(
            model_name="fillwork",
            index=models.Index(
                fields=["equipment"], name="fill_work_equipme_6bc642_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fillwork",
            index=models.Index(
                fields=["approval_status"], name="fill_work_approva_b14445_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fillwork",
            index=models.Index(
                fields=["is_completed"], name="fill_work_is_comp_a0d012_idx"
            ),
        ),
    ]
