# Generated by Django 5.1.8 on 2025-08-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fill_work", "0002_alter_fillwork_end_time_alter_fillwork_equipment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fillwork",
            name="equipment",
            field=models.CharField(
                blank=True,
                default="",
                help_text="使用的設備",
                max_length=100,
                verbose_name="使用的設備",
            ),
        ),
    ]
