# Generated by Django 5.1.8 on 2025-08-11 03:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0001_initial"),
        ("fill_work", "0003_remove_fillwork_fill_work_work_ty_618e94_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fillwork",
            name="company_code",
        ),
        migrations.RemoveField(
            model_name="fillwork",
            name="original_workorder_number",
        ),
        migrations.AddField(
            model_name="fillwork",
            name="company_name",
            field=models.CharField(
                default="",
                help_text="公司名稱",
                max_length=100,
                verbose_name="公司名稱",
            ),
        ),
        migrations.AlterField(
            model_name="fillwork",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                help_text="請選擇使用的設備（可選）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="equip.equipment",
                verbose_name="使用的設備",
            ),
        ),
        migrations.AlterField(
            model_name="fillwork",
            name="work_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="請選擇填報作業的日期",
                verbose_name="工作日期",
            ),
        ),
    ]
