# Generated by Django 5.1.8 on 2025-08-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fill_work", "0003_alter_fillwork_equipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fillwork",
            name="end_time",
            field=models.TimeField(help_text="結束時間", verbose_name="結束時間"),
        ),
        migrations.AlterField(
            model_name="fillwork",
            name="start_time",
            field=models.TimeField(help_text="開始時間", verbose_name="開始時間"),
        ),
    ]
