# Generated by Django 5.1.8 on 2025-08-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fill_work", "0004_alter_fillwork_end_time_alter_fillwork_start_time"),
        ("process", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fillwork",
            name="company_code",
            field=models.CharField(
                blank=True,
                help_text="公司代號",
                max_length=10,
                null=True,
                verbose_name="公司代號",
            ),
        ),
        migrations.AddIndex(
            model_name="fillwork",
            index=models.Index(
                fields=["company_code"], name="workorder_f_company_ad0826_idx"
            ),
        ),
    ]
