# Generated by Django 5.1.8 on 2025-08-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fill_work", "0005_fillwork_company_code_and_more"),
        ("process", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fillwork",
            unique_together={("company_name", "workorder", "product_id")},
        ),
        migrations.AddIndex(
            model_name="fillwork",
            index=models.Index(
                fields=["company_name"], name="workorder_f_company_888e04_idx"
            ),
        ),
    ]
