# Generated by Django 5.1.8 on 2025-08-17 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fill_work", "0006_alter_fillwork_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fillwork",
            unique_together=set(),
        ),
    ]
