# Generated by Django 5.1.8 on 2025-08-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fill_work", "0007_alter_fillwork_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fillwork",
            unique_together={
                (
                    "company_name",
                    "workorder",
                    "product_id",
                    "operation",
                    "operator",
                    "work_date",
                    "start_time",
                )
            },
        ),
    ]
