# Generated by Django 5.1.8 on 2025-08-02 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductionLineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_code",
                    models.CharField(
                        help_text="產線類型代號，例如：SMT、ASSY、TEST",
                        max_length=20,
                        unique=True,
                        verbose_name="類型代號",
                    ),
                ),
                (
                    "type_name",
                    models.CharField(
                        help_text="產線類型的中文名稱",
                        max_length=100,
                        verbose_name="類型名稱",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="產線類型的詳細描述",
                        null=True,
                        verbose_name="類型描述",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="是否啟用此產線類型",
                        verbose_name="啟用狀態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "產線類型",
                "verbose_name_plural": "產線類型管理",
                "ordering": ["type_code"],
            },
        ),
        migrations.CreateModel(
            name="ProductionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_code",
                    models.CharField(
                        help_text="產線的唯一識別代號",
                        max_length=20,
                        unique=True,
                        verbose_name="產線代號",
                    ),
                ),
                (
                    "line_name",
                    models.CharField(
                        help_text="產線的中文名稱",
                        max_length=100,
                        verbose_name="產線名稱",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="產線的詳細描述",
                        null=True,
                        verbose_name="產線描述",
                    ),
                ),
                (
                    "work_start_time",
                    models.TimeField(
                        help_text="每日工作開始時間，格式：HH:MM",
                        verbose_name="工作開始時間",
                    ),
                ),
                (
                    "work_end_time",
                    models.TimeField(
                        help_text="每日工作結束時間，格式：HH:MM",
                        verbose_name="工作結束時間",
                    ),
                ),
                (
                    "lunch_start_time",
                    models.TimeField(
                        blank=True,
                        help_text="午休開始時間，格式：HH:MM（可為空，表示無午休時間）",
                        null=True,
                        verbose_name="午休開始時間",
                    ),
                ),
                (
                    "lunch_end_time",
                    models.TimeField(
                        blank=True,
                        help_text="午休結束時間，格式：HH:MM（可為空，表示無午休時間）",
                        null=True,
                        verbose_name="午休結束時間",
                    ),
                ),
                (
                    "overtime_start_time",
                    models.TimeField(
                        blank=True,
                        help_text="加班開始時間，格式：HH:MM（可為空，表示無加班時間）",
                        null=True,
                        verbose_name="加班開始時間",
                    ),
                ),
                (
                    "overtime_end_time",
                    models.TimeField(
                        blank=True,
                        help_text="加班結束時間，格式：HH:MM（可為空，表示無加班時間）",
                        null=True,
                        verbose_name="加班結束時間",
                    ),
                ),
                (
                    "work_days",
                    models.TextField(
                        default='["1","2","3","4","5"]',
                        help_text="工作日設定，JSON格式，1=週一，2=週二，以此類推",
                        verbose_name="工作日設定",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="是否啟用此產線",
                        verbose_name="啟用狀態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "line_type",
                    models.ForeignKey(
                        help_text="此產線所屬的類型",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.productionlinetype",
                        verbose_name="產線類型",
                    ),
                ),
            ],
            options={
                "verbose_name": "產線管理",
                "verbose_name_plural": "產線管理",
                "ordering": ["line_code"],
            },
        ),
        migrations.CreateModel(
            name="ProductionLineSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedule_date", models.DateField(verbose_name="排程日期")),
                ("work_start_time", models.TimeField(verbose_name="工作開始時間")),
                ("work_end_time", models.TimeField(verbose_name="工作結束時間")),
                (
                    "lunch_start_time",
                    models.TimeField(
                        blank=True,
                        help_text="午休開始時間，格式：HH:MM（可為空，表示無午休時間）",
                        null=True,
                        verbose_name="午休開始時間",
                    ),
                ),
                (
                    "lunch_end_time",
                    models.TimeField(
                        blank=True,
                        help_text="午休結束時間，格式：HH:MM（可為空，表示無午休時間）",
                        null=True,
                        verbose_name="午休結束時間",
                    ),
                ),
                (
                    "overtime_start_time",
                    models.TimeField(
                        blank=True,
                        help_text="加班開始時間，格式：HH:MM（可為空，表示無加班時間）",
                        null=True,
                        verbose_name="加班開始時間",
                    ),
                ),
                (
                    "overtime_end_time",
                    models.TimeField(
                        blank=True,
                        help_text="加班結束時間，格式：HH:MM（可為空，表示無加班時間）",
                        null=True,
                        verbose_name="加班結束時間",
                    ),
                ),
                ("work_days", models.TextField(verbose_name="工作日設定")),
                (
                    "is_holiday",
                    models.BooleanField(default=False, verbose_name="是否為假日"),
                ),
                (
                    "holiday_reason",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="假日原因"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(max_length=100, verbose_name="建立人員"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "production_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="production.productionline",
                        verbose_name="產線",
                    ),
                ),
            ],
            options={
                "verbose_name": "產線排程記錄",
                "verbose_name_plural": "產線排程記錄",
                "ordering": ["-schedule_date", "production_line"],
                "unique_together": {("production_line", "schedule_date")},
            },
        ),
    ]
