# Generated by Django 5.1.8 on 2025-09-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder_id', models.CharField(max_length=50, verbose_name='工單ID')),
                ('product_id', models.CharField(max_length=50, verbose_name='產品ID')),
                ('production_line_id', models.CharField(max_length=50, verbose_name='產線ID')),
                ('production_line_name', models.CharField(max_length=100, verbose_name='產線名稱')),
                ('start_time', models.DateTimeField(verbose_name='開始時間')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('planned_quantity', models.IntegerField(verbose_name='計劃數量')),
                ('actual_quantity', models.IntegerField(default=0, verbose_name='實際數量')),
                ('status', models.CharField(choices=[('pending', '待開始'), ('running', '執行中'), ('completed', '已完成'), ('paused', '暫停'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='執行狀態')),
                ('operator', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作員')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '生產執行記錄',
                'verbose_name_plural': '生產執行記錄管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_code', models.CharField(help_text='產線的唯一識別代號', max_length=20, unique=True, verbose_name='產線代號')),
                ('line_name', models.CharField(help_text='產線的中文名稱', max_length=100, verbose_name='產線名稱')),
                ('line_type_id', models.CharField(max_length=50, verbose_name='產線類型ID')),
                ('line_type_name', models.CharField(max_length=100, verbose_name='產線類型名稱')),
                ('description', models.TextField(blank=True, help_text='產線的詳細描述', null=True, verbose_name='產線描述')),
                ('work_start_time', models.TimeField(help_text='每日工作開始時間，格式：HH:MM', verbose_name='工作開始時間')),
                ('work_end_time', models.TimeField(help_text='每日工作結束時間，格式：HH:MM', verbose_name='工作結束時間')),
                ('lunch_start_time', models.TimeField(blank=True, help_text='午休開始時間，格式：HH:MM（可為空，表示無午休時間）', null=True, verbose_name='午休開始時間')),
                ('lunch_end_time', models.TimeField(blank=True, help_text='午休結束時間，格式：HH:MM（可為空，表示無午休時間）', null=True, verbose_name='午休結束時間')),
                ('overtime_start_time', models.TimeField(blank=True, help_text='加班開始時間，格式：HH:MM（可為空，表示無加班時間）', null=True, verbose_name='加班開始時間')),
                ('overtime_end_time', models.TimeField(blank=True, help_text='加班結束時間，格式：HH:MM（可為空，表示無加班時間）', null=True, verbose_name='加班結束時間')),
                ('work_days', models.TextField(default='["1","2","3","4","5"]', help_text='工作日設定，JSON格式，1=週一，2=週二，以此類推', verbose_name='工作日設定')),
                ('is_active', models.BooleanField(default=True, help_text='是否啟用此產線', verbose_name='啟用狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '產線管理',
                'verbose_name_plural': '產線管理',
                'ordering': ['line_code'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(help_text='產線類型代號，例如：SMT、ASSY、TEST', max_length=20, unique=True, verbose_name='類型代號')),
                ('type_name', models.CharField(help_text='產線類型的中文名稱', max_length=100, verbose_name='類型名稱')),
                ('description', models.TextField(blank=True, help_text='產線類型的詳細描述', null=True, verbose_name='類型描述')),
                ('is_active', models.BooleanField(default=True, help_text='是否啟用此產線類型', verbose_name='啟用狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '產線類型',
                'verbose_name_plural': '產線類型管理',
                'ordering': ['type_code'],
            },
        ),
        migrations.CreateModel(
            name='ProductionMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_line_id', models.CharField(max_length=50, verbose_name='產線ID')),
                ('production_line_name', models.CharField(max_length=100, verbose_name='產線名稱')),
                ('equipment_status', models.CharField(choices=[('running', '運行中'), ('idle', '閒置'), ('maintenance', '維護中'), ('error', '故障')], default='idle', max_length=20, verbose_name='設備狀態')),
                ('current_speed', models.FloatField(default=0, verbose_name='當前速度')),
                ('target_speed', models.FloatField(default=0, verbose_name='目標速度')),
                ('efficiency', models.FloatField(default=0, verbose_name='效率')),
                ('quality_rate', models.FloatField(default=100, verbose_name='良品率')),
                ('defect_count', models.IntegerField(default=0, verbose_name='不良品數量')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='記錄時間')),
            ],
            options={
                'verbose_name': '生產監控數據',
                'verbose_name_plural': '生產監控數據管理',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_line_id', models.CharField(max_length=50, verbose_name='產線ID')),
                ('production_line_name', models.CharField(max_length=100, verbose_name='產線名稱')),
                ('schedule_date', models.DateField(verbose_name='排程日期')),
                ('work_start_time', models.TimeField(verbose_name='工作開始時間')),
                ('work_end_time', models.TimeField(verbose_name='工作結束時間')),
                ('lunch_start_time', models.TimeField(blank=True, help_text='午休開始時間，格式：HH:MM（可為空，表示無午休時間）', null=True, verbose_name='午休開始時間')),
                ('lunch_end_time', models.TimeField(blank=True, help_text='午休結束時間，格式：HH:MM（可為空，表示無午休時間）', null=True, verbose_name='午休結束時間')),
                ('overtime_start_time', models.TimeField(blank=True, help_text='加班開始時間，格式：HH:MM（可為空，表示無加班時間）', null=True, verbose_name='加班開始時間')),
                ('overtime_end_time', models.TimeField(blank=True, help_text='加班結束時間，格式：HH:MM（可為空，表示無加班時間）', null=True, verbose_name='加班結束時間')),
                ('work_days', models.TextField(verbose_name='工作日設定')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='是否為假日')),
                ('holiday_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='假日原因')),
                ('created_by', models.CharField(max_length=100, verbose_name='建立人員')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '產線排程記錄',
                'verbose_name_plural': '產線排程記錄',
                'ordering': ['-schedule_date', 'production_line_id'],
                'unique_together': {('production_line_id', 'schedule_date')},
            },
        ),
    ]
