# Generated by Django 5.1.8 on 2025-07-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productionline",
            options={
                "ordering": ["line_code"],
                "verbose_name": "產線管理",
                "verbose_name_plural": "產線管理",
            },
        ),
        migrations.AlterModelOptions(
            name="productionlinetype",
            options={
                "ordering": ["type_code"],
                "verbose_name": "產線類型",
                "verbose_name_plural": "產線類型管理",
            },
        ),
        migrations.AlterUniqueTogether(
            name="productionline",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="productionlinetype",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="productionlineschedule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
        migrations.AlterField(
            model_name="productionline",
            name="line_code",
            field=models.CharField(
                help_text="產線的唯一識別代號",
                max_length=20,
                unique=True,
                verbose_name="產線代號",
            ),
        ),
        migrations.AlterField(
            model_name="productionlinetype",
            name="type_code",
            field=models.CharField(
                help_text="產線類型代號，例如：SMT、ASSY、TEST",
                max_length=20,
                unique=True,
                verbose_name="類型代號",
            ),
        ),
        migrations.RemoveField(
            model_name="productionline",
            name="company_code",
        ),
        migrations.RemoveField(
            model_name="productionlinetype",
            name="company_code",
        ),
    ]
