# Generated by Django 5.1.8 on 2025-07-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_alter_productionline_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionline",
            name="lunch_end_time",
            field=models.TimeField(
                blank=True,
                help_text="午休結束時間，格式：HH:MM（可為空，表示無午休時間）",
                null=True,
                verbose_name="午休結束時間",
            ),
        ),
        migrations.AlterField(
            model_name="productionline",
            name="lunch_start_time",
            field=models.TimeField(
                blank=True,
                help_text="午休開始時間，格式：HH:MM（可為空，表示無午休時間）",
                null=True,
                verbose_name="午休開始時間",
            ),
        ),
        migrations.AlterField(
            model_name="productionline",
            name="overtime_end_time",
            field=models.TimeField(
                blank=True,
                help_text="加班結束時間，格式：HH:MM（可為空，表示無加班時間）",
                null=True,
                verbose_name="加班結束時間",
            ),
        ),
        migrations.AlterField(
            model_name="productionline",
            name="overtime_start_time",
            field=models.TimeField(
                blank=True,
                help_text="加班開始時間，格式：HH:MM（可為空，表示無加班時間）",
                null=True,
                verbose_name="加班開始時間",
            ),
        ),
        migrations.AlterField(
            model_name="productionlineschedule",
            name="lunch_end_time",
            field=models.TimeField(
                blank=True,
                help_text="午休結束時間，格式：HH:MM（可為空，表示無午休時間）",
                null=True,
                verbose_name="午休結束時間",
            ),
        ),
        migrations.AlterField(
            model_name="productionlineschedule",
            name="lunch_start_time",
            field=models.TimeField(
                blank=True,
                help_text="午休開始時間，格式：HH:MM（可為空，表示無午休時間）",
                null=True,
                verbose_name="午休開始時間",
            ),
        ),
        migrations.AlterField(
            model_name="productionlineschedule",
            name="overtime_end_time",
            field=models.TimeField(
                blank=True,
                help_text="加班結束時間，格式：HH:MM（可為空，表示無加班時間）",
                null=True,
                verbose_name="加班結束時間",
            ),
        ),
        migrations.AlterField(
            model_name="productionlineschedule",
            name="overtime_start_time",
            field=models.TimeField(
                blank=True,
                help_text="加班開始時間，格式：HH:MM（可為空，表示無加班時間）",
                null=True,
                verbose_name="加班開始時間",
            ),
        ),
    ]
