# Generated by Django 5.2.6 on 2025-09-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_auto_20250910_1046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionlineschedule",
            name="production_line_name",
            field=models.CharField(max_length=100, verbose_name="產線名稱"),
        ),
    ]
