# Generated by Django 5.1.8 on 2025-08-20 15:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MesWorkorderOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        help_text="公司代號，例如：01、02、03",
                        max_length=10,
                        verbose_name="公司代號",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="公司名稱", max_length=100, verbose_name="公司名稱"
                    ),
                ),
                (
                    "workorder_number",
                    models.CharField(
                        db_index=True,
                        help_text="工單號碼",
                        max_length=50,
                        verbose_name="工單號碼",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        db_index=True,
                        help_text="產品編號",
                        max_length=100,
                        verbose_name="產品編號",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        help_text="產品名稱",
                        max_length=200,
                        null=True,
                        verbose_name="產品名稱",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("production", "生產作業"),
                            ("inspection", "檢驗作業"),
                            ("packaging", "包裝作業"),
                            ("maintenance", "維護作業"),
                            ("other", "其他作業"),
                        ],
                        default="production",
                        help_text="作業類型",
                        max_length=20,
                        verbose_name="作業類型",
                    ),
                ),
                (
                    "operation_name",
                    models.CharField(
                        help_text="作業名稱", max_length=100, verbose_name="作業名稱"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待作業"),
                            ("in_progress", "作業中"),
                            ("paused", "暫停"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        help_text="作業狀態",
                        max_length=20,
                        verbose_name="作業狀態",
                    ),
                ),
                (
                    "planned_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="計劃作業數量", verbose_name="計劃數量"
                    ),
                ),
                (
                    "completed_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="已完成作業數量", verbose_name="完成數量"
                    ),
                ),
                (
                    "defect_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="不良品數量", verbose_name="不良品數量"
                    ),
                ),
                (
                    "planned_start_date",
                    models.DateField(
                        blank=True,
                        help_text="計劃開始日期",
                        null=True,
                        verbose_name="計劃開始日期",
                    ),
                ),
                (
                    "planned_end_date",
                    models.DateField(
                        blank=True,
                        help_text="計劃完成日期",
                        null=True,
                        verbose_name="計劃完成日期",
                    ),
                ),
                (
                    "actual_start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="實際開始時間",
                        null=True,
                        verbose_name="實際開始時間",
                    ),
                ),
                (
                    "actual_end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="實際完成時間",
                        null=True,
                        verbose_name="實際完成時間",
                    ),
                ),
                (
                    "assigned_operator",
                    models.CharField(
                        blank=True,
                        help_text="分配作業員",
                        max_length=100,
                        null=True,
                        verbose_name="分配作業員",
                    ),
                ),
                (
                    "assigned_equipment",
                    models.CharField(
                        blank=True,
                        help_text="分配設備",
                        max_length=100,
                        null=True,
                        verbose_name="分配設備",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="作業備註", null=True, verbose_name="備註"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="建立時間", verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="更新時間", verbose_name="更新時間"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="建立者",
                        max_length=100,
                        null=True,
                        verbose_name="建立者",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="更新者",
                        max_length=100,
                        null=True,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "MES 工單作業",
                "verbose_name_plural": "MES 工單作業",
                "db_table": "mes_workorder_operation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company_code", "workorder_number"],
                        name="mes_workord_company_babfd2_idx",
                    ),
                    models.Index(
                        fields=["status"], name="mes_workord_status_9e8765_idx"
                    ),
                    models.Index(
                        fields=["operation_type"], name="mes_workord_operati_830ede_idx"
                    ),
                    models.Index(
                        fields=["planned_start_date"],
                        name="mes_workord_planned_3a59b1_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "company_code",
                        "workorder_number",
                        "product_code",
                        "operation_name",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="MesWorkorderOperationDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detail_type",
                    models.CharField(
                        choices=[
                            ("process", "工序"),
                            ("material", "物料"),
                            ("equipment", "設備"),
                            ("quality", "品質"),
                            ("other", "其他"),
                        ],
                        default="process",
                        help_text="明細類型",
                        max_length=20,
                        verbose_name="明細類型",
                    ),
                ),
                (
                    "detail_name",
                    models.CharField(
                        help_text="明細名稱", max_length=100, verbose_name="明細名稱"
                    ),
                ),
                (
                    "detail_description",
                    models.TextField(
                        blank=True,
                        help_text="明細說明",
                        null=True,
                        verbose_name="明細說明",
                    ),
                ),
                (
                    "planned_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="計劃數量", verbose_name="計劃數量"
                    ),
                ),
                (
                    "actual_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="實際數量", verbose_name="實際數量"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="開始時間",
                        null=True,
                        verbose_name="開始時間",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="結束時間",
                        null=True,
                        verbose_name="結束時間",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, help_text="是否完成", verbose_name="是否完成"
                    ),
                ),
                (
                    "completion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="完成率（百分比）",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="完成率",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="明細備註", null=True, verbose_name="備註"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="建立時間", verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="更新時間", verbose_name="更新時間"
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        help_text="關聯的作業主表",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="mes_workorder_operation.mesworkorderoperation",
                        verbose_name="作業主表",
                    ),
                ),
            ],
            options={
                "verbose_name": "MES 工單作業明細",
                "verbose_name_plural": "MES 工單作業明細",
                "db_table": "mes_workorder_operation_detail",
                "ordering": ["operation", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["operation", "detail_type"],
                        name="mes_workord_operati_0e5aa8_idx",
                    ),
                    models.Index(
                        fields=["is_completed"], name="mes_workord_is_comp_2561fa_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MesWorkorderOperationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("created", "建立"),
                            ("updated", "更新"),
                            ("started", "開始"),
                            ("paused", "暫停"),
                            ("resumed", "重啟"),
                            ("completed", "完成"),
                            ("cancelled", "取消"),
                            ("deleted", "刪除"),
                        ],
                        help_text="歷史類型",
                        max_length=20,
                        verbose_name="歷史類型",
                    ),
                ),
                (
                    "history_description",
                    models.TextField(help_text="歷史說明", verbose_name="歷史說明"),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True,
                        help_text="變更前的值（JSON格式）",
                        null=True,
                        verbose_name="變更前值",
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True,
                        help_text="變更後的值（JSON格式）",
                        null=True,
                        verbose_name="變更後值",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True,
                        help_text="操作者",
                        max_length=100,
                        null=True,
                        verbose_name="操作者",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="操作者IP位址",
                        null=True,
                        verbose_name="IP位址",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="建立時間", verbose_name="建立時間"
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        help_text="關聯的作業主表",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="mes_workorder_operation.mesworkorderoperation",
                        verbose_name="作業主表",
                    ),
                ),
            ],
            options={
                "verbose_name": "MES 工單作業歷史",
                "verbose_name_plural": "MES 工單作業歷史",
                "db_table": "mes_workorder_operation_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["operation", "history_type"],
                        name="mes_workord_operati_37a405_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="mes_workord_created_88c423_idx"
                    ),
                    models.Index(
                        fields=["operator"], name="mes_workord_operato_b38519_idx"
                    ),
                ],
            },
        ),
    ]
