# Generated by Django 5.1.8 on 2025-08-20 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoAllocationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "setting_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="設定名稱"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="啟用狀態"),
                ),
                (
                    "allocation_type",
                    models.CharField(
                        choices=[
                            ("operator", "作業員分配"),
                            ("equipment", "設備分配"),
                            ("both", "作業員和設備分配"),
                        ],
                        max_length=20,
                        verbose_name="分配類型",
                    ),
                ),
                (
                    "priority_rules",
                    models.JSONField(default=dict, verbose_name="優先級規則"),
                ),
                (
                    "check_interval",
                    models.IntegerField(default=5, verbose_name="檢查間隔(分鐘)"),
                ),
                (
                    "last_check_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最後檢查時間"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="備註"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_auto_allocation_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="建立者",
                    ),
                ),
            ],
            options={
                "verbose_name": "自動分配設定",
                "verbose_name_plural": "自動分配設定",
                "db_table": "workorder_auto_allocation_settings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutoAllocationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocation_type",
                    models.CharField(
                        choices=[
                            ("operator", "作業員分配"),
                            ("equipment", "設備分配"),
                            ("both", "作業員和設備分配"),
                        ],
                        max_length=20,
                        verbose_name="分配類型",
                    ),
                ),
                (
                    "target_workorder",
                    models.CharField(max_length=100, verbose_name="目標工單"),
                ),
                (
                    "assigned_operator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分配作業員"
                    ),
                ),
                (
                    "assigned_equipment",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分配設備"
                    ),
                ),
                (
                    "allocation_status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失敗"),
                            ("partial", "部分成功"),
                        ],
                        max_length=20,
                        verbose_name="分配狀態",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="錯誤訊息"),
                ),
                (
                    "allocation_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="分配時間"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="備註"),
                ),
                (
                    "allocation_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_logs",
                        to="workorder_completed_workorder.autoallocationsettings",
                        verbose_name="分配設定",
                    ),
                ),
            ],
            options={
                "verbose_name": "自動分配日誌",
                "verbose_name_plural": "自動分配日誌",
                "db_table": "workorder_auto_allocation_log",
                "ordering": ["-allocation_time"],
            },
        ),
        migrations.CreateModel(
            name="CompletedWorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                (
                    "order_number",
                    models.CharField(max_length=50, verbose_name="工單號碼"),
                ),
                (
                    "product_code",
                    models.CharField(max_length=50, verbose_name="產品編號"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="產品名稱"),
                ),
                ("order_quantity", models.IntegerField(verbose_name="訂單數量")),
                ("completed_quantity", models.IntegerField(verbose_name="完工數量")),
                (
                    "defective_quantity",
                    models.IntegerField(default=0, verbose_name="不良品數量"),
                ),
                ("start_date", models.DateField(verbose_name="開始日期")),
                ("completion_date", models.DateField(verbose_name="完工日期")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "已完工"), ("archived", "已封存")],
                        default="completed",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="備註"),
                ),
            ],
            options={
                "verbose_name": "已完工工單",
                "verbose_name_plural": "已完工工單",
                "db_table": "workorder_completed_workorder",
                "ordering": ["-completion_date", "-created_at"],
                "unique_together": {("company_code", "order_number", "product_code")},
            },
        ),
        migrations.CreateModel(
            name="CompletedProductionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="報表日期")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "日報"),
                            ("weekly", "週報"),
                            ("monthly", "月報"),
                            ("final", "完工報表"),
                        ],
                        max_length=20,
                        verbose_name="報表類型",
                    ),
                ),
                ("total_production", models.IntegerField(verbose_name="總生產量")),
                ("good_quantity", models.IntegerField(verbose_name="良品數量")),
                ("defective_quantity", models.IntegerField(verbose_name="不良品數量")),
                (
                    "production_efficiency",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="生產效率(%)"
                    ),
                ),
                (
                    "quality_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="品質率(%)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="備註"),
                ),
                (
                    "completed_workorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_reports",
                        to="workorder_completed_workorder.completedworkorder",
                        verbose_name="已完工工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "已完工生產報表",
                "verbose_name_plural": "已完工生產報表",
                "db_table": "workorder_completed_production_report",
                "ordering": ["-report_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompletedWorkOrderProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                ("process_sequence", models.IntegerField(verbose_name="工序順序")),
                ("planned_quantity", models.IntegerField(verbose_name="計劃數量")),
                ("completed_quantity", models.IntegerField(verbose_name="完工數量")),
                (
                    "defective_quantity",
                    models.IntegerField(default=0, verbose_name="不良品數量"),
                ),
                ("start_time", models.DateTimeField(verbose_name="開始時間")),
                ("end_time", models.DateTimeField(verbose_name="結束時間")),
                (
                    "operator_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="作業員"
                    ),
                ),
                (
                    "equipment_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="設備"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="備註"),
                ),
                (
                    "completed_workorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processes",
                        to="workorder_completed_workorder.completedworkorder",
                        verbose_name="已完工工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "已完工工單工序",
                "verbose_name_plural": "已完工工單工序",
                "db_table": "workorder_completed_workorder_process",
                "ordering": ["process_sequence"],
            },
        ),
    ]
