# Generated by Django 5.1.8 on 2025-08-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workorder_reporting",
            "0002_operatorsupplementreport_original_workorder_number",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="smtproductionreport",
            name="original_workorder_number",
            field=models.CharField(
                blank=True,
                help_text="用於儲存舊資料匯入時的工單號碼，當工單不存在於系統中時使用",
                max_length=100,
                null=True,
                verbose_name="原始工單號碼",
            ),
        ),
    ]
