# Generated by Django 5.1.8 on 2025-08-04 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0001_initial"),
        (
            "workorder_reporting",
            "0004_operatorsupplementreport_allocation_check_result_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="operatorsupplementreport",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                help_text="請選擇此次補登使用的設備（排除SMT相關設備）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="equip.equipment",
                verbose_name="使用的設備",
            ),
        ),
        migrations.AlterField(
            model_name="smtproductionreport",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                help_text="請選擇本次報工使用的SMT設備",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="equip.equipment",
                verbose_name="使用的設備",
            ),
        ),
    ]
