# Generated by Django 5.1.8 on 2025-08-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "workorder_reporting",
            "0005_alter_operatorsupplementreport_equipment_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operatorsupplementreport",
            name="rd_product_code",
        ),
        migrations.RemoveField(
            model_name="operatorsupplementreport",
            name="rd_workorder_number",
        ),
        migrations.RemoveField(
            model_name="operatorsupplementreport",
            name="report_type",
        ),
        migrations.RemoveField(
            model_name="smtproductionreport",
            name="rd_product_code",
        ),
        migrations.RemoveField(
            model_name="smtproductionreport",
            name="rd_workorder_number",
        ),
        migrations.RemoveField(
            model_name="smtproductionreport",
            name="report_type",
        ),
    ]
