# Generated by Django 5.1.8 on 2025-08-04 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0001_initial"),
        (
            "workorder_reporting",
            "0006_remove_operatorsupplementreport_rd_product_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="smtproductionreport",
            name="process",
            field=models.ForeignKey(
                blank=True,
                help_text="請選擇此次補登的SMT工序",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process.processname",
                verbose_name="工序",
            ),
        ),
        migrations.AlterField(
            model_name="smtproductionreport",
            name="operation",
            field=models.CharField(
                default="",
                help_text="工序名稱（自動從 process 欄位取得）",
                max_length=100,
                verbose_name="工序名稱",
            ),
        ),
    ]
