# Generated by Django 5.1.8 on 2025-08-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder_reporting", "0008_operatorsupplementreport_company_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="smtproductionreport",
            name="company_code",
            field=models.CharField(
                default="",
                help_text="公司代號，用於多公司架構",
                max_length=10,
                verbose_name="公司代號",
            ),
        ),
    ]
