# Generated by Django 5.1.8 on 2025-08-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder_reporting", "0009_smtproductionreport_company_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="smtproductionreport",
            name="report_type",
            field=models.CharField(
                choices=[("normal", "一般SMT報工"), ("rd_sample", "RD樣品報工")],
                default="normal",
                help_text="區分一般SMT報工和RD樣品報工",
                max_length=20,
                verbose_name="報工類型",
            ),
        ),
    ]
