# Generated by Django 5.1.8 on 2025-08-05 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder_reporting", "0010_smtproductionreport_report_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smtproductionreport",
            name="report_type",
        ),
    ]
