# Generated by Django 5.1.8 on 2025-08-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workorder_reporting",
            "0008_operatorsupplementreport_company_code",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="allocated_quantity",
            field=models.IntegerField(
                default=0,
                help_text="系統智能分配的數量",
                verbose_name="分配數量",
            ),
        ),
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="quantity_source",
            field=models.CharField(
                choices=[
                    ("original", "原始數量"),
                    ("allocated", "智能分配"),
                    ("packaging", "包裝工序"),
                ],
                default="original",
                help_text="數量的來源類型",
                max_length=20,
                verbose_name="數量來源",
            ),
        ),
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="allocation_notes",
            field=models.TextField(
                blank=True,
                help_text="記錄分配計算過程和依據",
                verbose_name="分配說明",
            ),
        ),
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="allocation_checked",
            field=models.BooleanField(
                default=False,
                help_text="標記此記錄是否已經過自動分配檢查，避免重複檢查",
                verbose_name="已檢查自動分配",
            ),
        ),
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="allocation_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="記錄此記錄被自動分配檢查的時間",
                null=True,
                verbose_name="分配檢查時間",
            ),
        ),
        migrations.AddField(
            model_name="operatorsupplementreport",
            name="allocation_check_result",
            field=models.CharField(
                choices=[
                    ("not_checked", "未檢查"),
                    ("allocated", "已分配"),
                    ("excluded_packaging", "排除包裝"),
                    ("no_allocation_needed", "無需分配"),
                ],
                default="not_checked",
                help_text="記錄自動分配檢查的結果",
                max_length=20,
                verbose_name="分配檢查結果",
            ),
        ),
    ] 