# Generated by Django 5.1.8 on 2025-08-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder_reporting", "0013_add_missing_completion_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="smtproductionreport",
            name="equipment_operator_name",
            field=models.CharField(
                blank=True,
                help_text="SMT設備的作業員名稱，通常與設備名稱相同",
                max_length=100,
                null=True,
                verbose_name="設備作業員名稱",
            ),
        ),
    ]
