# Generated by Django 5.1.8 on 2025-08-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder_reporting", "0013_add_missing_completion_fields"),
    ]

    operations = []
