# Generated by Django 5.1.8 on 2025-08-07 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder_reporting", "0014_smtproductionreport_break_end_time_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="smtproductionreport",
            table="workorder_smt_supplement_report",
        ),
    ]
