# Generated by Django 5.1.8 on 2025-08-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_reporting', '0015_alter_smtsupplementreport_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SMTSupplementReport',
            new_name='BackupSMTSupplementReport',
        ),
        migrations.RenameModel(
            old_name='SMTRealtimeReport',
            new_name='BackupSMTRealtimeReport',
        ),
        migrations.RenameModel(
            old_name='OperatorRealtimeReport',
            new_name='BackupOperatorRealtimeReport',
        ),
        migrations.RenameModel(
            old_name='OperatorSupplementReport',
            new_name='BackupOperatorSupplementReport',
        ),
    ]
