# Generated by Django 5.1.8 on 2025-08-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder_reporting", "0015_alter_smtproductionreport_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="smtproductionreport",
            table="workorder_smt_report",
        ),
    ]
