# Generated by Django 5.1.8 on 2025-08-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder_reporting", "0016_auto_20250808_1611"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backupoperatorrealtimereport",
            options={
                "ordering": ["-work_date", "-start_time"],
                "verbose_name": "備用的作業員現場報工記錄",
                "verbose_name_plural": "備用的作業員現場報工記錄",
            },
        ),
        migrations.AlterModelOptions(
            name="backupoperatorsupplementreport",
            options={
                "ordering": ["-work_date", "-start_time"],
                "verbose_name": "備用的作業員補登報工記錄",
                "verbose_name_plural": "備用的作業員補登報工記錄",
            },
        ),
        migrations.AlterModelOptions(
            name="backupsmtrealtimereport",
            options={
                "ordering": ["-work_date", "-start_time"],
                "verbose_name": "備用的SMT現場報工記錄",
                "verbose_name_plural": "備用的SMT現場報工記錄",
            },
        ),
        migrations.AlterModelOptions(
            name="backupsmtsupplementreport",
            options={
                "ordering": ["-work_date", "-start_time"],
                "verbose_name": "備用的SMT補登報工記錄",
                "verbose_name_plural": "備用的SMT補登報工記錄",
            },
        ),
        migrations.AlterModelTable(
            name="backupoperatorrealtimereport",
            table="backup_workorder_operator_realtime_report",
        ),
        migrations.AlterModelTable(
            name="backupoperatorsupplementreport",
            table="backup_workorder_operator_supplement_report",
        ),
        migrations.AlterModelTable(
            name="backupsmtrealtimereport",
            table="backup_workorder_smt_realtime_report",
        ),
        migrations.AlterModelTable(
            name="backupsmtsupplementreport",
            table="backup_workorder_smt_supplement_report",
        ),
    ]
