# Generated by Django 5.1.8 on 2025-06-22 01:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=100, verbose_name='作業員名稱')),
                ('equipment_name', models.CharField(max_length=100, verbose_name='設備名稱')),
                ('production_quantity', models.IntegerField(verbose_name='生產數量')),
                ('equipment_usage_rate', models.FloatField(verbose_name='設備使用率 (%)')),
                ('date', models.DateField(verbose_name='日期')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '作業員生產報表數據',
                'verbose_name_plural': '作業員生產報表數據',
            },
        ),
        migrations.CreateModel(
            name='ProductionDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('line', models.CharField(choices=[('SMT1', 'SMT 線 1'), ('SMT2', 'SMT 線 2'), ('SMT3', 'SMT 線 3'), ('TEST', '測試設備')], max_length=50, verbose_name='生產線')),
                ('production_quantity', models.IntegerField(verbose_name='生產數量')),
                ('completed_quantity', models.IntegerField(verbose_name='完成數量')),
                ('completion_rate', models.FloatField(verbose_name='完成率 (%)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '生產日報表數據',
                'verbose_name_plural': '生產日報表數據',
            },
        ),
        migrations.CreateModel(
            name='ReportingOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='用戶')),
                ('action', models.TextField(verbose_name='操作')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='時間戳')),
            ],
            options={
                'verbose_name': '報表操作日誌',
                'verbose_name_plural': '報表操作日誌',
                'default_permissions': (),
            },
        ),
    ]
