# Generated by Django 5.1.8 on 2025-07-30 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("WORK_REPORT", "工作報表"),
                            ("WORKORDER_REPORT", "工單報表"),
                            ("WORK_HOUR_REPORT", "工時報表"),
                        ],
                        max_length=50,
                        verbose_name="報表類型",
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[("EXCEL", "Excel"), ("CSV", "CSV"), ("PDF", "PDF")],
                        max_length=10,
                        verbose_name="匯出格式",
                    ),
                ),
                (
                    "date_range",
                    models.CharField(
                        choices=[
                            ("TODAY", "今日"),
                            ("YESTERDAY", "昨日"),
                            ("THIS_WEEK", "本週"),
                            ("LAST_WEEK", "上週"),
                            ("THIS_MONTH", "本月"),
                            ("LAST_MONTH", "上月"),
                            ("CUSTOM", "自訂範圍"),
                        ],
                        max_length=20,
                        verbose_name="日期範圍",
                    ),
                ),
                (
                    "custom_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="自訂開始日期"
                    ),
                ),
                (
                    "custom_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="自訂結束日期"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="檔案路徑"
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="檔案大小(位元組)"
                    ),
                ),
                (
                    "export_status",
                    models.CharField(
                        default="SUCCESS", max_length=20, verbose_name="匯出狀態"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="錯誤訊息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="匯出時間"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作者",
                    ),
                ),
            ],
            options={
                "verbose_name": "報表匯出日誌",
                "verbose_name_plural": "報表匯出日誌",
                "db_table": "reporting_export_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("WORK_REPORT", "工作報表"),
                            ("WORKORDER_REPORT", "工單報表"),
                            ("WORK_HOUR_REPORT", "工時報表"),
                        ],
                        max_length=50,
                        verbose_name="報表類型",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="報表日期")),
                (
                    "report_period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="報表期間開始"
                    ),
                ),
                (
                    "report_period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="報表期間結束"
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        default="原始報工數據", max_length=100, verbose_name="數據來源"
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        default="無或按工時分配",
                        max_length=100,
                        verbose_name="計算方法",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "created_by",
                    models.CharField(
                        default="系統", max_length=100, verbose_name="建立者"
                    ),
                ),
                (
                    "work_order_no",
                    models.CharField(max_length=100, verbose_name="工單號"),
                ),
                (
                    "product_sn",
                    models.CharField(max_length=100, verbose_name="產品編號"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="產品名稱"),
                ),
                ("total_quantity", models.IntegerField(verbose_name="總數量")),
                (
                    "completed_quantity",
                    models.IntegerField(default=0, verbose_name="完成數量"),
                ),
                (
                    "defect_quantity",
                    models.IntegerField(default=0, verbose_name="不良品數量"),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="開始日期"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="結束日期"),
                ),
                (
                    "planned_duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="計劃工期(天)"
                    ),
                ),
                (
                    "actual_duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="實際工期(天)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "計劃中"),
                            ("IN_PROGRESS", "進行中"),
                            ("COMPLETED", "已完成"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="PLANNED",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
            ],
            options={
                "verbose_name": "工單報表",
                "verbose_name_plural": "工單報表",
                "db_table": "reporting_workorder_report",
                "indexes": [
                    models.Index(
                        fields=["work_order_no"], name="reporting_w_work_or_8c8070_idx"
                    ),
                    models.Index(
                        fields=["product_sn"], name="reporting_w_product_b55cc7_idx"
                    ),
                    models.Index(
                        fields=["status"], name="reporting_w_status_542534_idx"
                    ),
                    models.Index(
                        fields=["start_date"], name="reporting_w_start_d_ec8dae_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkHourReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("WORK_REPORT", "工作報表"),
                            ("WORKORDER_REPORT", "工單報表"),
                            ("WORK_HOUR_REPORT", "工時報表"),
                        ],
                        max_length=50,
                        verbose_name="報表類型",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="報表日期")),
                (
                    "report_period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="報表期間開始"
                    ),
                ),
                (
                    "report_period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="報表期間結束"
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        default="原始報工數據", max_length=100, verbose_name="數據來源"
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        default="無或按工時分配",
                        max_length=100,
                        verbose_name="計算方法",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "created_by",
                    models.CharField(
                        default="系統", max_length=100, verbose_name="建立者"
                    ),
                ),
                (
                    "equipment_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="設備名稱"
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=6, verbose_name="總工時"
                    ),
                ),
                (
                    "normal_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="正常工時",
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="加班工時",
                    ),
                ),
                (
                    "break_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="休息時間",
                    ),
                ),
                (
                    "efficiency_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="效率率(%)",
                    ),
                ),
                (
                    "utilization_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="利用率(%)",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作業員",
                    ),
                ),
            ],
            options={
                "verbose_name": "工時報表",
                "verbose_name_plural": "工時報表",
                "db_table": "reporting_work_hour_report",
                "indexes": [
                    models.Index(
                        fields=["report_date"], name="reporting_w_report__99a976_idx"
                    ),
                    models.Index(
                        fields=["operator"], name="reporting_w_operato_4dd770_idx"
                    ),
                    models.Index(
                        fields=["equipment_name"], name="reporting_w_equipme_b9b7b3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("WORK_REPORT", "工作報表"),
                            ("WORKORDER_REPORT", "工單報表"),
                            ("WORK_HOUR_REPORT", "工時報表"),
                        ],
                        max_length=50,
                        verbose_name="報表類型",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="報表日期")),
                (
                    "report_period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="報表期間開始"
                    ),
                ),
                (
                    "report_period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="報表期間結束"
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        default="原始報工數據", max_length=100, verbose_name="數據來源"
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        default="無或按工時分配",
                        max_length=100,
                        verbose_name="計算方法",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "created_by",
                    models.CharField(
                        default="系統", max_length=100, verbose_name="建立者"
                    ),
                ),
                (
                    "work_order_no",
                    models.CharField(max_length=100, verbose_name="工單號"),
                ),
                (
                    "product_sn",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="產品編號"
                    ),
                ),
                ("process", models.CharField(max_length=100, verbose_name="工序")),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="開始時間"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="結束時間"
                    ),
                ),
                (
                    "work_quantity",
                    models.IntegerField(default=0, verbose_name="工作數量"),
                ),
                (
                    "defect_quantity",
                    models.IntegerField(default=0, verbose_name="不良品數量"),
                ),
                (
                    "abnormal_notes",
                    models.TextField(blank=True, null=True, verbose_name="異常紀錄"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作業員",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作報表",
                "verbose_name_plural": "工作報表",
                "db_table": "reporting_work_report",
                "indexes": [
                    models.Index(
                        fields=["report_date"], name="reporting_w_report__426068_idx"
                    ),
                    models.Index(
                        fields=["operator"], name="reporting_w_operato_0286a3_idx"
                    ),
                    models.Index(
                        fields=["work_order_no"], name="reporting_w_work_or_18e3e5_idx"
                    ),
                    models.Index(
                        fields=["process"], name="reporting_w_process_3c87ed_idx"
                    ),
                ],
            },
        ),
    ]
