# Generated by Django 5.1.8 on 2025-08-17 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="報表名稱")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("weekly", "週報表"),
                            ("monthly", "月報表"),
                            ("quarterly", "季報表"),
                            ("yearly", "年報表"),
                        ],
                        max_length=20,
                        verbose_name="報表類型",
                    ),
                ),
                ("company", models.CharField(max_length=10, verbose_name="公司代號")),
                ("schedule_time", models.TimeField(verbose_name="執行時間")),
                (
                    "schedule_day",
                    models.IntegerField(
                        blank=True,
                        help_text="週報表：週幾(1-7)，月報表：每月幾號(1-31)",
                        null=True,
                        verbose_name="執行日期",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "啟用"), ("inactive", "停用")],
                        default="active",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "email_recipients",
                    models.TextField(
                        blank=True,
                        help_text="多個信箱用逗號分隔",
                        verbose_name="收件人信箱",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "報表排程",
                "verbose_name_plural": "報表排程",
                "db_table": "report_schedule",
            },
        ),
        migrations.CreateModel(
            name="ReportExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="執行時間"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失敗"),
                            ("running", "執行中"),
                        ],
                        max_length=20,
                        verbose_name="執行狀態",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="執行訊息")),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="檔案路徑"
                    ),
                ),
                (
                    "report_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.reportschedule",
                        verbose_name="報表排程",
                    ),
                ),
            ],
            options={
                "verbose_name": "報表執行日誌",
                "verbose_name_plural": "報表執行日誌",
                "db_table": "report_execution_log",
                "ordering": ["-execution_time"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderReportData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workorder_id",
                    models.CharField(max_length=50, verbose_name="工單編號"),
                ),
                ("company", models.CharField(max_length=10, verbose_name="公司代號")),
                ("work_date", models.DateField(verbose_name="工作日期")),
                ("work_week", models.IntegerField(verbose_name="工作週數")),
                ("work_month", models.IntegerField(verbose_name="工作月份")),
                ("work_quarter", models.IntegerField(verbose_name="工作季度")),
                ("work_year", models.IntegerField(verbose_name="工作年度")),
                (
                    "daily_work_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="日工作時數"
                    ),
                ),
                (
                    "weekly_work_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="週工作時數"
                    ),
                ),
                (
                    "monthly_work_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="月工作時數"
                    ),
                ),
                (
                    "operator_count",
                    models.IntegerField(default=1, verbose_name="作業員人數"),
                ),
                (
                    "equipment_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="設備使用時數"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "工單報表資料",
                "verbose_name_plural": "工單報表資料",
                "db_table": "workorder_report_data",
                "indexes": [
                    models.Index(
                        fields=["company", "work_date"],
                        name="workorder_r_company_268463_idx",
                    ),
                    models.Index(
                        fields=["company", "work_year", "work_month"],
                        name="workorder_r_company_f8ae33_idx",
                    ),
                    models.Index(
                        fields=["company", "work_year", "work_quarter"],
                        name="workorder_r_company_1584d0_idx",
                    ),
                    models.Index(
                        fields=["company", "work_year"],
                        name="workorder_r_company_b3176f_idx",
                    ),
                ],
            },
        ),
    ]
