# Generated by Django 5.1.8 on 2025-08-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletedWorkOrderReportData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workorder_id",
                    models.CharField(max_length=100, verbose_name="工單編號"),
                ),
                (
                    "product_code",
                    models.CharField(max_length=100, verbose_name="產品編號"),
                ),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                ("completion_date", models.DateField(verbose_name="完工日期")),
                ("completion_week", models.IntegerField(verbose_name="完工週數")),
                ("completion_month", models.IntegerField(verbose_name="完工月份")),
                ("completion_quarter", models.IntegerField(verbose_name="完工季度")),
                ("completion_year", models.IntegerField(verbose_name="完工年度")),
                ("planned_quantity", models.IntegerField(verbose_name="計劃數量")),
                ("completed_quantity", models.IntegerField(verbose_name="完成數量")),
                (
                    "completion_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="完工率"
                    ),
                ),
                (
                    "total_good_quantity",
                    models.IntegerField(verbose_name="總合格品數量"),
                ),
                (
                    "total_defect_quantity",
                    models.IntegerField(verbose_name="總不良品數量"),
                ),
                (
                    "defect_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="不良率"
                    ),
                ),
                (
                    "total_work_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="總工作時數"
                    ),
                ),
                (
                    "total_overtime_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="總加班時數"
                    ),
                ),
                (
                    "total_all_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="全部總時數"
                    ),
                ),
                (
                    "efficiency_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="效率率"
                    ),
                ),
                (
                    "hourly_output",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="每小時產出"
                    ),
                ),
                (
                    "unique_operators_count",
                    models.IntegerField(verbose_name="參與作業員數"),
                ),
                (
                    "unique_equipment_count",
                    models.IntegerField(verbose_name="使用設備數"),
                ),
                ("total_report_count", models.IntegerField(verbose_name="總報工次數")),
                ("total_processes", models.IntegerField(verbose_name="總工序數")),
                ("completed_processes", models.IntegerField(verbose_name="完成工序數")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "已完工工單報表資料",
                "verbose_name_plural": "已完工工單報表資料",
                "db_table": "completed_workorder_report_data",
                "indexes": [
                    models.Index(
                        fields=["company_code", "completion_date"],
                        name="completed_w_company_411280_idx",
                    ),
                    models.Index(
                        fields=["company_code", "completion_year", "completion_month"],
                        name="completed_w_company_3e8894_idx",
                    ),
                    models.Index(
                        fields=[
                            "company_code",
                            "completion_year",
                            "completion_quarter",
                        ],
                        name="completed_w_company_a3a66e_idx",
                    ),
                    models.Index(
                        fields=["company_code", "completion_year"],
                        name="completed_w_company_df409d_idx",
                    ),
                ],
                "unique_together": {
                    ("workorder_id", "company_code", "completion_date")
                },
            },
        ),
    ]
