# Generated by Django 5.2.6 on 2025-09-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = []
