# Generated by Django 5.2.6 on 2025-09-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workorder_id",
                    models.CharField(max_length=50, verbose_name="工單編號"),
                ),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                (
                    "product_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="產品編號"
                    ),
                ),
                ("error_message", models.TextField(verbose_name="錯誤訊息")),
                (
                    "error_type",
                    models.CharField(max_length=100, verbose_name="錯誤類型"),
                ),
                ("analysis_date", models.DateTimeField(verbose_name="分析時間")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "分析錯誤日誌",
                "verbose_name_plural": "分析錯誤日誌",
                "db_table": "analysis_error_log",
                "ordering": ["-analysis_date"],
                "indexes": [
                    models.Index(
                        fields=["workorder_id"], name="analysis_er_workord_c907d0_idx"
                    ),
                    models.Index(
                        fields=["company_code"], name="analysis_er_company_65598d_idx"
                    ),
                    models.Index(
                        fields=["analysis_date"], name="analysis_er_analysi_bf5ae3_idx"
                    ),
                    models.Index(
                        fields=["error_type"], name="analysis_er_error_t_6a6926_idx"
                    ),
                ],
            },
        ),
    ]
