# Generated by Django 5.2.6 on 2025-09-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportexecutionlog",
            name="file_path",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="檔案路徑"
            ),
        ),
    ]
