# Generated by Django 5.1.8 on 2025-08-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0002_completedworkorderreportdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorProcessCapacityScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator_name",
                    models.CharField(max_length=100, verbose_name="作業員姓名"),
                ),
                (
                    "operator_id",
                    models.CharField(max_length=50, verbose_name="作業員編號"),
                ),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                (
                    "product_code",
                    models.CharField(max_length=50, verbose_name="產品代號"),
                ),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                (
                    "workorder_id",
                    models.CharField(max_length=50, verbose_name="工單編號"),
                ),
                ("work_date", models.DateField(verbose_name="工作日期")),
                (
                    "work_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="工作時數"
                    ),
                ),
                (
                    "standard_capacity_per_hour",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="標準每小時產能"
                    ),
                ),
                (
                    "actual_capacity_per_hour",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="實際每小時產能"
                    ),
                ),
                ("completed_quantity", models.IntegerField(verbose_name="完成數量")),
                (
                    "capacity_ratio",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="產能比率"
                    ),
                ),
                (
                    "capacity_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="產能評分"
                    ),
                ),
                ("grade", models.CharField(max_length=20, verbose_name="等級")),
                (
                    "efficiency_factor",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="效率因子"
                    ),
                ),
                (
                    "learning_curve_factor",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="學習曲線因子"
                    ),
                ),
                (
                    "defect_quantity",
                    models.IntegerField(default=0, verbose_name="不良品數量"),
                ),
                (
                    "defect_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="不良率"
                    ),
                ),
                (
                    "quality_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="品質評分"
                    ),
                ),
                (
                    "supervisor_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=80,
                        max_digits=5,
                        verbose_name="主管評分",
                    ),
                ),
                (
                    "supervisor_comment",
                    models.TextField(blank=True, verbose_name="主管評語"),
                ),
                (
                    "supervisor_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="評分主管"
                    ),
                ),
                (
                    "supervisor_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="評分日期"
                    ),
                ),
                (
                    "is_supervisor_scored",
                    models.BooleanField(default=False, verbose_name="主管是否已評分"),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="總評分"
                    ),
                ),
                (
                    "overall_grade",
                    models.CharField(max_length=20, verbose_name="總體等級"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "作業員工序產能評分",
                "verbose_name_plural": "作業員工序產能評分",
                "db_table": "reporting_operator_process_capacity_score",
                "indexes": [
                    models.Index(
                        fields=["company_code", "work_date"],
                        name="reporting_o_company_51ec9d_idx",
                    ),
                    models.Index(
                        fields=["operator_id", "work_date"],
                        name="reporting_o_operato_eef1c7_idx",
                    ),
                    models.Index(
                        fields=["process_name", "work_date"],
                        name="reporting_o_process_4d973e_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "operator_id",
                        "company_code",
                        "product_code",
                        "process_name",
                        "workorder_id",
                        "work_date",
                    )
                },
            },
        ),
    ]
