# Generated by Django 5.2.6 on 2025-09-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0002_fix_file_path_null_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportschedule",
            name="interval_minutes",
            field=models.IntegerField(
                blank=True,
                help_text="資料同步：每多少分鐘執行一次",
                null=True,
                verbose_name="執行間隔（分鐘）",
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="is_interval_schedule",
            field=models.BooleanField(
                default=False,
                help_text="勾選表示使用間隔執行，否則使用固定時間",
                verbose_name="是否為間隔排程",
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="schedule_time",
            field=models.TimeField(
                blank=True,
                help_text="固定時間執行時使用",
                null=True,
                verbose_name="執行時間",
            ),
        ),
    ]
