# Generated by Django 5.2.6 on 2025-09-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0002_auto_20250910_1046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportexecutionlog",
            name="report_schedule_name",
            field=models.CharField(max_length=200, verbose_name="報表排程名稱"),
        ),
    ]
