# Generated by Django 5.1.8 on 2025-07-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0002_alter_operatorperformance_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="productiondailyreport",
            name="efficiency_rate",
            field=models.FloatField(default=0.0, verbose_name="效率 (%)"),
        ),
        migrations.AddField(
            model_name="productiondailyreport",
            name="equipment_name",
            field=models.CharField(
                default="未分配設備", max_length=100, verbose_name="設備名稱"
            ),
        ),
        migrations.AddField(
            model_name="productiondailyreport",
            name="operator_name",
            field=models.CharField(
                default="未指定作業員", max_length=100, verbose_name="作業員姓名"
            ),
        ),
        migrations.AddField(
            model_name="productiondailyreport",
            name="work_hours",
            field=models.FloatField(default=0.0, verbose_name="工作時數"),
        ),
        migrations.AlterUniqueTogether(
            name="productiondailyreport",
            unique_together={("date", "operator_name", "equipment_name")},
        ),
    ]
