# Generated by Django 5.2.6 on 2025-09-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0003_add_interval_schedule_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportschedule",
            name="interval_minutes",
        ),
        migrations.RemoveField(
            model_name="reportschedule",
            name="is_interval_schedule",
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="schedule_time",
            field=models.TimeField(verbose_name="執行時間"),
        ),
    ]
