# Generated by Django 5.1.8 on 2025-08-17 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0003_operatorprocesscapacityscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatorprocesscapacityscore",
            name="is_period_closed",
            field=models.BooleanField(default=False, verbose_name="週期是否已關閉"),
        ),
        migrations.AddField(
            model_name="operatorprocesscapacityscore",
            name="period_closed_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="週期關閉日期"
            ),
        ),
        migrations.AddField(
            model_name="operatorprocesscapacityscore",
            name="period_end_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="週期結束日期"
            ),
        ),
        migrations.AddField(
            model_name="operatorprocesscapacityscore",
            name="period_start_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="週期開始日期"
            ),
        ),
        migrations.AddField(
            model_name="operatorprocesscapacityscore",
            name="score_period",
            field=models.CharField(
                choices=[
                    ("monthly", "月評分"),
                    ("quarterly", "季評分"),
                    ("yearly", "年評分"),
                ],
                default="monthly",
                max_length=20,
                verbose_name="評分週期",
            ),
        ),
    ]
