# Generated by Django 5.1.8 on 2025-07-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0003_productiondailyreport_efficiency_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSyncSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("smt", "SMT生產報表"),
                            ("operator", "作業員生產報表"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="報表類型",
                    ),
                ),
                (
                    "sync_interval_hours",
                    models.IntegerField(
                        default=24,
                        help_text="設定自動同步的間隔時間，單位為小時",
                        verbose_name="同步間隔（小時）",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="啟用自動同步"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "報表同步設定",
                "verbose_name_plural": "報表同步設定",
            },
        ),
    ]
