# Generated by Django 5.1.8 on 2025-08-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0004_operatorprocesscapacityscore_is_period_closed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderreportdata",
            name="operator_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="作業員姓名"
            ),
        ),
        migrations.AddIndex(
            model_name="workorderreportdata",
            index=models.Index(
                fields=["operator_name", "work_date"],
                name="workorder_r_operato_421f5c_idx",
            ),
        ),
    ]
