# Generated by Django 5.2.6 on 2025-09-19 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0004_remove_reportschedule_interval_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportschedule",
            name="sync_execution_type",
            field=models.CharField(
                choices=[("interval", "間隔執行"), ("fixed_time", "固定時間")],
                default="interval",
                help_text="資料同步的執行方式",
                max_length=20,
                verbose_name="執行方式",
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="sync_fixed_time",
            field=models.TimeField(
                blank=True,
                help_text="每天固定時間執行資料同步",
                null=True,
                verbose_name="固定同步時間",
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="sync_interval_minutes",
            field=models.IntegerField(
                default=60,
                help_text="每多少分鐘執行一次資料同步",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1440),
                ],
                verbose_name="同步間隔（分鐘）",
            ),
        ),
    ]
