# Generated by Django 5.1.8 on 2025-08-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0004_operatorprocesscapacityscore_is_period_closed_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="completedworkorderreportdata",
            unique_together={
                ("workorder_id", "company_code", "product_code", "completion_date")
            },
        ),
    ]
