# Generated by Django 5.1.8 on 2025-08-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0005_alter_completedworkorderreportdata_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="completedworkorderreportdata",
            unique_together={("workorder_id", "company_code", "completion_date")},
        ),
    ]
