# Generated by Django 5.1.8 on 2025-08-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0005_workorderreportdata_operator_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderreportdata",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="結束時間"),
        ),
        migrations.AddField(
            model_name="workorderreportdata",
            name="overtime_hours",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="加班時數"
            ),
        ),
        migrations.AddField(
            model_name="workorderreportdata",
            name="process_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="工序名稱"
            ),
        ),
        migrations.AddField(
            model_name="workorderreportdata",
            name="product_code",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="產品編號"
            ),
        ),
        migrations.AddField(
            model_name="workorderreportdata",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="開始時間"),
        ),
        migrations.AddField(
            model_name="workorderreportdata",
            name="total_hours",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="合計時數"
            ),
        ),
        migrations.AddField(
            model_name="workorderreportdata",
            name="work_hours",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="工作時數"
            ),
        ),
    ]
