# Generated by Django 5.1.8 on 2025-07-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0006_operatorperformance_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatorperformance",
            name="process_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="工序名稱"
            ),
        ),
        migrations.AddField(
            model_name="productiondailyreport",
            name="process_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="工序名稱"
            ),
        ),
    ]
