# Generated by Django 5.1.8 on 2025-08-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0006_workorderreportdata_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportschedule",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("weekly", "週報表"),
                    ("monthly", "月報表"),
                    ("quarterly", "季報表"),
                    ("yearly", "年報表"),
                    ("data_sync", "資料同步"),
                ],
                max_length=20,
                verbose_name="報表類型",
            ),
        ),
    ]
