# Generated by Django 5.2.6 on 2025-09-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0002_auto_20250920_1653"),
        ("reporting", "0006_alter_reportschedule_report_type"),
    ]

    operations = []
