# Generated by Django 5.1.8 on 2025-07-05 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0007_operatorperformance_process_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorDailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "operator_name",
                    models.CharField(max_length=100, verbose_name="作業員姓名"),
                ),
                (
                    "operator_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="作業員編號"
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=100, verbose_name="部門"),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[("day", "日班"), ("night", "夜班"), ("other", "其他")],
                        default="day",
                        max_length=20,
                        verbose_name="班別",
                    ),
                ),
                (
                    "work_order_count",
                    models.IntegerField(default=0, verbose_name="處理工單數"),
                ),
                (
                    "total_quantity",
                    models.IntegerField(default=0, verbose_name="總生產數量"),
                ),
                (
                    "completed_quantity",
                    models.IntegerField(default=0, verbose_name="完成數量"),
                ),
                (
                    "defect_quantity",
                    models.IntegerField(default=0, verbose_name="不良品數量"),
                ),
                (
                    "rework_quantity",
                    models.IntegerField(default=0, verbose_name="重工數量"),
                ),
                ("work_hours", models.FloatField(default=0.0, verbose_name="工作時數")),
                (
                    "overtime_hours",
                    models.FloatField(default=0.0, verbose_name="加班時數"),
                ),
                ("break_time", models.FloatField(default=0.0, verbose_name="休息時數")),
                (
                    "actual_work_hours",
                    models.FloatField(default=0.0, verbose_name="實際工作時數"),
                ),
                (
                    "efficiency_rate",
                    models.FloatField(default=0.0, verbose_name="效率 (%)"),
                ),
                (
                    "completion_rate",
                    models.FloatField(default=0.0, verbose_name="完成率 (%)"),
                ),
                (
                    "quality_rate",
                    models.FloatField(default=0.0, verbose_name="品質率 (%)"),
                ),
                (
                    "productivity_rate",
                    models.FloatField(default=0.0, verbose_name="生產力 (件/小時)"),
                ),
                (
                    "equipment_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="使用設備"
                    ),
                ),
                (
                    "equipment_usage_rate",
                    models.FloatField(default=0.0, verbose_name="設備使用率 (%)"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備註")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="創建時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "作業員日報表",
                "verbose_name_plural": "作業員日報表",
                "ordering": ["-date", "operator_name"],
                "unique_together": {("date", "operator_name")},
            },
        ),
        migrations.CreateModel(
            name="OperatorMonthlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年份")),
                ("month", models.IntegerField(verbose_name="月份")),
                (
                    "operator_name",
                    models.CharField(max_length=100, verbose_name="作業員姓名"),
                ),
                (
                    "operator_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="作業員編號"
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=100, verbose_name="部門"),
                ),
                (
                    "total_work_days",
                    models.IntegerField(default=0, verbose_name="總工作天數"),
                ),
                (
                    "total_work_hours",
                    models.FloatField(default=0.0, verbose_name="總工作時數"),
                ),
                (
                    "total_overtime_hours",
                    models.FloatField(default=0.0, verbose_name="總加班時數"),
                ),
                (
                    "total_work_orders",
                    models.IntegerField(default=0, verbose_name="總工單數"),
                ),
                (
                    "total_quantity",
                    models.IntegerField(default=0, verbose_name="總生產數量"),
                ),
                (
                    "total_completed",
                    models.IntegerField(default=0, verbose_name="總完成數量"),
                ),
                (
                    "total_defects",
                    models.IntegerField(default=0, verbose_name="總不良品數"),
                ),
                (
                    "total_rework",
                    models.IntegerField(default=0, verbose_name="總重工數"),
                ),
                (
                    "avg_efficiency",
                    models.FloatField(default=0.0, verbose_name="平均效率 (%)"),
                ),
                (
                    "avg_completion_rate",
                    models.FloatField(default=0.0, verbose_name="平均完成率 (%)"),
                ),
                (
                    "avg_quality_rate",
                    models.FloatField(default=0.0, verbose_name="平均品質率 (%)"),
                ),
                (
                    "avg_productivity",
                    models.FloatField(default=0.0, verbose_name="平均生產力 (件/小時)"),
                ),
                (
                    "best_daily_quantity",
                    models.IntegerField(default=0, verbose_name="最佳日產量"),
                ),
                (
                    "best_daily_efficiency",
                    models.FloatField(default=0.0, verbose_name="最佳日效率 (%)"),
                ),
                (
                    "attendance_days",
                    models.IntegerField(default=0, verbose_name="出勤天數"),
                ),
                ("late_days", models.IntegerField(default=0, verbose_name="遲到天數")),
                (
                    "absent_days",
                    models.IntegerField(default=0, verbose_name="缺勤天數"),
                ),
                (
                    "attendance_rate",
                    models.FloatField(default=0.0, verbose_name="出勤率 (%)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="創建時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "作業員月報表",
                "verbose_name_plural": "作業員月報表",
                "ordering": ["-year", "-month", "operator_name"],
                "unique_together": {("year", "month", "operator_name")},
            },
        ),
        migrations.CreateModel(
            name="OperatorScoreReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="評分日期")),
                (
                    "operator_name",
                    models.CharField(max_length=100, verbose_name="作業員姓名"),
                ),
                (
                    "operator_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="作業員編號"
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=100, verbose_name="部門"),
                ),
                (
                    "productivity_score",
                    models.FloatField(default=0.0, verbose_name="生產力評分 (30%)"),
                ),
                (
                    "quality_score",
                    models.FloatField(default=0.0, verbose_name="品質評分 (25%)"),
                ),
                (
                    "efficiency_score",
                    models.FloatField(default=0.0, verbose_name="效率評分 (20%)"),
                ),
                (
                    "attendance_score",
                    models.FloatField(default=0.0, verbose_name="出勤評分 (15%)"),
                ),
                (
                    "teamwork_score",
                    models.FloatField(default=0.0, verbose_name="團隊合作評分 (10%)"),
                ),
                (
                    "total_score",
                    models.FloatField(default=0.0, verbose_name="綜合評分"),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A級 (90-100分)"),
                            ("B", "B級 (80-89分)"),
                            ("C", "C級 (70-79分)"),
                            ("D", "D級 (60-69分)"),
                            ("E", "E級 (60分以下)"),
                        ],
                        max_length=10,
                        verbose_name="等級",
                    ),
                ),
                (
                    "productivity_comment",
                    models.TextField(blank=True, verbose_name="生產力評語"),
                ),
                (
                    "quality_comment",
                    models.TextField(blank=True, verbose_name="品質評語"),
                ),
                (
                    "efficiency_comment",
                    models.TextField(blank=True, verbose_name="效率評語"),
                ),
                (
                    "attendance_comment",
                    models.TextField(blank=True, verbose_name="出勤評語"),
                ),
                (
                    "teamwork_comment",
                    models.TextField(blank=True, verbose_name="團隊合作評語"),
                ),
                (
                    "overall_comment",
                    models.TextField(blank=True, verbose_name="綜合評語"),
                ),
                (
                    "evaluator",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="評分人員"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="創建時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "作業員評分報表",
                "verbose_name_plural": "作業員評分報表",
                "ordering": ["-date", "operator_name"],
                "unique_together": {("date", "operator_name")},
            },
        ),
    ]
