# Generated by Django 5.1.8 on 2025-08-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0008_alter_reportschedule_report_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportschedule",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("data_sync", "資料同步"),
                    ("previous_workday", "前一個工作日報表"),
                    ("current_week", "本週報表"),
                    ("previous_week", "上週報表"),
                    ("current_month", "本月報表"),
                    ("previous_month", "上月報表"),
                    ("current_quarter", "本季報表"),
                    ("previous_quarter", "上季報表"),
                    ("current_year", "本年報表"),
                    ("previous_year", "上年報表"),
                ],
                max_length=20,
                verbose_name="報表類型",
            ),
        ),
    ]
