# Generated by Django 5.1.8 on 2025-07-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0008_operatordailyreport_operatormonthlyreport_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operatorscorereport",
            name="attendance_comment",
        ),
        migrations.RemoveField(
            model_name="operatorscorereport",
            name="attendance_score",
        ),
        migrations.AlterField(
            model_name="operatorscorereport",
            name="efficiency_score",
            field=models.FloatField(default=0.0, verbose_name="效率評分 (25%)"),
        ),
        migrations.AlterField(
            model_name="operatorscorereport",
            name="teamwork_score",
            field=models.FloatField(default=0.0, verbose_name="團隊合作評分 (20%)"),
        ),
    ]
