# Generated by Django 5.1.8 on 2025-08-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0009_alter_reportschedule_report_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportschedule",
            name="file_format",
            field=models.CharField(
                choices=[
                    ("html", "HTML格式"),
                    ("excel", "Excel格式"),
                    ("both", "HTML + Excel格式"),
                ],
                default="html",
                max_length=20,
                verbose_name="檔案格式",
            ),
        ),
    ]
