# Generated by Django 5.1.8 on 2025-07-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0009_remove_operatorscorereport_attendance_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatorscorereport",
            name="actual_productivity",
            field=models.FloatField(default=0.0, verbose_name="實際生產力 (件/小時)"),
        ),
        migrations.AddField(
            model_name="operatorscorereport",
            name="auto_calculate_productivity",
            field=models.BooleanField(default=True, verbose_name="自動計算生產力評分"),
        ),
        migrations.AddField(
            model_name="operatorscorereport",
            name="productivity_ratio",
            field=models.FloatField(default=0.0, verbose_name="生產力達成率 (%)"),
        ),
        migrations.AddField(
            model_name="operatorscorereport",
            name="standard_productivity",
            field=models.FloatField(default=0.0, verbose_name="標準生產力 (件/小時)"),
        ),
    ]
