# Generated by Django 5.1.8 on 2025-08-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0010_reportschedule_file_format"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletedWorkOrderAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workorder_id",
                    models.CharField(max_length=50, verbose_name="工單編號"),
                ),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "product_code",
                    models.CharField(max_length=100, verbose_name="產品編號"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="產品名稱"),
                ),
                ("order_quantity", models.IntegerField(verbose_name="訂單數量")),
                ("first_record_date", models.DateField(verbose_name="第一筆紀錄日期")),
                ("last_record_date", models.DateField(verbose_name="最後一筆紀錄日期")),
                (
                    "total_execution_days",
                    models.IntegerField(verbose_name="總執行天數"),
                ),
                (
                    "total_work_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="總工作時數"
                    ),
                ),
                (
                    "total_overtime_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="總加班時數"
                    ),
                ),
                (
                    "average_daily_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="平均每日工作時數"
                    ),
                ),
                (
                    "efficiency_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="效率比率"
                    ),
                ),
                ("total_processes", models.IntegerField(verbose_name="總工序數")),
                ("unique_processes", models.IntegerField(verbose_name="不重複工序數")),
                ("total_operators", models.IntegerField(verbose_name="參與作業員數")),
                ("completion_date", models.DateField(verbose_name="完工日期")),
                (
                    "completion_status",
                    models.CharField(max_length=20, verbose_name="完工狀態"),
                ),
                (
                    "process_details",
                    models.JSONField(
                        help_text="包含每個工序的執行順序、時間、作業員等詳細資訊",
                        verbose_name="工序詳細資料",
                    ),
                ),
                (
                    "operator_details",
                    models.JSONField(
                        help_text="包含每個作業員的工作時數、工序等資訊",
                        verbose_name="作業員詳細資料",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "已完工工單分析",
                "verbose_name_plural": "已完工工單分析",
                "db_table": "completed_workorder_analysis",
                "indexes": [
                    models.Index(
                        fields=["company_code", "completion_date"],
                        name="completed_w_company_330bcb_idx",
                    ),
                    models.Index(
                        fields=["completion_date"],
                        name="completed_w_complet_881df8_idx",
                    ),
                    models.Index(
                        fields=["workorder_id"], name="completed_w_workord_3930bd_idx"
                    ),
                ],
                "unique_together": {("workorder_id", "company_code")},
            },
        ),
    ]
