# Generated by Django 5.1.8 on 2025-07-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0010_operatorscorereport_actual_productivity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operatordailyreport",
            name="operator_id",
        ),
        migrations.RemoveField(
            model_name="operatordailyreport",
            name="rework_quantity",
        ),
        migrations.RemoveField(
            model_name="operatordailyreport",
            name="shift",
        ),
        migrations.RemoveField(
            model_name="operatormonthlyreport",
            name="operator_id",
        ),
        migrations.RemoveField(
            model_name="operatormonthlyreport",
            name="total_rework",
        ),
        migrations.RemoveField(
            model_name="operatorscorereport",
            name="operator_id",
        ),
    ]
