# Generated by Django 5.1.8 on 2025-08-26 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0011_add_completed_workorder_analysis"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompletedWorkOrderReportData",
        ),
    ]
