# Generated by Django 5.1.8 on 2025-07-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0012_delete_operatordailyreport_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManufacturingWorkHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operator", models.CharField(max_length=50, verbose_name="作業員")),
                ("company", models.CharField(max_length=50, verbose_name="公司別")),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "start_time",
                    models.CharField(max_length=10, verbose_name="開始時間"),
                ),
                ("end_time", models.CharField(max_length=10, verbose_name="完成時間")),
                (
                    "order_number",
                    models.CharField(max_length=50, verbose_name="製令號碼"),
                ),
                (
                    "equipment_name",
                    models.CharField(max_length=100, verbose_name="機種名稱"),
                ),
                (
                    "work_content",
                    models.CharField(max_length=100, verbose_name="工作內容"),
                ),
                ("good_qty", models.IntegerField(verbose_name="良品數量（只填數字）")),
                (
                    "defect_qty",
                    models.IntegerField(verbose_name="不良品數量（沒有請填0）"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "製造工時單",
                "verbose_name_plural": "製造工時單",
            },
        ),
    ]
