# Generated by Django 5.1.8 on 2025-08-26 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0013_update_completed_workorder_analysis_unique_constraint"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="completedworkorderanalysis",
            unique_together={("workorder_id", "company_code")},
        ),
    ]
