# Generated by Django 5.1.8 on 2025-07-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0013_manufacturingworkhour"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComprehensiveAnalysisReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "日報表"),
                            ("weekly", "週報表"),
                            ("monthly", "月報表"),
                            ("custom", "自訂期間報表"),
                        ],
                        max_length=20,
                        verbose_name="報表類型",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="報表日期")),
                ("report_period_start", models.DateField(verbose_name="報表期間開始")),
                ("report_period_end", models.DateField(verbose_name="報表期間結束")),
                (
                    "data_source",
                    models.CharField(
                        help_text="數據來源模組名稱",
                        max_length=50,
                        verbose_name="數據來源",
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        help_text="統計數據的計算邏輯",
                        max_length=50,
                        verbose_name="計算方法",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("created_by", models.CharField(max_length=100, verbose_name="建立者")),
                (
                    "total_production_quantity",
                    models.IntegerField(verbose_name="總生產數量"),
                ),
                ("total_work_hours", models.FloatField(verbose_name="總工作時數")),
                ("overall_efficiency", models.FloatField(verbose_name="整體效率 (%)")),
                (
                    "capacity_utilization",
                    models.FloatField(verbose_name="產能利用率 (%)"),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="材料成本",
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="人工成本",
                    ),
                ),
                (
                    "overhead_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="間接成本",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="總成本",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="單位成本",
                    ),
                ),
                ("overall_yield_rate", models.FloatField(verbose_name="整體良率 (%)")),
                ("quality_cost_rate", models.FloatField(verbose_name="品質成本率 (%)")),
                (
                    "on_time_delivery_rate",
                    models.FloatField(verbose_name="準時交貨率 (%)"),
                ),
                ("average_lead_time", models.FloatField(verbose_name="平均交期 (天)")),
                ("production_score", models.FloatField(verbose_name="生產評分")),
                ("quality_score", models.FloatField(verbose_name="品質評分")),
                ("cost_score", models.FloatField(verbose_name="成本評分")),
                ("delivery_score", models.FloatField(verbose_name="交期評分")),
                ("overall_score", models.FloatField(verbose_name="綜合評分")),
                (
                    "key_improvements",
                    models.JSONField(default=list, verbose_name="關鍵改善項目"),
                ),
                ("action_plans", models.TextField(blank=True, verbose_name="行動計劃")),
            ],
            options={
                "verbose_name": "綜合分析報表",
                "verbose_name_plural": "綜合分析報表",
                "db_table": "reporting_comprehensive_analysis_report",
                "unique_together": {("report_type", "report_date")},
            },
        ),
        migrations.CreateModel(
            name="EquipmentEfficiencyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "日報表"),
                            ("weekly", "週報表"),
                            ("monthly", "月報表"),
                            ("custom", "自訂期間報表"),
                        ],
                        max_length=20,
                        verbose_name="報表類型",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="報表日期")),
                ("report_period_start", models.DateField(verbose_name="報表期間開始")),
                ("report_period_end", models.DateField(verbose_name="報表期間結束")),
                (
                    "data_source",
                    models.CharField(
                        help_text="數據來源模組名稱",
                        max_length=50,
                        verbose_name="數據來源",
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        help_text="統計數據的計算邏輯",
                        max_length=50,
                        verbose_name="計算方法",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("created_by", models.CharField(max_length=100, verbose_name="建立者")),
                (
                    "equipment_name",
                    models.CharField(max_length=100, verbose_name="設備名稱"),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("smt", "SMT設備"),
                            ("general", "一般設備"),
                            ("test", "測試設備"),
                        ],
                        max_length=10,
                        verbose_name="設備類型",
                    ),
                ),
                (
                    "equipment_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="設備型號"
                    ),
                ),
                (
                    "production_line",
                    models.CharField(blank=True, max_length=50, verbose_name="生產線"),
                ),
                ("total_operation_hours", models.FloatField(verbose_name="總運作時數")),
                (
                    "actual_operation_hours",
                    models.FloatField(verbose_name="實際運作時數"),
                ),
                ("idle_hours", models.FloatField(verbose_name="閒置時數")),
                ("maintenance_hours", models.FloatField(verbose_name="維護時數")),
                ("availability_rate", models.FloatField(verbose_name="可用率 (%)")),
                ("performance_rate", models.FloatField(verbose_name="性能率 (%)")),
                ("quality_rate", models.FloatField(verbose_name="品質率 (%)")),
                ("oee_rate", models.FloatField(verbose_name="整體設備效率 (OEE) (%)")),
                ("total_output", models.IntegerField(verbose_name="總產出")),
                (
                    "defect_output",
                    models.IntegerField(default=0, verbose_name="不良品產出"),
                ),
                ("yield_rate", models.FloatField(verbose_name="良率 (%)")),
                ("throughput_rate", models.FloatField(verbose_name="產能利用率 (%)")),
                (
                    "maintenance_count",
                    models.IntegerField(default=0, verbose_name="維護次數"),
                ),
                (
                    "breakdown_count",
                    models.IntegerField(default=0, verbose_name="故障次數"),
                ),
                (
                    "mttr_hours",
                    models.FloatField(default=0.0, verbose_name="平均修復時間 (小時)"),
                ),
                (
                    "mtbf_hours",
                    models.FloatField(default=0.0, verbose_name="平均故障間隔 (小時)"),
                ),
                (
                    "energy_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="能源成本",
                    ),
                ),
                (
                    "maintenance_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="維護成本",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="總成本",
                    ),
                ),
            ],
            options={
                "verbose_name": "設備效率報表",
                "verbose_name_plural": "設備效率報表",
                "db_table": "reporting_equipment_efficiency_report",
                "unique_together": {("report_type", "report_date", "equipment_name")},
            },
        ),
        migrations.CreateModel(
            name="PersonnelPerformanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "日報表"),
                            ("weekly", "週報表"),
                            ("monthly", "月報表"),
                            ("custom", "自訂期間報表"),
                        ],
                        max_length=20,
                        verbose_name="報表類型",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="報表日期")),
                ("report_period_start", models.DateField(verbose_name="報表期間開始")),
                ("report_period_end", models.DateField(verbose_name="報表期間結束")),
                (
                    "data_source",
                    models.CharField(
                        help_text="數據來源模組名稱",
                        max_length=50,
                        verbose_name="數據來源",
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        help_text="統計數據的計算邏輯",
                        max_length=50,
                        verbose_name="計算方法",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("created_by", models.CharField(max_length=100, verbose_name="建立者")),
                (
                    "personnel_name",
                    models.CharField(max_length=100, verbose_name="人員姓名"),
                ),
                (
                    "personnel_type",
                    models.CharField(
                        choices=[
                            ("operator", "作業員"),
                            ("supervisor", "主管"),
                            ("team", "團隊"),
                        ],
                        max_length=10,
                        verbose_name="人員類型",
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=100, verbose_name="部門"),
                ),
                (
                    "position",
                    models.CharField(blank=True, max_length=100, verbose_name="職位"),
                ),
                ("total_work_hours", models.FloatField(verbose_name="總工作時數")),
                (
                    "overtime_hours",
                    models.FloatField(default=0.0, verbose_name="加班時數"),
                ),
                ("work_days", models.IntegerField(verbose_name="工作天數")),
                ("attendance_rate", models.FloatField(verbose_name="出勤率 (%)")),
                (
                    "total_completed_quantity",
                    models.IntegerField(verbose_name="總完成數量"),
                ),
                (
                    "total_defect_quantity",
                    models.IntegerField(default=0, verbose_name="總不良品數量"),
                ),
                (
                    "average_efficiency",
                    models.FloatField(verbose_name="平均效率 (件/小時)"),
                ),
                ("productivity_score", models.FloatField(verbose_name="生產力評分")),
                ("quality_score", models.FloatField(verbose_name="品質評分")),
                ("attendance_score", models.FloatField(verbose_name="出勤評分")),
                ("overall_score", models.FloatField(verbose_name="綜合評分")),
                (
                    "completed_workorders",
                    models.IntegerField(verbose_name="完成工單數"),
                ),
                ("total_workorders", models.IntegerField(verbose_name="總工單數")),
                (
                    "workorder_completion_rate",
                    models.FloatField(verbose_name="工單完成率 (%)"),
                ),
                (
                    "abnormal_count",
                    models.IntegerField(default=0, verbose_name="異常次數"),
                ),
                (
                    "abnormal_hours",
                    models.FloatField(default=0.0, verbose_name="異常時數"),
                ),
            ],
            options={
                "verbose_name": "人員績效報表",
                "verbose_name_plural": "人員績效報表",
                "db_table": "reporting_personnel_performance_report",
                "unique_together": {("report_type", "report_date", "personnel_name")},
            },
        ),
        migrations.CreateModel(
            name="QualityAnalysisReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "日報表"),
                            ("weekly", "週報表"),
                            ("monthly", "月報表"),
                            ("custom", "自訂期間報表"),
                        ],
                        max_length=20,
                        verbose_name="報表類型",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="報表日期")),
                ("report_period_start", models.DateField(verbose_name="報表期間開始")),
                ("report_period_end", models.DateField(verbose_name="報表期間結束")),
                (
                    "data_source",
                    models.CharField(
                        help_text="數據來源模組名稱",
                        max_length=50,
                        verbose_name="數據來源",
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        help_text="統計數據的計算邏輯",
                        max_length=50,
                        verbose_name="計算方法",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("created_by", models.CharField(max_length=100, verbose_name="建立者")),
                ("total_inspected", models.IntegerField(verbose_name="總檢驗數量")),
                ("passed_quantity", models.IntegerField(verbose_name="合格數量")),
                ("failed_quantity", models.IntegerField(verbose_name="不合格數量")),
                ("yield_rate", models.FloatField(verbose_name="良率 (%)")),
                (
                    "defect_categories",
                    models.JSONField(default=dict, verbose_name="不良品分類統計"),
                ),
                (
                    "top_defect_types",
                    models.JSONField(default=list, verbose_name="主要不良品類型"),
                ),
                (
                    "customer_complaints",
                    models.IntegerField(default=0, verbose_name="客戶投訴數"),
                ),
                ("return_rate", models.FloatField(verbose_name="退貨率 (%)")),
                (
                    "quality_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="品質成本",
                    ),
                ),
                (
                    "quality_trend",
                    models.JSONField(default=list, verbose_name="品質趨勢數據"),
                ),
                (
                    "improvement_suggestions",
                    models.TextField(blank=True, verbose_name="改善建議"),
                ),
            ],
            options={
                "verbose_name": "品質分析報表",
                "verbose_name_plural": "品質分析報表",
                "db_table": "reporting_quality_analysis_report",
                "unique_together": {("report_type", "report_date")},
            },
        ),
        migrations.CreateModel(
            name="WorkOrderProductReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "日報表"),
                            ("weekly", "週報表"),
                            ("monthly", "月報表"),
                            ("custom", "自訂期間報表"),
                        ],
                        max_length=20,
                        verbose_name="報表類型",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="報表日期")),
                ("report_period_start", models.DateField(verbose_name="報表期間開始")),
                ("report_period_end", models.DateField(verbose_name="報表期間結束")),
                (
                    "data_source",
                    models.CharField(
                        help_text="數據來源模組名稱",
                        max_length=50,
                        verbose_name="數據來源",
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        help_text="統計數據的計算邏輯",
                        max_length=50,
                        verbose_name="計算方法",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("created_by", models.CharField(max_length=100, verbose_name="建立者")),
                (
                    "workorder_number",
                    models.CharField(max_length=100, verbose_name="工單號碼"),
                ),
                (
                    "product_code",
                    models.CharField(max_length=100, verbose_name="產品編號"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="產品名稱"),
                ),
                ("planned_quantity", models.IntegerField(verbose_name="計劃數量")),
                ("planned_start_date", models.DateField(verbose_name="計劃開始日期")),
                ("planned_end_date", models.DateField(verbose_name="計劃完成日期")),
                (
                    "completed_quantity",
                    models.IntegerField(verbose_name="實際完成數量"),
                ),
                ("completion_rate", models.FloatField(verbose_name="完成率 (%)")),
                (
                    "actual_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="實際開始日期"
                    ),
                ),
                (
                    "actual_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="實際完成日期"
                    ),
                ),
                (
                    "assigned_operators",
                    models.TextField(blank=True, verbose_name="作業員清單"),
                ),
                ("total_work_hours", models.FloatField(verbose_name="總工作時數")),
                (
                    "assigned_equipment",
                    models.TextField(blank=True, verbose_name="設備清單"),
                ),
                (
                    "equipment_usage_rate",
                    models.FloatField(verbose_name="設備使用率 (%)"),
                ),
                (
                    "defect_quantity",
                    models.IntegerField(default=0, verbose_name="不良品數量"),
                ),
                ("yield_rate", models.FloatField(verbose_name="良率 (%)")),
                (
                    "quality_score",
                    models.FloatField(default=0.0, verbose_name="品質評分"),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="材料成本",
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="人工成本",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="總成本",
                    ),
                ),
            ],
            options={
                "verbose_name": "工單機種報表",
                "verbose_name_plural": "工單機種報表",
                "db_table": "reporting_work_order_product_report",
                "unique_together": {("report_type", "report_date", "workorder_number")},
            },
        ),
        migrations.CreateModel(
            name="WorkTimeReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "日報表"),
                            ("weekly", "週報表"),
                            ("monthly", "月報表"),
                            ("custom", "自訂期間報表"),
                        ],
                        max_length=20,
                        verbose_name="報表類型",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="報表日期")),
                ("report_period_start", models.DateField(verbose_name="報表期間開始")),
                ("report_period_end", models.DateField(verbose_name="報表期間結束")),
                (
                    "data_source",
                    models.CharField(
                        help_text="數據來源模組名稱",
                        max_length=50,
                        verbose_name="數據來源",
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        help_text="統計數據的計算邏輯",
                        max_length=50,
                        verbose_name="計算方法",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("created_by", models.CharField(max_length=100, verbose_name="建立者")),
                (
                    "worker_name",
                    models.CharField(max_length=100, verbose_name="作業員/設備名稱"),
                ),
                (
                    "worker_type",
                    models.CharField(
                        choices=[
                            ("operator", "作業員"),
                            ("smt", "SMT設備"),
                            ("general", "一般設備"),
                        ],
                        max_length=10,
                        verbose_name="工作人員類型",
                    ),
                ),
                (
                    "workorder_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="工單號碼"
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="產品編號"
                    ),
                ),
                (
                    "process_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="工序名稱"
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="開始時間"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="結束時間"),
                ),
                ("total_work_hours", models.FloatField(verbose_name="總工作時數")),
                ("actual_work_hours", models.FloatField(verbose_name="實際工作時數")),
                (
                    "break_hours",
                    models.FloatField(default=0.0, verbose_name="休息時數"),
                ),
                (
                    "overtime_hours",
                    models.FloatField(default=0.0, verbose_name="加班時數"),
                ),
                ("completed_quantity", models.IntegerField(verbose_name="完成數量")),
                (
                    "defect_quantity",
                    models.IntegerField(default=0, verbose_name="不良品數量"),
                ),
                ("yield_rate", models.FloatField(verbose_name="良率 (%)")),
                ("efficiency_rate", models.FloatField(verbose_name="效率 (件/小時)")),
                (
                    "original_quantity",
                    models.IntegerField(default=0, verbose_name="原始數量"),
                ),
                (
                    "allocated_quantity",
                    models.IntegerField(default=0, verbose_name="分配數量"),
                ),
                (
                    "quantity_source",
                    models.CharField(
                        choices=[("original", "原始數量"), ("allocated", "智能分配")],
                        default="original",
                        max_length=20,
                        verbose_name="數量來源",
                    ),
                ),
                (
                    "allocation_notes",
                    models.TextField(blank=True, verbose_name="分配計算說明"),
                ),
                (
                    "abnormal_notes",
                    models.TextField(blank=True, verbose_name="異常記錄"),
                ),
            ],
            options={
                "verbose_name": "工作時間報表",
                "verbose_name_plural": "工作時間報表",
                "db_table": "reporting_work_time_report",
                "unique_together": {
                    ("report_type", "report_date", "worker_name", "workorder_number")
                },
            },
        ),
    ]
