# Generated by Django 5.1.8 on 2025-07-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0014_comprehensiveanalysisreport_and_more"),
    ]

    operations = [
        # 第一步：新增新欄位
        migrations.AddField(
            model_name="productiondailyreport",
            name="operator_or_line",
            field=models.CharField(
                default="未指定", max_length=100, verbose_name="作業員/SMT產線"
            ),
        ),
        # 第二步：修改 unique_together
        migrations.AlterUniqueTogether(
            name="productiondailyreport",
            unique_together={("date", "operator_or_line", "equipment_name")},
        ),
        # 第三步：移除舊欄位
        migrations.RemoveField(
            model_name="productiondailyreport",
            name="operator_name",
        ),
    ] 