# Generated by Django 5.1.8 on 2025-07-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0015_alter_productiondailyreport_operator_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDataSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sync_type", models.CharField(max_length=50, verbose_name="同步類型")),
                ("period_start", models.DateField(verbose_name="期間開始")),
                ("period_end", models.DateField(verbose_name="期間結束")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失敗"),
                            ("partial", "部分成功"),
                        ],
                        max_length=20,
                        verbose_name="同步狀態",
                    ),
                ),
                (
                    "records_processed",
                    models.IntegerField(default=0, verbose_name="處理記錄數"),
                ),
                (
                    "records_updated",
                    models.IntegerField(default=0, verbose_name="更新記錄數"),
                ),
                (
                    "records_created",
                    models.IntegerField(default=0, verbose_name="新增記錄數"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="錯誤訊息"),
                ),
                ("started_at", models.DateTimeField(verbose_name="開始時間")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成時間"
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(default=0, verbose_name="執行時間(秒)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "報表數據同步日誌",
                "verbose_name_plural": "報表數據同步日誌",
                "db_table": "reporting_data_sync_log",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkerPerformanceCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "worker_name",
                    models.CharField(max_length=100, verbose_name="作業員姓名"),
                ),
                (
                    "worker_type",
                    models.CharField(max_length=20, verbose_name="作業員類型"),
                ),
                ("period_start", models.DateField(verbose_name="期間開始")),
                ("period_end", models.DateField(verbose_name="期間結束")),
                (
                    "total_work_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="總工作時數",
                    ),
                ),
                (
                    "total_completed_quantity",
                    models.IntegerField(default=0, verbose_name="總完成數量"),
                ),
                (
                    "total_defect_quantity",
                    models.IntegerField(default=0, verbose_name="總不良品數量"),
                ),
                (
                    "workorder_count",
                    models.IntegerField(default=0, verbose_name="工單數量"),
                ),
                (
                    "report_count",
                    models.IntegerField(default=0, verbose_name="報工次數"),
                ),
                (
                    "efficiency_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, verbose_name="效率"
                    ),
                ),
                (
                    "yield_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="良率"
                    ),
                ),
                (
                    "avg_hourly_output",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="平均每小時產出",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="快取鍵值"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最後更新時間"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "作業員績效快取",
                "verbose_name_plural": "作業員績效快取",
                "db_table": "reporting_worker_performance_cache",
                "indexes": [
                    models.Index(
                        fields=["worker_name", "period_start", "period_end"],
                        name="reporting_w_worker__8709e0_idx",
                    ),
                    models.Index(
                        fields=["worker_type"], name="reporting_w_worker__befacf_idx"
                    ),
                    models.Index(
                        fields=["cache_key"], name="reporting_w_cache_k_ce5433_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderSummaryCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workorder_number",
                    models.CharField(max_length=50, verbose_name="工單號碼"),
                ),
                (
                    "product_code",
                    models.CharField(max_length=100, verbose_name="產品編號"),
                ),
                ("period_start", models.DateField(verbose_name="期間開始")),
                ("period_end", models.DateField(verbose_name="期間結束")),
                (
                    "total_work_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="總工作時數",
                    ),
                ),
                (
                    "total_completed_quantity",
                    models.IntegerField(default=0, verbose_name="總完成數量"),
                ),
                (
                    "total_defect_quantity",
                    models.IntegerField(default=0, verbose_name="總不良品數量"),
                ),
                (
                    "worker_count",
                    models.IntegerField(default=0, verbose_name="參與作業員數"),
                ),
                (
                    "process_count",
                    models.IntegerField(default=0, verbose_name="工序數量"),
                ),
                (
                    "report_count",
                    models.IntegerField(default=0, verbose_name="報工次數"),
                ),
                (
                    "efficiency_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, verbose_name="效率"
                    ),
                ),
                (
                    "yield_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="良率"
                    ),
                ),
                (
                    "avg_hourly_output",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="平均每小時產出",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="快取鍵值"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最後更新時間"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "工單摘要快取",
                "verbose_name_plural": "工單摘要快取",
                "db_table": "reporting_workorder_summary_cache",
                "indexes": [
                    models.Index(
                        fields=["workorder_number", "period_start", "period_end"],
                        name="reporting_w_workord_41fd93_idx",
                    ),
                    models.Index(
                        fields=["product_code"], name="reporting_w_product_539d3b_idx"
                    ),
                    models.Index(
                        fields=["cache_key"], name="reporting_w_cache_k_9418d9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkTimeReportCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "日報"),
                            ("weekly", "週報"),
                            ("monthly", "月報"),
                        ],
                        max_length=20,
                        verbose_name="報表類型",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="報表日期")),
                ("period_start", models.DateField(verbose_name="期間開始")),
                ("period_end", models.DateField(verbose_name="期間結束")),
                (
                    "total_work_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="總工作時數",
                    ),
                ),
                (
                    "total_completed_quantity",
                    models.IntegerField(default=0, verbose_name="總完成數量"),
                ),
                (
                    "total_defect_quantity",
                    models.IntegerField(default=0, verbose_name="總不良品數量"),
                ),
                (
                    "worker_count",
                    models.IntegerField(default=0, verbose_name="參與作業員數"),
                ),
                (
                    "workorder_count",
                    models.IntegerField(default=0, verbose_name="工單數量"),
                ),
                (
                    "avg_efficiency_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="平均效率",
                    ),
                ),
                (
                    "avg_yield_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="平均良率",
                    ),
                ),
                (
                    "detail_data",
                    models.JSONField(default=dict, verbose_name="詳細數據"),
                ),
                (
                    "cache_key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="快取鍵值"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最後更新時間"),
                ),
                (
                    "data_source",
                    models.CharField(
                        default="workorder", max_length=50, verbose_name="數據來源"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "工作時間報表快取",
                "verbose_name_plural": "工作時間報表快取",
                "db_table": "reporting_work_time_cache",
                "indexes": [
                    models.Index(
                        fields=["report_type", "report_date"],
                        name="reporting_w_report__c83c9c_idx",
                    ),
                    models.Index(
                        fields=["period_start", "period_end"],
                        name="reporting_w_period__f05bdf_idx",
                    ),
                    models.Index(
                        fields=["cache_key"], name="reporting_w_cache_k_38722f_idx"
                    ),
                ],
            },
        ),
    ]
