# Generated by Django 5.1.8 on 2025-07-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0016_reportdatasynclog_workerperformancecache_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReportDataSyncLog",
        ),
        migrations.DeleteModel(
            name="ReportSyncSettings",
        ),
    ]
