# Generated by Django 5.1.8 on 2025-07-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0017_delete_reportdatasynclog_delete_reportsyncsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrderProductReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "日報表"),
                            ("weekly", "週報表"),
                            ("monthly", "月報表"),
                            ("custom", "自訂期間報表"),
                        ],
                        max_length=20,
                        verbose_name="報表類型",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="報表日期")),
                ("report_period_start", models.DateField(verbose_name="報表期間開始")),
                ("report_period_end", models.DateField(verbose_name="報表期間結束")),
                (
                    "data_source",
                    models.CharField(
                        help_text="數據來源模組名稱",
                        max_length=50,
                        verbose_name="數據來源",
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        help_text="統計數據的計算邏輯",
                        max_length=50,
                        verbose_name="計算方法",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("created_by", models.CharField(max_length=100, verbose_name="建立者")),
                (
                    "workorder_number",
                    models.CharField(max_length=100, verbose_name="工單號碼"),
                ),
                (
                    "product_code",
                    models.CharField(max_length=100, verbose_name="產品編號"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="產品名稱"),
                ),
                ("planned_quantity", models.IntegerField(verbose_name="計劃數量")),
                ("planned_start_date", models.DateField(verbose_name="計劃開始日期")),
                ("planned_end_date", models.DateField(verbose_name="計劃完成日期")),
                (
                    "completed_quantity",
                    models.IntegerField(verbose_name="實際完成數量"),
                ),
                ("completion_rate", models.FloatField(verbose_name="完成率 (%)")),
                (
                    "actual_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="實際開始日期"
                    ),
                ),
                (
                    "actual_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="實際完成日期"
                    ),
                ),
                (
                    "assigned_operators",
                    models.TextField(blank=True, verbose_name="作業員清單"),
                ),
                ("total_work_hours", models.FloatField(verbose_name="總工作時數")),
                (
                    "assigned_equipment",
                    models.TextField(blank=True, verbose_name="設備清單"),
                ),
                (
                    "equipment_usage_rate",
                    models.FloatField(verbose_name="設備使用率 (%)"),
                ),
                (
                    "defect_quantity",
                    models.IntegerField(default=0, verbose_name="不良品數量"),
                ),
                ("yield_rate", models.FloatField(verbose_name="良率 (%)")),
                (
                    "quality_score",
                    models.FloatField(default=0.0, verbose_name="品質評分"),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="材料成本",
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="人工成本",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="總成本",
                    ),
                ),
            ],
            options={
                "verbose_name": "工單機種報表",
                "verbose_name_plural": "工單機種報表",
                "db_table": "reporting_work_order_product_report",
                "unique_together": {("report_type", "report_date", "workorder_number")},
            },
        ),
    ]
