# Generated by Django 5.1.8 on 2025-07-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0018_create_missing_work_order_product_report"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worktimereport",
            options={"verbose_name": "工作報表", "verbose_name_plural": "工作報表"},
        ),
        migrations.AlterModelOptions(
            name="worktimereportcache",
            options={
                "verbose_name": "工作報表快取",
                "verbose_name_plural": "工作報表快取",
            },
        ),
        migrations.AddField(
            model_name="worktimereport",
            name="regular_hours",
            field=models.FloatField(default=0.0, verbose_name="正常工時"),
        ),
    ]
