# Generated by Django 5.1.8 on 2025-07-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0019_alter_worktimereport_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkHourReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="報表日期")),
                (
                    "worker_name",
                    models.CharField(max_length=100, verbose_name="作業員姓名"),
                ),
                (
                    "worker_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="作業員編號"
                    ),
                ),
                (
                    "workorder_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="工單號碼"
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="產品編號"
                    ),
                ),
                (
                    "process_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="工序名稱"
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="開始時間"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="結束時間"),
                ),
                (
                    "total_work_hours",
                    models.FloatField(default=0.0, verbose_name="總工作時數"),
                ),
                (
                    "actual_work_hours",
                    models.FloatField(default=0.0, verbose_name="實際工作時數"),
                ),
                (
                    "break_hours",
                    models.FloatField(default=0.0, verbose_name="休息時數"),
                ),
                (
                    "regular_hours",
                    models.FloatField(default=0.0, verbose_name="正常工時"),
                ),
                (
                    "overtime_hours",
                    models.FloatField(default=0.0, verbose_name="加班時數"),
                ),
                (
                    "completed_quantity",
                    models.IntegerField(default=0, verbose_name="完成數量"),
                ),
                (
                    "defect_quantity",
                    models.IntegerField(default=0, verbose_name="不良品數量"),
                ),
                (
                    "efficiency_rate",
                    models.FloatField(default=0.0, verbose_name="效率 (件/小時)"),
                ),
                ("yield_rate", models.FloatField(default=0.0, verbose_name="良率 (%)")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "data_source",
                    models.CharField(
                        default="workorder", max_length=50, verbose_name="數據來源"
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        default="work_time_calculator",
                        max_length=50,
                        verbose_name="計算方法",
                    ),
                ),
            ],
            options={
                "verbose_name": "工時報表",
                "verbose_name_plural": "工時報表",
                "db_table": "reporting_work_hour_report",
                "indexes": [
                    models.Index(
                        fields=["report_date"], name="reporting_w_report__99a976_idx"
                    ),
                    models.Index(
                        fields=["worker_name"], name="reporting_w_worker__7af946_idx"
                    ),
                    models.Index(
                        fields=["workorder_number"],
                        name="reporting_w_workord_d13e4a_idx",
                    ),
                    models.Index(
                        fields=["process_name"], name="reporting_w_process_4d8c6e_idx"
                    ),
                ],
                "unique_together": {
                    ("report_date", "worker_name", "workorder_number", "process_name")
                },
            },
        ),
    ]
