# Generated by Django 5.1.8 on 2025-07-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0020_workhourreport"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkHourReport",
        ),
        migrations.AlterUniqueTogether(
            name="worktimereport",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="worktimereport",
            name="report_category",
            field=models.CharField(
                choices=[("work_report", "工作報表"), ("work_hour_report", "工時報表")],
                default="work_report",
                max_length=20,
                verbose_name="報表分類",
            ),
        ),
        migrations.AddField(
            model_name="worktimereport",
            name="worker_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="作業員編號"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="worktimereport",
            unique_together={
                (
                    "report_type",
                    "report_date",
                    "report_category",
                    "worker_name",
                    "workorder_number",
                )
            },
        ),
        migrations.AddIndex(
            model_name="worktimereport",
            index=models.Index(
                fields=["report_date"], name="reporting_w_report__bfe935_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="worktimereport",
            index=models.Index(
                fields=["worker_name"], name="reporting_w_worker__f7df73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="worktimereport",
            index=models.Index(
                fields=["workorder_number"], name="reporting_w_workord_0be415_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="worktimereport",
            index=models.Index(
                fields=["process_name"], name="reporting_w_process_6e4dde_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="worktimereport",
            index=models.Index(
                fields=["report_category"], name="reporting_w_report__fcb944_idx"
            ),
        ),
    ]
