# Generated by Django 5.2.6 on 2025-09-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_integration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="erpintegrationoperationlog",
            name="user",
            field=models.CharField(
                help_text="操作者名稱（非外鍵關係，純文字欄位）",
                max_length=150,
                verbose_name="操作者",
            ),
        ),
    ]
