# Generated by Django 5.1.8 on 2025-07-07 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="材料名稱"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="材料編號"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="材料分類"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="單位"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "材料",
                "verbose_name_plural": "材料管理",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="工序名稱"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="建立時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "工序",
                "verbose_name_plural": "工序管理",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="產品名稱"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="產品編號"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="產品分類"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "產品",
                "verbose_name_plural": "產品管理",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaterialKanban",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kanban_type",
                    models.CharField(
                        choices=[
                            ("production", "生產看板"),
                            ("withdrawal", "取料看板"),
                            ("supplier", "供應商看板"),
                        ],
                        max_length=20,
                        verbose_name="看板類型",
                    ),
                ),
                (
                    "kanban_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="看板編號"
                    ),
                ),
                (
                    "quantity_per_kanban",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="看板數量"
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="當前數量"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("full", "滿"), ("partial", "部分"), ("empty", "空")],
                        default="full",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="位置"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最後更新時間"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.material",
                        verbose_name="材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "物料看板",
                "verbose_name_plural": "物料看板管理",
                "ordering": ["kanban_number"],
            },
        ),
        migrations.CreateModel(
            name="MaterialShortageAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_order",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="影響工單"
                    ),
                ),
                (
                    "required_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="需求數量"
                    ),
                ),
                (
                    "available_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="可用數量"
                    ),
                ),
                (
                    "shortage_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="短缺數量"
                    ),
                ),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "緊急"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="警告等級",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="是否已解決"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解決時間"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.material",
                        verbose_name="材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "缺料警告",
                "verbose_name_plural": "缺料警告管理",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialSupplyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_order",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="工單號"
                    ),
                ),
                (
                    "planned_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="計劃用量"
                    ),
                ),
                ("supply_time", models.DateTimeField(verbose_name="供應時間")),
                (
                    "supply_location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="供應位置"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "已計劃"),
                            ("in_transit", "運輸中"),
                            ("arrived", "已到達"),
                            ("consumed", "已消耗"),
                            ("cancelled", "已取消"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.material",
                        verbose_name="材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "物料供應計劃",
                "verbose_name_plural": "物料供應計劃管理",
                "ordering": ["supply_time"],
            },
        ),
        migrations.CreateModel(
            name="MaterialInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="庫存數量",
                    ),
                ),
                (
                    "last_sync_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="最後同步時間"
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("synced", "已同步"),
                            ("pending", "待同步"),
                            ("error", "同步錯誤"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="同步狀態",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.material",
                        verbose_name="材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "材料庫存",
                "verbose_name_plural": "材料庫存管理",
                "unique_together": {("material",)},
            },
        ),
        migrations.CreateModel(
            name="MaterialRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_per_unit",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="單位用量"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.material",
                        verbose_name="材料",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.product",
                        verbose_name="產品",
                    ),
                ),
            ],
            options={
                "verbose_name": "物料需求",
                "verbose_name_plural": "物料需求管理",
                "ordering": ["product", "material"],
                "unique_together": {("product", "material")},
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="路線名稱"
                    ),
                ),
                (
                    "step_order",
                    models.IntegerField(blank=True, null=True, verbose_name="步驟順序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="建立時間"
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.process",
                        verbose_name="工序",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.product",
                        verbose_name="產品",
                    ),
                ),
            ],
            options={
                "verbose_name": "工藝路線",
                "verbose_name_plural": "工藝路線管理",
                "ordering": ["product", "step_order"],
                "unique_together": {("product", "step_order")},
            },
        ),
    ]
