# Generated by Django 5.1.8 on 2025-09-04 11:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="材料名稱"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="材料編號"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="材料分類"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="單位"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="公司編號"
                    ),
                ),
            ],
            options={
                "verbose_name": "材料",
                "verbose_name_plural": "材料管理",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaterialOperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=50, verbose_name="操作用戶")),
                ("action", models.CharField(max_length=200, verbose_name="操作內容")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="操作時間"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備註")),
            ],
            options={
                "verbose_name": "物料操作日誌",
                "verbose_name_plural": "物料操作日誌",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="工序名稱"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="建立時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "工序",
                "verbose_name_plural": "工序管理",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="產品名稱"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="產品編號"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="產品分類"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "產品",
                "verbose_name_plural": "產品管理",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaterialKanban",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kanban_type",
                    models.CharField(
                        choices=[
                            ("production", "生產看板"),
                            ("withdrawal", "取料看板"),
                            ("supplier", "供應商看板"),
                        ],
                        max_length=20,
                        verbose_name="看板類型",
                    ),
                ),
                (
                    "kanban_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="看板編號"
                    ),
                ),
                (
                    "quantity_per_kanban",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="看板數量"
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="當前數量"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("full", "滿"), ("partial", "部分"), ("empty", "空")],
                        default="full",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="位置"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最後更新時間"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.material",
                        verbose_name="材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "物料看板",
                "verbose_name_plural": "物料看板管理",
                "ordering": ["kanban_number"],
            },
        ),
        migrations.CreateModel(
            name="MaterialShortageAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_order",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="影響工單"
                    ),
                ),
                (
                    "required_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="需求數量"
                    ),
                ),
                (
                    "available_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="可用數量"
                    ),
                ),
                (
                    "shortage_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="短缺數量"
                    ),
                ),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "緊急"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="警告等級",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="是否已解決"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解決時間"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.material",
                        verbose_name="材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "缺料警告",
                "verbose_name_plural": "缺料警告管理",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialSupplyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_order",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="工單號"
                    ),
                ),
                (
                    "planned_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="計劃用量"
                    ),
                ),
                ("supply_time", models.DateTimeField(verbose_name="供應時間")),
                (
                    "supply_location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="供應位置"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "已計劃"),
                            ("in_transit", "運輸中"),
                            ("arrived", "已到達"),
                            ("consumed", "已消耗"),
                            ("cancelled", "已取消"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.material",
                        verbose_name="材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "物料供應計劃",
                "verbose_name_plural": "物料供應計劃管理",
                "ordering": ["supply_time"],
            },
        ),
        migrations.CreateModel(
            name="MaterialTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("in", "入庫"),
                            ("out", "出庫"),
                            ("transfer", "調撥"),
                            ("adjustment", "調整"),
                            ("return", "退貨"),
                        ],
                        max_length=20,
                        verbose_name="交易類型",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="數量"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="單位成本",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="總成本",
                    ),
                ),
                (
                    "from_location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="來源位置"
                    ),
                ),
                (
                    "to_location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="目標位置"
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="參考單號"
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("purchase_order", "採購單"),
                            ("work_order", "工單"),
                            ("transfer_order", "調撥單"),
                            ("adjustment", "調整單"),
                            ("return", "退貨單"),
                        ],
                        max_length=20,
                        verbose_name="參考類型",
                    ),
                ),
                (
                    "batch_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="批次號"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="效期"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備註")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="建立者"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.material",
                        verbose_name="材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "物料交易記錄",
                "verbose_name_plural": "物料交易記錄",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="庫存數量",
                    ),
                ),
                (
                    "last_sync_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="最後同步時間"
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("synced", "已同步"),
                            ("pending", "待同步"),
                            ("error", "同步錯誤"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="同步狀態",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.material",
                        verbose_name="材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "材料庫存",
                "verbose_name_plural": "材料庫存管理",
                "unique_together": {("material",)},
            },
        ),
        migrations.CreateModel(
            name="MaterialInventoryManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warehouse",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="倉庫位置"
                    ),
                ),
                (
                    "current_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="當前庫存",
                    ),
                ),
                (
                    "safety_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="安全庫存",
                    ),
                ),
                (
                    "max_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="最大庫存",
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="補貨點",
                    ),
                ),
                (
                    "reorder_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="補貨數量",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="單位成本",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最後更新時間"),
                ),
                (
                    "stock_status",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("low", "低庫存"),
                            ("out", "缺貨"),
                            ("excess", "過剩"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="庫存狀態",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.material",
                        verbose_name="材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "庫存管理",
                "verbose_name_plural": "庫存管理",
                "ordering": ["material__name"],
                "unique_together": {("material", "warehouse")},
            },
        ),
        migrations.CreateModel(
            name="MaterialRequirementEstimation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estimation_date", models.DateField(verbose_name="估算日期")),
                ("period_start", models.DateField(verbose_name="期間開始")),
                ("period_end", models.DateField(verbose_name="期間結束")),
                (
                    "estimated_demand",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="估算需求"
                    ),
                ),
                (
                    "actual_demand",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="實際需求",
                    ),
                ),
                (
                    "forecast_accuracy",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="預測準確率(%)",
                    ),
                ),
                (
                    "planned_supply",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="計劃供應",
                    ),
                ),
                (
                    "actual_supply",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="實際供應",
                    ),
                ),
                (
                    "beginning_stock",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="期初庫存"
                    ),
                ),
                (
                    "ending_stock",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="期末庫存"
                    ),
                ),
                (
                    "estimation_method",
                    models.CharField(
                        choices=[
                            ("historical", "歷史平均"),
                            ("trend", "趨勢分析"),
                            ("seasonal", "季節性分析"),
                            ("manual", "手動估算"),
                            ("ai", "AI預測"),
                        ],
                        default="historical",
                        max_length=20,
                        verbose_name="估算方法",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("confirmed", "已確認"),
                            ("in_progress", "執行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備註")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.material",
                        verbose_name="材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "物料需求估算",
                "verbose_name_plural": "物料需求估算",
                "ordering": ["-estimation_date", "material__name"],
                "unique_together": {
                    ("material", "estimation_date", "period_start", "period_end")
                },
            },
        ),
        migrations.CreateModel(
            name="MaterialRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_per_unit",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="單位用量"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.material",
                        verbose_name="材料",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.product",
                        verbose_name="產品",
                    ),
                ),
            ],
            options={
                "verbose_name": "物料需求",
                "verbose_name_plural": "物料需求管理",
                "ordering": ["product", "material"],
                "unique_together": {("product", "material")},
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="路線名稱"
                    ),
                ),
                (
                    "step_order",
                    models.IntegerField(blank=True, null=True, verbose_name="步驟順序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="建立時間"
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.process",
                        verbose_name="工序",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.product",
                        verbose_name="產品",
                    ),
                ),
            ],
            options={
                "verbose_name": "工藝路線",
                "verbose_name_plural": "工藝路線管理",
                "ordering": ["product", "step_order"],
                "unique_together": {("product", "step_order")},
            },
        ),
    ]
