# Generated by Django 5.1.8 on 2025-07-07 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("in", "入庫"),
                            ("out", "出庫"),
                            ("transfer", "調撥"),
                            ("adjustment", "調整"),
                            ("return", "退貨"),
                        ],
                        max_length=20,
                        verbose_name="交易類型",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="數量"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="單位成本",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="總成本",
                    ),
                ),
                (
                    "from_location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="來源位置"
                    ),
                ),
                (
                    "to_location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="目標位置"
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="參考單號"
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("purchase_order", "採購單"),
                            ("work_order", "工單"),
                            ("transfer_order", "調撥單"),
                            ("adjustment", "調整單"),
                            ("return", "退貨單"),
                        ],
                        max_length=20,
                        verbose_name="參考類型",
                    ),
                ),
                (
                    "batch_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="批次號"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="效期"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備註")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="建立者"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.material",
                        verbose_name="材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "物料交易記錄",
                "verbose_name_plural": "物料交易記錄",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialInventoryManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warehouse",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="倉庫位置"
                    ),
                ),
                (
                    "current_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="當前庫存",
                    ),
                ),
                (
                    "safety_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="安全庫存",
                    ),
                ),
                (
                    "max_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="最大庫存",
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="補貨點",
                    ),
                ),
                (
                    "reorder_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="補貨數量",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="單位成本",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最後更新時間"),
                ),
                (
                    "stock_status",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("low", "低庫存"),
                            ("out", "缺貨"),
                            ("excess", "過剩"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="庫存狀態",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.material",
                        verbose_name="材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "庫存管理",
                "verbose_name_plural": "庫存管理",
                "ordering": ["material__name"],
                "unique_together": {("material", "warehouse")},
            },
        ),
        migrations.CreateModel(
            name="MaterialRequirementEstimation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estimation_date", models.DateField(verbose_name="估算日期")),
                ("period_start", models.DateField(verbose_name="期間開始")),
                ("period_end", models.DateField(verbose_name="期間結束")),
                (
                    "estimated_demand",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="估算需求"
                    ),
                ),
                (
                    "actual_demand",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="實際需求",
                    ),
                ),
                (
                    "forecast_accuracy",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="預測準確率(%)",
                    ),
                ),
                (
                    "planned_supply",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="計劃供應",
                    ),
                ),
                (
                    "actual_supply",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="實際供應",
                    ),
                ),
                (
                    "beginning_stock",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="期初庫存"
                    ),
                ),
                (
                    "ending_stock",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="期末庫存"
                    ),
                ),
                (
                    "estimation_method",
                    models.CharField(
                        choices=[
                            ("historical", "歷史平均"),
                            ("trend", "趨勢分析"),
                            ("seasonal", "季節性分析"),
                            ("manual", "手動估算"),
                            ("ai", "AI預測"),
                        ],
                        default="historical",
                        max_length=20,
                        verbose_name="估算方法",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("confirmed", "已確認"),
                            ("in_progress", "執行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備註")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.material",
                        verbose_name="材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "物料需求估算",
                "verbose_name_plural": "物料需求估算",
                "ordering": ["-estimation_date", "material__name"],
                "unique_together": {
                    ("material", "estimation_date", "period_start", "period_end")
                },
            },
        ),
    ]
