# Generated by Django 5.2.6 on 2025-09-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0002_auto_20250910_1045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialinventory",
            name="material_name",
            field=models.CharField(max_length=200, verbose_name="材料名稱"),
        ),
        migrations.AlterField(
            model_name="materialinventorymanagement",
            name="material_name",
            field=models.CharField(max_length=200, verbose_name="材料名稱"),
        ),
        migrations.AlterField(
            model_name="materialkanban",
            name="material_name",
            field=models.CharField(max_length=200, verbose_name="材料名稱"),
        ),
        migrations.AlterField(
            model_name="materialrequirement",
            name="material_name",
            field=models.CharField(max_length=200, verbose_name="材料名稱"),
        ),
        migrations.AlterField(
            model_name="materialrequirement",
            name="product_name",
            field=models.CharField(max_length=200, verbose_name="產品名稱"),
        ),
        migrations.AlterField(
            model_name="materialrequirementestimation",
            name="material_name",
            field=models.CharField(max_length=200, verbose_name="材料名稱"),
        ),
        migrations.AlterField(
            model_name="materialshortagealert",
            name="material_name",
            field=models.CharField(max_length=200, verbose_name="材料名稱"),
        ),
        migrations.AlterField(
            model_name="materialsupplyplan",
            name="material_name",
            field=models.CharField(max_length=200, verbose_name="材料名稱"),
        ),
        migrations.AlterField(
            model_name="materialtransaction",
            name="material_name",
            field=models.CharField(max_length=200, verbose_name="材料名稱"),
        ),
        migrations.AlterField(
            model_name="route",
            name="process_name",
            field=models.CharField(max_length=200, verbose_name="工序名稱"),
        ),
        migrations.AlterField(
            model_name="route",
            name="product_name",
            field=models.CharField(max_length=200, verbose_name="產品名稱"),
        ),
    ]
