# Generated by Django 5.1.8 on 2025-07-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0003_materialoperationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="產品分類"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="建立時間"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
        migrations.AddField(
            model_name="material",
            name="category",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="材料分類"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="unit",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="單位"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AddField(
            model_name="material",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="建立時間"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
    ]
