# Generated by Django 5.2.6 on 2025-09-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0003_alter_materialinventory_material_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="test_field",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="測試欄位"
            ),
        ),
    ]
