# Generated by Django 5.1.8 on 2025-07-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0004_fix_product_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="company_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="公司編號"
            ),
        ),
    ]
