# Generated by Django 5.2.6 on 2025-09-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0005_remove_material_test_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialoperationlog",
            name="user",
            field=models.CharField(
                help_text="操作用戶名稱（非外鍵關係，純文字欄位）",
                max_length=50,
                verbose_name="操作用戶",
            ),
        ),
    ]
