# Generated by Django 5.1.8 on 2025-08-02 06:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipOperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="時間"
                    ),
                ),
                ("user", models.CharField(max_length=150, verbose_name="用戶")),
                ("action", models.CharField(max_length=255, verbose_name="操作")),
            ],
            options={
                "verbose_name": "設備操作日誌",
                "verbose_name_plural": "設備操作日誌",
                "ordering": ["-timestamp"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="設備名稱"
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="型號"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "閒置"),
                            ("running", "運轉中"),
                            ("maintenance", "維修"),
                        ],
                        default="idle",
                        max_length=20,
                        verbose_name="設備狀態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="創建時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "production_line",
                    models.ForeignKey(
                        blank=True,
                        help_text="此設備所屬的生產線",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="production.productionline",
                        verbose_name="所屬產線",
                    ),
                ),
            ],
            options={
                "verbose_name": "設備",
                "verbose_name_plural": "設備",
                "ordering": ["name"],
                "default_permissions": (),
            },
        ),
    ]
