# Generated by Django 5.2.6 on 2025-09-22 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="設備名稱"
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="型號"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "閒置"),
                            ("running", "運轉中"),
                            ("maintenance", "維修"),
                        ],
                        default="idle",
                        max_length=20,
                        verbose_name="設備狀態",
                    ),
                ),
                (
                    "production_line_id",
                    models.CharField(
                        blank=True,
                        help_text="此設備所屬的生產線ID",
                        max_length=100,
                        null=True,
                        verbose_name="產線ID",
                    ),
                ),
                (
                    "production_line_name",
                    models.CharField(
                        blank=True,
                        help_text="此設備所屬的生產線名稱",
                        max_length=200,
                        null=True,
                        verbose_name="產線名稱",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="創建時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "設備",
                "verbose_name_plural": "設備",
                "ordering": ["name"],
                "permissions": [
                    ("can_view_equipment", "可以查看設備"),
                    ("can_add_equipment", "可以添加設備"),
                    ("can_edit_equipment", "可以編輯設備"),
                    ("can_delete_equipment", "可以刪除設備"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EquipOperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="時間"
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        help_text="用戶名稱（非外鍵關係，純文字欄位）",
                        max_length=150,
                        verbose_name="用戶",
                    ),
                ),
                ("action", models.CharField(max_length=255, verbose_name="操作")),
            ],
            options={
                "verbose_name": "設備操作日誌",
                "verbose_name_plural": "設備操作日誌",
                "ordering": ["-timestamp"],
                "permissions": [
                    ("can_view_equipoperationlog", "可以查看設備操作日誌"),
                    ("can_add_equipoperationlog", "可以添加設備操作日誌"),
                    ("can_edit_equipoperationlog", "可以編輯設備操作日誌"),
                    ("can_delete_equipoperationlog", "可以刪除設備操作日誌"),
                ],
            },
        ),
    ]
