# Generated by Django 5.1.8 on 2025-06-22 01:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="設備名稱"
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="型號"),
                ),
                (
                    "function_settings",
                    models.TextField(blank=True, verbose_name="功能設置"),
                ),
                (
                    "unit_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="單位"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="創建時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "設備",
                "verbose_name_plural": "設備",
                "permissions": [
                    ("can_view_equipment", "可以查看設備"),
                    ("can_add_equipment", "可以添加設備"),
                    ("can_monitor_equipment", "可以監控設備狀態"),
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="EquipOperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="時間"
                    ),
                ),
                ("user", models.CharField(max_length=150, verbose_name="用戶")),
                ("action", models.CharField(max_length=255, verbose_name="操作")),
            ],
            options={
                "verbose_name": "設備操作日誌",
                "verbose_name_plural": "設備操作日誌",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="EquipmentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("start", "啟動"),
                            ("stop", "停止"),
                            ("fault", "故障"),
                            ("maintenance", "維護"),
                        ],
                        max_length=20,
                        verbose_name="事件",
                    ),
                ),
                (
                    "runtime",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="運行時間"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="時間"
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="equip.equipment",
                        verbose_name="設備",
                    ),
                ),
            ],
            options={
                "verbose_name": "設備日誌",
                "verbose_name_plural": "設備日誌",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="EquipmentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="通知訊息")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="創建時間"
                    ),
                ),
                ("sent", models.BooleanField(default=False, verbose_name="是否已發送")),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="equip.equipment",
                        verbose_name="設備",
                    ),
                ),
            ],
            options={
                "verbose_name": "設備通知",
                "verbose_name_plural": "設備通知",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="EquipmentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "運行中"),
                            ("stopped", "停止"),
                            ("alarm", "報警"),
                            ("fault", "故障"),
                        ],
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "alarm_message",
                    models.TextField(blank=True, verbose_name="報警訊息"),
                ),
                (
                    "fault_detected",
                    models.BooleanField(default=False, verbose_name="故障檢測"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="時間"
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="equip.equipment",
                        verbose_name="設備",
                    ),
                ),
            ],
            options={
                "verbose_name": "設備狀態",
                "verbose_name_plural": "設備狀態",
                "default_permissions": (),
            },
        ),
    ]
