# Generated by Django 5.1.8 on 2025-06-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="equipment_type",
            field=models.CharField(
                choices=[
                    ("smt", "SMT 設備"),
                    ("test", "測試設備"),
                    ("inspection", "檢測設備"),
                    ("assembly", "組裝設備"),
                    ("packaging", "包裝設備"),
                    ("other", "其他設備"),
                ],
                default="other",
                max_length=20,
                verbose_name="設備類型",
            ),
        ),
    ]
