# Generated by Django 5.1.8 on 2025-06-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0002_equipment_equipment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="point_per_hour",
            field=models.IntegerField(blank=True, null=True, verbose_name="每小時點數"),
        ),
    ]
