# Generated by Django 5.1.8 on 2025-07-06 09:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0003_equipment_point_per_hour"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={
                "default_permissions": (),
                "ordering": ["name"],
                "permissions": [
                    ("can_view_equipment", "可以查看設備"),
                    ("can_add_equipment", "可以添加設備"),
                    ("can_edit_equipment", "可以編輯設備"),
                    ("can_delete_equipment", "可以刪除設備"),
                    ("can_monitor_equipment", "可以監控設備狀態"),
                    ("can_maintain_equipment", "可以維護設備"),
                ],
                "verbose_name": "設備",
                "verbose_name_plural": "設備",
            },
        ),
        migrations.AlterModelOptions(
            name="equipmentlog",
            options={
                "default_permissions": (),
                "ordering": ["-timestamp"],
                "verbose_name": "設備日誌",
                "verbose_name_plural": "設備日誌",
            },
        ),
        migrations.AlterModelOptions(
            name="equipmentnotification",
            options={
                "default_permissions": (),
                "ordering": ["-created_at"],
                "verbose_name": "設備通知",
                "verbose_name_plural": "設備通知",
            },
        ),
        migrations.AlterModelOptions(
            name="equipmentstatus",
            options={
                "default_permissions": (),
                "ordering": ["-timestamp"],
                "verbose_name": "設備狀態",
                "verbose_name_plural": "設備狀態",
            },
        ),
        migrations.AlterModelOptions(
            name="equipoperationlog",
            options={
                "default_permissions": (),
                "ordering": ["-timestamp"],
                "verbose_name": "設備操作日誌",
                "verbose_name_plural": "設備操作日誌",
            },
        ),
        migrations.RemoveField(
            model_name="equipmentlog",
            name="runtime",
        ),
        migrations.AddField(
            model_name="equipment",
            name="department",
            field=models.CharField(blank=True, max_length=50, verbose_name="所屬部門"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="depreciation_rate",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="折舊率(%)"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="installation_date",
            field=models.DateField(blank=True, null=True, verbose_name="安裝日期"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="last_maintenance_date",
            field=models.DateField(blank=True, null=True, verbose_name="最後維護日期"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="location",
            field=models.CharField(blank=True, max_length=100, verbose_name="設備位置"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="maintenance_cycle_days",
            field=models.PositiveIntegerField(default=30, verbose_name="維護週期(天)"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=100, verbose_name="製造商"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="max_capacity_per_hour",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="最大每小時產能"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="next_maintenance_date",
            field=models.DateField(blank=True, null=True, verbose_name="下次維護日期"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="notes",
            field=models.TextField(blank=True, verbose_name="備註"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="optimal_capacity_per_hour",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="最佳每小時產能"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="purchase_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="購置成本",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100, verbose_name="序號"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "啟用"),
                    ("inactive", "停用"),
                    ("maintenance", "維護中"),
                    ("retired", "報廢"),
                ],
                default="active",
                max_length=20,
                verbose_name="設備狀態",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="technical_specs",
            field=models.JSONField(blank=True, default=dict, verbose_name="技術規格"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="warranty_expiry",
            field=models.DateField(blank=True, null=True, verbose_name="保固到期日"),
        ),
        migrations.AddField(
            model_name="equipmentlog",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="成本",
            ),
        ),
        migrations.AddField(
            model_name="equipmentlog",
            name="efficiency_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="效率率(%)",
            ),
        ),
        migrations.AddField(
            model_name="equipmentlog",
            name="maintenance_type",
            field=models.CharField(blank=True, max_length=50, verbose_name="維護類型"),
        ),
        migrations.AddField(
            model_name="equipmentlog",
            name="operator",
            field=models.CharField(blank=True, max_length=100, verbose_name="操作員"),
        ),
        migrations.AddField(
            model_name="equipmentlog",
            name="parts_replaced",
            field=models.TextField(blank=True, verbose_name="更換零件"),
        ),
        migrations.AddField(
            model_name="equipmentlog",
            name="production_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="生產數量"
            ),
        ),
        migrations.AddField(
            model_name="equipmentlog",
            name="runtime_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="運行時數",
            ),
        ),
        migrations.AddField(
            model_name="equipmentnotification",
            name="acknowledged",
            field=models.BooleanField(default=False, verbose_name="是否已確認"),
        ),
        migrations.AddField(
            model_name="equipmentnotification",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="確認時間"),
        ),
        migrations.AddField(
            model_name="equipmentnotification",
            name="acknowledged_by",
            field=models.CharField(blank=True, max_length=100, verbose_name="確認人員"),
        ),
        migrations.AddField(
            model_name="equipmentnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("alarm", "警報"),
                    ("maintenance", "維護提醒"),
                    ("fault", "故障通知"),
                    ("status_change", "狀態變更"),
                    ("performance", "效能警告"),
                    ("general", "一般通知"),
                ],
                default="general",
                max_length=20,
                verbose_name="通知類型",
            ),
        ),
        migrations.AddField(
            model_name="equipmentnotification",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "低"),
                    ("medium", "中"),
                    ("high", "高"),
                    ("urgent", "緊急"),
                ],
                default="medium",
                max_length=20,
                verbose_name="優先級",
            ),
        ),
        migrations.AddField(
            model_name="equipmentnotification",
            name="recipients",
            field=models.TextField(blank=True, verbose_name="收件人"),
        ),
        migrations.AddField(
            model_name="equipmentnotification",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="發送時間"),
        ),
        migrations.AddField(
            model_name="equipmentnotification",
            name="title",
            field=models.CharField(
                default="設備通知", max_length=200, verbose_name="通知標題"
            ),
        ),
        migrations.AddField(
            model_name="equipmentstatus",
            name="alarm_code",
            field=models.CharField(blank=True, max_length=20, verbose_name="警報代碼"),
        ),
        migrations.AddField(
            model_name="equipmentstatus",
            name="current_speed",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="當前速度",
            ),
        ),
        migrations.AddField(
            model_name="equipmentstatus",
            name="pressure",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="壓力(Pa)",
            ),
        ),
        migrations.AddField(
            model_name="equipmentstatus",
            name="production_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="生產數量"
            ),
        ),
        migrations.AddField(
            model_name="equipmentstatus",
            name="runtime_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="運行時數",
            ),
        ),
        migrations.AddField(
            model_name="equipmentstatus",
            name="severity_level",
            field=models.CharField(
                choices=[
                    ("low", "低"),
                    ("medium", "中"),
                    ("high", "高"),
                    ("critical", "嚴重"),
                ],
                default="low",
                max_length=20,
                verbose_name="嚴重程度",
            ),
        ),
        migrations.AddField(
            model_name="equipmentstatus",
            name="temperature",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="溫度(°C)",
            ),
        ),
        migrations.AddField(
            model_name="equipmentstatus",
            name="vibration",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="振動值",
            ),
        ),
        migrations.AddField(
            model_name="equipoperationlog",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="equip.equipment",
                verbose_name="相關設備",
            ),
        ),
        migrations.AddField(
            model_name="equipoperationlog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP地址"
            ),
        ),
        migrations.AddField(
            model_name="equipoperationlog",
            name="user_agent",
            field=models.TextField(blank=True, verbose_name="用戶代理"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="equipment_type",
            field=models.CharField(
                choices=[
                    ("smt", "SMT 設備"),
                    ("dip", "DIP 設備"),
                    ("test", "測試設備"),
                    ("inspection", "檢測設備"),
                    ("assembly", "組裝設備"),
                    ("packaging", "包裝設備"),
                    ("warehouse", "倉儲設備"),
                    ("other", "其他設備"),
                ],
                default="other",
                max_length=20,
                verbose_name="設備類型",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="point_per_hour",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="每小時點數"
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="unit_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="產能單位"),
        ),
        migrations.AlterField(
            model_name="equipmentlog",
            name="event",
            field=models.CharField(
                choices=[
                    ("start", "啟動"),
                    ("stop", "停止"),
                    ("pause", "暫停"),
                    ("resume", "恢復"),
                    ("fault", "故障"),
                    ("alarm", "報警"),
                    ("maintenance", "維護"),
                    ("setup", "換線"),
                    ("calibration", "校準"),
                    ("cleaning", "清潔"),
                    ("inspection", "檢查"),
                ],
                max_length=20,
                verbose_name="事件",
            ),
        ),
        migrations.AlterField(
            model_name="equipmentstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "運行中"),
                    ("idle", "閒置"),
                    ("stopped", "停止"),
                    ("alarm", "報警"),
                    ("fault", "故障"),
                    ("maintenance", "維護中"),
                    ("setup", "換線中"),
                    ("offline", "離線"),
                ],
                max_length=20,
                verbose_name="狀態",
            ),
        ),
        migrations.CreateModel(
            name="EquipmentMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("preventive", "預防性維護"),
                            ("corrective", "矯正性維護"),
                            ("emergency", "緊急維護"),
                            ("inspection", "定期檢查"),
                            ("calibration", "校準"),
                            ("cleaning", "清潔"),
                        ],
                        max_length=20,
                        verbose_name="維護類型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="維護標題")),
                ("description", models.TextField(verbose_name="維護描述")),
                ("planned_date", models.DateField(verbose_name="計劃日期")),
                (
                    "estimated_duration_hours",
                    models.PositiveIntegerField(verbose_name="預計時數"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("urgent", "緊急"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="優先級",
                    ),
                ),
                (
                    "actual_start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="實際開始時間"
                    ),
                ),
                (
                    "actual_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="實際結束時間"
                    ),
                ),
                (
                    "actual_duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="實際時數",
                    ),
                ),
                (
                    "assigned_technician",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="指派技師"
                    ),
                ),
                (
                    "performed_by",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="執行人員"
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="人工成本",
                    ),
                ),
                (
                    "parts_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="零件成本",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="總成本",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "已計劃"),
                            ("in_progress", "進行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                            ("overdue", "逾期"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                ("findings", models.TextField(blank=True, verbose_name="檢查發現")),
                (
                    "actions_taken",
                    models.TextField(blank=True, verbose_name="採取行動"),
                ),
                ("recommendations", models.TextField(blank=True, verbose_name="建議")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="創建時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenances",
                        to="equip.equipment",
                        verbose_name="設備",
                    ),
                ),
            ],
            options={
                "verbose_name": "設備維護",
                "verbose_name_plural": "設備維護",
                "ordering": ["-planned_date"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="EquipmentPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "total_runtime_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="總運行時數"
                    ),
                ),
                (
                    "total_production_count",
                    models.PositiveIntegerField(verbose_name="總生產數量"),
                ),
                (
                    "actual_capacity_per_hour",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="實際每小時產能"
                    ),
                ),
                (
                    "efficiency_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="效率率(%)"
                    ),
                ),
                (
                    "defect_count",
                    models.PositiveIntegerField(default=0, verbose_name="不良品數量"),
                ),
                (
                    "defect_rate",
                    models.DecimalField(
                        decimal_places=4, max_digits=5, verbose_name="不良率"
                    ),
                ),
                (
                    "rework_count",
                    models.PositiveIntegerField(default=0, verbose_name="重工數量"),
                ),
                (
                    "downtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="停機時數",
                    ),
                ),
                (
                    "downtime_reasons",
                    models.JSONField(blank=True, default=dict, verbose_name="停機原因"),
                ),
                (
                    "energy_consumption",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="能耗(kWh)",
                    ),
                ),
                (
                    "maintenance_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="維護成本",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="創建時間"
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performances",
                        to="equip.equipment",
                        verbose_name="設備",
                    ),
                ),
            ],
            options={
                "verbose_name": "設備效能",
                "verbose_name_plural": "設備效能",
                "ordering": ["-date"],
                "default_permissions": (),
                "unique_together": {("equipment", "date")},
            },
        ),
    ]
