# Generated by Django 5.1.8 on 2025-07-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0004_alter_equipment_options_alter_equipmentlog_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="equipmentperformance",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="equipmentperformance",
            name="equipment",
        ),
        migrations.AlterModelOptions(
            name="equipment",
            options={
                "default_permissions": (),
                "permissions": [
                    ("can_view_equipment", "可以查看設備"),
                    ("can_add_equipment", "可以添加設備"),
                    ("can_monitor_equipment", "可以監控設備狀態"),
                ],
                "verbose_name": "設備",
                "verbose_name_plural": "設備",
            },
        ),
        migrations.AlterModelOptions(
            name="equipmentlog",
            options={
                "default_permissions": (),
                "verbose_name": "設備日誌",
                "verbose_name_plural": "設備日誌",
            },
        ),
        migrations.AlterModelOptions(
            name="equipmentnotification",
            options={
                "default_permissions": (),
                "verbose_name": "設備通知",
                "verbose_name_plural": "設備通知",
            },
        ),
        migrations.AlterModelOptions(
            name="equipmentstatus",
            options={
                "default_permissions": (),
                "verbose_name": "設備狀態",
                "verbose_name_plural": "設備狀態",
            },
        ),
        migrations.AlterModelOptions(
            name="equipoperationlog",
            options={
                "default_permissions": (),
                "verbose_name": "設備操作日誌",
                "verbose_name_plural": "設備操作日誌",
            },
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="department",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="depreciation_rate",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="installation_date",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="last_maintenance_date",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="location",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="maintenance_cycle_days",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="max_capacity_per_hour",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="next_maintenance_date",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="optimal_capacity_per_hour",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="purchase_cost",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="serial_number",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="technical_specs",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="warranty_expiry",
        ),
        migrations.RemoveField(
            model_name="equipmentlog",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="equipmentlog",
            name="efficiency_rate",
        ),
        migrations.RemoveField(
            model_name="equipmentlog",
            name="maintenance_type",
        ),
        migrations.RemoveField(
            model_name="equipmentlog",
            name="operator",
        ),
        migrations.RemoveField(
            model_name="equipmentlog",
            name="parts_replaced",
        ),
        migrations.RemoveField(
            model_name="equipmentlog",
            name="production_count",
        ),
        migrations.RemoveField(
            model_name="equipmentlog",
            name="runtime_hours",
        ),
        migrations.RemoveField(
            model_name="equipmentnotification",
            name="acknowledged",
        ),
        migrations.RemoveField(
            model_name="equipmentnotification",
            name="acknowledged_at",
        ),
        migrations.RemoveField(
            model_name="equipmentnotification",
            name="acknowledged_by",
        ),
        migrations.RemoveField(
            model_name="equipmentnotification",
            name="notification_type",
        ),
        migrations.RemoveField(
            model_name="equipmentnotification",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="equipmentnotification",
            name="recipients",
        ),
        migrations.RemoveField(
            model_name="equipmentnotification",
            name="sent_at",
        ),
        migrations.RemoveField(
            model_name="equipmentnotification",
            name="title",
        ),
        migrations.RemoveField(
            model_name="equipmentstatus",
            name="alarm_code",
        ),
        migrations.RemoveField(
            model_name="equipmentstatus",
            name="current_speed",
        ),
        migrations.RemoveField(
            model_name="equipmentstatus",
            name="pressure",
        ),
        migrations.RemoveField(
            model_name="equipmentstatus",
            name="production_count",
        ),
        migrations.RemoveField(
            model_name="equipmentstatus",
            name="runtime_hours",
        ),
        migrations.RemoveField(
            model_name="equipmentstatus",
            name="severity_level",
        ),
        migrations.RemoveField(
            model_name="equipmentstatus",
            name="temperature",
        ),
        migrations.RemoveField(
            model_name="equipmentstatus",
            name="vibration",
        ),
        migrations.RemoveField(
            model_name="equipoperationlog",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="equipoperationlog",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="equipoperationlog",
            name="user_agent",
        ),
        migrations.AddField(
            model_name="equipmentlog",
            name="runtime",
            field=models.CharField(blank=True, max_length=20, verbose_name="運行時間"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="equipment_type",
            field=models.CharField(
                choices=[
                    ("smt", "SMT 設備"),
                    ("test", "測試設備"),
                    ("inspection", "檢測設備"),
                    ("assembly", "組裝設備"),
                    ("packaging", "包裝設備"),
                    ("other", "其他設備"),
                ],
                default="other",
                max_length=20,
                verbose_name="設備類型",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="point_per_hour",
            field=models.IntegerField(blank=True, null=True, verbose_name="每小時點數"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="unit_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="單位"
            ),
        ),
        migrations.AlterField(
            model_name="equipmentlog",
            name="event",
            field=models.CharField(
                choices=[
                    ("start", "啟動"),
                    ("stop", "停止"),
                    ("fault", "故障"),
                    ("maintenance", "維護"),
                ],
                max_length=20,
                verbose_name="事件",
            ),
        ),
        migrations.AlterField(
            model_name="equipmentstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "運行中"),
                    ("stopped", "停止"),
                    ("alarm", "報警"),
                    ("fault", "故障"),
                ],
                max_length=20,
                verbose_name="狀態",
            ),
        ),
        migrations.DeleteModel(
            name="EquipmentMaintenance",
        ),
        migrations.DeleteModel(
            name="EquipmentPerformance",
        ),
    ]
