# Generated by Django 5.1.8 on 2025-07-08 00:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0005_alter_equipmentperformance_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="類型名稱"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="類型描述")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否啟用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="創建時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "設備類型",
                "verbose_name_plural": "設備類型",
                "ordering": ["name"],
                "default_permissions": (),
            },
        ),
        migrations.AlterField(
            model_name="equipment",
            name="equipment_type",
            field=models.CharField(
                choices=[
                    ("smt", "SMT 設備"),
                    ("test", "測試設備"),
                    ("inspection", "檢測設備"),
                    ("assembly", "組裝設備"),
                    ("packaging", "包裝設備"),
                    ("other", "其他設備"),
                ],
                default="other",
                max_length=20,
                verbose_name="設備類型（舊）",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="equipment_type_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="equip.equipmenttype",
                verbose_name="設備類型（新）",
            ),
        ),
    ]
