# Generated by Django 5.1.8 on 2025-07-08 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0007_migrate_equipment_type_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="equipment_type",
        ),
    ]
