# Generated by Django 5.1.8 on 2025-07-08 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0008_remove_equipment_equipment_type_fk_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="equipment_type_fk",
        ),
        migrations.AddField(
            model_name="equipment",
            name="equipment_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="equip.equipmenttype",
                verbose_name="設備類型",
            ),
        ),
    ]
