# Generated by Django 5.1.8 on 2025-07-08 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0009_remove_equipment_equipment_type_fk_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="point_per_hour",
        ),
    ]
