# Generated by Django 5.1.8 on 2025-07-08 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0010_remove_equipment_point_per_hour"),
        ("production", "0003_alter_productionline_lunch_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="unit_name",
        ),
        migrations.AddField(
            model_name="equipment",
            name="production_line",
            field=models.ForeignKey(
                blank=True,
                help_text="此設備所屬的生產線",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="production.productionline",
                verbose_name="所屬產線",
            ),
        ),
    ]
