# Generated by Django 5.1.8 on 2025-07-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0011_remove_equipment_unit_name_equipment_production_line"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipmentnotification",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="equipmentstatus",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="equipment_type",
        ),
        migrations.AlterModelOptions(
            name="equipment",
            options={
                "default_permissions": (),
                "ordering": ["name"],
                "verbose_name": "設備",
                "verbose_name_plural": "設備",
            },
        ),
        migrations.AlterModelOptions(
            name="equipoperationlog",
            options={
                "default_permissions": (),
                "ordering": ["-timestamp"],
                "verbose_name": "設備操作日誌",
                "verbose_name_plural": "設備操作日誌",
            },
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="function_settings",
        ),
        migrations.AddField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("idle", "閒置"),
                    ("running", "運轉中"),
                    ("maintenance", "維修"),
                ],
                default="idle",
                max_length=20,
                verbose_name="設備狀態",
            ),
        ),
        migrations.DeleteModel(
            name="EquipmentLog",
        ),
        migrations.DeleteModel(
            name="EquipmentNotification",
        ),
        migrations.DeleteModel(
            name="EquipmentStatus",
        ),
        migrations.DeleteModel(
            name="EquipmentType",
        ),
    ]
