# Generated by Django 5.2.6 on 2025-09-10 02:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AOITestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='產品名稱')),
                ('test_date', models.DateField(verbose_name='測試日期')),
                ('defect_detected', models.BooleanField(verbose_name='是否檢測到缺陷')),
                ('defect_details', models.TextField(blank=True, verbose_name='缺陷詳情')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': 'AOI 測試報告',
                'verbose_name_plural': 'AOI 測試報告',
            },
        ),
        migrations.CreateModel(
            name='DefectiveProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='產品名稱')),
                ('defect_reason', models.TextField(verbose_name='不合格原因')),
                ('quantity', models.IntegerField(verbose_name='不合格數量')),
                ('defect_date', models.DateField(verbose_name='不合格日期')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '不良品記錄',
                'verbose_name_plural': '不良品記錄',
            },
        ),
        migrations.CreateModel(
            name='FinalInspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='產品名稱')),
                ('inspection_date', models.DateField(verbose_name='檢驗日期')),
                ('meets_standards', models.BooleanField(verbose_name='是否符合入庫標準')),
                ('remarks', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '製成檢驗/入庫檢驗表',
                'verbose_name_plural': '製成檢驗/入庫檢驗表',
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='檢驗項目名稱')),
                ('standard', models.TextField(verbose_name='檢驗標準')),
                ('requirement', models.TextField(blank=True, verbose_name='檢驗要求')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '檢驗項目',
                'verbose_name_plural': '檢驗項目',
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_item_id', models.CharField(max_length=50, verbose_name='檢驗項目ID')),
                ('inspection_item_name', models.CharField(max_length=100, verbose_name='檢驗項目名稱')),
                ('product_name', models.CharField(max_length=100, verbose_name='產品名稱')),
                ('inspection_date', models.DateField(verbose_name='檢驗日期')),
                ('result', models.CharField(choices=[('pass', '通過'), ('fail', '不通過')], max_length=20, verbose_name='檢驗結果')),
                ('remarks', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '檢驗記錄',
                'verbose_name_plural': '檢驗記錄',
            },
        ),
        migrations.CreateModel(
            name='QualityOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='用戶')),
                ('action', models.TextField(verbose_name='操作')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='時間戳')),
            ],
            options={
                'verbose_name': '品質操作日誌',
                'verbose_name_plural': '品質操作日誌',
                'default_permissions': (),
            },
        ),
    ]
