# Generated by Django 5.2.6 on 2025-09-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0002_auto_20250910_1046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectionrecord",
            name="inspection_item_name",
            field=models.CharField(max_length=100, verbose_name="檢驗項目名稱"),
        ),
    ]
