# Generated by Django 5.2.6 on 2025-09-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0004_inspectionitem_test_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inspectionitem",
            name="test_field",
        ),
    ]
