# Generated by Django 5.1.8 on 2025-08-07 11:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("process", "0001_initial"),
        ("workorder", "0008_rename_auto_allocation_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnifiedWorkReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        help_text="作業員姓名（純文字輸入）",
                        max_length=100,
                        verbose_name="作業員",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        help_text="公司代號，例如：01、02、03",
                        max_length=10,
                        verbose_name="公司代號",
                    ),
                ),
                (
                    "original_workorder_number",
                    models.CharField(
                        help_text="原始工單號碼（字串格式）",
                        max_length=50,
                        verbose_name="原始工單號碼",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        help_text="產品編號", max_length=100, verbose_name="產品編號"
                    ),
                ),
                (
                    "planned_quantity",
                    models.IntegerField(
                        help_text="工單預設的生產數量", verbose_name="工單預設生產數量"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        help_text="工序名稱", max_length=100, verbose_name="工序名稱"
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        help_text="使用的設備名稱或編號",
                        max_length=100,
                        verbose_name="使用的設備",
                    ),
                ),
                (
                    "work_date",
                    models.DateField(help_text="工作日期", verbose_name="日期"),
                ),
                (
                    "start_time",
                    models.TimeField(help_text="工作開始時間", verbose_name="開始時間"),
                ),
                (
                    "end_time",
                    models.TimeField(help_text="工作結束時間", verbose_name="結束時間"),
                ),
                (
                    "has_break",
                    models.BooleanField(
                        default=False,
                        help_text="是否有休息時間",
                        verbose_name="是否有休息時間",
                    ),
                ),
                (
                    "break_start_time",
                    models.TimeField(
                        blank=True,
                        help_text="休息開始時間",
                        null=True,
                        verbose_name="休息開始時間",
                    ),
                ),
                (
                    "break_end_time",
                    models.TimeField(
                        blank=True,
                        help_text="休息結束時間",
                        null=True,
                        verbose_name="休息結束時間",
                    ),
                ),
                (
                    "break_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="休息時數（小時）",
                        max_digits=4,
                        verbose_name="休息時數",
                    ),
                ),
                (
                    "work_hours_calculated",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="計算得出的工作時數（小時）",
                        max_digits=6,
                        verbose_name="工作時數",
                    ),
                ),
                (
                    "overtime_hours_calculated",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="計算得出的加班時數（小時）",
                        max_digits=6,
                        verbose_name="加班時數",
                    ),
                ),
                (
                    "work_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="工作數量（良品）",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="工作數量",
                    ),
                ),
                (
                    "defect_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="不良品數量",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="不良品數量",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, help_text="是否已完工", verbose_name="是否已完工"
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "待核准"),
                            ("approved", "已核准"),
                            ("rejected", "已駁回"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        help_text="核准狀態",
                        max_length=20,
                        verbose_name="核准狀態",
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True,
                        help_text="核准人員姓名",
                        max_length=100,
                        null=True,
                        verbose_name="核准人員",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="核准時間",
                        null=True,
                        verbose_name="核准時間",
                    ),
                ),
                (
                    "approval_remarks",
                    models.TextField(
                        blank=True, help_text="核准備註", verbose_name="核准備註"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="駁回原因", verbose_name="駁回原因"
                    ),
                ),
                (
                    "rejected_by",
                    models.CharField(
                        blank=True,
                        help_text="駁回人員姓名",
                        max_length=100,
                        null=True,
                        verbose_name="駁回人員",
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="駁回時間",
                        null=True,
                        verbose_name="駁回時間",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="一般備註", verbose_name="備註"
                    ),
                ),
                (
                    "abnormal_notes",
                    models.TextField(
                        blank=True, help_text="異常記錄", verbose_name="異常記錄"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        help_text="建立人員姓名",
                        max_length=100,
                        verbose_name="建立人員",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="建立時間", verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="更新時間", verbose_name="更新時間"
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        help_text="關聯到製程管理的工序",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process.processname",
                        verbose_name="工序",
                    ),
                ),
                (
                    "workorder",
                    models.ForeignKey(
                        help_text="關聯到工單管理系統的工單",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workorder.workorder",
                        verbose_name="工單號碼",
                    ),
                ),
            ],
            options={
                "verbose_name": "統一補登報工",
                "verbose_name_plural": "統一補登報工管理",
                "db_table": "unified_work_report",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_view_unified_work_report", "可以查看統一補登報工"),
                    ("can_add_unified_work_report", "可以新增統一補登報工"),
                    ("can_edit_unified_work_report", "可以編輯統一補登報工"),
                    ("can_delete_unified_work_report", "可以刪除統一補登報工"),
                    ("can_approve_unified_work_report", "可以核准統一補登報工"),
                    ("can_reject_unified_work_report", "可以駁回統一補登報工"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UnifiedWorkReportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "建立"),
                            ("updated", "更新"),
                            ("deleted", "刪除"),
                            ("approved", "核准"),
                            ("rejected", "駁回"),
                            ("cancelled", "取消"),
                        ],
                        max_length=20,
                        verbose_name="操作類型",
                    ),
                ),
                ("operator", models.CharField(max_length=100, verbose_name="操作人員")),
                ("remarks", models.TextField(blank=True, verbose_name="操作備註")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作時間"),
                ),
                (
                    "work_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="unified_work_reporting.unifiedworkreport",
                        verbose_name="統一補登報工",
                    ),
                ),
            ],
            options={
                "verbose_name": "統一補登報工操作日誌",
                "verbose_name_plural": "統一補登報工操作日誌",
                "db_table": "unified_work_report_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="unifiedworkreport",
            index=models.Index(
                fields=["operator"], name="unified_wor_operato_a7cdcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedworkreport",
            index=models.Index(
                fields=["company_code"], name="unified_wor_company_159dec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedworkreport",
            index=models.Index(
                fields=["work_date"], name="unified_wor_work_da_1ccc2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedworkreport",
            index=models.Index(
                fields=["approval_status"], name="unified_wor_approva_0af6b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedworkreport",
            index=models.Index(
                fields=["workorder"], name="unified_wor_workord_ed4a7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedworkreport",
            index=models.Index(
                fields=["process"], name="unified_wor_process_6e7b1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedworkreport",
            index=models.Index(
                fields=["created_at"], name="unified_wor_created_9fabe3_idx"
            ),
        ),
    ]
