# Generated by Django 5.1.8 on 2025-08-02 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkOrderDispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="公司代號"
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="工單號碼"
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="產品編號"
                    ),
                ),
                (
                    "planned_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="計劃數量"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待派工"),
                            ("dispatched", "已派工"),
                            ("in_production", "生產中"),
                            ("completed", "已完工"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="派工狀態",
                    ),
                ),
                (
                    "dispatch_date",
                    models.DateField(blank=True, null=True, verbose_name="派工日期"),
                ),
                (
                    "planned_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="計劃開始日期"
                    ),
                ),
                (
                    "planned_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="計劃完成日期"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備註")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "created_by",
                    models.CharField(
                        default="system", max_length=100, verbose_name="建立人員"
                    ),
                ),
            ],
            options={
                "verbose_name": "派工單",
                "verbose_name_plural": "派工單管理",
                "db_table": "workorder_dispatch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderDispatchProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="工序名稱"),
                ),
                ("step_order", models.IntegerField(verbose_name="工序順序")),
                ("planned_quantity", models.IntegerField(verbose_name="計劃數量")),
                (
                    "assigned_operator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分配作業員"
                    ),
                ),
                (
                    "assigned_equipment",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分配設備"
                    ),
                ),
                (
                    "dispatch_status",
                    models.CharField(
                        choices=[
                            ("pending", "待派工"),
                            ("dispatched", "已派工"),
                            ("in_progress", "進行中"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="派工狀態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "workorder_dispatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_processes",
                        to="workorder_dispatch.workorderdispatch",
                        verbose_name="派工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "派工單工序",
                "verbose_name_plural": "派工單工序明細",
                "db_table": "workorder_dispatch_process",
                "ordering": ["workorder_dispatch", "step_order"],
                "unique_together": {("workorder_dispatch", "step_order")},
            },
        ),
    ]
