# Generated by Django 5.1.8 on 2025-09-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder_dispatch_id', models.CharField(max_length=50, verbose_name='派工單ID')),
                ('workorder_dispatch_name', models.CharField(max_length=200, verbose_name='派工單名稱')),
                ('action', models.CharField(max_length=50, verbose_name='操作類型')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='原狀態')),
                ('new_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='新狀態')),
                ('operator', models.CharField(max_length=100, verbose_name='操作人員')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作時間')),
            ],
            options={
                'verbose_name': '派工歷史',
                'verbose_name_plural': '派工歷史記錄',
                'db_table': 'workorder_dispatch_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='公司代號')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司名稱')),
                ('order_number', models.CharField(db_index=True, max_length=100, verbose_name='工單號碼')),
                ('product_code', models.CharField(db_index=True, max_length=100, verbose_name='產品編號')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='產品名稱')),
                ('planned_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='計劃數量')),
                ('status', models.CharField(choices=[('pending', '待派工'), ('dispatched', '已派工'), ('in_production', '生產中'), ('completed', '已完工'), ('cancelled', '已取消')], default='in_production', max_length=20, verbose_name='派工狀態')),
                ('dispatch_date', models.DateField(blank=True, null=True, verbose_name='派工日期')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='計劃開始日期')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='計劃完成日期')),
                ('assigned_operator', models.CharField(blank=True, max_length=100, null=True, verbose_name='分配作業員')),
                ('assigned_equipment', models.CharField(blank=True, max_length=100, null=True, verbose_name='分配設備')),
                ('process_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='工序名稱')),
                ('total_work_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='總工作時數')),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='總加班時數')),
                ('total_all_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='總時數')),
                ('total_good_quantity', models.IntegerField(default=0, verbose_name='總良品數量')),
                ('total_defect_quantity', models.IntegerField(default=0, verbose_name='總不良品數量')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='總數量')),
                ('packaging_good_quantity', models.IntegerField(default=0, verbose_name='出貨包裝良品數量')),
                ('packaging_defect_quantity', models.IntegerField(default=0, verbose_name='出貨包裝不良品數量')),
                ('packaging_total_quantity', models.IntegerField(default=0, verbose_name='出貨包裝總數量')),
                ('fillwork_report_count', models.IntegerField(default=0, verbose_name='填報記錄數量')),
                ('fillwork_approved_count', models.IntegerField(default=0, verbose_name='已核准填報數量')),
                ('fillwork_pending_count', models.IntegerField(default=0, verbose_name='待審核填報數量')),
                ('onsite_report_count', models.IntegerField(default=0, verbose_name='現場報工記錄數量')),
                ('onsite_completed_count', models.IntegerField(default=0, verbose_name='已完成現場報工數量')),
                ('total_processes', models.IntegerField(default=0, verbose_name='總工序數')),
                ('completed_processes', models.IntegerField(default=0, verbose_name='已完成工序數')),
                ('in_progress_processes', models.IntegerField(default=0, verbose_name='進行中工序數')),
                ('pending_processes', models.IntegerField(default=0, verbose_name='待開始工序數')),
                ('unique_operators', models.JSONField(default=list, verbose_name='參與作業員清單')),
                ('unique_equipment', models.JSONField(default=list, verbose_name='使用設備清單')),
                ('operator_count', models.IntegerField(default=0, verbose_name='參與作業員數量')),
                ('equipment_count', models.IntegerField(default=0, verbose_name='使用設備數量')),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='完成率(%)')),
                ('packaging_completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='出貨包裝完成率(%)')),
                ('can_complete', models.BooleanField(default=False, verbose_name='可完工')),
                ('completion_threshold_met', models.BooleanField(default=False, verbose_name='達到完工閾值')),
                ('last_fillwork_update', models.DateTimeField(blank=True, null=True, verbose_name='最後填報更新時間')),
                ('last_onsite_update', models.DateTimeField(blank=True, null=True, verbose_name='最後現場報工更新時間')),
                ('last_process_update', models.DateTimeField(blank=True, null=True, verbose_name='最後工序更新時間')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.CharField(default='system', max_length=100, verbose_name='建立人員')),
            ],
            options={
                'verbose_name': '派工單',
                'verbose_name_plural': '派工單管理',
                'db_table': 'workorder_dispatch',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_number'], name='workorder_d_order_n_ec825f_idx'), models.Index(fields=['product_code'], name='workorder_d_product_3ddd67_idx'), models.Index(fields=['status'], name='workorder_d_status_89e324_idx'), models.Index(fields=['dispatch_date'], name='workorder_d_dispatc_469baf_idx')],
                'unique_together': {('company_code', 'order_number', 'product_code')},
            },
        ),
        migrations.CreateModel(
            name='WorkOrderDispatchProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder_dispatch_id', models.CharField(max_length=50, verbose_name='派工單ID')),
                ('workorder_dispatch_name', models.CharField(max_length=200, verbose_name='派工單名稱')),
                ('process_name', models.CharField(max_length=100, verbose_name='工序名稱')),
                ('step_order', models.IntegerField(verbose_name='工序順序')),
                ('planned_quantity', models.IntegerField(verbose_name='計劃數量')),
                ('assigned_operator', models.CharField(blank=True, max_length=100, null=True, verbose_name='分配作業員')),
                ('assigned_equipment', models.CharField(blank=True, max_length=100, null=True, verbose_name='分配設備')),
                ('dispatch_status', models.CharField(choices=[('pending', '待派工'), ('dispatched', '已派工'), ('in_progress', '進行中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='派工狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '派工單工序',
                'verbose_name_plural': '派工單工序明細',
                'db_table': 'workorder_dispatch_process',
                'ordering': ['workorder_dispatch_id', 'step_order'],
                'unique_together': {('workorder_dispatch_id', 'step_order')},
            },
        ),
    ]
