# Generated by Django 5.1.8 on 2025-08-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder_dispatch", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workorderdispatch",
            name="operator",
        ),
        migrations.RemoveField(
            model_name="workorderdispatch",
            name="process",
        ),
        migrations.RemoveField(
            model_name="workorderdispatch",
            name="work_order",
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="company_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="公司代號"
            ),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="order_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="工單號碼"
            ),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="product_code",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="產品編號"
            ),
        ),
        migrations.AlterField(
            model_name="workorderdispatch",
            name="planned_quantity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="計劃數量"
            ),
        ),
    ]
