# Generated by Django 5.1.8 on 2025-08-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder_dispatch", "0002_update_dispatch_model"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="workorderdispatch",
            new_name="workorder_d_order_n_ec825f_idx",
            old_name="workorder_d_order_n_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="workorderdispatch",
            new_name="workorder_d_product_3ddd67_idx",
            old_name="workorder_d_product_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="workorderdispatch",
            new_name="workorder_d_status_89e324_idx",
            old_name="workorder_d_status_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="workorderdispatch",
            new_name="workorder_d_dispatc_469baf_idx",
            old_name="workorder_d_dispatch_123456_idx",
        ),
        migrations.AlterField(
            model_name="workorderdispatch",
            name="order_number",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="工單號碼"
            ),
        ),
        migrations.AlterField(
            model_name="workorderdispatch",
            name="product_code",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="產品編號"
            ),
        ),
    ]
