# Generated by Django 5.2.6 on 2025-09-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder_dispatch", "0002_auto_20250910_1048"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatchhistory",
            name="workorder_dispatch_name",
            field=models.CharField(max_length=200, verbose_name="派工單名稱"),
        ),
        migrations.AlterField(
            model_name="workorderdispatchprocess",
            name="workorder_dispatch_name",
            field=models.CharField(max_length=200, verbose_name="派工單名稱"),
        ),
    ]
