# Generated by Django 5.1.8 on 2025-08-17 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "workorder_dispatch",
            "0003_rename_workorder_d_order_n_123456_idx_workorder_d_order_n_ec825f_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workorderdispatch",
            unique_together={("company_code", "order_number", "product_code")},
        ),
    ]
