# Generated by Django 5.1.8 on 2025-08-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder_dispatch", "0004_alter_workorderdispatch_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderdispatch",
            name="can_complete",
            field=models.BooleanField(default=False, verbose_name="可完工"),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="completed_processes",
            field=models.IntegerField(default=0, verbose_name="已完成工序數"),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="completion_rate",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="完成率(%)"
            ),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="completion_threshold_met",
            field=models.BooleanField(default=False, verbose_name="達到完工閾值"),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="equipment_count",
            field=models.IntegerField(default=0, verbose_name="使用設備數量"),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="fillwork_approved_count",
            field=models.IntegerField(default=0, verbose_name="已核准填報數量"),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="fillwork_pending_count",
            field=models.IntegerField(default=0, verbose_name="待審核填報數量"),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="fillwork_report_count",
            field=models.IntegerField(default=0, verbose_name="填報記錄數量"),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="in_progress_processes",
            field=models.IntegerField(default=0, verbose_name="進行中工序數"),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="last_fillwork_update",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最後填報更新時間"
            ),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="last_onsite_update",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最後現場報工更新時間"
            ),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="last_process_update",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最後工序更新時間"
            ),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="onsite_completed_count",
            field=models.IntegerField(default=0, verbose_name="已完成現場報工數量"),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="onsite_report_count",
            field=models.IntegerField(default=0, verbose_name="現場報工記錄數量"),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="operator_count",
            field=models.IntegerField(default=0, verbose_name="參與作業員數量"),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="packaging_completion_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="出貨包裝完成率(%)",
            ),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="packaging_defect_quantity",
            field=models.IntegerField(default=0, verbose_name="出貨包裝不良品數量"),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="packaging_good_quantity",
            field=models.IntegerField(default=0, verbose_name="出貨包裝良品數量"),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="packaging_total_quantity",
            field=models.IntegerField(default=0, verbose_name="出貨包裝總數量"),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="pending_processes",
            field=models.IntegerField(default=0, verbose_name="待開始工序數"),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="total_all_hours",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="總時數"
            ),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="total_defect_quantity",
            field=models.IntegerField(default=0, verbose_name="總不良品數量"),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="total_good_quantity",
            field=models.IntegerField(default=0, verbose_name="總良品數量"),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="total_overtime_hours",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="總加班時數"
            ),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="total_processes",
            field=models.IntegerField(default=0, verbose_name="總工序數"),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="total_quantity",
            field=models.IntegerField(default=0, verbose_name="總數量"),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="total_work_hours",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="總工作時數"
            ),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="unique_equipment",
            field=models.JSONField(default=list, verbose_name="使用設備清單"),
        ),
        migrations.AddField(
            model_name="workorderdispatch",
            name="unique_operators",
            field=models.JSONField(default=list, verbose_name="參與作業員清單"),
        ),
    ]
