# Generated by Django 5.1.8 on 2025-08-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder_dispatch", "0005_workorderdispatch_can_complete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderdispatch",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="公司名稱"
            ),
        ),
    ]
