# Generated by Django 5.1.8 on 2025-08-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder_dispatch", "0006_workorderdispatch_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorderdispatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待派工"),
                    ("dispatched", "已派工"),
                    ("in_production", "生產中"),
                    ("completed", "已完工"),
                    ("cancelled", "已取消"),
                ],
                default="in_production",
                max_length=20,
                verbose_name="派工狀態",
            ),
        ),
    ]
