# Generated by Django 5.1.8 on 2025-09-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(help_text='公司代號，例如：01、02、03', max_length=10, verbose_name='公司代號')),
                ('mkordno', models.CharField(help_text='製令單號', max_length=50, verbose_name='製令單號')),
                ('product_id', models.CharField(help_text='產品編號', max_length=100, verbose_name='產品編號')),
                ('prodt_qty', models.PositiveIntegerField(help_text='生產數量', verbose_name='生產數量')),
                ('est_take_mat_date', models.CharField(help_text='預定開工日', max_length=20, verbose_name='預定開工日')),
                ('est_stock_out_date', models.CharField(help_text='預定出貨日', max_length=20, verbose_name='預定出貨日')),
                ('sync_time', models.DateTimeField(auto_now=True, help_text='同步時間', verbose_name='同步時間')),
                ('complete_status', models.IntegerField(blank=True, help_text='完工狀態', null=True, verbose_name='完工狀態')),
                ('bill_status', models.IntegerField(blank=True, help_text='單況', null=True, verbose_name='單況')),
                ('is_converted', models.BooleanField(default=False, help_text='是否已轉換成工單', verbose_name='是否已轉換成工單')),
                ('flag', models.IntegerField(blank=True, help_text='ERP狀態Flag', null=True, verbose_name='ERP狀態Flag')),
                ('mkord_date', models.CharField(blank=True, help_text='製令日期', max_length=20, null=True, verbose_name='製令日期')),
                ('make_type', models.CharField(blank=True, help_text='製令類型', max_length=20, null=True, verbose_name='製令類型')),
                ('producer', models.CharField(blank=True, help_text='生產人員', max_length=20, null=True, verbose_name='生產人員')),
                ('functionary', models.CharField(blank=True, help_text='負責人', max_length=20, null=True, verbose_name='負責人')),
                ('remark', models.TextField(blank=True, help_text='備註', null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間', verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新時間', verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '公司製造命令',
                'verbose_name_plural': '公司製造命令',
                'db_table': 'workorder_manufacturing_order',
                'ordering': ['-est_stock_out_date', '-created_at'],
                'indexes': [models.Index(fields=['company_code'], name='workorder_m_company_de46d8_idx'), models.Index(fields=['mkordno'], name='workorder_m_mkordno_b77447_idx'), models.Index(fields=['product_id'], name='workorder_m_product_4c63ee_idx'), models.Index(fields=['complete_status'], name='workorder_m_complet_51121d_idx'), models.Index(fields=['bill_status'], name='workorder_m_bill_st_423179_idx'), models.Index(fields=['is_converted'], name='workorder_m_is_conv_f2f160_idx'), models.Index(fields=['est_stock_out_date'], name='workorder_m_est_sto_c424fe_idx'), models.Index(fields=['sync_time'], name='workorder_m_sync_ti_e70e9e_idx')],
                'unique_together': {('company_code', 'mkordno', 'product_id')},
            },
        ),
    ]
