# Generated by Django 5.1.8 on 2025-09-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companyorder",
            options={
                "ordering": ["-est_stock_out_date", "-created_at"],
                "verbose_name": "公司生產製造命令",
                "verbose_name_plural": "公司生產製造命令",
            },
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="is_converted",
            field=models.BooleanField(
                default=False,
                help_text="是否已轉換成MES工單",
                verbose_name="是否已轉換成MES工單",
            ),
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="make_type",
            field=models.CharField(
                blank=True,
                help_text="生產製造命令類型",
                max_length=20,
                null=True,
                verbose_name="生產製造命令類型",
            ),
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="mkord_date",
            field=models.CharField(
                blank=True,
                help_text="生產製造命令日期",
                max_length=20,
                null=True,
                verbose_name="生產製造命令日期",
            ),
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="mkordno",
            field=models.CharField(
                help_text="生產製造命令單號",
                max_length=50,
                verbose_name="生產製造命令單號",
            ),
        ),
    ]
