# Generated by Django 5.1.8 on 2025-08-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_order", "0003_create_company_order_tables"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PrdMKOrdMain",
        ),
        migrations.DeleteModel(
            name="PrdMkOrdMats",
        ),
        migrations.DeleteModel(
            name="SystemConfig",
        ),
        migrations.RenameIndex(
            model_name="companyorder",
            new_name="workorder_c_company_6e7431_idx",
            old_name="workorder_company_order_company_code_idx",
        ),
        migrations.RenameIndex(
            model_name="companyorder",
            new_name="workorder_c_mkordno_1cb9ec_idx",
            old_name="workorder_company_order_mkordno_idx",
        ),
        migrations.RenameIndex(
            model_name="companyorder",
            new_name="workorder_c_product_0820a1_idx",
            old_name="workorder_company_order_product_id_idx",
        ),
        migrations.RenameIndex(
            model_name="companyorder",
            new_name="workorder_c_complet_cc8945_idx",
            old_name="workorder_company_order_complete_status_idx",
        ),
        migrations.RenameIndex(
            model_name="companyorder",
            new_name="workorder_c_bill_st_52d386_idx",
            old_name="workorder_company_order_bill_status_idx",
        ),
        migrations.RenameIndex(
            model_name="companyorder",
            new_name="workorder_c_is_conv_03d329_idx",
            old_name="workorder_company_order_is_converted_idx",
        ),
        migrations.RenameIndex(
            model_name="companyorder",
            new_name="workorder_c_est_sto_fe87be_idx",
            old_name="workorder_company_order_est_stock_out_date_idx",
        ),
        migrations.RenameIndex(
            model_name="companyorder",
            new_name="workorder_c_sync_ti_83e171_idx",
            old_name="workorder_company_order_sync_time_idx",
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="bill_status",
            field=models.IntegerField(
                blank=True, help_text="單況", null=True, verbose_name="單況"
            ),
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="company_code",
            field=models.CharField(
                help_text="公司代號，例如：01、02、03",
                max_length=10,
                verbose_name="公司代號",
            ),
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="complete_status",
            field=models.IntegerField(
                blank=True, help_text="完工狀態", null=True, verbose_name="完工狀態"
            ),
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="建立時間", verbose_name="建立時間"
            ),
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="est_stock_out_date",
            field=models.CharField(
                help_text="預定出貨日", max_length=20, verbose_name="預定出貨日"
            ),
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="est_take_mat_date",
            field=models.CharField(
                help_text="預定開工日", max_length=20, verbose_name="預定開工日"
            ),
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="flag",
            field=models.IntegerField(
                blank=True,
                help_text="ERP狀態Flag",
                null=True,
                verbose_name="ERP狀態Flag",
            ),
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="functionary",
            field=models.CharField(
                blank=True,
                help_text="負責人",
                max_length=20,
                null=True,
                verbose_name="負責人",
            ),
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="is_converted",
            field=models.BooleanField(
                default=False,
                help_text="是否已轉換成工單",
                verbose_name="是否已轉換成工單",
            ),
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="make_type",
            field=models.CharField(
                blank=True,
                help_text="製令類型",
                max_length=20,
                null=True,
                verbose_name="製令類型",
            ),
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="mkord_date",
            field=models.CharField(
                blank=True,
                help_text="製令日期",
                max_length=20,
                null=True,
                verbose_name="製令日期",
            ),
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="mkordno",
            field=models.CharField(
                help_text="製令單號", max_length=50, verbose_name="製令單號"
            ),
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="prodt_qty",
            field=models.PositiveIntegerField(
                help_text="生產數量", verbose_name="生產數量"
            ),
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="producer",
            field=models.CharField(
                blank=True,
                help_text="生產人員",
                max_length=20,
                null=True,
                verbose_name="生產人員",
            ),
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="product_id",
            field=models.CharField(
                help_text="產品編號", max_length=100, verbose_name="產品編號"
            ),
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="remark",
            field=models.TextField(
                blank=True, help_text="備註", null=True, verbose_name="備註"
            ),
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="sync_time",
            field=models.DateTimeField(
                auto_now=True, help_text="同步時間", verbose_name="同步時間"
            ),
        ),
        migrations.AlterField(
            model_name="companyorder",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="更新時間", verbose_name="更新時間"
            ),
        ),
        migrations.AlterField(
            model_name="companyordersystemconfig",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="建立時間", verbose_name="建立時間"
            ),
        ),
        migrations.AlterField(
            model_name="companyordersystemconfig",
            name="description",
            field=models.TextField(
                blank=True, help_text="設定說明", verbose_name="設定說明"
            ),
        ),
        migrations.AlterField(
            model_name="companyordersystemconfig",
            name="key",
            field=models.CharField(
                help_text="設定名稱",
                max_length=50,
                unique=True,
                verbose_name="設定名稱",
            ),
        ),
        migrations.AlterField(
            model_name="companyordersystemconfig",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="更新時間", verbose_name="更新時間"
            ),
        ),
        migrations.AlterField(
            model_name="companyordersystemconfig",
            name="value",
            field=models.CharField(
                help_text="設定值", max_length=100, verbose_name="設定值"
            ),
        ),
    ]
