# Generated by Django 5.1.8 on 2025-08-24 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company_order", "0004_delete_prdmkordmain_delete_prdmkordmats_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompanyOrderSystemConfig",
        ),
    ]
